### ISSUE TITLE
Proposal: Submodules

### ISSUE THREAD

**Issue by tomberek** [jasonrohrer/OneLife#1]
https://github.com/jasonrohrer/OneLife/blob/master/build/source/buildAndPostLinux.sh#L28

While they are not perfect, sub-modules or a similar mechanism may help build-system. Thoughts?

**Comment by jasonrohrer** [comment]
Hmm... didn't know this was possible.

But I've already got loads of server-side scripts written that expect the three parts to be in separate repos.
