### ISSUE TITLE
Editor: Error importing sprites on Windows build

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1001]
Hi.

When trying to import sprites on the Windows build of the OHOL Editor, we only get the error:
"Failed to import PNG from: /home/jasonrohrer2/default.png"

Is this a bug or do I just not know the correct instructions to import sprites?
If it's a bug, I would suggest using the current directory for the application as the base directory, and using /import/sprites as the location folder for the sprites to be imported.

Loving the new editor and the original content it has brought! Keep up the great work <3

![image](https://github.com/jasonrohrer/OneLife/assets/494864/005d7cbc-8f4d-4ad8-9909-4f617e91b267)

**Comment by DopiePanda** [comment]
And if I create an "overlayImport" folder and add .png-files to it, I am able to import them, but after adding a tag and clicking "Save Overlay", the sprite does not show up in any of the search panels on any screens (anim, objects, sprites, etc.)

![image](https://github.com/jasonrohrer/OneLife/assets/494864/58d127fb-f052-436c-96d6-352940a47231)

**Comment by kanmikan** [comment]
change the path in settings/editorImportPath.ini to a relative path to the game folder: ./default.png

**Comment by jasonrohrer** [comment]
Yes, see @kanmikan's comment.

This is explained in the Mod Update post here:

https://onehouronelife.com/forums/viewtopic.php?id=10907

I will improve that error message too (to explain that you can change it in settings)

**Comment by DopiePanda** [comment]
Aha! Did not check the forums, my bad. Thank you both for good info ♥️
