### ISSUE TITLE
Donkey Town Is Very Balenced

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#1002]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/3690aeee-53dc-49d7-b668-61f547c04183)

**Comment by Shadie116** [comment]
How am I not able to be born into 8 families with varying populations specifically at 2:15 central time US for five years

**Comment by Shadie116** [comment]
ima start making players go missing soon, all you need is an alt account and a rumor

**Comment by DougLefelhocz** [comment]
Since Donkey Town is "Very Balanced" as the title of this post reads, this thread should get closed.

**Comment by Shadie116** [comment]
speedrun?
