### ISSUE TITLE
Tutorial Has Outdated Information

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1003]
Someone in a Twitch stream going by the name 'birdy_isthewordy' brought this up (I did NOT remember this).

The last stone in the tutorial prompts a message which says:

"PLAYERS FALL OFF YOUR CURSE LIST AFTER SEVERAL DAYS, SO REDEMPTION IS POSSIBLE."

Of course, this no longer sounds right.

Perhaps some message about forgiveness like:

"PLAYERS CAN GET FORGIVEN BY SAYING I FORGIVE YOU, SO REDEMPTION IS POSSIBLE."

would be a more updated message.

**Comment by Shadie116** [comment]
This is one thing I am not mad at
