### ISSUE TITLE
Tapout Makes the Game More Grindy/New Players Won't Know to Move

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1005]
The servers split on Tuesday, December 26th, and I chose server1 as a custom server.  I played as [Twonda Bles](http://lineage.onehouronelife.com/server.php?action=character_page&id=10030504&rel_id=10030196) twinning with the streamer trekkiea (who doesn't save his streams).  We got born to a camp with no spring in sight, probably because the new player didn't have any idea about how that system works.  That's not all that uncommon, and probably even more expected if there are new Eves due to a server split.

We found a natural spring nearby and started work on developing tools.  However, before we could dig up the well, we had a dry spring.  I saw later that springs pointed south, and since we were tan, this implied that black family had tapped us out (edit: some destructive players like kilian have commented in his streams in the past.. and kilian could have done that).  Thus, we had to trek west a bit, so that the family would have a well for water.  We had what looked like a good amount of clay and branches, but again, we had to move.

But, that also meant we had to build kilns in the new spot, an oven, and get stones for a natural spring there.  It was basically a repetition of what we had done just 10 minutes before.  This isn't the sort of grind that works out as interesting.  And I'm not exactly sure that everyone even tried to make it to the new spot.  I've also had problems with tapout before, where a griefer tapped out the natural spring I had been [making](https://github.com/jasonrohrer/OneLife/issues/752) _out of biome_  Furthermore, this isn't the sort of issue that I would expect new players to figure out, yet they end up the most vulnerable during a case where the servers split, when well tapout can easily happen, since new player Eves aren't likely to understand that they need to spread out.

Tapout originally got put in BEFORE the band (in)fertility system (some time during The Rift according to Eve Troll's [post](http://onehouronelife.com/forums/viewtopic.php?id=10707)).  The band system renders well tapout as unnecessary.

Edit quote added:

"With this constant push west that is killing off towns and disabling the longevity of towns it has me questioning if the tap out range is still necessary. The well tap out system was introduced during the rift. Initally this was necessary after an update that made water far more plentiful and accessible. But since it has me wondering why it still exists. Family wells/homelands were introduced because families of different races were all living in the same town to subvert race restrictions. Jason wanted to "encourage" families to make seperate towns so traveling and trade would be necessary.

But what is well tap out doing to the game and what is its value in the game today?"

**Comment by Shadie116** [comment]
I'd honestly just let them learn.

**Comment by DougLefelhocz** [comment]
Addendum:

A few hours later I played as [Fujie Dessert](http://lineage.onehouronelife.com/server.php?action=character_page&id=10031983).  When I was born we had a dry spring.  We were actually in the mountain band, but the ginger family had tapped us out (actually, there were two Ginger families living there... no idea if one of them got tapped out).  I didn't even bother looking for a new spot.  I had played as a white man in a previous life (in a much further away place) and walked to ginger town, and figured I'd do that as a white lady, and found the same gingers as before, who tapped out the whites.

Would it have been worth it to try to find a new spot?  Not as white, I don't think.  Only if white AND server population was full (which it wasn't, and since servers split, too many players in one city wasn't anticipated).

**Comment by DougLefelhocz** [comment]
Further addendum:

Eve Dessert also posted [her persepctive](https://www.reddit.com/r/onehouronelife/comments/18rq44b/the_bittersweet_story_of_eve_dessert/) on reddit (and posted the link to the reddit on discord).

I quote:

"... When I returned, I met Vanilla's new baby girl. The child bore ill-omens for our town.

"Well dry" the baby said. I was shocked. ..."

"... Not a soul to be found but my mother's intuition told me that Cocoa had a grandchild northeast. I ran due east from my dry spring just to find two more mines. I lament the lost potential. Imagine the industry! Four iron mines to a single town!"

[Poolos](http://lineage.onehouronelife.com/server.php?action=character_page&id=10031576) family was the family that dug up the ginger well.

Eve Dessert died about 40 minutes after Eve Poolos.

**Comment by Shadie116** [comment]
Also something funny server 1 has little to no phex players. Is this what they call serverisem?

**Comment by Shadie116** [comment]
Also I think Jason explained tapout before, and you're in an infinite world, just look for another one. The water table doesn't just stay the same forever
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/0d73f465-f854-488a-a3ef-0849c70db721)
you see this really cool thing I found online about water tables or whatever

**Comment by Shadie116** [comment]
where the elevation dips, or where you did in the spring, the water table is there which gets you that fresh water. Also the fact it says "dry" should be an indicator. Plus you could just make a mod for that

**Comment by DougLefelhocz** [comment]
> Also I think Jason explained tapout before, and you're in an infinite world, just look for another one.

Digging up another well is always possible in principle, and simply accomplished for an experienced player.  However, sometimes, like with Eve Dessert, another iron unlock is not possible.  It also wasn't like Desserts could import an engine and kerosene to some sunken iron vein, since they were on server1!  Moving a family involves further complications.  I guess you wouldn't know about such complexities though Shadie116, since that isn't the sort of position you've been in with your curse record (I've tried it... nope... moving a family without mods or playing with a streamer?  Forget it).  

Eve Troll says this in a referenced comment in the edited version of the first post above:

"In short the well tap out radius is forcing families to move further in order to make a new town. "

That's exactly what I had to do in the first life today as a tan.  In the second life, everyone just ran away to Gingers.

Jason says in a [linked comment](https://github.com/jasonrohrer/OneLife/issues/752#issuecomment-1553036823):

"It's not supposed to be straight-forward and the same every time."

Well, it happened 2 out of 3 lives that I played on server1 that my family had their natural spring tapped out.  And in the live between those two lives it turns out that I was helping the family get a shovel up who would tap out the new white family!  Families tapping each other out isn't supposed to happen that close together, is it?

Also, anytime I've been Eve for a long, long time on bs2, I try to find a spot with 2 iron veins.  It turns out that a new Eve spawns just outside the tapout radius of the last family often enough.  Now, if you're a Ginger Eve and the last unlock was a Black family or Tan Family, that doesn't pose an issue.  But if the previous Eve was Ginger and you're Ginger, 40 tiles to the west is likely not a viable spot (viable meaning having at least two unlockable iron veins), since you only have 4 potential veins on the left side and none on the right that can get unlocked.  If the last family was a White family, there still can be an issue.  If you're tan?  You're even more likely to have tapped out iron veins to the right of you, since the last family could have been tan, white, or black  and any of them could have tapped the iron to the right of you out.

What does tapout cause?  More running around by experienced players and more thoughts of "what in the world are they doing?" by new players.

**Comment by DougLefelhocz** [comment]
Tapout also doesn't lead to players leaving a ghost town, in my experience.

It's more like tapout _prevents_ the beginning of towns, and Eve Dessert's story makes that more clear.

**Comment by Shadie116** [comment]
man, rn I'm cutting a marshmallow from a lucky charms box using my braces.

**Comment by Shadie116** [comment]
You have to teach silicon how to think.

**Comment by Shadie116** [comment]
we use stretchy glass to transport light as data

**Comment by jasonrohrer** [comment]
Yeah, this is fine as it is.

In the rare case where someone settles right near you and beats you to digging a well.... well, it makes for an interesting story.  The well went dry!  We have to move!

The game, as you know, is supposed to be an infinite situation generator.  Weird edge cases, village disasters, etc. are supposed to crop up from time to time.

As for the realism of tapout... they have a long straw, and they are drinking your milkshake:

https://youtu.be/s_hFTR6qyEo?si=Sl8HdvHtJ2FvR2LG

**Comment by MooseSeven** [comment]
But it's not just the water. Iron is locked to the place where you begin to build a on a spring that later becomes blocked. An infinite situation generator would let you move to a new place to find both water and iron, not turn the situation into a game over. /sad

**Comment by DougLefelhocz** [comment]
> But it's not just the water. Iron is locked to the place where you begin to build a on a spring that later becomes blocked. An infinite situation generator would let you move to a new place to find both water and iron, not turn the situation into a game over. /sad

If you have kerosene, you can get iron from a diesel mining pick.  [A diesel engine can get placed on a muddy iron vein or a sunken iron vein](https://onetech.info/2365-Diesel-Engine).  Wells can get dug up anywhere.  That applies even if you are generation 100+.  It applies at all times

Also, is your name a reference to playing on server7?  All Eves have an iron unlock (unless their children make a ready well site first).  So, if Eve chaining, one can unlock iron everytime one is Eve the usual way, and move that way also.

**Comment by Shadie116** [comment]
this isn't a game of freedom and innovation, sorry

**Comment by MooseSeven** [comment]
> If you have kerosene, you can get iron from a diesel mining pick. [A diesel engine can get placed on a muddy iron vein or a sunken iron vein](https://onetech.info/2365-Diesel-Engine). Wells can get dug up anywhere. That applies even if you are generation 100+. It applies at all times
> 
> Also, is your name a reference to playing on server7? All Eves have an iron unlock (unless their children make a ready well site first). So, if Eve chaining, one can unlock iron everytime one is Eve the usual way, and move that way also.

Yes, though I haven't played in a while now. Thank you , I didn't know that about the diesel engine iron. It helps. But I have been in Eve families and early towns on main that were separated from their iron because of their original springs being locked. It's a mechanic I'd love to see change. Jason has rejected it in the past though, so I doubt it will ever happen.

**Comment by DougLefelhocz** [comment]
You're welcome, MooseSeven.
