### ISSUE TITLE
Donkey Town will never be a town

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#1006]
It's impossible to settle down because it keeps moving, it's kinda like sticking a piece of wood in the sand but than the sand just moves. The sand being the eve spawn for Donked out players. We attempted to set up a road there but after a week it fell off due to the eve spawn moving west like it would for normal players.

**Comment by Shadie116** [comment]
(this only applies to donkey town and not to the main player base)

**Comment by DougLefelhocz** [comment]
If you play on a server separate from bs2, and no one else is on the server when you log in, you won't be in Donkeytown.  You only end up Donkeytown, if you get cursed out.  That's impossible if you log into an empty server, or everyone on the server does not have you cursed.  So, you and others can potentially use the custom server box, and log in on a different server and make an actual town.

**Comment by Shadie116** [comment]
Well this is for the people who get cursed out. Also I forgot to mention my 120 curses

**Comment by Shadie116** [comment]
if your going to be in a place for five years at least have people have a place to go that they built themselves

**Comment by Shadie116** [comment]
Wait this time I actually read what you said. Donkey players aren't sent to make new towns, each server has the same west moving mechanic. Dt players should perhaps have like a radius in the same location so they can stay where they are and build some place to stay and not complain about the terrible guest accommodations.
