### ISSUE TITLE
Lag During Server Split

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1007]
On December 26th, 2023, the servers split.  They seemed to split at about 126 people on, as expected.  A few minutes after I saw BlahWizard report lag on her stream.  TheGeniusPhoenix on the discord said:

"I can't get back on the main one."

at about 4:14 P. M. (EST)

At 4:22 P. M. Rizzler1984

"I'm havign rlly bad lag" [sic]

"so is the leader lol"

"ORDER FROM YOUR LADY SHINE CLARA:
SORRY, YOUR LEADER IS LAGGY AF" [sic]

Also:

"TheGeniusPhoenix — Yesterday at 4:33 PM
Big server 2 was never offline. People just couldn't connect to it for a bit"

I'm not finding more relevant quotes, and it doesn't seem to have persisted.

**Comment by Shadie116** [comment]
Why are you worried about the smallest things, I literally just killed two towns.

**Comment by Shadie116** [comment]
nah i'm joking 
i just like to f with sensitive people sometimes

**Comment by Rukhmar** [comment]
I have also experienced pretty bad lag the past couple days when the population got high. I was so laggy my horse would take off running, and as I went to click it to retrieve it, I would lag again so it would run again before I could actually mount it. Please can you look into the lag, or at least have a way we can further domesticate horses so we don't have to chase them for 5min hoping we will stop lagging enough to actually get back on it?

**Comment by Shadie116** [comment]
You got terrible connection, get closer to your router or just change the frequency. I had no lag at all, or just make your own personal network specifically for your computer using an extender
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/896a9371-1f25-4334-baa6-9c5e98b04641)

**Comment by Shadie116** [comment]
Infact I'm not even sure what Jason would be able to do about this. You want him to switch providers?? Bang on his server with a rock, if anything this is a problem for your network, if you got lag that means your wired or wireless network isn't receiving all packets so the tcp/ip protocol is just repeating the process till it gets that segment. Jason's server is ok, servers got like 64 gb of ram and straight terabyte hard drives, I don't even see why this is an issue nor how it can even be fixed.

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/6771a1b0-1ef5-42eb-9693-d91709eb6a7e)
Here is my server, this thing is from 2016. It can still hold multiple connections. If the lag isn't server wide you could possibly guess that it is not a server issue and by that it is not an issue.

**Comment by Shadie116** [comment]
wait that would be 2400 gb, tf am I talkin about

**Comment by jasonrohrer** [comment]
Well, yeah, there are two questions here:

1.  Is the server so bogged that it can't keep up with the traffic itself?  I'm guessing this isn't the case, because looking at the logs, it looks like BS2 never got over 80% CPU even during the peak.

2.  Is the server generating so many messages that some people's internet connections or clients can't keep up?  This is more likely the case.  Especially if you are near a crowded village, you will receive loads of messages.

I've just reduced maxPlayers on BS2 to 230 (was 260).  This means the split will start happening at 115 instead of 130.  Hopefully this will help the lagging players somewhat.
