### ISSUE TITLE
Server Direction Apparently Bugged

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1012]
Incoming players split sometime around 3:00 P. M. EST between bs2 and s1.

At 6:52 P. M. I observed bs2 up to 98... s1 down to 16.

At 7:10 P. M. I observed bs2 at 125, and s1 at 8.

At the very least, I don't see anything on live-dev-changes.

From what I understand, incoming players not checking a custom server end up very close to a server split again, as the number for server split I thought was 126 or 120, though maybe it's not just number of players on the server intentionally or unintentionally?

At 7:12 P. M. 128 bs2 and 7 s1.

If the servers split again, then people end up in the very early game.  As interesting as the very early game may be to some, a sense of progression ends up lost if overdone.

"You can see that as the population rises, server 4 is brought into the mix to handle it, and then the population reaches a noisy plateau, which soon after results in server 4 being removed from the mix, only to be brought back into the mix a few hours later, only to be removed again shortly after.  Villages on server4 were dying out over and over.  Pity the players who were stuck playing on server 4 that evening."

[Jason Rohrer](https://onehouronelife.com/forums/viewtopic.php?id=4930)

**Comment by DougLefelhocz** [comment]
8:44 P. M. bs2 80, s1 28.  So, they split again.

**Comment by jasonrohrer** [comment]
It's when it reaches 50% population on all active servers together.

So since s1 is set to handle 400, and BS2 was set to handle 260, it would split first at 130 (when BS2 is half full) and then the next split point would be 130 + 200 or 330.
