### ISSUE TITLE
Connection to Server Failed

### ISSUE THREAD

**Issue by FunkyFungus99** [jasonrohrer/OneLife#1013]
I just bought this game and when I try to "Log In" it loads for a few seconds, but ultimately ends up as "Connection Failed" in red letters on the main screen. I restarted the app and my computer already and moved closer to the WiFi, but it still won't work. I have full connection with the modem and the internet is good too.

**Comment by Shadie116** [comment]
I uninstalled the entire game to go religous

**Comment by jasonrohrer** [comment]
Please email me directly, and I'll help you get it sorted:

jasonrohrer AT fastmail DOT fm
