### ISSUE TITLE
Apocalypses Reset Tutorial Areas

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1014]
I closed all my issues several months ago out of frustration with the game.  Some are not worth reopening or thinking about.

However, [this is one](https://github.com/jasonrohrer/OneLifeData7/issues/932) I think worth the time.  Twisted suggests to apply the ostrich algorithm.  However, there was an apocalypse on server1 recently, and likely enough someone in some tutorial area.

**Comment by Shadie116** [comment]
We already tried that, didn't work. Can't give birth in the bounds of the tutorial area. We were really pushing the boundary's of the game before anybody really tried. Real collaboration in that group is what we had.

**Comment by Shadie116** [comment]
but if you don't trust me you should go form your own group from whatever your common beliefs are and start doing wacky antics with the game

**Comment by Shadie116** [comment]
like as an example, we went to the bell at the tutorial, you can't ring it :(

**Comment by DougLefelhocz** [comment]
> We already tried that, didn't work. 

I experienced an apocalypse in a tutorial area on bs2, April 1st, 2022 when VOGmode was enabled.  Perhaps that implies that an apocalypse in the main area via a tower would reset the tutorial areas.  Perhaps it does not.  However, you did not do an apocalypse in the main area Shadie116 (on bs2... and to my knowledge on s1 also).  Bluehawk did (on server1), though I think it unlikely that he had his alt in a tutorial area to see what happened with a tutorial area.

**Comment by Shadie116** [comment]
Yeah also it's an apocalypse, they tend to do that

**Comment by Shadie116** [comment]
like clear the entire earth, the entire generating degenerating infimum

**Comment by jasonrohrer** [comment]
Yeah, this is true!  If you're in the tutorial during the Apocalypse, your tutorial area will be cleared out from underneath you.

This would be a rare moment indeed.  I know it would be confusing to a new players, but... still worth it, probably.

**Comment by Kaden56** [comment]
The tutorial loads the map everytime you click the tutorial button on the menu. Unless theres already enough tutorials then you just pop up in one of those instead. So if you did apoc in tutroial then you can just die and click tutorial again to have it load the first one of the new world.

**Comment by Shadie116** [comment]
Who puts that much time into a solo apocalypse, for all that you might as well hop off the game and start reading a book or sparking productivity in your life.

**Comment by DougLefelhocz** [comment]
> for all that you might as well hop off the game and start reading a book

Shadie116,

As the saying goes:

Be the change you wish to see in the world.

**Comment by Shadie116** [comment]
agreed

**Comment by Shadie116** [comment]
that's why I'm not playing games till the end of this month
