### ISSUE TITLE
Disappearing Baby Without Bones

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1015]
Where did [the baby](https://discord.com/channels/328215300279500800/328215300279500800/1194063863591735446) go?

[Where](http://lineage.onehouronelife.com/server.php?action=character_page&id=10076610)

[did](http://lineage.onehouronelife.com/server.php?action=character_page&id=10079911)

[he](http://lineage.onehouronelife.com/server.php?action=character_page&id=10081755)

[go](http://lineage.onehouronelife.com/server.php?action=character_page&id=10079308)?

**Comment by Shadie116** [comment]
I ate it

**Comment by Shadie116** [comment]
24 days till I return

**Comment by Shadie116** [comment]
ok now ima be honest, the only thing I learned within these 8 days was how to make a timer and how to play music. 😂

**Comment by jasonrohrer** [comment]
Note that the area around the baby is very very cluttered with stuff... no empty ground tiles.

When someone dies, it searches for a grave spot in some radius, but if it can't find one, it eventually gives up.  My guess is that the grave happened off-screen, or if not, then the area was so cluttered that it gave up and the grave disappeared.
