### ISSUE TITLE
#live-dev-changes discord channel not updating

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#1019]

**Comment by jasonrohrer** [comment]
Okay, I posted a support request in the MonitorRSS Discord.  We'll see what happens.

https://discord.com/channels/268797598926766090/1195017551936237608

**Comment by Shadie116** [comment]
You should have posted the raw ip and directory just to make it funnier. But that's just me.

**Comment by jasonrohrer** [comment]
The MonitorRSS guy fixed it for me!

Now that's great service for a free product.

**Comment by Shadie116** [comment]
![pixil-frame-0 (3)](https://github.com/jasonrohrer/OneLife/assets/126846097/dd93b6a8-a2b3-4a45-ae0b-5b2b370cbac5)
This is the only picture on my computer, what u think
