### ISSUE TITLE
Editor Bug: If you export green bean plants in your mod none of the changes will be made

### ISSUE THREAD

**Issue by spiderface721** [jasonrohrer/OneLife#1020]
If you export green bean plants in your mod none of the changes in your mod will be made (including other objects). Your mod will be empty even though its number of changes is high

**Comment by jasonrohrer** [comment]
Some questions:

First, I can't recall... but can you confirm that you did export other mods that did work and didn't have this problem?

Second, do you know the specific Green Bean Plant object that you tried to export?  Do you know the object ID of that plant?  There are several stages, and I want to make sure I test the right one.

Third, did you edit the Green Bean Plant at all before exporting it?

And finally:
Can you send me the broken OXZ file that won't load?

**Comment by spiderface721** [comment]
I exported a lot of mods but they only worked when beans was not being exported
2 I'm pretty sure in the editor there is only one green beans plants that i could choose from the objects on the right side so I'm not sure how does that work, its literally called "Green Bean Plants"
3 I only tried with edited green bean plant and I tried making various changes separately and it would always break the mod
4 im pretty sure this file did not work, its most of the features of quality of life mod so among other changes all plants should have a green marker (i sent the file on discord dm's)

**Comment by jasonrohrer** [comment]
Very helpful!  Turns out one of the sprites in the Bean Plants has a # symbol in the name of the sprite, which breaks the mod file format.  I'm going to fix this!

**Comment by Shadie116** [comment]
I tossed my white friend into the desert and instead of turning red and dying of a heat stroke he attempted to impale me on a cactus.

**Comment by Shadie116** [comment]
game inaccurate >:(
