### ISSUE TITLE
Issues post update

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1021]
Hey!

So... After the update, you cannot remove wheat from a tile unless you do it before you remove the straw.
Removing the straw first makes the wheat become un-moveable from the tile it is on.

Also, when emptying a bowl of beans into a bucket, it leaves you with a plate afterwards, I guess this is not supposed to happen.

**Comment by DougLefelhocz** [comment]
1. Those both concern the content, not the program, and thus, the above would belong [in the other section](https://github.com/jasonrohrer/OneLifeData7) (Jason will move something like this if it's wrong.. it's better to post than to worry too much about getting things in the wrong section).

2. I believe those issues got addressed [as referenced](https://github.com/jasonrohrer/OneLifeData7/issues/1173) (see the 096d77a hyperlink).  Here are the relevant transitions on onetech:

[One ](https://onetech.info/226-Threshed-Wheat)

[Two](https://onetech.info/297-Threshed-Wheat-straw-removed)

[Three](https://onetech.info/1179-Bowl-of-Cleaned-Dried-Beans)

All three of which were different, before Saturday's fix for One and Three.

Do you still experience a bug in-game?

**Comment by Shadie116** [comment]
Sounds like an issue involving your ability to remove wheat from a tile effectively. I.E a skill issue. Fr though yes I agree this needs a fix

**Comment by jasonrohrer** [comment]
Pretty sure this was fixed.

Please open a new issue if it's still a problem.

**Comment by Shadie116** [comment]
heey jason
