### ISSUE TITLE
Would be nice to add in protocol.txt how to make a newline in player say commands (PS)

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#1023]
Would be nice to add in protocol.txt how to make a newline in player say commands (PS)
Yea i know this is just a convention between client and server but would be still nice to know if you read about PS.

I think this indicates a new line or? 
**

**Comment by jasonrohrer** [comment]
Hmm... I'm having trouble finding examples of where the server sends a two-line message THROUGH the player via a PS message ...

I'm seeing lots of examples of multi-line DING messages, which indeed use ** for newlines.  I will add that to the protocol notes.

Yeah, I've looked at the code closely, and there's no way to force a newline in what the player says.  Even the distance-away things (like for a gate visitor) get simply appended to what the player says with a " - " hyphen, and no forced newlines.
