### ISSUE TITLE
January 28th Server1 log check?  Some Players (I Guess Not Checking a Custom Server) Seemed to Have Gone to Server1 When They Should Not Have.

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1025]
I happened to check the family trees and saw [this lineage](http://lineage.onehouronelife.com/server.php?action=character_page&id=10149826&rel_id=10149826), which struck me as odd.

I logged into the tutorial and read PXChat finding Hopie, Byte, and Clay apparently talking and showing signs of not having checked s1 as a custom server, but ending up there.

Byte: "14 players online"

"lol so many Eves"

Clay: "traveled 5k west no signs of civilization" (maybe he meant east?)

Byte: "are we that far"

...

Clay: "nevermind we're on server1"

...

Byte: "thats why"

...

hopie: "Test server1"

**Comment by DougLefelhocz** [comment]
Byte's "14 players online" isn't clear to me.  I assume that Byte looked at the upper right hand corner in YumLife mod.  But, that number is one less than the number of players online on a server, and thus Byte might have implied 14 players on s1 or 15 players on the server.

**Comment by jasonrohrer** [comment]
I'm pretty sure this is all part of #1018
