### ISSUE TITLE
The Button Does Not Exist For Players

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1027]
> In a game that starts back at zero as a premise, a question arises:  how did we get to zero in the first place?  And what if, Edmund suggested, **players** [emphasis added] were in control of taking everything back to zero?  What if, at the top of the tech tree, the most difficult-to-craft item was The Button?

[December 28th, 2018](http://www.onehouronelife.com/forums/viewtopic.php?id=4877)

I checked logs from [the last server1 apocalypse](https://discord.com/channels/328215300279500800/328215300279500800/1204255326413787166) and the day after.  The button does not move characters back to anywhere close to zero.  The button does not reset Eve spawns back to zero.

Perhaps in 2018 character position on the map didn't matter.  But, now with not only one monument, but another monument which depends on map position AND another object for players to construct based on that object, map position matters.  Even if an Additional Methman Monument gets constructed on bs2, without Eve spawns shifting back right, a new Additional Methman Monument on bs2 could become permanently dead content.  If not now, it still holds that eventually, those monuments become too far away to qualify as accessible.

If The Apocalypse cannot get reprogrammed to shift Eve spawn positions, then can we that [cron job](https://discord.com/channels/328215300279500800/328215300279500800/821082007794090028) you once talked about?

Also, it looks like server1 Eve spawns position(s) currently sits about 130,000 tiles left of (0, 0).  If, for example, there happens an influx of players from a big YouTube video, it seems that players would be far away from those monuments.  An improved apocalypse that pushed players to the origin area or reset Eve spawns to the origin area could do something to improve things there.

**Comment by Kaden56** [comment]
The very old "oddity" Apocalypse used to kill everyone on the server. Now Idk if it pushed them back to 0,0. But if we had that now then maybe he could make it so after the apoc and everyones dead When new eves spawn they spawn around 0,0

Btw Im not talking about returning the very broken oddity into the apoc. Im talking about making the apoc we have now kill everyone. Ik most ppl will not like that but thats probably the only way to restart spawns.

**Comment by Kaden56** [comment]
Also eve spawning is dependant on tapping springs. So since the apoc lets you live. Ppl tap springs right after and thus it causes future spawns to start there

**Comment by DougLefelhocz** [comment]
> Monoliths that clear the whole world (at least once), plus abandoned map culling, **plus better Eve placement** [emphasis added], is the fix.

[Source](http://onehouronelife.com/forums/viewtopic.php?pid=10954#p10954)

**Comment by DougLefelhocz** [comment]
> Also eve spawning is dependant on tapping springs. So since the apoc lets you live. Ppl tap springs right after and thus it causes future spawns to start there

People would dig up wells right, [but fixes got put in to prevent rightward Eve spawns](https://github.com/jasonrohrer/OneLife/commit/3367b9abc535e134f2c5937748856e4d971f51ec)

> Another fix to Eve placement to prevent eastward jump-backs: we now use west-of-homeland Eve placements to keep pushing the last-eve position further west

It has happened before that a family who lived through an apocalpyse dug up a well.  If a family lives through an apocalypse, why would their well count with respect to Eve spawn placement?  If Eve spawns had a jump back to around (0, 0), and we have most families around there, but the only tan family somehow surviving, all sorts of technology ends up blocked.  No loom clothes, nothing beyond a deep well, no engines, no tomatoes, no peppers, families might get stuck on a banana craving from Eve's craving even, etc.  Or at least until a server goes low population with respect to race restrictions.

Everyone getting killed off by an apocalypse would give more clear messaging to a new player in a tutorial.

**Comment by jasonrohrer** [comment]
Yes, "back to zero" was referring to being naked with no technology again, not 0,0 on the map!
