### ISSUE TITLE
Inconsistency in clothes warmth

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#103]
Sames clothes make sometimes a small difference in temperature, other times a big difference and sometimes clothes make temperature colder

Clothes making temperature colder:

https://imgur.com/a/VxJdOuk
https://imgur.com/a/QSYnvtF
https://imgur.com/a/NOl89UM

Bigger gap (compared to previous screenshots) with same clothes :

https://imgur.com/a/yL0UKck
https://imgur.com/a/7rf4n94
https://imgur.com/a/vcKwqh3

**Comment by jasonrohrer** [comment]
In one case, you are standing in the desert, which is hot.  So there's a greater heat build-up when you're wearing warm clothes there.
