### ISSUE TITLE
Ghosts on Servers During Updates Can Delay The Process For a Very Long Time

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1030]
> As some players spend a couple of IRL days as ghosts.

Cordy alludes to [the issue](https://github.com/jasonrohrer/OneLife/issues/1022) elsewhere.

Also, [Ru](https://discord.com/channels/328215300279500800/328215300279500800/1208172682131284030) during the update period:

> yeah but you know what's really funny? there's a ghost right now.

> i'm talking to him now, he'll probably just die

> ill exorcise him if he doesn't want to die
> its a phex user tho

> they said okay, there's still some living people who are 40 though, so 20 more mins

[TheGeniusPhoenix](https://discord.com/channels/328215300279500800/328215300279500800/1208182364052914327):

> Ok, the ghost is the only person left

Ru chimes in and apparently talking to that ghost wasn't enough:

> I exorcised him before I died. maybe there was another ghost?

Some others thought you kicked the ghost.

I could imagine someone getting ghost on their Eve spawn on a low pop server also.  Testo has suggested that he or someone else got ghost in a tutorial area also.  

Maybe the power of The Computer needs to compel ghosts to go during an update period?  If that's possible?  Or ghost mode gets disabled a few hours before an update starts?

**Comment by Tarr-OHOL** [comment]
Jason can literally kill everyone on the server when he wants. He has done it before, and can do it again. So no, if Jason absolutely wants to kill a ghost trying to postpone an update there already exists a solution.

**Comment by DougLefelhocz** [comment]
> Jason can literally kill everyone on the server when he wants. He has done it before, and can do it again. So no, if Jason absolutely wants to kill a ghost trying to postpone an update there already exists a solution.

Sure, he can do that.  But, he has to do that manually.  If he wants to do that manually any time there's an update which requires server shift, alright.  But such a solution doesn't exist until that ghost gets killed off manually.  It isn't like he can do a future action in the present.

**Comment by teliot** [comment]
This might need to be addressed @jasonrohrer 
![image](https://github.com/jasonrohrer/OneLife/assets/6187302/7d133c0b-5cb6-482a-b8e4-2ed3583a0a9d)

**Comment by jasonrohrer** [comment]
Yes, I saw that happening last update, and had to intervene....

I will fix this.

**Comment by jasonrohrer** [comment]
Probably something like this:

If the server is in shutdown mode, and the only people left are ghosts, they are force-killed.
