### ISSUE TITLE
long curses are stupid (go to the bottom)p.s take the elevator, its quicker

### ISSUE THREAD

**Issue by AccountAbandoned** [jasonrohrer/OneLife#1033]
Abandoned Arguement was up here

**Comment by Shadie116** [comment]
I forgot the iconic hoard of raging bears 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/a2f4d01b-7aa2-45e7-9a45-93192b3902a4)

**Comment by Shadie116** [comment]
I hope but not pray that these symbols I'm sending you will convince you

**Comment by Shadie116** [comment]
As a matter a fact I'd even argue that greater things were created, this game was really milked to its true potential through group collaboration. Everybody in the grief group became good friends and actually had fun with each other outside of the game and in. We built grand structures and took down great towns. It was some real group collaboration that was just sucked away with the changing of a variable. You ruined some really good moments, you 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/bc68e804-0589-41e4-a25f-d5398dc259f6)

**Comment by Shadie116** [comment]
things were really fun back then 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/febee461-ea7d-4492-980f-0c74f6fc42ce)

**Comment by Shadie116** [comment]
now things like this are hardly even possible, you've walled this game. I'm not even going to lie

**Comment by Shadie116** [comment]
Another thing I'd like to iterate is that it is through conflict that advancements were made in society. The internet might not have been how it is today, we needed a way to convey information from long distances. Something I noticed is that the people were getting better at killing bears and defending against attacks, development. They were learning and pushing, we we're getting better at setting up the apocalypse, it was a natural development that was shutdown, it was a path that was locked off with all the updates you made restricting any free thinking or anything that would change the way the game was played and it is that I find troubling. Its what made the game not fun and what made it generic.

**Comment by Shadie116** [comment]
The curse length might as well be the chance of griefing, its the circulation to a bloodstream of unpredictability and the higher the value the less possibility for eventfulness.

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/d10c58ed-101f-4205-93e8-5571955b861a)
The limitations to which you have bounded this game have made this about as far as it can go,

**Comment by Shadie116** [comment]
this is about as far griefing and grief prevention could ever be. 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/e55d8967-10f9-4377-ba63-2f4c306a09d8)
oh no my sheep, lemmie just go get new ones.

**Comment by Shadie116** [comment]
I forgot to mention how people made kits to stop griefers from attacking like a medical kit and bow and arrow kit using clothing to prevent or cause the fall of towns.

**Comment by katarrry** [comment]
I agree with you, I miss the drama and action :(

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/f5ca419b-01f5-4113-a2c9-a6a11cb3c239)
what happened to this game.

**Comment by Shadie116** [comment]
where the fun at

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/46e2ff62-2276-46e4-a91b-7a022f710af2)
Why is everything how it is now, just look, bears, those things that killed entire towns of people don't even attack you anymore. They were my greatest fear as a new player. My entire family was once wiped out by a bear, now I can just walk around it. 
I can freely stand in the nursery around an open flame and not have the risk of being killed by nothing. I can stand outside away from civilization with a hunger bar that's yummed up to the max and not have problems

**Comment by Shadie116** [comment]
ima take a shower real fast and come back and see what i die to first in the swamp

**Comment by Shadie116** [comment]
jason, i took a shower and I'm still alive
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/fae94fbe-ef9b-4a4c-b8ab-bd389d260e8a)

**Comment by Shadie116** [comment]
![Screenshot 2024-02-28 033300](https://github.com/jasonrohrer/OneLife/assets/126846097/3adcda28-425e-4182-bb09-0da21763635d)
please make this game more of a challenge

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/8beee18d-abcf-4aa5-b1dc-6572a9ff05a0)
jason wow

**Comment by Shadie116** [comment]
you see this
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/6476309e-5f86-481d-baca-f42b7ce61c80)
clear they got a problem if we got enough trucks in a single family to power the economy of a small city.

**Comment by Shadie116** [comment]
call that shit amazon

**Comment by Shadie116** [comment]
@jasonrohrer  , I've literally spent more hours in the penitentiary than the actual game. please fix this

**Comment by Shadie116** [comment]
I could put this in 1000's of ways till the end of winter. Everything seems "expected"

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/c3f5451c-335a-4832-b946-b18f7e307286)
also donkey town leaves no place for forgiveness ever. People are not forgiving, you get stuck you're stuck

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/8d5b6278-ef63-46a1-b8b5-14ee35c51fbf)
this was in donkeytown afew months ago under the guides that nothing really mattered there.
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/711e2fb3-864d-4d88-ab56-730c4d9270ee)

**Comment by Shadie116** [comment]
I'd like to argue this game has regressed from its development back to its fundamentals which is you can give birth to kids and that's it. Anything else was strategically worked around and outlawed by people who were not the entire community but just random power-hungry people who were like 2% of a community of 1000's. Its only about what they want and not what people actually want I feel.

**Comment by Shadie116** [comment]
Ima sound off again, people fear that good things will be taken away from them. It is overcoming that fear that makes a good town. Adaptation to the fear via whatever the solution may be

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/78eadb8d-935e-4020-89c8-7f6d606ba43d)


I simulated a world without problems in this guys life simulator
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/c7a84e99-c4a3-477b-a8c5-2ca2f6318b34)
 It can just produce food forever, no need to reproduce or for complexity nor evolution. natural selection for this creature that just makes everything it needs is not a thing

**Comment by Shadyverycool** [comment]
Wait so if curses stop you from playing with people you don't want to play with how come 20$ lets me play with people who don't want to play with me. Cursing is more anti griefing than I don't like you. Life is unpredictable curses are futile

**Comment by Shadyverycool** [comment]
Also why is it that you want there to be an intended way to play the game of life. What makes life not boring is how unpredictable it is. When society, the thing you helped to create begins to collapse under it's own weight you need to maintain order. Yn but ofc we could just add an update that forces everyone to behave like good little humans. I think these updates that limit creativity and mask our human nature are stopping this game from being fun. I think it all started when people had to trade out of necessity or else their civilization wouldn't evolve into nothing big and when the world was built like an anthill

**Comment by Shadyverycool** [comment]
Then there was the bear update that ruined the biggest predator in the game. At this point just download rust 🙄
I hate being petty and mean but how is this even a survival game anymore? What are we surviving.. if its not other people than it's our hunger bar. Also about that hunger bar, all you need is a basket to survive. Time isn't dangerous, bears are not dangerous, the society you're creating will always be stable. You're basically playing life with cheats, I'm sure whatever middle eastern or African ancestors I had will have loved to have had these cheats on. Lions are now friendly till you feed your baby to them, camels stand in one place, you can now curse the French, British, Spanish and Germans. Machine guns don't work unless you're in a possy.

**Comment by Shadyverycool** [comment]
You took the phrase "your life is on the line" to a whole different level 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/454a288e-2499-4590-8929-8c04fab82c4b)

**Comment by Shadyverycool** [comment]
before all this was this

**Comment by Shadyverycool** [comment]
This is why these 15 servers you got running aren't being filled up, people don't got anything to look forward to but the same playstyle over and over and over again so why play something so repetitive. The social aspect of the game has lost any potential , group projects don't happen anymore, community is an exhausted aquafer which is why the majority of your moderation team up and dipped. If they can't influence the game after the final big update what's the point of being there.

**Comment by Shadyverycool** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/c5085d7b-148e-4dee-

**Comment by Shadyverycool** [comment]
also one more thing, I don't think the idea that I don't want you to be born near me applies when none of you know who eachother are in 3 months @jasonrohrer flimsy ideology

**Comment by Shadyverycool** [comment]
so in the end Ima just call it out, this is just forcing a gameplay style so Ima keep doing what I'm doing

**Comment by Shadyverycool** [comment]
![Screenshot 2024-03-16 125131](https://github.com/jasonrohrer/OneLife/assets/126846097/89aed4ae-9e79-47a7-907e-76ede57788aa)
ngl jason I'm pretty sure they used you 😂😂

**Comment by Shadyverycool** [comment]
Ok that's it, I'm replacing the curse sound with the rd2 low honor sound.

**Comment by AccountAbandonedArtByMyFriend** [comment]
Final message of resignation I guess:

We did so much together, we changed the game forever. With the power of group actions. Think you Jason for being the catalos for a change in the way the entire game will operate for most of the rest of my life and yours. I never thought me being a new player would create such a terrible impact on the quality of the game but it seems wherever I go things are left worsened. But me and my friends could not have done it without you. Thank you for the people I met along the way on this honorific journey to changing the game, change is still change.. no matter the impact. You can imagine I was never here, thank you for allowing me 1/7000's to make a brute force impact with the other 1/7000's, together we were 12/7000 and we changed the game in perhaps a negative way thanks to you. It's time I hop on noah's ark, I've been swimming in a flood of curses. I'll wait this one out. Now you are containing nobody, I'm loose but unknown. WOOO spooky Jason. Goodbye from your best friend shady! 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/05d37458-b596-435c-a3c6-4f8bce08e570)

**Comment by AccountAbandonedArtByMyFriend** [comment]
oh and I'm soo soo glad that I could make a big change so that millions in the future will have their hopes crushed because there are 100's of 10000's of 100,000,0s of things to cry about 
![OIP](https://github.com/jasonrohrer/OneLife/assets/126846097/522c4f21-8613-4745-a7df-e2a45cbe3507)

**Comment by AccountAbandoned** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/0fd38c93-cc99-4418-88dc-357940a02154)
the idea that personal curses even need to be this long is some bullshit, here is me taking a selfie with everybody who cursed me on my alt account, they lack the knowledge its me and if the same thing applies to me than do we even know eachother? Just revert the function and admit it was just targeted against a specific group of griefers

**Comment by AccountAbandoned** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/a6436c98-a33e-4962-ac2c-c33680a8b44b)
Also, Jason, peep the giftcard balence! luckly I got a good friend so I don't gotta pay for another copy. This game glazed itself so hard it died. This game don't even max out 70 on a Saturday
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/644d135c-4784-4ed8-b5d7-97cfa76b5cb2)

**Comment by AccountAbandoned** [comment]
long curses are worthless you can't play it off as nothing else
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/3724c4eb-0c0e-475d-abbf-ef7926a45e93)

**Comment by AccountAbandoned** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/f62e405d-ab8e-4168-960d-05386a6c8c16)
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/36f3539b-0cf1-4be9-a6bf-4066124e242c)
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/6e50ba5d-78d6-4179-b640-85c0cf152048)
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/7fb52e04-48d4-4a7b-80fc-296a5620c09)
long curses are worthless

**Comment by AccountAbandoned** [comment]
Try and prove me wrong @jasonrohrer

**Comment by AccountAbandoned** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/a5a3528c-c92e-42e5-acf1-cff327e81b83)
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/b7925460-5850-4776-9922-986b0761f814)
