### ISSUE TITLE
The apocalypse is literally impossible like literally 99.9% chance of happening absolutely 0.1% chance of happening ever if the entire game population of 1000's agrees they want it it would happen

### ISSUE THREAD

**Issue by 3x2xShady** [jasonrohrer/OneLife#1035]
I believe there should be accommodations for the fact that the average player is walking around with a fancy cheat client with a built in gps and navigation system while on a horse. My parents didn't even have that in the 80's, they had to use actual paper maps or map books to navigate in their cars. Make the apocalypse less of a hassle, game arks been running for like 2 years now

**Comment by Shadie116** [comment]
There is a reason nobody has been able to make an apocalypse in two years, the closest anybody had got was a year ago

**Comment by Shadie116** [comment]
another thing you gotta look at is you literally made it so it can only happen at a threshold of players????? what, all these players will hop on and stop it before it even happens

**Comment by 3x2xShady** [comment]
I don't think I'm getting rid of this one
