### ISSUE TITLE
People getting banned who are not me 😂😂😂😂😂😂

### ISSUE THREAD

**Issue by Shadyverycool** [jasonrohrer/OneLife#1037]
Screw this, I'm telling the teacher >:( So I was just breaking into the discord for the first time since November and what I saw was your own moderation team just banning people out of the fear that it was me. As a matter of a fact I left the game for near 3 months because of how mentally draining it was to see just a bunch of people saying lies about me. I don't really care now but they really banned over 6 people because they thought it was me throughout the three months I was not spying on the discord. The people in this game just got something going on at home or something. Just look up the tag of my name on discord and you'll see the weird shit and lies and all that whatever @jasonrohrer

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/4f25ed97-52f2-4ad4-b6a8-37cb4b91d31a)
=_=

**Comment by Shadie116** [comment]
like jason this is seriously sad
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/a9f8d2ba-dbf7-42aa-b31d-47cd472ded3e)
I could be watching from a whole other account and see some poor dude get banned

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/da027fad-f088-40de-83c2-4ed300db465a)
seeing this from my perspective it feels like I've been on vacation and this is just a cartoon where I'm just watching the whole thing unfold from a security tape. This is straight loony toons activity

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/f748b9de-c0bc-4bef-a499-4393fe04e676)
ok now that's just saddening no joke. rest in peace methman, this is about it for this issue

**Comment by Shadie116** [comment]
yeah but please get your server and your mods in check

**Comment by Shadie116** [comment]
This is like the one thing I'm serious about because they're accusing me of posting porn
