### ISSUE TITLE
radios translate language

### ISSUE THREAD

**Issue by AccountAbandoned** [jasonrohrer/OneLife#1038]
Long time bug, don't know what to say.
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/89196483-5e09-43fb-a14e-7ac8fe1b4eb6)
I don't think my great great grandfather had google translate

**Comment by Shadie116** [comment]
or my father for that matter

**Comment by Shadie116** [comment]
But yk all radios got built in micro software made by giant hot laser machines and cooled by huge fans

**Comment by Shadie116** [comment]
I remember my first time building one of these in game than I built the osi module in game as well and set up the internet on all ingame radios.
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/1f1bc3ec-7c03-4360-b173-d225648004bd) 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/aac0cff7-212f-454d-becf-7f2b865e45e0)
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/40cfb984-c0d5-4fd0-a77c-c84b57348e95)
