### ISSUE TITLE
Airplanes are bugged.

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLife#1040]
I think whats happening is, when you launch from a plane the game checks if the player who launched has any strips loaded, and if not, you end up in the wild. But if you do make a strip in your town and then take off, it'll always land on that strip even if you're trying to go to another strip, because that strip is the only one that you have seen in your life. So in order for it to work you'll have to have the strip you want to go to loaded in while taking off. Which of course doesn't make sense to do because you're trying to fly a long distance.

**Comment by jasonrohrer** [comment]
Well, it's not supposed to work this way, but I will test it.

**Comment by jasonrohrer** [comment]
Also, it looks in whatever DIRECTION you take off (East or West) for the closest pad in that direction to land on...

**Comment by jasonrohrer** [comment]
Oh, one thing to consider is that flight landing positions are NOT remembered across server resets.

So it's only "freshly built" landing pads that will work, not ancient ones left over in abandoned towns.

**Comment by jasonrohrer** [comment]
So yeah, it's not whether YOU have seen the pad.... but whether the "server" itself has seen the pad being built, since the last reset.

I will think about a way to preserve these across server resets...

**Comment by jasonrohrer** [comment]
Whoops!  And there's another bug!

When maxDistance is 0 (current setting) it seems like the next hop thing isn't working.  So if there's more than one strip, you only land at the closest one.
