### ISSUE TITLE
Way to determine Tutorial and Donkeytown lives in logs 

### ISSUE THREAD

**Issue by MrMendeleev2** [jasonrohrer/OneLife#1041]
Now that both Tutorial and Donkey Town coordinates are dinamic, (and in case of Donkey Town on the same Y coord as main spawn area) 
I would welcome a way to quickly determine DT and Tut characters in Logs that doesn't require obscure manipulations with birth X coord.

**Comment by jasonrohrer** [comment]
Tutorial lives aren't logged.... not sure if this changed at some point, or they never have been.  But they're not logged now.

D-town lives are logged... I will add logging a notation about that.

**Comment by MrMendeleev2** [comment]
They were logged before spawn location change. 
```2023_01_01: B 1672553479 5735253 fd63a4648b82d9af35a80de00339e1b6ad999902 F (5400000,3920) noParent pop=39 chain=1```
```2023_01_01: B 1672554007 5735284 fd63a4648b82d9af35a80de00339e1b6ad999902 F (6124730,189258) noParent pop=40 chain=1```
But indeed stopped after 2023_08_25

**Comment by cordy-123** [comment]
> They were logged before spawn location change. `2023_01_01: B 1672553479 5735253 fd63a4648b82d9af35a80de00339e1b6ad999902 F (5400000,3920) noParent pop=39 chain=1` `2023_01_01: B 1672554007 5735284 fd63a4648b82d9af35a80de00339e1b6ad999902 F (6124730,189258) noParent pop=40 chain=1` But indeed stopped after 2023_08_25

Tutorial lives were never intended to be logged. 

There was one reason for when they were accidentally logged.

Whole explanation can be seen here: https://github.com/jasonrohrer/OneLife/issues/914
