### ISSUE TITLE
Hold weapons like swords and bows on a horse 

### ISSUE THREAD

**Issue by AccountAbandoned** [jasonrohrer/OneLife#1042]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/fc209b18-ef71-47cd-a4af-579cabb07972)
this stock image Arabian warrior seems to be having alot of fun

**Comment by Shadyverycool** [comment]
this guy is just doing it for fun
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/0222c9e6-8158-4c05-af27-1761e3af53ad)
