### ISSUE TITLE
The reason why long curses have got to go.

### ISSUE THREAD

**Issue by CommunityExile** [jasonrohrer/OneLife#1043]
Don't take this as disrespectful: The long curse update is useless and a burden of an update as much as people would like to deny it. According to you "A curse is a mechanism by which you can say, "I don't want to play with this person anymore."  After you curse someone, it prevents that person from being born near you---or you being born near them.  Originally, this block was only supposed to be temporary, perhaps a few days.  But over time, my thinking about curses has changed.  If you really don't want to play near this person, why should the game second-guess your wishes by applying a time limit?  So the duration got longer, eventually reaching 90 days, which is where it stayed for quite a long time.

But even 90 days isn't that long, in the grand scheme of things.  Especially in the face of griefers who have dozens of accounts and cycle through them every 90 days after their curses wear off.  You thought you had taken care of this annoying player.  Having them buy an alt account is bad enough.  But then facing the original account 90 days later, popping up like an eternal and glacial whack-a-mole, is even more ridiculous.  How many times do you need to say it?  You don't want to play near this person anymore."

The long curse update is meant so you don't have to play with people you don't want to play with. Now allow me to explain what I think about that:

**Comment by AccountAbandoned** [comment]
Here is me on my entirely curse clean dirt clean alt account graciously provided by my friend: 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/112b311c-a156-48f5-b7e3-27af145affa1)
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/10aed0ef-6f16-478a-9e13-7973685d5276)

**Comment by AccountAbandoned** [comment]
The thing all these pictures have in common is that none of these people know its me. And so that's where the real issue comes in.  
These long curses you have do not serve to keep people away from those they don't like. You'll never know who they are if you never curse them and if you do curse them you and them won't know each other for three whole months, or as you said (90 days)

**Comment by AccountAbandoned** [comment]
Another thing I'd like to iterate is that curses allow the person you don't like to not be born near you, but for you to be born near them. Such is why the incident with the mass cursing killing families happened, there is no consequence to cursing in vein. @jasonrohrer  I'm hoping you'll hear me out formally and understand why long curses have got be removed.

**Comment by NoobForYears** [comment]
Sure. Anyone can buy a new account and pretend to be a different person any time they want. That doesn't mean the curse time should be shorter. 
Griefers can only pretend to be a different person on an alt for so long. Eventually they do the same things on their alt that got their main sent to donkey town in the first place. The shear amount of accounts some griefers have is just a testament to this. The fact that one of your griefer buddies had so many alts he was willing to give you one is just another example. 
I'm pretty happy with the 5 years update. I'd appreciate it it were left how it is. ❤️

**Comment by 3x2xShady** [comment]
You're entitled to what you think but I still think it's not beneficial and serves as an annoyance in the future

**Comment by 3x2xShady** [comment]
Also one more thing, we wasn't buying no accounts in Argentina, if we were all the accounts would be steam accounts. We bought them off your website. I'd be alot more of an asshole if I could by accounts for 78 cent 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/21ef54ec-d1ff-48b2-ae69-eb554ea3974b)
