### ISSUE TITLE
Account manager issue

### ISSUE THREAD

**Issue by XENOCIDE-10** [jasonrohrer/OneLife#1059]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/83a5455a-e4ed-4beb-8560-f96cb4e9ef50)
So I made an account manager to escape Donkey Town whenever I want and I spread it around my group mates, just came here to say that with the new programs I've been producing you can just kinda glide by like nobody ever knew you and they wouldn't have a problem because they don't know you. 

I got very little accounts but my version of the account manager has a cycle because I'm the soul developer and yayadayda. What I'm saying is this is an adaptation to curses and it kinda only locked the problem in a box because now in the future you can cycle accounts with ease and all that stupid stuff like spamming accounts. I just wanted to leave Donkey Town so I kinda had to Jason, it's all about wanting to not be a cornered rat or some nonsense like that. This client will also endorse buying accounts because it's a client manager. The more accounts the more freedom, I had to endorse this because it was my only choice out of checkmate. There wouldn't really be a need for an account manager if you got out every 3 months so I guess the problem will just get worse or something, IDK I love computers, you just math all over the paper till it works, I'm a strong believer that the curse time logically works as the freedom amount. **It feels like freedom is a thing to be bought.** the dystopia I had envisioned popped into existence leaving a shockwave that would change sales and how people played and thought about the entire player base. Before the update the point of buying accounts was to have a sense of freedom in a restricted world. Free and lawless with no care for rules created by the community to restrict them. Now the current 5 year system just gives people more of a reason to buy accounts. Instead of one group of people it's now more groups of people in donkey town who are going to be forced to buy accounts because of tarnishing. Not every individual user has the ability to amass more than one account. I see this as a gateway to advancement.

**Comment by ShadyInExile** [comment]
I thought i'd add people can use the autologin function as well in the next update of the client and I'm experimenting with twins

**Comment by ShadyInExile** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/20d56c34-e6cd-4905-8043-02e2e1775747)
check it

**Comment by ShadyInExile** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/d045c13d-25bf-40d1-85f1-23af656f4cdf)
I think I made somebody in the hivemind mad

**Comment by ShadyInExile** [comment]
btw this should be compatible with any client the way it's setup

**Comment by ShadyInExile** [comment]
Oh and btw I killed the Ans

**Comment by ShadyInExile** [comment]
It's content collection day, this is cool idea. I take into consideration.
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/5e7db0b4-b9ba-4743-adac-1833f50890f8)

**Comment by XENOCIDE-10** [comment]
I will reap this benefit
