### ISSUE TITLE
bring back tutorial button

### ISSUE THREAD

**Issue by tifaclocxii** [jasonrohrer/OneLife#1063]
This game has missing tutorial button.I want tutorial for testin eve name

![tutorial button missing](https://github.com/jasonrohrer/OneLife/assets/167689678/c4082963-5f3d-4ff6-8f0d-46016bdc060b)

**Comment by MarkLindsay** [comment]
Here is the list of valid last names:
https://github.com/jasonrohrer/OneLife/blob/master/server/lastNames.txt

**Comment by DougLefelhocz** [comment]
This works fine for me.  Sometimes the tutorial button disappears, because one died in a tutorial area without lighting a torch.  If one logins after that, my experience has consisted of spawning into a tutorial area.  Then the tutorial button comes back once I light a torch.

**Comment by jasonrohrer** [comment]
I can't reproduce this with the vanilla client.  Closing for now.
