### ISSUE TITLE
AHAP: Publish voting data as part of public data logs

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1064]
Please :)

**Comment by MrMendeleev2** [comment]
I would really prefer secret ballot. 
Maybe new hash function to generate email-hash for every election to anonymize votes and but keep transparency...
Something like this could work, but i certainly wouldn't want more OHOL Illuminate action with tracking your votes too.

It just feels bad to have possibility to interfere with sacred ritual of vote casting

**Comment by connorhsm** [comment]
Very much in support of proper anonymity.

The data is all I was interested in. eg. "Only 10% voted this week" or "10 people received more than 3 votes" or "This person got 10 votes and that person got 11"

**Comment by jasonrohrer** [comment]
ahapGate is tracking all this.

I will create a votingStats page for it.

**Comment by jasonrohrer** [comment]
http://onehouronelife.com/ahapGate/server.php?action=show_vote_stats
