### ISSUE TITLE
Rocket animation character needs translation

### ISSUE THREAD

**Issue by MrMendeleev2** [jasonrohrer/OneLife#1067]
So, everyone alive sees person fly away in the rocket, and pilot can give a speech. 
Problem is language restrictions still apply, and many just read gibberish.

I believe it would be nice if we could understand what they say, they are supposed to talk through radio anyways. And radio does translate language.

**Comment by jasonrohrer** [comment]
Interesting!

They also would see gibberish from other players who don't speak their language.

Actually, I think this is fine.  If they are from a foreign land, it should feel different than if they are from your village.  A different sense of pride... like watching the Russians walk on the moon first.
