### ISSUE TITLE
Overwriting previously saved transition adds extra author line to txt file

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1071]
When changing a transition that is saved previously, it writes a new author line, even if the previous one is by the same user.

I understand doing this to keep track of different users changing the same transition, but don't know if it's intended to do this for the same user for each time the transition is saved again.

Here is an example of what happens when changing one object in the transition:
![image](https://github.com/jasonrohrer/OneLife/assets/494864/d0da8780-197a-4f73-b92d-90968eac2da8)

![image](https://github.com/jasonrohrer/OneLife/assets/494864/9f9be486-b26b-437b-bab4-82ed4cb19811)

**Comment by jasonrohrer** [comment]
Yeah, this is a bug!

**Comment by jasonrohrer** [comment]
Ah... I see the problem...

If the transition has no comment, the first author= line is treated like the comment, not the author!

And that causes a second one to get added.
