### ISSUE TITLE
Wrong ID's assigned when using import_replace in AHAP editor with a mod exported from OHOL

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1072]
When using the "import_replace" folder to replace parts or entirety of a user submitted mod, if the object does not already exist, it creates a new object using the object ID from the user who submits it. 

So if someone exports a mod for me to replace from OHOL and I import it into AHAP, if it contains brand new objects it creates object starting from f.ex. 5001, 5002, etc. and bumps up the nextObjectId.txt as well, instead of continuing from the object ID's currently in my folder; 201,.202, etc.

In the screenshot below I added the mod to the import_replace folder, all of these sprites and objects already existed in the editor.

![image](https://github.com/jasonrohrer/OneLife/assets/494864/087a5622-15ce-48b1-bf27-a8b8088b9c73)

An already existing object as reference:

![image](https://github.com/jasonrohrer/OneLife/assets/494864/429f6a0b-e3e5-44ee-bec7-adf0accc18ba)

![image](https://github.com/jasonrohrer/OneLife/assets/494864/be0527f8-ebe8-47f1-8c6f-dee7304e11f9)

**Comment by jasonrohrer** [comment]
Working on fixing this.
