### ISSUE TITLE
Editor- vanishing sprites inconsistency

### ISSUE THREAD

**Issue by Jinbaili83** [jasonrohrer/OneLife#1073]
Object and Scene tabs use different ways to display vanishing sprites. This got changed to fix issue OneLifeData7#869.

**Comment by jasonrohrer** [comment]
Ah, I see...

The slider in the Scene Editor has steps in it (one step per use), where in the Object Edtor, the slider is continuous, and you have to drag it past the first step to see a change.

I will look into fixing this.
