### ISSUE TITLE
Eve Spawns and Apocalypse?

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1077]
I see the code changes [here](https://github.com/jasonrohrer/OneLife/commit/a0833fac0d7fad193d5b3e908fff942384067fba) and [here](https://github.com/jasonrohrer/OneLife/commit/60adaf20c96ec794aabd9becda8adfc2e48656d5).

I can tell that it shifts living players.

But does it shift _new_ Eve positions also?

**Comment by jasonrohrer** [comment]
Ah, good catch!
