### ISSUE TITLE
Early game resources tough to get till iron age.

### ISSUE THREAD

**Issue by 4ferrocyanide** [jasonrohrer/OneLife#1078]
![image](https://github.com/jasonrohrer/OneLife/assets/167921232/4716474b-211b-4309-be2d-a939d21026cf)

**Comment by 4ferrocyanide** [comment]
Also with the turkey thing again you have no way to cut turkey early game without getting a knife despite being able to easily hunt them and cook them with an oven and fire.

**Comment by NotSoShady80** [comment]
I think this is a real issue and I approve

**Comment by Tarr-OHOL** [comment]
Cringe.

**Comment by NotSoShady80** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/170677766/e9d1e926-c740-49ef-abcc-b472fd73e6b1)
This you lil bro, littlest of brothers??

**Comment by NotSoShady80** [comment]
I think these hours might be primed for my kind of people Tarr.

**Comment by NotSoShady80** [comment]
Well really 45 minutes is what it took

**Comment by GnihtonSeodYdahs** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171100996/7014a78d-581a-413b-bc72-d1040fbdd097)

**Comment by GnihtonSeodYdahs** [comment]
Really 45 minutes

**Comment by GnihtonSeodYdahs** [comment]
It seems like you were going to do something today but gave up
