### ISSUE TITLE
Mods not removed from import_add after importing

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1079]
When importing mods, the mods imported gets copied into the "imported" folder, but does not get removed from the import_add folder, so you need to remember to manually remove it from this as well as the import_replace folders, if not if will keep creating new duplicate objects everytime you lauch the editor untill the OXZ file(s) are removed.

I suggest it gets automatically removed either at the end of importing, or when closing out of the editor cause this is easy to forget and causes extra confusion and a lot of extra work if there is multiple mods or mods with many objects you are importing.

**Comment by jasonrohrer** [comment]
This is surprising... I've tested this a bunch...  I'm guessing there's a bug here, maybe on Windows only.  Looking into it.

**Comment by jasonrohrer** [comment]
Yeah, on Linux this is definitely working correctly...

**Comment by jasonrohrer** [comment]
[NewColoritems_104_16521c.oxz.zip](https://github.com/jasonrohrer/OneLife/files/15488499/NewColoritems_104_16521c.oxz.zip)

Adding a sample import file to test with.

**Comment by jasonrohrer** [comment]
Indeed!  Removing the imported stuff isn't working on Windows.  Sorry about that!

**Comment by jasonrohrer** [comment]
This line isn't working on Windows:

https://github.com/jasonrohrer/minorGems/blob/aeaa3543bb856c90dea53ed54fe19d12a2e781a5/io/file/File.h#L877

**Comment by jasonrohrer** [comment]
Actually, the problem seems to be that elsewhere in the importer code, there are fopen calls without corresponding calls to fclose.  Windows won't let a file get removed that is still open somewhere.
