### ISSUE TITLE
Tutorial confusingly participates in server events

### ISSUE THREAD

**Issue by d0sboots** [jasonrohrer/OneLife#1080]
Apparently, when you are in the tutorial, you are still logged in to a server. This probably makes sense for architectural reasons, but it leads to some weirdnesses as a new player:

* You see a "bell" label, when this is never discussed in the tutorial. But this can be ignored.

* If you are ~~un~~lucky enough to witness a rocket launch while in the tutorial, you will be *very* confused, especially since it takes over the whole screen.

Yes, both of those *did* happen to me.

**Comment by squishysquid** [comment]
honestly the whole tutorial probably needs a rework. I've watched streamers try to pick up the game and have that thing destroy them.

**Comment by jasonrohrer** [comment]
Yeah... there's the question about whether the tutorial is needed at all...

I never wanted to have one, and the game didn't have one for a long time.

There are also negative reviews on Steam about people not being able to skip it, or about it being too long, or too hard, or too much reading.  And then phase 2, the solo survival challenge, is even more confusing.  I thought this was a multiplayer game!

I'm somewhat tempted to just disable it.

**Comment by jasonrohrer** [comment]
I mean, it's easy enough for me to fix this bug without disabling the tutorial.... I think I can turn off the BELL stuff, and obviously disable sending tutorial players the rocket animation trigger.

**Comment by d0sboots** [comment]
I think I skipped phase 2? Not sure how exactly. I found phase 1 useful, but I explicitly went into it *wanting* a chance to hone my skills without letting anyone else down, so I might be odd that way. For that reason, I found the "optional/don't come here" part of the phase 1 tutorial the most useful.

**Comment by DougLefelhocz** [comment]
> Yeah... there's the question about whether the tutorial is needed at all...

This was not a question posed or implied by the original post.  Nor has it gotten posed or implied by many other posts about the tutorial here and on the forums also.  You are not agreeing with the sentiment of the person who posted it.

The issue was NOT that the tutorial does something.  And if it helps some players, how could it be absolutely bad to begin with?

The issue was that *some* particular information gets thrown at tutorial players which has *no relevance* to their learning.

**Comment by jasonrohrer** [comment]
Good point.  Polls show that most people like the tutorial anyway:

http://onehouronelife.com/reviewServer/server.php?action=list_polls

So yeah, I will fix this issue, and leave the tutorial, for now.
