### ISSUE TITLE
New log file data from "Please download the latest version" screen

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1082]
So, I'm still getting the same issue as after every update.
And here is the log output;

> L4 | Sun May 19 23:49:38 2024 (981 ms) | general | New game starting up
> L4 | Sun May 19 23:49:38 2024 (981 ms) | general | Target game image size:  1280x720
> 
> L4 | Sun May 19 23:49:38 2024 (982 ms) | general | Ideal window dimensions:  1280x720
> 
> L4 | Sun May 19 23:49:38 2024 (982 ms) | general | Trying to start in fullscreen mode.
> L4 | Sun May 19 23:49:38 2024 (983 ms) | general | The following frame rates are considered possible:
> L4 | Sun May 19 23:49:38 2024 (983 ms) | general | 30 fps
> L4 | Sun May 19 23:49:38 2024 (983 ms) | general | 60 fps
> L4 | Sun May 19 23:49:38 2024 (983 ms) | general | 100 fps
> L4 | Sun May 19 23:49:38 2024 (983 ms) | general | 120 fps
> L4 | Sun May 19 23:49:38 2024 (983 ms) | general | 144 fps
> L4 | Sun May 19 23:49:38 2024 (985 ms) | general | 165 fps
> L4 | Sun May 19 23:49:38 2024 (988 ms) | general | Constructing ScreenGL with requested 1280x720, 60 fps, fullscreen(1)
> L4 | Sun May 19 23:49:38 2024 (988 ms) | general | Setting borderless mode for fullscreen
> L4 | Sun May 19 23:49:38 2024 (988 ms) | general | Current screen configuration is 2560x1440 with aspect ratio 1.77
> L4 | Sun May 19 23:49:38 2024 (988 ms) | general | All resolutions available
> L4 | Sun May 19 23:49:38 2024 (988 ms) | general | Sticking with user's current screen resolution
> L4 | Sun May 19 23:49:38 2024 (989 ms) | general | Adding 1 to borderless window height of 1440 resulting in total height of 1441
> L4 | Sun May 19 23:49:39 2024 (272 ms) | general | ScreenGL gave us 2560x1441, 60 fps
> L4 | Sun May 19 23:49:39 2024 (273 ms) | general | Trying to load pointer from graphics/bigPointer.tga
> L4 | Sun May 19 23:49:39 2024 (274 ms) | general | Setting non-integer-scaled screen image size of 2560x1440
> L4 | Sun May 19 23:49:39 2024 (436 ms) | general | Successfully opened audio: 44100Hz (requested 44100Hz), sample buffer size=1024 (requested 1024)
> 
> L4 | Sun May 19 23:49:39 2024 (514 ms) | general | setViewSize called with 1280.000000
> L4 | Sun May 19 23:49:39 2024 (514 ms) | general | setLetterbox called with 1280.000000x720.000000
> L4 | Sun May 19 23:49:39 2024 (616 ms) | general | OneLife client v425 (binV=425, dataV=11) starting up
> L4 | Sun May 19 23:49:39 2024 (616 ms) | general | setViewSize called with 1280.000000
> L4 | Sun May 19 23:49:39 2024 (616 ms) | general | setLetterbox called with 1280.000000x720.000000
> L4 | Sun May 19 23:49:40 2024 (388 ms) | general | Got required AHAP version from server: 12
> L4 | Sun May 19 23:49:40 2024 (388 ms) | general | Our AHAP dataVersionNumber = 11 < required version number 12
> L4 | Sun May 19 23:49:40 2024 (388 ms) | general | Trying to start AHAP auto-update from update server http://onehouronelife.com/ahapUpdateServer/server.php
> L2 | Sun May 19 23:49:40 2024 (388 ms) | general | Starting AHAP data update failed
> L4 | Sun May 19 23:49:41 2024 (299 ms) | general | exiting...
> 
> L4 | Sun May 19 23:49:41 2024 (299 ms) | general | exiting: calling SDL_CloseAudio
> 
> L4 | Sun May 19 23:49:41 2024 (355 ms) | general | exiting: Deleting sceneHandler
> 
> L4 | Sun May 19 23:49:41 2024 (355 ms) | general | Freeing sound sprites
> 
> L4 | Sun May 19 23:49:41 2024 (355 ms) | general | exiting: freeing frameDrawer
> 
> L4 | Sun May 19 23:49:41 2024 (357 ms) | general | exiting: Deleting screen
> 
> L4 | Sun May 19 23:49:41 2024 (357 ms) | general | exiting: freeing drawString
> 
> L4 | Sun May 19 23:49:41 2024 (357 ms) | general | exiting: calling SDL_Quit()
> 
> L4 | Sun May 19 23:49:41 2024 (386 ms) | general | exiting: Done.

**Comment by jasonrohrer** [comment]
Looks like there needs to be even more logging in there about why starting the update fails.

**Comment by DopiePanda** [comment]
I found out what is causing this specific issue.

It's the following line in the minorGems file diffBundleClient.cpp;
https://github.com/jasonrohrer/minorGems/blob/master/game/diffBundle/client/diffBundleClient.cpp#L167

This is what's triggering the follwing code in game.cpp;
https://github.com/jasonrohrer/OneLife/blob/master/gameSource/game.cpp#L1587

So it seems like this is specific to having a .git folder in the OHOL game install directory. If there's a .git folder in there, the auto update will always fail.

**Comment by jasonrohrer** [comment]
Ah... yeah, I think this is by design.

Because... if there's a git folder in there, you DON'T want to pull down auto-updates, since you are probably pulling from git already.... or working on live data that can be accidentally overwritten by an auto-update.

This is hopefully not affecting anyone who's simply playing the game on Steam...

And it shouldn't be affecting MOST content creators, since they don't have git push access.  It should only be affecting you, Mr. Content Creator.  Lonely old you.

BUT....

I will add some more logging about these failure cases.

**Comment by DopiePanda** [comment]
With how it is now, all content creators *should* initiate a local git repository in their modding directory, cause if they don't do that, and they are working on mods that have not yet exported, the auto-update will overwrite all of their work without warning them as soon as they launch the game if they wanna check something out on the local server.
