### ISSUE TITLE
AHAP while holding any object, a grey highlight will appear when you hover your cursor over the square of another object.

### ISSUE THREAD

**Issue by sadlero** [jasonrohrer/OneLife#1083]
**Description:**
While holding any object, a grey highlight will appear when you hover your cursor over the square of another object.
This bug does not occur when you are not holding an object.
It's most visible on darker biome backgrounds, but occurs on all biomes.

Version: 12
App ID: 2787060
Build ID: 14328987
Installed content updated: May 20, 2024 at 9:39 PM CEST.

**Repro rate:** 100%

**Repro steps:**
1. Launch AHAP and login and be born.
2. Wait until you are at least 3 years old in order to pick up objects.
3. Pick up any object (I tested with Metal Basket and Booberry Squishwrap)
4. While holding an object, hover your mouse over _the square of_ any other object (but don't hover over the object itself).
5. [FAIL] The square the object is on is highlighted.
[Desired behavior] Only objects are highlighted when they are hovered over, not their squares.

Here are some screenshots of how the game reacts to hover when you are holding an item vs. not holding an item.
![grey-highlight](https://github.com/jasonrohrer/OneLife/assets/112980434/df2b412a-d60f-46f8-b742-ef5511ea808c)

![Without-holding-object](https://github.com/jasonrohrer/OneLife/assets/112980434/62e2df97-71d2-4997-8ac0-61a7d8ad7fa1)

**Log files:**
[log.txt](https://github.com/jasonrohrer/OneLife/files/15381682/log.txt)

**Comment by jasonrohrer** [comment]
This is normal behavior in OHOL too.

It's showing you what square you are hovering over.  If you hover over an empty square, you will eventually see that square highlighted too.  This is telling you, "This is where you will walk if you click," or, "This is where you will drop your item if you right-click."
