### ISSUE TITLE
Life Tokens are near vestigial 

### ISSUE THREAD

**Issue by 4ferrocyanide** [jasonrohrer/OneLife#1087]
The server only has like 4-5 families and nobody is going to /die 48 times in under 5 minutes which is why I think it's an issue. People will just /die on any town than move on to the one they like which sometimes leaves places undeveloped. People can just move over to wherever they want.

**Comment by selb** [comment]
They're clearly not vestigial if they successfully kept you from endlessly spamming `/die` trying to get out of DT. :)

**Comment by 4ferrocyanide** [comment]
The end goal is to reduce the amount of tokens, nobody was talking about dt. I'm trying to abid by the rules of issue making in not screaming out a solution like an idiot

**Comment by DopiePanda** [comment]
Of course YOUR goal would be to lower everyone elses life tokens when you have multiple accounts to use.

**Comment by 4ferrocyanide** [comment]
Not really, you shouldn't have no problem with that if you're not cursed.

**Comment by 4ferrocyanide** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/167921232/f21ff501-bae9-4f69-b0b0-2d334c277e47)
In this outdated forum document it says there were only 24 lives a day and you get one life when it deeps below 12 lives every hour. That makes it vestigial by now's standards because you got 48 lives. It's his choice what the solution is though so don't call me pushy towards any type of solution.

**Comment by DopiePanda** [comment]
>I just hate it when you're playing normally and babies just come and go to the nearest rich town they find while towns like browns and blacks are literally dying.

That's very rich coming from someone who has been killing the brown and black families several times, and even recently.

**Comment by DopiePanda** [comment]
>It's his choice what the solution is though so don't call me pushy towards any type of solution. There are infinite @DopiePanda reguardless it's not my problem. It's an issue

It's a personal issue for you Shady, and does not affect the 95+% of the player base. And as you admitted in your previous post, you dont care about the community.

**Comment by 4ferrocyanide** [comment]
Who said I'm Shady Dopie, try being professional "content leader"

**Comment by 4ferrocyanide** [comment]
Who said Shady was the only one making an account manager. Also stop flooding the issue with unnecessary messages.

**Comment by 4ferrocyanide** [comment]
now ima have to make another issue so i can look more neat, thank you dopie
