### ISSUE TITLE
If game can't find any of its files, it shouldn't just crash

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#1089]
On many platforms, it can probably pop-up a system message box explaining the problem, then exit gracefully.

**Comment by dopiecockroach** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171101838/1203f0b8-6ac1-42a3-8bce-aa49d35efa20)

**Comment by dopiecockroach** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171101838/aafd18a4-0d73-493e-bcc9-542909c49f54)

**Comment by SeriousAutomatations** [comment]
Why do so many people dislike this? I'm pretty sure that's a picture of the fucking Simsons

**Comment by HexatronicsHomeboy** [comment]
I want to contribute 🥺

**Comment by GnihtonSeodYdahs** [comment]
You guys are all not being real shadys right now 
![image](https://github.com/jasonrohrer/OneLife/assets/171100996/b3e9f86e-6f9c-4be1-a28a-4fc4dfd24326)
I might have to stand up 
![image](https://github.com/jasonrohrer/OneLife/assets/171100996/6897df69-cecf-4d16-ad22-229369f2988c)

**Comment by ContractTakingRichHuman** [comment]
poetic 
![image](https://github.com/jasonrohrer/OneLife/assets/171103057/74c34f59-4572-48f5-beb0-ffbb5a54a262)

**Comment by GnihtonSeodYdahs** [comment]
Who the fuck uses youtube emojis sorry we can't be friends anymore. Get off this planet. Go to another planet dork.

**Comment by ContractTakingRichHuman** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171103057/9f4b854b-041b-426a-91c9-6912d95eb9c5)

**Comment by ContractTakingRichHuman** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171103057/f844aba2-0339-4b05-ba2b-4390fe195b0b)

**Comment by ContractTakingRichHuman** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171103057/6dde88c8-5d30-4c94-a8e5-ac16c9f75c5d)

**Comment by ContractTakingRichHuman** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171103057/89c9c4f7-60ca-41cb-ac4f-7b09693314cd)

**Comment by GnihtonSeodYdahs** [comment]
Wow you really opened my eyes with that.

**Comment by GnihtonSeodYdahs** [comment]
You really showed me how the brain processes symbols. If I scrape my knee the image of me scrapping my knee is seen as dangrous. Now when I make Scrape knee = ! I know that ! hurts. If you tell me that gun = ! I know that gun is == ! so I know not to mess with gun.

**Comment by GnihtonSeodYdahs** [comment]
Many things ! me

**Comment by GnihtonSeodYdahs** [comment]
Yup I do and God I do think you for granting me over 122 available and free Ip Addresses so if this one dies we can go to the next.

**Comment by GnihtonSeodYdahs** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/171100996/9f4c7625-a2a4-4590-8f19-383884725848)
Next time I'm going for 20.
