### ISSUE TITLE
Author tag being overwritten upon save 

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#1093]
Hiya! We have found out that author tags on all of the different elements (objects, animations, etc.) gets overwritten if another person interacts with them.

So if you make a game object and export it to me, it will have your author tag, but if I import it and make a change, i.e. set the object to be permanent, then replace the object, the object authorship is overwritten by me.

And as content leader I have had to do a lot of small changes to multiple of the mods, so I might have ended up with a lot of author tags I am not supposed so have.

Once an author has been signed to an object, there should be no way for it to change thereafter, especially using the "Replace" button, only when "Save new" is clicked

**Comment by oholseven** [comment]
Today I made objects in the AHAP editor and it was attaching someone else's ID to my objects, using my original sprites, so I deleted the whole folder and tried making an object in the game folder and my ID was back.  We might need to keep an eye on the ID attached to files, to make sure it is correct.

**Comment by jasonrohrer** [comment]
Yeah, sounds like I should fix this to make it permanent, and not get overwritten.  So the original author gets credit.

This is already true for sprites and sounds, which never get changed after being made.

**Comment by jasonrohrer** [comment]
Also, wherever you are editing, you need to make sure this file contains your correct email (or fake Steam-id email):

`settings/email.ini`

I'm definitely seeing some objects that have been committed, or that are packaged into mods, which have their hash set to the "blank email" hash.  I believe this "blank email hash" is:

`102CA969F5`

So we can keep a lookout for it.

**Comment by jasonrohrer** [comment]
Also, I will NOT change this behavior for transitions, since.... well, changing a transition is pretty much the same thing as making a new transition.  So if you edit someone else's transition, it will get overwritten with your hash.  (We only expect the content leaders to be doing this, since transitions can't be exported in mods).
