### ISSUE TITLE
Servers Restarted Strangely

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1099]
I only know what people on discord said.  [Relevant reports start here](https://discord.com/channels/328215300279500800/328215300279500800/1256873026889191445), but there were several sources and some tried to use screenshots it seems.

**Comment by jasonrohrer** [comment]
Yeah, I don't think the server actually went down...

I think there was a network outage during that time, and the server was simply unreachable (though still running).  This might cause many people to die of starvation, of course.

This happens from time to time, but unfortunately, it's outside of my control.


I do get an email every time the server restarts, so I always investigate if that happens unexpectedly for some reason.
