### ISSUE TITLE
Apocalypse Bugged... Says Something about Rockets

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1101]
I think Shady had stuck a bloody knife in the tower, which did stick (as can get seen... but it's at/near the bottom of the tower).  But, apparently it didn't do anything.

In this [video](https://clips.twitch.tv/CoyElegantUdonSoBayed-GTrPcTYqE4SAtYUc) a little after, Reformed sticks a knife in the tower, but it just gives some message about 'orbital alignment' and 'rocket construction', whatever that is.

Also, is the apocalypse supposed to teleport tutorial and donkeytown players to (0, 0) with everyone else if it happens?  I was waiting in a "solo challenge" area when they were about to do it, but it didn't happen, so I couldn't tell how it did actually work.

Edit: The message says:

"ORBITAL ALIGNMENT WITH ANOTHER PLANET DETECTED.  ROCKET CONSTRUCTION LOCATION IDENTIFIED."

**Comment by Kaden56** [comment]
Nah, I know the rocket cycle. It was actually the time for that message to appear.

**Comment by DougLefelhocz** [comment]
At about 20:03 [here](https://discord.com/channels/@me/1259108931595407440/1259112115806011462) there's a knife stuck into the tower.

**Comment by jasonrohrer** [comment]
Yeah, Apoc was just turned off on BS2 in the server settings for some reason.  Sorry about that.  When the servers restart today, that will be fixed.
