### ISSUE TITLE
Apocalypse is Too Difficult And Available Anytime/No Arc Resets/Possibility of Too Early Arc Resets

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1102]
Tarr went over some of the problems with the [apocalypse](https://github.com/jasonrohrer/OneLifeData7/issues/1243) here.  People shouldn't have to use alt accounts to do an apocalypse.  Nor should they have to farm for a ghost and then have a poor sleeping schedule.  Sleeping 50 minutes and getting up for a bit with a clock for 10+ hours or whatever is not a one hour game.  Things like that shouldn't be required nor encouraged.

One of the problems with the original apocalypse system was that it could happen very early after the last one.  That happened multiple times on April 1st, 2022 and was repeatedly awful.  Any arc reset also has the threat of an apocalypse starting up immediately after the last one and then happening on the next day.  Anyone who does that though isn't playing the game constructively.  Apocalypse shouldn't be something like that which someone could, theoretically, exclusively focus on.  People who want all resources on the map gone should at least sometimes play in more advanced stages of the game when the main families are far from The Tarr Monument and The Original Methman Monument.

The Apocalypse shouldn't even be available until an extended period after the last arc reset.  24 hours may have once made sense, but with the possibility of making an Additional Methman Monument, that makes for *far* too short of a time, since players will still be rather close to the original monuments after 30 hours.  The apocalypse shouldn't be possible to even start for a month.  Or maybe 3 months.

Or maybe it should only be possible if the latest Eves that can have children (and are not donkeys) have gotten at least 10,000 or something tiles away from the original monuments.

And once the arc has reached an "old" period, the apocalypse shouldn't be difficult to complete or have people using alts to try to do it.

Honestly, other games with consistent arc resets must have a better system than the inactive, yet stupidly conceivable too early apocalypse system of this game.

**Comment by MarkLindsay** [comment]
It’s easy if most everyone thinks it’s the right thing to do. What is your reason for doing it?

**Comment by DougLefelhocz** [comment]
> It’s easy if most everyone thinks it’s the right thing to do. What is your reason for doing it?

So all families are similarly timed and so that people build on their ancestors work, not loot from other deceased family's settlements.

**Comment by MarkLindsay** [comment]
To prevent that, you want to erase everything when the first family dies out? Is that right?

**Comment by DougLefelhocz** [comment]
> To prevent that, you want to erase everything when the first family dies out? Is that right?

No.

**Comment by MarkLindsay** [comment]
Ok, sorry, I was too reductive.

You want people to not loot dead towns. And you want people to not abuse the apocalypse. (Still overly simplified, I’m sure.)

I’m pessimistic that those things can be engineered out when every change feels like whac-a-mole. I’m probably thinking too small.

**Comment by jasonrohrer** [comment]
Well, for now, we'll see how often the apocalypse happens.

It's been 5 days since the last one.
