### ISSUE TITLE
Apocalypse Teleports Tutorial Players and Makes Them Fertile

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1106]
PloddyOneDay talks about this starting [here](https://discord.com/channels/328215300279500800/328215300279500800/1261810720929087518).

Maybe that's alright.  Maybe it doesn't fit with the game though.

But, I would guess that applies to *donkeytown* players also.  I'm not sure that they should get teleported to around the origin after an apocalypse and become fertile also.

**Comment by jasonrohrer** [comment]
Tutorial players and d-town players are NOT moved during the apocalypse.  They are skipped.

However, the map IS wiped, so the tutorial areas are wiped also.

I will test this now and double-check that it works this way.

**Comment by jasonrohrer** [comment]
I just tested it, and tutorial players stay put during apocalypse.  They also don't lose their "tutorial" status, which keeps them infertile.

D-town players are subject to the same code, so that should be the same.
