### ISSUE TITLE
AHAP voting is too easy to forget

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1107]
I've consistently watched AHAP votes remain <3 for a few weeks, there was one case in the past week when it reached 5 after I believe ~~15~~ 27 or so people played at once.

I've just sniped the Content Leader because of this. You could argue this is working as intended, but I'd like to suggest many people are simply never setting up their vote because the client doesn't make this very obvious.

I'd also note that if votes are equal, wouldn't it be best the incumbent retains power instead of changing the leader?

![image](https://github.com/user-attachments/assets/933de590-d14a-4d68-953e-b0cdba4e6a34)
![image](https://github.com/user-attachments/assets/8e1c1e9d-e8b5-46a7-886d-9479cdf2ef1d)

**Comment by connorhsm** [comment]
It also appears that the leader "flip flops" between the two equal options. I've had the invite to GitHub 3 times now, this happens every so often when I keep checking my "planet" page in the client.

**Comment by TanyaPegasus** [comment]
I would suggest that even having a button labelled "vote" would go a long way towards correcting this. 
I just opened the game, specifically looking for the voting section, and it still took me a moment as it is very un-intuitive. 
If I had trouble finding it, when specifically looking for it, the average player is not even going to think about it. This is especially true if they've needed to delete files in the past to make an update work, and then never thought about voting again.

**Comment by connorhsm** [comment]
If candidate names could also please be made unique?
It's not clear who is who on the count.

**Comment by MarkLindsay** [comment]
Is there anything wrong with showing their actual github handle? Candidate 1 could be me for all I know. Or what if I had a typo in my vote?

**Comment by connorhsm** [comment]
It doesn't appear that a GitHub username is verified as a valid account, only that another AHAP user has input that they are that user. You'd have to moderate the user input.

Would be nice to consider something like the unique leaderboard names, which has been repeated in other systems before.
http://onehouronelife.com/fitnessServer/server.php?action=show_leaderboard

**Comment by connorhsm** [comment]
I've spent 3 days campaigning in the unofficial AHAP Discord to NOT be the leader. It took until now for 1 of the known 73 players to vote.

![image](https://github.com/user-attachments/assets/f0741d60-4272-4ba1-8ece-3e54c47c48b0)

**Comment by DopiePanda** [comment]
There are a few more votes now (7 total), but unless we remind these people to vote again every single week, it will probably be back to 1 or 2 total votes already by next week.

I think vote retention should be increased to at least 30 days or potentially even longer, either that or making it easier to vote without having to launch the game.

The current vote stats page should also be updated to include the GitHub names of the candidates.

**Comment by jasonrohrer** [comment]
Okay, I will update it to show the github names.

Also, the POST button will change to say VOTE.

**Comment by jasonrohrer** [comment]
Okay, votes are now counted over 30 days, and the github names are shown.

Also, the full list of potential candidates is now show.

See:

http://onehouronelife.com/ahapGate/server.php?action=show_vote_stats

**Comment by connorhsm** [comment]
Thank you!

**Comment by connorhsm** [comment]
@jasonrohrer Thank you for the changes you made above.

I'm still concerned that voting is hidden behind a button named as "PLANET". After you click this "VOTE" button you still haven't actually voted, you must live a life for the vote to count, if I understand correctly.

I understand if you have the client open, you can reasonably expect someone to play a game, but the button being labelled "VOTE" is misleading.
