### ISSUE TITLE
AHAP copyChangesToRepo script copies "unmodified" files.

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1109]
When making AHAP data changes, there are cases where I might edit an object and save it (replacing) but then undo the change by editing it again, meaning all the values of the object are now equal to what's in the remote repository.

The copyChangesToRepo script still copies these object files into the repository to be committed, where git shows they are modified, but not any visible characters. I suspect this is simply line ending changes, though I would expect this to be handled at or before the script.

**Comment by jasonrohrer** [comment]
Well, that script is just kinda blindly copying things over into the git repo, where git decides wither things have changed or not.

If there's a line-end issue... I think you need to make sure that git is NOT fixing line ends when it checks things out onto your Windows machine....  if it's changing the Unix line ends to Windows line ends, that might screw things up.

I'm pretty sure the OHOL editor is outputting Unix line ends only.

Git is probably fixing things to make them consistent....

But anyway, is there a way, in your Git checkout, to tell it NOT to change things to Windows line ends?  Maybe a setting in your Git client?
