### ISSUE TITLE
Dead puppies

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#111]
Hungry puppies that die still do not decay, only wolf puppies decay.

**Comment by Stylingirl** [comment]
Same goes for all dead dogs, except for dead semi-tame wolves.

**Comment by jasonrohrer** [comment]
Are you sure about this?

OneTech does not handle patterns correctly.

I'm testing it on my end, though.

**Comment by jasonrohrer** [comment]
Yeah, seems like it's working in the actual game.  Not sure what's up with OneTech on this one.  See Kazetsukai/onetech#103
