### ISSUE TITLE
AHAP users can imitate any GitHub user

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1112]
I can specify my GitHub username in AHAP as anything, even to imitate you, Jason.

Of course, if I am voted Content Leader, that GitHub user is then invited to the repo as would be expected.

But the following issues arise:
- I can proxy spam invites to any GitHub user on your behalf when I am voted Content Leader
  - This is made more extreme by the fact that equal leader vote does not produce a consistent outcome. (Repeated posting or voting will flip-flop the leader, I am not certain of the trigger)
  - Exhibit A, @torvalds is currently the content leader.
- I can post any message on the OHOL domain or in the client with candidate names available

![image](https://github.com/user-attachments/assets/f21e0d1b-f6df-4580-865f-00d0784fea50)
![image](https://github.com/user-attachments/assets/31386b2e-e596-4b7a-aedd-94de3e419a81)

**Comment by jasonrohrer** [comment]
Okay, I think it's fixed now.

Voting is now tracked internally by github name, and not email address.

Thus, if two users specify the same github name, people are voting by github name, and votes are now counted by github name.  And when it comes to allowing one user to submit update triggers (which do not go through Github), if multiple users have the same github name, the *oldest* AHAP user wins.

In terms of a content leader spamming other github accounts with invites.... well, a good leader won't do this.  Vote them out of they are doing it.

I will also look at the tie vote thing.

**Comment by jasonrohrer** [comment]
Okay, it's now consistent on ties based on  afc4861d4cf129c0dbc2b84e79775efc651ea31b

If there's a tie, the leader is the user with the oldest AHAP account (who rode the rocket first).

There's also a marker for the winner, in the case of ties, on the public results page.

http://onehouronelife.com/ahapGate/server.php?action=show_vote_stats
