### ISSUE TITLE
Iron Unlock After Apocalypse?

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1113]
I was part of a tan family after the apocalypse, though I didn't live through it.  Where I got born, someone did place 10 stones on a natural spring, but there wasn't an iron unlock.  I don't know if someone ran away and placed stones elsewhere though, and that can get done much more quickly by one player focused on it than an adult trying to feed children, find a good spot, make a kiln, bowls and plates, and a small farm.  Even just feeding children and finding a decent spot might be enough of a slowdown on an adult.  

But, I'm guessing when the current iron system got coded there wasn't any accounting for an extra unlock needed after an apocalypse?

**Comment by jasonrohrer** [comment]
Yes, that's likely the case!  Looking into it.

**Comment by jasonrohrer** [comment]
Looking at the code.... freeMap is called during the apocalypse, which clears all homelands (deletes the homeland records).

I will test this to double-check...

**Comment by jasonrohrer** [comment]
Not sure what's going on here, but I just tested it, and post-apocalypse, you can indeed build a new shallow well and unlock a muddy iron vein again.  Seems to be working correctly.
