### ISSUE TITLE
Issue logging into AHAP

### ISSUE THREAD

**Issue by KirbyBabydolly** [jasonrohrer/OneLife#1118]
I recently unlocked Another Hour Another Planet. I can load the game from steam just fine but when I try to login it starts to load and then says login failed. I have tried deleting all the files and redownloading and I have made sure custom servers are off. I do not know if it is an issue with my account because I can access One Hour One Life just fine. 

Thank You

**Comment by jasonrohrer** [comment]
Please email me:  jasonrohrer AT fastmail DOT fm
