### ISSUE TITLE
/recipe doesn't display recipes

### ISSUE THREAD

**Issue by Kailied** [jasonrohrer/OneLife#114]
For example in the tutorial it says to do /hatchet, when entered it just says MAKING HATCHET: (NO MATCH)

**Comment by tana-OHOL** [comment]
the /recipe won't give you the solution or step by step instruction when you use it, rather it will tell you if what you're holding or touching is relevant in any of the steps of the making of what you're looking for, so you still have to play around with things and try to figure out the steps yourself by holding stuff, but at least you will have a clue if it's relevant or not.
But I agree, I always thought the tutorial wasn't really clear on that point, letting you believe it will show you what to do, it should be explained more clearly.

**Comment by jasonrohrer** [comment]
Tutorial has been fixed to tell you to grab the stone before typing /hatchet
