### ISSUE TITLE
Stepping on snake with horsecart deletes items.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#115]
Occasionally when stepping on a snake with a full horse cart the game will delete some of the contents within the cart. Some items will fling out like normal but other times cargo just gets deleted like it would with previous deletion bugs.

**Comment by ghost** [comment]
Also had a reported issue of items being deleted off of /die babies but cannot confirm this happens as of yet.

**Comment by jasonrohrer** [comment]
Looking for specific steps to reproduce this.  Testing on my end, and it works.  Might it be a situation where you're completely surrounded, and there's no place for the items to go?

**Comment by jasonrohrer** [comment]
Or a youtube video of hit happening would be great.

**Comment by ghost** [comment]
Remade my github account and I'm the one who posted this. When this was happening I'm pretty sure what was occurring was related to mosquitoes where you would step on them and the items would fly to where you were intending to go vs where the mosquitoes/snake bit you. So items weren't ever actually getting deleted just flying to some unseeable area which made them seem like they were deleted.

**Comment by jasonrohrer** [comment]
Yeah, I think I will close this for now.
