### ISSUE TITLE
Paper coded really funky.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#118]
I was attempting to write out the history of different towns within one town as a fun project when I came upon an issue.

My work was overwriting older pages but it would seemingly produce almost random copy pages. I came across four copy pages of something I had wrote within the town. 

I'm not sure how many pages the server holds at one time but after writing 54 pages worth of stuff 27 pages within the town (that were not related at all to the stories) had become duplicate pages of what I wrote. 

Within the 150 papers or so in town - 54 papers were written by me, 33 or so copy pages of mine and others work were found, and the rest were written by other towns folk without duplicates within the town.

**Comment by jasonrohrer** [comment]
Whoops, they are getting ovewritten after server restarts.  Will fix.
