### ISSUE TITLE
[video] objects get deleted when baby use /die

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#121]
The object standing on same tile as baby gets deleted when /die is used

https://www.youtube.com/watch?v=OdCEg2oB_OA&feature=youtu.be&t=1347

Doesnt seem to work for all objects i tried with big hard rock but it didnt get deleted

**Comment by jasonrohrer** [comment]
Fixed by 55b161552c21e79847edccd70e79bb878c4126a6
