### ISSUE TITLE
Character stops moving after letting go of mouse

### ISSUE THREAD

**Issue by kanikamu** [jasonrohrer/OneLife#124]
Don't know if this is intentional or not, but its really annoying. Character stops as soon as you let go of the mouse, even if it still hasn't arrived to the destination.

**Comment by jasonrohrer** [comment]
This only happens if you are holding down the mouse for a half second or more (i.e., long-distance walking.

It now stops instantly when you release, to make the character more responsive.

It's supposed to be an improvement.
