### ISSUE TITLE
Cant click on other player sometimes

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#128]
Happens sometimes, other players cant be fed, held, interacted with
player moving to a different tile fixes it

**Comment by laccy** [comment]
some people glitch themselves out and arrow cant hit them

**Comment by jasonrohrer** [comment]
Can someone get a short recordedGame file showing this and post it?

**Comment by Davidj361** [comment]
> 
> 
> Can someone get a short recordedGame file showing this and post it?

@jasonrohrer What do you mean a recordedGame file? Like a video? Or some sort of file dumped by the game? If a file dumped by the game, would it still be dumped from playing on official?

I also had this bug sometimes too.

**Comment by jasonrohrer** [comment]
Yes, look in your game folder.

There's a recordedGames file that contains recording of all recent games that you played (from the time you started the client until the time you quit the client, all the lives you lived are recorded in order in one file).

These are text files describing all your actions frame-by-frame, and all network traffic.

Thus, when the file is played back, it can fully simulate exactly what happened, frame-by-frame, in your game.

Drop in playbackGame folder to watch one of them.

On Steam, there's a sticky thread that shows you how to find your game folder.

**Comment by trevorhackman** [comment]
I believe this has been fixed. Has anyone still seen it happen?

**Comment by jasonrohrer** [comment]
Will call this fixed for now.
