### ISSUE TITLE
things desappear

### ISSUE THREAD

**Issue by Zeenyy** [jasonrohrer/OneLife#131]
Hi! I'm playing since a few days and today I noticed that things desappear. for exemple, when i put things in my basket, they desappear when i take my basket back. when I set my base, its all gone when i come back. It's just not playable anymore.

**Comment by Zeenyy** [comment]
When we play, the world is always reseting. Even with the tutorial the world is reseting so all the walls and stuff for the tutorial desappear.

**Comment by jasonrohrer** [comment]
Server3 was out of disk space.  This has been fixed now.
