### ISSUE TITLE
In-Progress Kraut Crocks

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLife#133]
In-progress stew crocks can now be moved, but in-progress sauerkraut crocks can't be.

I understand it was mentioned in a previous bug report that this is because the result is very heavy,  especially with the weight on. But it'd make sense to at least have the in-progress ones a bit more mobile, I think. We'd be able to spread the kraut around camp a little more this way, and have it be immobile once weighted, similar to how stew is immobile once cooked. It'd make it a little more viable, even if it's not 100% realistic. 

Proposing these be in-progress variants be movable, and storable in carts:

- Shredded Cabbage
- Shredded Cabbage with Salt
- Possibly Stomped Fresh Sauerkraut and Covered Fresh Sauerkraut

**Comment by jasonrohrer** [comment]
Yeah... again, we make kraut every year here at home.... after you get it going, you really don't move it.  It's the kind of thing you do in place.

Move the empty crock and plan it out.  Pick a good spot for kraut-making, and go for it.
