### ISSUE TITLE
storage issues

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#136]
right now its hard to clean up a city as there are a lot of garbage around

worms arent garbage now but still on wrong places can be bad
bones can be taken out but then there is a lot of stuff used on later stages, new players toss alum, coloring stuff, all useless things

janitor is always full time job in this game, but we need more storage, easier storage

this could happen by: giving better rope recipes than milkweed
increase boxes and cart containability
bigger, better tier of carts
more stacks, bowl of worms

**Comment by swallis21** [comment]
This game needs hemp, honestly.

**Comment by jasonrohrer** [comment]
Closing for now.  This is more of a feature request than a bug.
