### ISSUE TITLE
iron too scarce

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#137]
you already tried nerfing ground iron, didn't work, same nerf this time, same problem, just too scarce

part of problem is that the random generated biome is not so random, i see one type of animal or resource in screen size parts, like 20 muflon or 30 limestone, all flat rocks, all onion in green biome
this limits iron even more as i experienced, especially in small badlands no lose iron, or cant find 3 with a basket and get back to camp safely

you talk about 1 minute radius, but that like 300 tile, when going one direction
people normally go in circles around camp, return, go out again, check out biome by biome

the initial iron is also a problem, we need kinda 10, just to make the full set of tools
now if the shovels and hoe starts breaking we need new, i can use alone 4-5 hoes in a life or 3 shovels making projects

the other problem is huge population so an outpost is required, that's even more iron to make 2 set of tools
now it's ok to make things harder for veterans, but kinda impossible for newbies
even if some of us find a mine, might not be ready with it in a life

one possible fix would be to not require stanchion kit at first and give some iron just by using pickaxe, like 6 or so, the order is still hammer, axe shovel, hoe, than 5 initial iron could be enough for pick, and with pickaxe we could make adze froh file saw chisel
than the mine could give some extra possibilities
pickaxe isn't used for creating other things just destroying stuff, so is a liability

also the grave diggers, give us something for digging graves, like a spade, also digging up potatoes should be with other tool, to make it viable form of food with scarce water

i don't mind if a vein gives 12-15 iron only, getting there is too hard if there is no 10 iron at least
 the other option would be to spawn iron when an eve sets a home marker, make iron regenerate each 10 min from a vein but decay if not picked like eggs
this is not too op, considering that the smaller the family the harder for one player to get iron
and the bigger it is, needs more hoes for food production

currently is just make or break, can you get 3 iron? than it becomes a viable camp where you can have fire and wells
can you get 3 more? than hoe, boards, maybe bell bases
but the mine making is kinda huge step as in meantime you can make carts and deep wells and have horses already but without the 10 initial iron the camp might just die out

**Comment by jasonrohrer** [comment]
Looking for other opinions here...

I was born into a village yesterday and they had stacks and stacks and stacks of refined steel ingots.

**Comment by jasonrohrer** [comment]
Closing for now, because this isn't really a bug.
