### ISSUE TITLE
buff corn a bit

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#138]
as we got a lot of newbies i feel like overeating is an issue

corn was too good at start but then it became just meh
main problem is takes more micromanagement to maintain, and may be eaten raw

we need a bit more love to popcorn, at least 1-2 more bites

popcorn would be perfect teaching newbies and feeding abandoned babies,  elder food, i don't think is too op, considering that needs fire, planting, cutting, waiting than bowls

berry is still the most used, and yeah it stops overeating a bit, i would like to see how much food is wasted in camps by not managing hunger properly, but if we cant even feed newbies, we cannot teach them either
it's a long process making pop corn and should buff it to be the nr1 food for newbees

**Comment by jasonrohrer** [comment]
Yeah, I really want to keep this list as legitimate bugs or inconsistent behavior.
