### ISSUE TITLE
Login failed before update,custom server

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#139]
If a custom server is selected, game cant update and there is a login failed message that doesnt explain why the login failed, need to uncheck custom server for the update to dowload

on steam version even if update was already done also didnt work had to uncheck custom server or i would get a login failed

Edit: Nvm server one being down is what caused the issue

**Comment by Dodg-e** [comment]
actually cant custom connect when theres an update queued
after it loads can reenable it

but it doesnt specify why it cant connect

**Comment by jasonrohrer** [comment]
Isn't it showing a VERSION MISMATCH along with a button to DISABLE CUSTOM SERVER right on the login screen?

**Comment by jasonrohrer** [comment]
Closing for now.  Please re-open if you have more info about this.
