### ISSUE TITLE
new rubber wheel cart

### ISSUE THREAD

**Issue by Thre3** [jasonrohrer/OneLife#140]
The new rubber wheel cart cant be attached to a horse and a horse cart cant get rubber wheels

**Comment by TwistedHBG** [comment]
I think that might be intentional - you choose how to upgrade your cart. Do you want to add a horse to make it faster, or improve its wheels to increase the capacity?

**Comment by swallis21** [comment]
That would be dumb. If we make it to the Industrial Age when it's finally added, will we still not be able to put wheels on our horse-drawn buggies because we have to "choose" how to upgrade them?

**Comment by jasonrohrer** [comment]
Yeah, it is kinda intentional, for now.

It was just to give you something "real" to do with rubber as a placeholder until cars arrive (soon).
