### ISSUE TITLE
Turkey Hat

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#144]
Plucked Turkeys are wearable as hats

**Comment by Dodg-e** [comment]
![image](https://user-images.githubusercontent.com/44139102/48932019-bd992d80-eef9-11e8-8207-279b889528f0.png)

**Comment by swallis21** [comment]
I'm pretty sure it's an easter egg. It looks too silly to keep, though.

**Comment by CallMeAce95** [comment]
by carrying the turkey on your head you can get the bow and arrow back to camp

**Comment by jasonrohrer** [comment]
Hilarious.  Leaving it for now.  I even fixed the position of the hat a bit.
