### ISSUE TITLE
Some hair textures make it really difficult to use your backpack

### ISSUE THREAD

**Issue by swallis21** [jasonrohrer/OneLife#146]
There are certain characters you can be born as which make it exceedingly difficult to use a backpack. They cover up the backpack (ESPECIALLY a tattered backpack) so it's incredibly hard to click on it without clicking on yourself instead (and potentially wasting a whole damn pie slice). It would be nice if the backpack's hitbox extended in front of the hair texture, even if the backpack's texture didn't.

**Comment by trevorhackman** [comment]
It would be nice if the backpack highlighted like how a basket (or other items) does when you mouse over, so you can see where the hitbox is instead of guessing.
