### ISSUE TITLE
Deer and Sinew

### ISSUE THREAD

**Issue by swallis21** [jasonrohrer/OneLife#148]
Milkweed farming is time consuming, resource consuming, boring, and adds a lot of clutter to a base. Hardly anyone does it, even though rope is extremely useful for any settlement at any stage of civilization. To help ease this, I suggest adding sinew as a resource, which can be combined to make thread. Historically, sinew was used for all the same purposes that thread and rope are used in the game.

In order to provide a way for players to get sinew, you should add deer. They can be forest biome wildlife, since that's where milkweed is normally found and there aren't any wild animals in forest biomes at the moment. Wild deer work functionally identically to boars; they can be shot with a bow and arrow to be killed, and occasionally they will spawn a fawn which can be separated from the deer by killing it. Fawns can be picked up and dropped, then fed to turn them into domestic deer, which can be killed with a knife.

A sharp stone can be used on a dead deer to create sinew. The dead deer, sinewless or not, can be butchered for four venison (useful for pies, like mutton). Two sinew can be combined to make thread. This would allow deer to be farmed as a much more hands-off and efficient way of generating thread and rope.

**Comment by jasonrohrer** [comment]
This is a feature request, not a bug report.  Please post here:

https://www.reddit.com/r/OneLifeSuggestions/
