### ISSUE TITLE
Semi-Tame wolves cross biome boundries

### ISSUE THREAD

**Issue by iumiforgot** [jasonrohrer/OneLife#153]
Wolves that are naturally spawning are stuck inside of the biome they spawned inside. Feeding a wild wolf makes it so that the wolf no longer has this limit, and can freely cross to any biome it wants to. I feel like the biome boundries should cross over to the semi-tame wolf, and should only stop applying to the wolves pups, like the German Shepard and the Collie.

**Comment by jasonrohrer** [comment]
Semi-tame follows people.

Any animal that follows people does not respect biome boundaries.  That's why the bear can chase you into your village.
