### ISSUE TITLE
Water refilling problem?

### ISSUE THREAD

**Issue by CallMeAce95** [jasonrohrer/OneLife#154]
I noticed on onetech that ponds, shallow wells and deep wells have the same percentage chance to add 1 usage If not dry for refilling on a timer than putting water back. Let's take ponds for this example:
- if one pond has a 20% chance to add 1 use after 1h, this means on average every 5h you get 1 use, this one use gives on average 5 bowls of water -> 1 bowl of water every 1hour
- if the pond is dry, you get 2 bowls of water in 1h if you take one after 30min but that's not the point
- if the ponds or wells have a percentage chance to refill water, it cannot be as stated in the last patch, for example 5 water per hour for ponds, nowhere near that

![capture1](https://user-images.githubusercontent.com/45493986/49302808-c4fba080-f4d0-11e8-9c25-7e999eb17d8b.PNG)
![capture2](https://user-images.githubusercontent.com/45493986/49302809-c4fba080-f4d0-11e8-96c3-0571d99a6beb.PNG)
![capture4](https://user-images.githubusercontent.com/45493986/49302811-c4fba080-f4d0-11e8-8bed-a165cead2d1e.PNG)

**Comment by CallMeAce95** [comment]
it has been made here also https://github.com/jasonrohrer/OneLifeData7/issues/79

**Comment by jasonrohrer** [comment]
Closing this and merging it with jasonrohrer/OneLifeData7#79
