### ISSUE TITLE
twins, cursing, knives, adjusments needed

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#155]
instead of cursing, the first should be a mark of cursing, this could be seen on a player either visually or on his text, flagging someone would mean that person is shady and keep an eye on it
the second curse should give curse points
why?
people use it pathetically like attacking you, and when they die curse you
this whole system of being judge and jury wont really work out

curses also should cost something, currently you just play a few hours and curse someone each 2 hours
lot of people curse people who don't like and tell others to do so for a full life or more
now people who seen the issue, can curse, but who don't need to be convinced, its quite easy to convince people, ''curse this person cause it's a griefer''
curse cause has the only knife, curse cause killed a poor 8 year old who just wanted to hunt
you got a curse token, you use it, when multiple people use it, others do might as well

when cursing others can get you in trouble, then it would be a decision to be made
i can imagine 2 points for cursed, 1 for the person who says curse
why? you would bring yourself down, but the other person more
if others agree, the griefer could be cursed, if not, you kinda wasted your curse points
people use it way too often for personal issues
now the limti could be the same just everything 2x
same way if 8 people curse you you will get to donkeytown,but in meantime the oens who curse you, get closer as well, now their decision would be: do i got any proof that he was the issue?
should i curse it bringing myself down?
could be a different token which stacks, if you curse often, you increase your score and you also end up in donkeytown, could be higher but non decaying, so after 10 or 20 you get a timeout
people curse too often for no reason
people don't understand what they do is harmful, i cant be so pitiful to curse a person for standing in the way of forge, but  i get cursed by her when i tell that this blocks the view, this makes teaching harder, because there is a chance they curse you for telling their mistakes
i got cursed for telling a young girl that i will smith on the other side, and she shouldn't take iron from there, instead bring the tools, was perfectly logic and i don't see why it hurts anyone feelings, i was there longer, i was working constantly, i made all those tools and she just comes and focusing on all the wrng things, and doesn't even know the map as me, even goes on a suicide mission with the bellows, to piss me off
some of us know what others do and why and why is wrong, others dont
why would someone with no knowledge about anything get same power as someone who worked his all life?

framers are an issue, and people who don't do anything just sponge resources, talk all lfie are defended by it, cause anyone having a problem with the mom who eats the berry farm popping out tons of babies, gets cursed by her and her kids, and who works, has no time to talk and convince others that someone is useless or bad intended

same goes for twins, they already are 2, 3, 4 persons with better communication
they can just kill someone and the other twins curse it, convincing others it was just, they can also kill you, revenge kil lyou, save the other twin while you are on cooldown, me as a twi ndont really  care who i kill, my twins feed me and back me up anyway, they trust my judgement

knives- we just got too many
while it can be good to have some for work or defense, once you pass it on, it can be still ok if you choose the right person, but after that can end up on a newbee girl who starves, or passed on to the last daughter for the existence of her
kills should be meaningful, and for a reason, knives are tools too, they should break too (maybe not on killing one of twins, only if all of them) but generally you got one single griefer or power hungry person, killing it worth a knife, killing innocents whould break the knife
or after 3 uses? or just allow us to melt it back  for steel 
maybe make it a longer process to use it again, use file again on it to sharpen

sometimes  i see like 12 knives in decaying cities and people will start killing before doing anything productive

**Comment by jasonrohrer** [comment]
This is an interesting idea, and yes, it would be nice if cursing had a cost of some kind.

Tying the cost into the curse system itself misses something, however.

Think about the person who likes to curse others, but never does anything curse-worthy themselves.  They currently curse one person every 2 hours.

If instead of curse tokens, they got 1 curse point for cursing, then they could start cursing one person every hour (because they burn a curse point every hour themselves).

So, of course, you'd still need curse tokens to limit the rate.  But then that person would be able to curse one person every 2 hours still.  They earn a curse point every time, but easily burn it off before two hours have passed.

Thus, it doesn't really seem to change anything.


What other kinds of costs can we think about?

**Comment by trevorhackman** [comment]
Even tho the self-awarded curse point burns off before your curse token restores, it still makes it take one less curse for you to get sent to donkey town. Could up the number to 3 curse points for cursing, that would be significant, but for other costs,

Perhaps the black magic of cursing could drain your vitality, giving you a temporary (few years) sickness that lowers your movespeed, just something a bit annoying.

**Comment by laccy** [comment]
this became a trend, and i tested it. i was killed once, for killing a griefer
general reaction is to curse you instantly then the chain goes on, i was just killed and not enough curses
i got back in other family and griefed the hell out of the city, making kilns from ovens, making newcommen foundations to block the ovens, planting berries and spamming seeds, everything that makes that city unviable
i mixed it with some useful actions like bringing firewood or carry stuff to other place
so whenever they followed me, i looked like a newbee who tries to do stuff

the reason why they killed me was naming babies dumb names
they are less likely to curse a naked player, than one fully clothed, even if he made all the clothes for himself, even if he fed them at birth or give them clothes too
they always believe the poor young kid even if its naked with bow in hand

i could imagine a dropdown menu to select a reason, this would stay above the killer if he chooses to select one, predifined answers that: "he was a thief" "he was a racist" "he was ruining buildings" etc.
or maybe record the thing he says in deffence and show both on next kill
i seen people saying "was an accident" 3-4 times

i know you don't like meritocracy or xp system, but generally i would believe a player who performed more actions that game and crafted more items, a 8 year old runs around until finds a weapon, then kills the first girl he sees
someone picks of berries into bowl and makes a compost, now that is a big difference to others to decide who was the fault
sure, people could abuse this to work a bit then kill some young kids, but it would be still some benefit to it
if they would do dumb actions like dropping seeds onto basket that would raise a flag anyway

they are a lot of players who curse but don't do curse worthy, if you don't consider doing nothing at all curse worthy

me personally would prefer if someone tries to kill me rather than cursing preemptively
its totally fine if they don't believe me and try to kill me for it, at least i got a chance to live

mount and blade had an interesting system
doing things for the npcs rewarded with relationship points, their actions depended on this points, if they would normally would attack you and burn down your villages, if they had good relation, they acted more like an opponent than an enemy and let you go 
we could have a system to have neutral, positive or negative stance toward others
automatic actions might not work, like gearing a baby (could be abused by swapping 2 clothes over and over) but maybe if they say TY, thanks, thank you, that would increase relationship level
sure they could still say it to anyone so wont be perfect
but having a statistic hovering over someone, that he is friendly to most of people or offensive or neutral would help people decide
some games even use honor system at the end of the games which can be seen when you see someone, if someone has  a good reputation that can mean that no need to be afraid
some people like me are controversial, maybe visible clues on babies would be bad (people were hunting black speech babies and justified their acts with it), but maybe if we met other life we could see positive relationships only

the other would be certain actions, which i generally see  positive act and proof of skill
making a compost means a player cares about the future 
or planting a tree 
now some are complex and cant be defined, like making a pen, or making a mine
doing this things just to have power over others? i would be fine with that, it takes time and why would they do it just to kill others or curse them?


people always expect that the killer might kill others or them
so they kill him, which is kinda fine but, could be some kind of temporary ban, like they could forgive at their end of their life (on the death screen) if the person doesn't commit anything else

this could be a screen on their end of the life, showing every person they met
they could mark people invisibly for curse (cause lot of people will kill the ones who curse them)
they should remember the person if what he did its curse worthy
if not they would forgive, it makes sense, cursing because others cursed him? what he actually did?
was he helpful afterwards? you cannot decide on things like that if you don't know what happened or what will happen
if im the one who is cursed what choice do i have? leave the town i built? people will act hostile 


also donkey town wont really make sense as it wont teach them anything, they just afk bananas, or go around shooting animals
the sense of time out makes sense, maybe should be 1 active hour or 4-6 inactive, like drop 1 curse if the player doesn't play for 6 hours?
some times people troll or kill cause they bored, not having to play with them for a day solves the issue
but being cursed falsely feels so bad, i got 5 curses so total like 10 for killing a 8 year old with a bow
it was justified, and a dumb king just ran around convincing others to curse me
i was playing hearthstone and ate a banana each 8-10 minutes

did it teach me anything? be more sneaky when killing people

there could be some puzzles to  solve to drop a curse point
like a quest in tutorial just with different expectations
like plant bushes or make a pack
maybe some people don't know how to do this and they think this is a shooter game

the thing is, you said you leave killing in the game so players arent defenseless against griefers
if others think im a griefer they can kill me, but nowadays "grifer" means that the person doesnt do what i want
now the preference is cursing the person and letting it run around
if he really a griefer they should kill him
if he is not a griefer and was rightful to kill someone, the curses are unjust and should have the right to curse back or kill them

maybe lower the curses value if they are not a witness? in case of awbz mod they can see more but still the game could give full curse value for people who seen the kill and only half for who does not, meaning it should be confirmed by others who also havent seen a bloody knife or any kind of proof (destroyed pen or destroyed kilns, etc) maybe players could mark a tile or person for proof and would be there for 1-2 minutes and people would get full value standing in visible range of it, or even show a different color "home marker" so others can go there and check, i can see the problem with that too, like removing boards from desert tiles might be considered griefing who does not know that it heats up the tile

we are on a point where you call someone lazy or point out a problem with the thing she is doing, then she will run around trying to kill you and curse you for 40 years or more

**Comment by jasonrohrer** [comment]
Well, this should probably be moved to a forum discussion at this point.  It's not exactly a bug report.

The curse system will likely be revisited at some point in the future.
