### ISSUE TITLE
professions

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#156]
you said at a point that you want professions

people quickly lose interest in a city if they don't know what to do, moms got to eat and have other babies
kids jump into already occupied positions, etc.

you need to give some support to have professions, or demands, tasks

first of all letters could be cheaper cause paper is very easy compared to it and shouldn't be like that, letters are way too expensive

second, you could have some quest or something to accept someone to a profession
for example
cook 12 pies= baker- can be archived quite fast but maybe keeps a newbie busy
feed 4 sheep= shepherd
hunt 5 rabbits=hunter 
cut 30 trees = lumberjack
dig 30 bones to ground= gravedigger
water 30 planted seeds= farmer
do multiple of above= professor or something
make 3 tools= smith
but it could be just the 3 most common things the person did on a new layer or holding down a button
stake hitter
bush digger
turkey hatter
ball bouncer
berry muncher
would be quite funny but informative
or a description by the player  chosen from a list
like farmer-berry
farmer-other
chef-stew
chef-rabbit
shepherd-feeding

doesn't have to be too complex, maybe could have different tiers like master farmer or pro farmer, etc

this would help associate people with their job
also to kill master sponges

extra layers
maybe we could have an extra layer with attached comments to characters, you could hit a button which brings up a top layer, containing some comments about the person
''this is daddy''
this guy got me that rope i asked"""
like a personal note board

tasks
while gathering is essential and kind of easy, hard to communicate what you need
kids want to help but no one tells them what you need
now you spend half of your life to make paper and write it? when you can just make it yourself

so the new shared layer could contain blueprints of buildings needed there, for example as eve mark a kiln , you could show/hide layer and put the kiln where the other player wants
and a short comment for it (make second kiln here)
or simply stuff like (move this rabbits to the oven)
i could imagine a table with charcoal as well
maybe in a few different colors so people see that pink table has important information from the eve
there would be a better way to teach and organize
()move this bones out)
(don't build room here, too hot)
(don't put soil on this berry, want to dig it)
(bring branches here)
(stack firewood here)
( cut buttlog into board) etc
also wold e nice to attach to a tile
i don't think its too op if each person can have only one and can be moved by him/her only (doesn't block movement, decays if user dead)

possibly a request/reward feature where you place items somewhere and when someone brings it, it gives a reward to the person making the task
for example 1 clay-reward a basket
this would ensure people can ask and offer help
this tasks would turn  invisible after a few minutes even on hidden screen and people should refresh it

other possibility is clay boards which could be watered back to make clay table and reuse it

 i want help, others want to help, but we just run to eat and lose each other on screen

follow button - mark a person like with home marker to follow it, maybe just one person each player, this would work like home marker, also if someone doesn't move for logn we would know is dead, or arrange a move or nomadic lfie that people can follow each other

**Comment by jasonrohrer** [comment]
Interesting idea.... but this is not a bug!

**Comment by jasonrohrer** [comment]
Can you post this on the Suggestions subreddit?
