### ISSUE TITLE
No copyright license

### ISSUE THREAD

**Issue by badosu** [jasonrohrer/OneLife#16]
Hello Jason, thanks for the great game, I just purchased it and really like it.

Looking at the repository I noticed you put a `no_copyright.txt' file. I have some concerns with it:

- Some liabilities for bad use and damages could be inflicted upon you.
- It enables the possibility of a company using your game's source code to publish as their own with few tweaks.
- By default all creative material has copyright, I am not sure your current license file changes that. See [this](https://en.wikipedia.org/wiki/Anti-copyright_notice).

As popularity grows (I certainly hope so!) some of these issues will have more probability of happening.

Ideally you would want to have a custom license to make sure your purposes with this enterprise are covered, while still being free software or open source, but that would require legal advice and time I am not sure you have at your disposal.

In the meantime, using a copyleft license would make sure that if a company wants to modify this game everyone can reap the benefits. There are other licenses that enforce other rules that may be desirable (a company that just runs modified servers would not need to release the source code for some licenses).

I think GPL or AGPL is a nice start, you can always relicense it later. If you want to be permissive for use within proprietary software I suggest the MIT license, which just requires the copyright notice to be available on redistributions and clears you from any responsibility over the source code's use. The most (serious) similar license I could find to your `no_license.txt` is the [Unlicense](https://en.wikipedia.org/wiki/Unlicense), which also frees you from liabilities.

I do not have an extensive knowledge on the matter though, I am not a lawyer, I am just someone who is enthusiastic about your game with some concerns. I also do not have any agenda towards this change, I simply want your hard work and effort not be ripped off in any way.

**Comment by jasonrohrer** [comment]
I'm aware of the risks.

But I don't care!

The game is in the public domain and there are no restrictions on use or reuse.

Everyone out there in the world is a free person and can do whatever they want.  I cannot stop them, even if I wanted to, and with this notice, I have promised not to even TRY to stop them.

As far as liability, sheesh, let someone try to sue me.  I will trounce them in court, and defend myself, so there will be no legal fees on my end.  I mean, what, if they install the game in a commercial airliner and it causes the whole plane to crash?  The possible situations of liability are pretty outlandish...

**Comment by jasonrohrer** [comment]
But I do appreciate your concerns.

I actually think you don't have much to worry about here.  I was first to market with this idea and this game, and I'm running servers that no one else has access to.

So any knock-offs will always be running on separate servers and therefore second-best.

**Comment by badosu** [comment]
Great, thanks for the acknowledgement. 

Keep up with the good work!

**Comment by lakeman** [comment]
What about the WTFPL? :)
