### ISSUE TITLE
how to use steam account on linux 

### ISSUE THREAD

**Issue by tolgayapici** [jasonrohrer/OneLife#164]
I bought the game on steam for my windows machine. Later I decided to use my linux computer but when I compiled, it is asking me for an email in addition to the key. I used my steam email address but no luck. I tried looking at forums and could not find an answer. I wanted to post this on the forum but since I did not get an email with the information to register to the forum, I could not do that either.

**Comment by cerealbox** [comment]
i also bought the game through steam and it generated an email address for me that looked like this:
37645861243768914@steamgames.com

try getting this email from the windows version and typing it into the linux version.

also, for access to the forum and other stuff, try this link and click the log into steam button:
http://onehouronelife.com/steamGate/server.php?action=show_download_link

**Comment by tolgayapici** [comment]
indeed the steam id and steamgames.com email worked. i suggest you remove your comment as it shows your steam id.

**Comment by cerealbox** [comment]
hahahahahah...thanx.  it's a fake number.
