### ISSUE TITLE
two clients, same ip issues

### ISSUE THREAD

**Issue by Isoterik** [jasonrohrer/OneLife#167]
unable to connect to the same server with two different clients/machines from the same ip.
twins also aren't working.

**Comment by AlecYawata** [comment]
Are you use different email and account keys?
Only one email can be used at the same time.

**Comment by Isoterik** [comment]
> Are you use different email and account keys?
> Only one email can be used at the same time.

@AlecYawata tried it with the steam version, different ids and keys though. but i have to double check that later again. i am not sure anymore. could be a conflict, due one the 2nd machine it was installed 1st as a shared game from the 1st steam account. so when the key was not overwritten after purchasing it on the 2nd steam account too, that could be the reason. never thought about that till now.

**Comment by Isoterik** [comment]
well that was it:
**accountKey.ini** and **email.ini** had to be manually removed from the 2nd steam acccount to recreate those files properly, since the game used the steam id and key from the 1st steam account, due the game was installed through the shared libraries and did not overwrite those files after purchasing it on the 2nd account.
