### ISSUE TITLE
Linux Multi Monitor Setup

### ISSUE THREAD

**Issue by FlorianLudwig** [jasonrohrer/OneLife#17]
One Linux with a dual monitor setup OneLife creates one window over both monitors. Also the mouse position is not correctly used, so click events seem to not go to the right position. For example I cannot click on the settings button.

**Comment by UbiquitousTailor** [comment]
This might need to be another issue, but on a multi monitor setup on Windows the cursor is able to leave the game when full screened and then when clicked, minimises the game. Rather annoying issue when you are getting chased by a bear and you click outside the window by accident.

**Comment by UncleGus** [comment]
I confirm this happens on three monitors as well. The game displays centred on my middle monitor (the main one) but the mouse click positions seem to be scaled across all three monitors, so the centre is still the centre, but everything else is scaled away from that.

**Comment by ghost** [comment]
Same here with to monitors. The game is completely unplayable. As one of my screen is twice as wide and has a 4K resolution (while the other only HD) and that I can't change the screen on which I play I have to disable one of my monitors... 
An option to choose on which screen the game is displayed would be great!

**Comment by UncleGus** [comment]
It's only unplayable in full screen mode. You can still turn this off by editing fullScreen.ini in the settings folder and changing it to 0.

**Comment by ghost** [comment]
Thanks for the notice! It'll at least allow me to play more comfortably for now. Though I hope you succeed to fix this issue. :)

**Comment by jasonrohrer** [comment]
Can someone check whether the new borderless.ini setting helps this issue on Linux?

**Comment by UncleGus** [comment]
I'll give it a quick check now.

**Comment by UncleGus** [comment]
Hmm, nah, it's still bodgy. This time it only opened on two monitors instead of three, the main one being a different monitor, and the clicks were still offset.

**Comment by UncleGus** [comment]
From a Discord conversation:

Nubbcakes - Yesterday at 6:30 PM
if anyone has been having trouble with the mouse pointer being off while fullscreen i figured out that you can change the screenHeight and screenWidth files in the settings to the dimensions of your monitor

**Comment by jasonrohrer** [comment]
I'm closing this for now, just for clarity.  Maybe this will be revisited if I ever get more info about it.
