### ISSUE TITLE
Yellow fever removable

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#170]
Reports of player being able to emote with yellow fever and remove it and pick it up as if it were an item.

**Comment by jasonrohrer** [comment]
Realized that emoting the jaundice is possible if they mod the files to add a new client-side trigger word for it.  Will fix that.

**Comment by jasonrohrer** [comment]
As far as dropping yellow fever, I'm not sure.

Hopefully someone will report steps to reproduce.

**Comment by ghost** [comment]
Pretty sure no one was actually picking it up and dropping it only abusing the ability to turn yellow and carry stuff around.
