### ISSUE TITLE
Reflector opens up new servers when they're not really needed

### ISSUE THREAD

**Issue by thundersen** [jasonrohrer/OneLife#171]
I have plotted server population over time here: https://plot.ly/~thundersen/0.embed 
The plot is a bit messy, but it should be enough to illustrate my point.
If you look at servers 3 and 4 after Dec 14, 10pm (UTC), you see that server 4 is being populated at the cost of server 3 only to reverse the process a few hours later. I assume that this led to people experiencing infertility on both servers without a good reason. Is this desired behaviour or an unintended side-effect from recent changes to the reflector?
Take a look at [this forum thread](https://onehouronelife.com/forums/viewtopic.php?pid=40484#p40484) for more context.

**Comment by jasonrohrer** [comment]
Thinking about what to do here.

This is not a straight-forward problem to solve.

Population will change over time.  This is reality.  This means birth rate will change over time.  Who gets hit with this change?  It creates a negative experience.  How do we spread that negative experience among players?
