### ISSUE TITLE
God Cow (uninteractable bugged cows)

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#173]
Sometimes cows get stuck in the Milk Cow (or Milk Cow - _just drank_ (I can't tell)) state. Once stuck in this state, they are a so called 'God Cow'. Cannot be milked. Cannot be interacted with. Cannot be killed. Will never stop being an unmilkable milk cow. 

Unsure of exact steps to reproduce. Happened twice in a row when I delayed giving a dry cow a bowl of water until I imagine its timer was almost up, and then immediately tried using bucket on the new milk cow. The cows in question couldn't move as they were surrounded on all sides by a pen and other cows if that makes a difference.

**Comment by AlecYawata** [comment]
Duplicate issue.
https://github.com/jasonrohrer/OneLifeData7/issues/88

Cow has number of uses "10".
And it's decrement at
1. Walked
2. Feed water
3. Milked
And "just drank" cow doesn't have transaction when number of uses is zero.

**Comment by jasonrohrer** [comment]
Thanks!  Will close this one and use the other report to fix this.
