### ISSUE TITLE
Snowballs Cause Invincibility 

### ISSUE THREAD

**Issue by AzyAzrael** [jasonrohrer/OneLife#179]
I was just goofing off with snowballs the other day when I noticed something.

Today I also just tested it with consistent results, after throwing a snowball on someone, they become invincible for that 10-second frame they are slowed. 

I tested this with a knife and bow and also with animals and all results are similar, the victims don't get hurt and the perpetrators like the human stabbing/shooting and the animals, show signs of attack. People are slowed and have bloody knife even though the person they attacked didn't die because of the snowball effect. 
![595690_screenshots_20181222010330_1](https://user-images.githubusercontent.com/46035936/50371417-a85eff80-0588-11e9-95ee-8d9c48ae92b7.jpg)
![595690_screenshots_20181222010800_1](https://user-images.githubusercontent.com/46035936/50371418-a9902c80-0588-11e9-84a8-345c0e1ed86e.jpg)
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/46035936/50371419-aac15980-0588-11e9-8504-2bc5eeaa34c1.jpg)
![595690_screenshots_20181222010804_1](https://user-images.githubusercontent.com/46035936/50371420-abf28680-0588-11e9-901a-3dcd630c33ea.jpg)

**Comment by ghost** [comment]
This is/was the case with yellow fever as well.

**Comment by AzyAzrael** [comment]
> This is/was the case with yellow fever as well.

Yes but this is in reverse, meaning that with yellow fever it could save you from death once already attacked, while with this effect it prevents being killed during that time.

**Comment by ghost** [comment]
Yellow fever does/did exactly this where you couldn't be stabbed while under the effect of the jaundice emote. For the curative effect it was the opposite stabbed > yellow fever > cured while if done the other way yellow fever > stabbed > murder cooldown for attacker, attacked player invulnerable to player attacks. 

This is likely the same exact bug and I'm not sure it was fixed the first time around or if it was then snowball disease is just different.

**Comment by jasonrohrer** [comment]
Yes, these are both similar bugs caused by the same root issue.

Also, it's hilarious that you all have been having snowball fights without any visual indicator that you've been hit all this time.  It's not supposed to be that way.

**Comment by jasonrohrer** [comment]
Fixed along with #162
