### ISSUE TITLE
Instant death

### ISSUE THREAD

**Issue by Morb0** [jasonrohrer/OneLife#181]
If send `MOVE 0 0#` to server you instant death with `UNKNOWN` reason. https://github.com/0ArturkA/OneLife/commit/29c10b68cc3b6df028ad51ffd6fc0c54082549ff

**Comment by jasonrohrer** [comment]
Yeah, that's not a valid move message.

The server insta-kills any clients that are sending improperly formatted messages.

**Comment by CrazyEddieTK** [comment]
Perhaps instead of killing malformed clients, it would be better to disconnect them? The Awbz client uses this "functionality" to implement universal instant-die, which runs counter to the stated intended game behavior (i.e. to suicide you must use /die or starve).

**Comment by CrazyEddieTK** [comment]
Note that one consequence of the (unintended?) universal instant-die is that, unlike /die, the death doesn't reset the mother's birth cooldown timer. Some of the implications of this are discussed on the forum here: https://onehouronelife.com/forums/viewtopic.php?id=4956
