### ISSUE TITLE
Baskets with stuff in it dont switch in big containers

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#184]
Fow example a box with baskets in it that have a pie, a rope and an iron ore for each basket wont switch so player  has to remove all the baskets before reaching the last basket in the box/chest/cart etc

**Comment by jasonrohrer** [comment]
Aha!
It's because the swap only happens if the game finds a different object in there to swap.

A basket is a basket, so it thinks its the same object, and refuses to swap (even if they contain different things).

Will fix.

**Comment by jasonrohrer** [comment]
Actually, there's a simple bug in there, where if they contain different numbers of items, they won't swap.  The fact that they're both baskets isn't the problem (the code already handles that by making sure they don't contain the same thing before saying they're identical).
