### ISSUE TITLE
The Eve naming tutorial message is not very clear

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#185]
The tutorial tells you to 'Say I am Jones to set your last name as Eve.' The wording is unclear and people think that this will set your name to be Eve, not Jones.

I think it should say 'Say I am Jones to set your last name when you are an Eve.' or 'Say I am Jones to set your last name as an Eve.' instead.

**Comment by jasonrohrer** [comment]
No sense in talking about Eve there at all, because new players won't know what that means.  Fixed.
