### ISSUE TITLE
Not connecting to server with current life ongoing when restarting client and bouncing bug

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#187]
Im having bouncing bugs lately, checking my internet connection by going to websites and it's fine, when i close client and restart it, it solves the issue (wanted to post stdout here but personnal information are not encrypted in it)

Usually i use custom server but this time it was disabled, and when login back in i got a new spawn on another server instead of continuing the one that was already on going

**Comment by laccy** [comment]
i had a daughter who disconnected, i fed her 20 years then she came back
told me she was killed by a bear in other life

**Comment by jasonrohrer** [comment]
I'm pretty sure this has been fixed along with the "lag in cities" issue.  Please post a new issue if you have more details.
