### ISSUE TITLE
Editor run in non-fullscreen cuts off the edges of the screen

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLife#19]
As per screenshot:

![editor screen cut off](https://i.imgur.com/6RzQ4Kh.png)

**Comment by jasonrohrer** [comment]
Can you verify that setting useLargestWindow to 0 in the settings folder fixes this?

**Comment by UncleGus** [comment]
Yes it does, thanks.

**Comment by UncleGus** [comment]
I'm going to close this one for you :)
