### ISSUE TITLE
Steam Issues for Gifted Copies

### ISSUE THREAD

**Issue by betalpha8** [jasonrohrer/OneLife#193]
The issue below discovered the source of the problem and fixed it themselves.
(just trying to resurface that issue)

(url=https://github.com/jasonrohrer/OneLife/issues/167)two clients, same ip issues #167

**Comment by jasonrohrer** [comment]
It's not something that I have control over, I don't think.

I mean, if people use library sharing, and Steam saves their settings, and then they buy a copy for themselves, they have to clear their settings manually.

There's no way for me to detect this case.
