### ISSUE TITLE
Give potato some love

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#200]
Potatoes are very bad right now, removing one single tile of them cost 10 shovel uses which is half of an expected brand new shovel
and the food value wont justify this

shovels are needed to advance the civilization, digging up rocks, soil piles, wells and fences, carry dung

so potatoes and digging graves should use other tool specifically designed for this
like spade, this would solve the issue of the way too common grave digging in usable spaces or people breaking shovels on graves and potato
this is something people will kill others and the other half wont get it why they deserve it

**Comment by jasonrohrer** [comment]
Well, this is a suggestion, not a bug report.... maybe someday I will revisit potato viability.
