### ISSUE TITLE
pork and sheep

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#202]
people still cant see difference between pork meat and sheep, i was taking out pork meat multiple times to hide them behind trees, as they never get used, people still try to put the pigs in the sheep pen, and is quite annoying
the color should be different like more dark red or brownish
also maybe different uses of it, pork is kinda common food in a lot of countries except arabics (europe, america, china)
a less optimal but simple recipe would be nice, like oven cook it for 8-10 food bars

**Comment by jasonrohrer** [comment]
Isn't there a white bone sticking out of one?

But again, this is meant for true bug reports, not suggestions.  Maybe more pork recipes will be added in the future.
