### ISSUE TITLE
Can't login to bigserver1

### ISSUE THREAD

**Issue by Profilore** [jasonrohrer/OneLife#205]
The game starts loading, but then it goes back to menu with a message "connection failed". I tried to log with custom server disabled/enabled, same results. When I put in the server14, it loaded.

**Comment by jasonrohrer** [comment]
Are you in Russia?

**Comment by Profilore** [comment]
Yes

**Comment by jasonrohrer** [comment]
This has been fixed.  bigserver2 is accessible from Russia now.
