### ISSUE TITLE
Map culling doesn't cull partially-used objects?

### ISSUE THREAD

**Issue by CrazyEddieTK** [jasonrohrer/OneLife#206]
There's a [forum thread](https://onehouronelife.com/forums/viewtopic.php?id=5086) discussing the odd patterns players have observed in partially-remaining ruined towns and settlements.

In [this post](https://onehouronelife.com/forums/viewtopic.php?pid=43870#p43870) Ilka noticed that most objects had disappeared, but the ones remaining were all objects which have multiple uses and which had been partially used.

Perhaps there is a bug in the culling code? If so, this could be keeping the map database larger than intended, possibly affecting performance.

**Comment by jasonrohrer** [comment]
Ah, yes, that would be happening.

Partially-used objects are stored in a special file at shut-down so that they can be restored.

If the tiles are cleared because they haven't been seen in a long time, then these used objects would still get restored in those spots...  will fix.

**Comment by BlueDiamondAvatar** [comment]
Here's the full list of things I've seen lasting longer than expected:
tilled rows of plants with corn, beans, berry bushes (maybe partially harvested???)
stacks of items, like plates and iron ore
flint chips, usually as single items (see the original post in the thread CE linked to)
wells and newcommen pumps.

Just thought I'd share in case any of these items would not count as partially-used objects.

**Comment by CrazyEddieTK** [comment]
Everything you mentioned there is a multi-use item (except for individual flint chips). You can check the items out on onetech and look for a "Number of uses" value. Stacks of items are implemented as single items (a stack) with multiple uses. Corn, beans, berry bushes have multiple uses corresponding to how many corn ears, beans, and berries they have remaining. Etc.
