### ISSUE TITLE
critical bug on bigserver1

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#208]
havent tested other but bs1 was bugged, it seems it resets time to a previous state

first i thought just lags and people taking items but shows the previous one, tried to fix the pen, which was open, a kindling instead of a wall, but in 5 minutes was open again
i tried to make adobe from clay and straw, did it, made the adobe, pen was open in 5 min
i picked off tons of berry from bushes, and put carrot in each
wasn't even 2 minutes, everything was grown back
with that huge population and no one working, just feeding babies and eating berry almost no one starved

i could only describe as time is frozen and tiles reset back to previous state, not into past, seems like a fixed state, only been in one village but everyone says the same, glitched

**Comment by laccy** [comment]
seems its same on eve run, built a snowman first 2 steps, it wouldn't melt normally, like 5-6 minutes later didn't see it, nor my son, but it bumped me clicking on it, and even clicking under it, which normally should redirect me somewhere, the onion i ate grew back, so its not just big cities

**Comment by jasonrohrer** [comment]
Disk was read-only.  This has been fixed.
