### ISSUE TITLE
Server - segmentation fault

### ISSUE THREAD

**Issue by hodasemi** [jasonrohrer/OneLife#21]
When running a local server and I try to connect, the server throws an segmentation fault.
Running the server with GDB I get the following message:

`0x000055555555a017 in getFemale (inPlayer=0x7fffffffc8a0) at server.cpp:1110`
`1110	    return ! r->male;`

EDIT: Running on Archlinux 64 bit

EDIT2: nvm, just forget to symlink the folders, runs fine now. Sorry for inconvenience.

**Comment by FlorianLudwig** [comment]
@hodasemi you could close the issue, thanks :+1:
