### ISSUE TITLE
Recipe index is missing info on using pickaxe to break roads

### ISSUE THREAD

**Issue by BlueDiamondAvatar** [jasonrohrer/OneLife#213]
When you pick up an pickaxe, it does not tell you that you can use it to break a road made with flat stones.  Also, when you pick up an Adze, it does not tell you that you can use it to remove floor boards.  

People are surprised when these events occur, and act as though placed boards and roads can not be removed.

**Comment by jasonrohrer** [comment]
For me, when I pick up pickaxe, recipe #6 of 12 is:

Steel mining pick
+ stone road
= flat rock

This is working as intended.
