### ISSUE TITLE
Suggestion: Let us speak with numbers

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLife#214]
Please let us type numbers into the speech box so we can communicate distances etc. easier. E.g. instead of "Four point seven k West", we could say "4.7k west".

**Comment by Jummit** [comment]
If you speak you can't use special characters (noises) for numbers, and so you can't do it in game. Makes sense to me.

**Comment by jasonrohrer** [comment]
Yeah, I don't like the way it looks to have 6 in the middle of a sentence.  It violates MLA style guidelines and all that!

This is on purpose.
