### ISSUE TITLE
Afterimage of characters leaving loaded tile area

### ISSUE THREAD

**Issue by BlueDiamondAvatar** [jasonrohrer/OneLife#216]
In the course of play yesterday, I twice encountered an issue with an after image of a player and their belongings remaining minutes after the player had left the village.

In both cases this involved characters that left the village without returning.  During one of these lives, several other players joined me in making plans to kill the character that appeared to have disconnected in the middle of leaving with the last horsecart.  After a few minutes the image suddenly disappeared.

In a second incident, a character was leaving the town with a basket and some tools.  Both myself and my twin could see an image of this character, although we did not recall interacting with her previously.  Because we were talking through discord, we determined that we saw the image of our cousin in two different locations.

![20190203002919_1](https://user-images.githubusercontent.com/47229314/52180224-a015f900-27b1-11e9-925d-edca6ef902cb.jpg)

In this screenshot I am standing behind the unresponsive image of my cousin. My twin saw this image by the sheep bones a few tiles to the left.

**Comment by jasonrohrer** [comment]
Well, I guess I'd need a recording of this.  (recordedGame)

Also, probably a good idea to try reproducing this in the official client, instead of a mod.

**Comment by BlueDiamondAvatar** [comment]
yeah, I checked, but I didn't have recordings for the two lives where the afterimage happened.

**Comment by jasonrohrer** [comment]
Closing for now.  If you ever see it with the official client, please re-open.
