### ISSUE TITLE
Baskets with stuff in it dont switch in big containers (2)

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#217]
Issue was closed : https://github.com/jasonrohrer/OneLife/issues/184

With the comment : "Actually, there's a simple bug in there, where if they contain different numbers of items, they won't swap. The fact that they're both baskets isn't the problem (the code already handles that by making sure they don't contain the same thing before saying they're identical)."

But the issue isn't fixed, is it intended?

**Comment by jasonrohrer** [comment]
Not fixed?  I think it is fixed.  Lemme check.

**Comment by jasonrohrer** [comment]
Whoops... now it's not working if both baskets contain the same number!  Fixing now.
