### ISSUE TITLE
Client starts to freak out if you fly to the tutorial.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#219]
As the title says. Screen went full white fuzzies and started to jerk around. Ended up killing myself without thinking but both the loading screen got messed up and upon "arrival" game was a jerky spazzing mess of white. 
<img width="671" alt="tutorial" src="https://user-images.githubusercontent.com/47055947/52186107-49311380-27f3-11e9-8a28-68ac4358adea.png">

Proof of arriving at the tutorial coordinates for the record. 

![screen00063](https://user-images.githubusercontent.com/47055947/52186529-de350c00-27f5-11e9-8043-03142b3ff966.jpg)

Edit: found the plane too.

**Comment by ghost** [comment]
Closing and reopening the client fixes all the weird distortion that occurs from flying to and from the tutorial it turns out however that still is an issue since the game is unplayable after flight otherwise.

**Comment by jasonrohrer** [comment]
Fixed in 4a1bad0b09b448f351c74fdadbb527851c21df30
