### ISSUE TITLE
It is possible suicide without using the /die command, which probably doesn't reset the mother's birth cooldown

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#220]
Babies can suicide without using the /die command, I am guessing it's related to Awbz's OneLife+ mod. It has been happening more and more frequently recently and it's becoming a problem. The cause of death on the family tree says 'starved.'

They can suicide without being held by their mother, so I'm guessing adults might be able to use this to suicide as well.

**Comment by CrazyEddieTK** [comment]
See also #194 for further discussion of this issue.

**Comment by jasonrohrer** [comment]
This has been fixed now.  You can't use the mod to suicide anymore (it just DC's you instead of kiling you), and a new /DIE command works up to age 2, even if not held.
