### ISSUE TITLE
Forced disconnects and unable to reconnect.

### ISSUE THREAD

**Issue by Mcjoshinz** [jasonrohrer/OneLife#225]
We're experiencing random disconnects without lag. Lag was present in one life but other than that its just instant disconnects. I have been unable to reconnect after disconnecting a single time since the update.

**Comment by dogwolf12** [comment]
I managed it once but was kicked out 30 seconds later.  This update also kills you with temperature too. Between that and the lag, it is extremely rare to find a family in early generation 3, and it is only 50% of the time that you spawn as a baby.

**Comment by jasonrohrer** [comment]
Oh, yeah, servers were crashing!  That was a bad day...
