### ISSUE TITLE
Is it possible to build it by Visual Studio in Windows?

### ISSUE THREAD

**Issue by HiddenStar0412** [jasonrohrer/OneLife#228]
Hi,
I'd like to build it with MS Visual Studio.
Is it possible?
I'll appreciate if someone advice me about that.
Thank you.

**Comment by jasonrohrer** [comment]
Yes, should be possible, though I haven't tried it myself.

I don't have time to provide this kind of dev support.  I suggest asking in the forums---I think some people on there have been able to compile it in VS.
