### ISSUE TITLE
Mouse fetching position incorrect with a 3440x1440 screen

### ISSUE THREAD

**Issue by goblinsky** [jasonrohrer/OneLife#237]
My screen's default resolution is 3440x1440. When I play game with full screen mode, I always pick up things on the tile next to the mouse. It seems the system cannot get the correct mouse position to determine which item should be activated. The resolution of full screen mode game looks like 2560x1440.

When I tune the screen’s resolution down to 2560x1080, the problem still exists.
When 1920x1080, it works well.
When 1800x1440, the mouse fetching position is right. However the picture is strengthened extremely wide.

Everything works well when I play with window mode.

**Comment by jasonrohrer** [comment]
I don't think we're going to get more info about this.  Closing for now.

**Comment by sblom** [comment]
Figured out what's going on and opened a new issue #782.
