### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by Behoston** [jasonrohrer/OneLife#24]
I'm trying to translate this game to PL. I found that it doesn't support UTF-8
![obraz](https://user-images.githubusercontent.com/7823689/38783467-c2ae0908-4102-11e8-9ca1-22c9a56def18.png)

It should be `NAPISZ RECENZJĘ` and `WYJDŹ`

**Comment by KKSzymanowski** [comment]
I haven't looked at the code but isn't it just an issue with the font? As far as I remember C++ supports UTF8 out of the box.

**Comment by Behoston** [comment]
I'm working on top level (only translations) for now.
Is possible to change font without recompiling game?

**Comment by Behoston** [comment]
It looks like font not contains extended Latin chars.
![obraz](https://user-images.githubusercontent.com/7823689/38803879-d7846ea8-4170-11e8-98a8-c3191b3792a3.png)

So... maybe better solution is to configure font in language file and give user possibility to use own (like languages)?
I can try do this, but my C++ skill are really basic.

**Comment by jasonrohrer** [comment]
You will need to edit the font file in the graphics/ folder to add characters for a Latin1 character set.  Then what you are doing should work.

I believe some people in the forums have worked this out.
