### ISSUE TITLE
Biomes can (appear to) change between server starts, but not very much.

### ISSUE THREAD

**Issue by oddbury** [jasonrohrer/OneLife#245]
Steps to reproduce:
1. Remove the database.
2. Force Eve spawn to X=50, Y=-7.
3. Start the server.
4. Join the server.
5. Walk 6 tiles West and 9 tiles North.
6. You are standing on a desert tile.
7. Exit the game.
8. Shutdown the server.
9. Start the server.
10. Join the server.
11. Walk 6 tiles West and 9 tiles North.
12. You are standing on a prairie.

If you go 2 tiles West and 13 tiles North there's a swamp tile that becomes in desert. In both cases it behaves like the tile it originally displayed as from a heat point of view: the former, appearing as a prairie, gives heat like a desert; the latter, appearing as a desert gives heat like a swamp. It might affect animal behaviour similarly.

**Comment by jasonrohrer** [comment]
Thanks!  I integrated this fix.

By the way, it was strange, but I couldn't reproduce this using your steps.

I think it was probably a moving turkey that caused the problem, and maybe I just didn't walk up there at exactly the same time you did.

(I didn't see any wide or tall objects up there, so the moving animal would be the only thing that would check the biome for neighboring tiles, b/c the animal wants to stay in-biome).
