### ISSUE TITLE
Cannot get back into fullscreen mode after [Alt] + [TAB]

### ISSUE THREAD

**Issue by psilove** [jasonrohrer/OneLife#248]
![screenshot from 2019-03-07 09-44-09](https://user-images.githubusercontent.com/48240214/53943595-b28b9700-40bd-11e9-8877-14ae326719c6.png)
Hello,

I play the game in fullscreen mode, which works fine.

When I want to get to my workspace/desktop while playing I use [Alt]+[Tab] - the game gets forced into a window. I cannot get back into fullscreen though, there is also no maximize button. It became a fixed window with my screen resolution. I am unable to see my hunger bar because of this, since a part of the game is cut from the screen. So after leaving fullscreen I cannot properly play the game anymore.

Ubuntu 16.04. / 64-bit / Screen 1920x1080

P.S. The reason for me leaving fullscreen mode is that I want to change my audio volume, since it doesn't work ingame (I have a volume control on my keyboard that doesn't work in game for unknown reasons).

/edit
I added a screenshot of my screen after going out of fullscreen while in the game menu. As you can see the windows is cut off on the right and bottom, there is no maximize button, and if I click into the window, it's not going into fullscreen again like I would expect (since other games do that).

**Comment by jasonrohrer** [comment]
Hmm... this isn't happening on my Ubuntu here.

It minimizes on ALT-TAB, but then goes back to fullscreen afterward.

Have you tried Borderless for this purpose?  When I use that, it doesn't even minimize, but instead hangs out in the background.

**Comment by psilove** [comment]
When I use borderless mode, fullscreen mode does not work properly, it just fills out the "desktop area" with the game, but Unity and the top bar acts as the border. Picture attached.
![Screenshot from 2019-03-17 22-32-50](https://user-images.githubusercontent.com/48240214/54498237-e0b27780-4904-11e9-9a21-a4dc09c6d348.png)

**Comment by Dredonkey** [comment]
I also experience this issue on Ubuntu, just to confirm.

**Comment by jasonrohrer** [comment]
I'm not sure there's going to be a way to fix this.

I think this is something that SDL is just doing, though I'm not 100% sure.

**Comment by Dredonkey** [comment]
Yeah.. I have found a workaround by playing through proton on steam, could probably also do it with wine on the standalone. So for now there's that.

**Comment by jasonrohrer** [comment]
I'm going to close this for now.
