### ISSUE TITLE
Remove locks

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#253]
Locks are useless for players who build up the towns, but an extremly potent tool to for griefers to
1. waste two steel (key and lock)
2. lock away items
3. lock rooms, potentially this way mass murdering the inhabitants

In the player community is a broad consensus that this feature is only used for destroying entire towns, even though the game is already difficult enough.

**Comment by jasonrohrer** [comment]
Property rights need locks.  Inheritance of houses needs locks, etc.

This isn't a bug report!

**Comment by ghost** [comment]
Dear Jason,
This was meant as a suggestion. I was told that I have to file those here.
In this game, keeping a room or other property is impossible because locks can easily be picked by brute force due to only having 10 possible values for the key.
On the other hand some purely destructive players intensivly use those to damage towns severly.
Once in the past I have demonstrated how dangerous that can be. Please have a look here:
https://onehouronelife.com/forums/viewtopic.php?pid=44353#p44353
