### ISSUE TITLE
Snowball + stab = longer death stagger

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#258]
If someone is snowballed then stabbed and padded they'll live for about three minutes which is obviously longer than server death stagger. Player will be stuck with yellow text unable to interact with items until either they starve out, hit the three minute death, or are finished being healed via being stitched up. 

Not sure if yellow fever with have the same disease effect or if snowball + arrow produces the same extended death stagger length.

**Comment by jasonrohrer** [comment]
Snowballs have been changed, so I don't think this is an issue anymore.
