### ISSUE TITLE
Placeholder Names in firstNames.txt

### ISSUE THREAD

**Issue by CrazyEddieTK** [jasonrohrer/OneLife#259]
As per [this post](https://onehouronelife.com/forums/viewtopic.php?pid=49992#p49992) by Whatever, among the allowable first names are:

BABY
BABYBOY
BABYGIRL

Probably these are placeholder names used by parents or hospitals when filling out Social Security registration paperwork before they've chosen a name.

Probably BABYBOY and BABYGIRL should be removed from the list, although perhaps BABY should stay given that it's a [plausible actual name](https://www.ranker.com/list/famous-people-named-baby/reference) (or at least nickname) for a child.

**Comment by jasonrohrer** [comment]
Well, those are damn cute, so I think I'll leave them.

Nice find!

**Comment by Kinrany** [comment]
[Another reason to keep BABY](https://en.wikipedia.org/wiki/Baby_Driver)

**Comment by TwistedHBG** [comment]
Yes, please don't take away my Baby--- names

**Comment by riiles** [comment]
Here is more information for anyone who finds this:
https://www.hit.msu.edu/training/howto/Naming_and_Social_Security_Conventions.pdf
https://www.ncbi.nlm.nih.gov/pubmed/28403654
https://pediatrics.aappublications.org/content/136/2/327
https://www.washingtonpost.com/news/to-your-health/wp/2015/07/13/babyboy-babygirl-hospital-naming-conventions-may-be-cause-of-mix-ups/

Yes it is a placeholder name.
