### ISSUE TITLE
Players getting stuck on waiting to be born, possible link to a script on the forum

### ISSUE THREAD

**Issue by JoePaulsen** [jasonrohrer/OneLife#264]
So recently a bunch of scripts were made by Whatever to access public data
http://onehouronelife.com/forums/viewtopic.php?id=5607

I and one or two others were running these scripts, and during the time we were running the data fetching scripts, people could not log on.  Immediately after I stopped everyone could log on again.  The script for me was causing thousands of timeout/reconnects.

This also affected the One City Server (which uses the official ticketing), as people would get stuck when trying to log on during the time others on the main server would.  

Meanwhile, people are running the scripts off and on, and people are getting stuck on waiting to be born off and on.

While it's possible this is all a coincidence, I think it's important to bring up, and even if it's not related, this "waiting to be born" issue is occuring off and on.

**Comment by jasonrohrer** [comment]
Okay, took the data offline just to be safe.

Will move it to a separate server when I return from GDC.

**Comment by jasonrohrer** [comment]
Data has been moved to a separate server.
