### ISSUE TITLE
Mosquitoes and clothes temperature bug

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#266]
Not sure exactly what causes that, but sometimes temperature seems to get locked and even going in a colder biome doesn't change anything which makes mosquitoes 100%  deadly when bug happens out of town
<a href="https://ibb.co/cC9DPgn"><img src="https://i.ibb.co/b2VzxW9/screen00303.jpg" alt="screen00303" border="0"></a><br />

**Comment by Dodg-e** [comment]
It actually happens everytime,with full gear mosquitoes are 100% deadly if no one feeds

**Comment by jasonrohrer** [comment]
This isn't a bug, exactly.  You have yellow fever, and you're wearing a full suit of fur clothing.  Being sick is supposed to require help to survive, at least some of the time.
