### ISSUE TITLE
Remove yum from wild foods

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLife#271]
Introduction:
Yum is a great incentive for players to produce multiple foods. Having multiple food streams not only adds flavour to the game but also helps extending the life of communities by providing alternatives when the main staple food fails. This behavior is desirable.

Wild foods contributing to yum chain disrupts this behavior. Abandoning town to forage for wild foods is fast and easy providing the individual with multiple yum levels in exchange for their time. On the other hand the effort of creating and maintaining new food types for the entire community is big and time consuming.

This incentivises selfish behavior where if 10 people were trying to yum, every one of them would abandon town to forage. If instead all invested the same time in helping to create new "higher food" options then town would effectively advance making it easier for future generations to yum properly.

Suggestion:
Remove wild foods from the list of foods that contribute to yum chain.

Intended result:
Players would be more likely to create and eat multiple "high foods" instead of heading out to forage by themselves.

**Comment by jasonrohrer** [comment]
I haven't heard any other complaints about this.  Wild food is supposed to be a viable way to boost YUM.
