### ISSUE TITLE
Non breakable yum chains

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLife#272]
Introduction:
Yum chaining is probably my favorite feature in the game. It provides a (in my opinion fun) mini game that incentivises players to diversify food,  experience new recipes and allows for improved food efficiency (both in terms of time and potentially resources).

However the fact that chain can be broken results in two counter behaviors thaat are less desirable:
1) Since the yum chain is constantly on the line, like drug addicts, players who yum will inevitably spend a significant amount of their time trying to ensure their next "fix". This causes them to focus mostly on "fast food" such as wild foods, raw carrots, berries, green beans, popcorn;
2) Players will focus on maintaining their yum chain rather than creating new "high foods".
3) Most "fast food" is terribly inefficient (either by time or resources) potentially causing a significantive drain on the town.
4) Players will break yum and start eating the same food again from zero. This negates most incentives to create new food after yum chain failed once.
5) Players overly attached to their yum can be griefed by others by simply being fed a berry either accidentally or on purpose, this causes frustration, drama and leaves a bad taste in your mouth afterwards.

Suggestion:
Make yum chain non breakable and bonuses not repeatable.

Intended result:
A chain that doesn't break would free yummers from having to focus solely on yumming while still keeping the incentive to create and maintaining new food types.

Player yum level and their associated bonus (values might need adjustmemts) depend on lifetime consumption allowing for a more stable yumming and converting yumming from an individual mini game to a quantifiable benefit to the community.

Future:
Trade of different staple foods between towns? ;)

**Comment by jasonrohrer** [comment]
This is an interesting idea.

I'm going to pass this one to the forums to see what other people think.

The idea here would be that your YUM multiplier would grow each time you ate a new food in your life, but you'd only get the bonus when you ate another new food.

So...  with this sequence:

```
berry      +0 bonus (yum becomes x1)
banana     +1 bonus (yum becomes x2)
carrot     +2 bonus (yum becomes x3)
berry      +0 bonus (yum remains x3)
berry      +0 bonus (yum remains x3)
burdock    +3 bonus (yum becomes x4)
burdock    +0 bonus (yum remains x4)
berry      +0 bonus (yum remains x4)
banana     +0 bonus (yum remains x4)
carrot     +0 bonus (yum remains x4)
carrot pie +4 bonus (yum becomes x5)
carrot pie +0 bonus (yum remains x5)
carrot     +0 bonus (yum remains x5)
carrot     +0 bonus (yum remains x5)
```

**Comment by jasonrohrer** [comment]
Based on the forum discussion, there would be too many side-effects to this change.

I'm going to leave well enough alone for now.
