### ISSUE TITLE
[Bug] Can not talk

### ISSUE THREAD

**Issue by hetuw** [jasonrohrer/OneLife#274]
I cannot talk in game anymore.
When i press enter no text panel appears.
When i press enter type something and press enter again it does nothing.

I am using Ubuntu and compiled and downloaded with the pullAndBuildLatest script
https://github.com/jasonrohrer/OneLife/blob/master/build/source/OneLife_Live_UnixSource/pullAndBuildLatest
Am i the only one having this issue?
I can see other people talk, and everything else seems to work fine.

**Comment by hetuw** [comment]
After some testing i was able to fix it myself.
At this line: https://github.com/jasonrohrer/OneLife/blob/OneLife_v212/gameSource/LivingLifePage.cpp#L19466
I replaced: 
`if( ! TextField::isAnyFocused() ) {`
with
`if( ! mSayField.isFocused() ) {`

**Comment by hetuw** [comment]
I dont think that my fix is the correct way of doing this?
I am not sure if it has any bad side effects, so far it works well.
Why am i the only one affected by this?

**Comment by TwistedHBG** [comment]
I had the same bug occur to me once - hitting the up arrow key fixed it. I have not encountered the bug since.

**Comment by hetuw** [comment]
Nice to hear i am not the only one TwistedHBG, maybe this issue will help people in the future with the same problem.

**Comment by jasonrohrer** [comment]
This was fixed a while back, in a slightly different way:

https://github.com/jasonrohrer/OneLife/commit/dd9986035e95fbfec88928c118ca51447788c475
