### ISSUE TITLE
No MacOS version available on steam

### ISSUE THREAD

**Issue by winrey** [jasonrohrer/OneLife#275]
Because notice that there  **IS** MacOS version on the [official website](http://onehouronelife.com/), I bought the game on steam, but final found that MacOS version is not available on steam.
I think it's just a small setting mistake which can be easily solved.
Isn't it?

**Comment by jasonrohrer** [comment]
Sadly, building the Mac version for Steam is a pretty big undertaking.  I'm only one guy, and the number of people with Macs on Steam is very small.  All Steam users can download the mac version for free from here:

http://onehouronelife.com/steamGate/server.php?action=show_download_link
