### ISSUE TITLE
Family naming update not working as intended

### ISSUE THREAD

**Issue by BlueDiamondAvatar** [jasonrohrer/OneLife#277]
The description of the High Society update states:
"Your family's last name is remembered, even if your mother doesn't give you a name. ...This will make family trees more coherent, with a last name shared by every named person in the tree. No more lost family names over time."

However, families are still losing last names.  
A gen 11 member of the Bufalino family had an unnamed daughter.  After this point all the daughter's descendant had no last name. (currently at generation 26)

http://lineage.onehouronelife.com/server.php?action=character_page&id=4024477&rel_id=4022027

**Comment by jasonrohrer** [comment]
Hmm.... looks like it's not working!

**Comment by JustinLove** [comment]
betsst told me that "If somebody names you while not picking you up you dont get fam name"
