### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [jasonrohrer/OneLife#279]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [freeLineageLog](https://github.com/jasonrohrer/OneLife/blob/0a6e20f2362d873000a4afc090bb175379dc9908/server/lineageLog.cpp#L59 "freeLineageLog function")
- [freePlayerStats](https://github.com/jasonrohrer/OneLife/blob/0a6e20f2362d873000a4afc090bb175379dc9908/server/playerStats.cpp#L73 "freePlayerStats function")
- [usage](https://github.com/jasonrohrer/OneLife/blob/39b111abf0171ebde1333f42d2af832332325673/documentation/video/trailer1/lipSync/genMouthShapes.cpp#L26 "usage function")

**Comment by jasonrohrer** [comment]
I do that in a few places like that because there aren't necessarily any gurantees that these functions are going to be called correctly from the outside, in the right order.  For example, if freeLineageLog was called on its own, without initLineageLog ever being called.

**Comment by elfring** [comment]
I suggest to avoid redundant checks a bit more.
