### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [jasonrohrer/OneLife#280]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [EditorObjectPage](https://github.com/jasonrohrer/OneLife/blob/a84c951b78956fb7a16518d2678170f8450c9b87/gameSource/EditorObjectPage.cpp#L501)
- [HashTable](https://github.com/jasonrohrer/OneLife/blob/9ea6076f9c7d3440ce127ff6f4a19050d0cb7c21/server/HashTable.h#L64)

**Comment by jasonrohrer** [comment]
No, I would not like to do that.

FYI, "new" is called 774 times in the current code.

**Comment by elfring** [comment]
Source code which contains multiple delete statements in destructors is questionable today.
How do you think about [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation")?
