### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Dababymasta** [jasonrohrer/OneLife#287]
When logging in, I write in my email carefully and copy and paste the key. But when I try to log in, it says "connecting" "Waiting to be born" then it takes me back to the log in page and says in red letters "LOGIN FAILED". My email has no special characters. I found this error when building the game; 
In file included from ../../minorGems/graphics/openGL/SingleTextureGL.h:34:
../../minorGems/graphics/openGL/glInclude.h:30:10: fatal error: 'GL/gl.h' file
      not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
In file included from ../../minorGems/graphics/openGL/SingleTextureGL.cpp:28:
In file included from ../../minorGems/graphics/openGL/SingleTextureGL.h:34:
../../minorGems/graphics/openGL/glInclude.h:30:10: fatal error: 'GL/gl.h' file
      not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
../../minorGems/game/platforms/SDL/gameSDL.cpp:16:10: fatal error: 
      'SDL/SDL_main.h' file not found
#include <SDL/SDL_main.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
In file included from ../../minorGems/game/platforms/openGL/gameGraphicsGL.cpp:3:
In file included from ../../minorGems/game/platforms/openGL/SpriteGL.h:5:
In file included from ../../minorGems/graphics/openGL/SingleTextureGL.h:34:
../../minorGems/graphics/openGL/glInclude.h:30:10: fatal error: 'GL/gl.h' file
      not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
In file included from ../../minorGems/game/platforms/openGL/SpriteGL.cpp:1:
In file included from ../../minorGems/game/platforms/openGL/SpriteGL.h:5:
In file included from ../../minorGems/graphics/openGL/SingleTextureGL.h:34:
../../minorGems/graphics/openGL/glInclude.h:30:10: fatal error: 'GL/gl.h' file
      not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile.minorGems_dependencies] Error 1

Perhaps this could be linked to me not being able to log in?

**Comment by Dababymasta** [comment]
Im on MacOS

**Comment by jasonrohrer** [comment]
Please email me for tech support:  jasonrohrer AT fastmail.fm
