### ISSUE TITLE
Making someone a marked graves losses their name

### ISSUE THREAD

**Issue by Tipy1802** [jasonrohrer/OneLife#288]
In the High Society update (fancy clothes update) we got the ability to see the names of people that died before us on their bone piles but if you make a marked grave the name is lost and you get ''Forgotten Person'' instead. The point of making a marked grave is to remember one but now if you actually make a marked grave the person will be forgotten forever

**Comment by TwistedHBG** [comment]
The grave names seem to be borked. I've had a situation where I spam dropped/picked up the bones on the same spot and it would cycle between two different names.

**Comment by jasonrohrer** [comment]
Fixed this here:  7426243327e5817cae343b5cac6774dd67f325bd

Note that putting a bone basket in a cart will still cause info about the grave to be forgotten.
