### ISSUE TITLE
getRandomDeathMarker() always returns the same ID but still runs a for loop for 87 iterations every time a default grave is created

### ISSUE THREAD

**Issue by TyrantNomad** [jasonrohrer/OneLife#29]
attached is my local change that keeps the original function while removing the repeated for loop; marked at lines 3048 through 3065

file format changed to .txt due to file format upload limitations

[objectBank.cpp.txt](https://github.com/jasonrohrer/OneLife/files/1933957/objectBank.cpp.txt)

**Comment by jasonrohrer** [comment]
Well, it's way more than 87 iterations!

More like 1000 currently, and would be 10,000 eventually.  Also, it's currently not random at all, is it?

Fixed this by making it actually random, and not looping at all.  See this commit:

https://github.com/jasonrohrer/OneLife/commit/663fe1cd843b3fb656f284f0bb5bee2d661ad6c3

**Comment by jasonrohrer** [comment]
And there was a bug in that commit.  This one fixes it:

https://github.com/jasonrohrer/OneLife/commit/186c945e3d599ae999d3025f8b7076d2478606ff
