### ISSUE TITLE
[Bug] Photos too small

### ISSUE THREAD

**Issue by hetuw** [jasonrohrer/OneLife#290]
Right now photos are 2x2 tiles big, but it seems to be they should be 3x3 tiles big

**Comment by jasonrohrer** [comment]
Depends on the zoom of your screen.  I'm grabbing 400x400 raw pixels from your graphics card, and presenting them in the photo as-is with no scaling.  Scaling would introduce visual artifacts.

On a 1280x720 display, 400x400 is approximately 3x3 tiles.  On a larger display, it will be less than that.

**Comment by hetuw** [comment]
You could look up how big the screen is, than depending on the screen size, zoom in or out while the photo is taken (like the zoom mods do). This way you can always get 3x3 tiles without creating artifacts.
