### ISSUE TITLE
Items that should go in carts, boxes, bags, baskets, do not

### ISSUE THREAD

**Issue by futurebird** [jasonrohrer/OneLife#292]
Palm kernels but not crushed palm kernels.
Latex but not sulfured latex. 
A bowl of berries but not a bowl of berry SEEDS. 
Wheat but not flour. 
Pie crusts, but not a bowl of pie dough.
Meat and bowls (in stacks! I love that) but not carnitas

There is no way to predict what you can and cannot put in a cart or box.  It's a major obstacle to organizing and cleaning towns. Nearly all items in bowls should be able to be put in a cart IMO. It's not like we can't move liquids... buckets of water are fine. So why not everything else?

THINGS YOU CAN'T PUT IN A CART BUT YOU SHOULD BE ABLE TO
(tested on the one city server)
bowl of crushed palm kernels
bowl of soaking palm kernels
bowl of separating palm oil
Sulfured Latex bucket
Sulfured and Oiled Latex bucket
Bowl of Green Beans
Turkey Drumstick (also should go in basket and bag)
Pork Taco (also should go in basket and bag)
Bean Taco (also should go in basket and bag)
Popcorn
Bowl of Ice Cream
Cooked Shrimp (also should go in basket and bag)
Bowl of raw sugar
Bowl of Cream
Bowl of Butter
Cooked Turkey (before it’s cut)
Kraut board
All bowls of seeds
Turkey leg bone (also should go in basket and bag)
Carnitas
Bowl of Saltpeter and Sulfur
Turkey bones on a plate
bowl of palm oil
bowl of tortilla chips
bowl of pigment 
bowl of dye
bowl of salt
bowl of bagasse
bowl of cooked beans
bowl of flour
bowl of quicklime
bowl of slaked lime
bowl of dough
Dice in a bowl (also cannot be put down without swapping an object)
transmitter and receivers

Based on a forum thread.
http://onehouronelife.com/forums/viewtopic.php?id=6119

**Comment by futurebird** [comment]
Latex buckets

**Comment by futurebird** [comment]
Bowl of limestone (also cannot be put down without swapping an object)
Bowl of gold (also cannot be put down without swapping an object)

**Comment by futurebird** [comment]
Snake skin

**Comment by jasonrohrer** [comment]
Yeah, I think that most of these were handled.  Please open an new issue if I missed anything.
