### ISSUE TITLE
How can I re-download the game after it was deleted?

### ISSUE THREAD

**Issue by Versy77** [jasonrohrer/OneLife#296]
Hello Mr. Rohrer,

I have been very much enjoying the game ONE HOUR ONE LIFE.

But my brother, while touching the computer, accidently erased it!! 

I don't know how to re-download it , since it is asking me to pay again...

Could you tell me a way to re-download it?

**Comment by Tipy1802** [comment]
You should have the key in the email that Jason send you (if you bought it through the website)
If you got the game from steam you can just redownload it from there my going to your steam library rightcliking on One Hour One Life and selecting ''install''

**Comment by laccy** [comment]
search hitory for "ticket server"(the link you downloaded it) or your weekly updates contain an uppercase key in xxxxx-xxxxx-xxxxx-xxxxx format at the end of link
or steam
also save your key somewhere

**Comment by jasonrohrer** [comment]
Please email me:  jasonrohrer AT fastmail.fm
