### ISSUE TITLE
[Nevermind, misread] Deep Well Bug: Very Broken, Much Feedback Loop, Wow

### ISSUE THREAD

**Issue by MonsWTF** [jasonrohrer/OneLife#298]
Edit: misread certain transitions. Jason definitely closed it and I combined incorrect wells.

------

Unfortunately, I just now checked One Tech to verify the states of wells, and it looks like there is still a feedback loop stuck in the recent code.

Dry Deep Wells can be replaced by a Pump Valve, returning the Stanchion Kit.

The Pump Valve can be removed by hand, giving a Dry Shallow Well (the default one). 

The Dry Shallow Well can have the Stanchion Kit re-applied to give a Deep Well, full of water again.

Suggested fix: This one's tricky, because sure you can probably mark it as "Exhausted Deep Well" to make it consistent w/ the Newcomen Pump exhaustion. But then, that runs into the issue of how to track when a Well site has already applied a Newcomen Pump in its past, because someone could grief Dry wells with a Pump Valve and lock them out of being able to have used the Newcomen water source before the 5% exhaustion. 

Each tier basically restricting the possibility of going backwards to the previous tier.

Pic for reference of the feedback loop.

![image](https://user-images.githubusercontent.com/7107685/57185037-501b0100-6e8a-11e9-8c5a-8ef0b6c2908b.png)

**Comment by Ari-ori** [comment]
yeah this is big and needs to be fixed very soon
