### ISSUE TITLE
Ghost Player

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#299]
There was a permanent ghost of a player. Standing perfectly still. Throughout my entire life she was there. I asked others if they could see her, but I was the only one that could see her. Leaving the area and coming back didn't make the ghost go away. Couldn't hit ghost with snowball, wasn't really anyone there. The ghost aged overtime. I died before I could see if the ghost would die of old age.

**Comment by futurebird** [comment]
I have also seen this happen more than once. Player just standing there. Can't feed them. They age. I was able to wait until she died and she just vanished.
