### ISSUE TITLE
Sprites that aren't supposed to showing infront of characters

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#300]
For example, https://puu.sh/Dq7om/9309c49729.png, the hat on his face is on the tile above him and should be drawn behind him. 

I notice this happen usually two or three times a life. Seems pretty random. Not sure how to replicate. When it happens, moving to a different tile then moving back fixes it.

**Comment by jasonrohrer** [comment]
Yes, I've seen this too...

Has something to do with the person moving while off-screen, and then when you move so that they are on screen...

**Comment by trevorhackman** [comment]
I've seen it happening in reverse, a person standing above a newcomen machine but being drawn infront of it

**Comment by jasonrohrer** [comment]
This may have been fixed by JustinLove's pull request.

Let's see this week if we still notice this happening or not.

**Comment by jasonrohrer** [comment]
I think this has been fixed.
