### ISSUE TITLE
When attempting to twin, can be born without twin

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#305]
Saw this happen to a new player streaming. 
He tried to kill himself by closing the game and reopening. The quit screen doesn't make it clear that that doesn't kill you only disconnects. Then he tried to twin with a friend. No idea that he was still alive in his previous life. Instead of being born with his twin, he was reconnected to his previous life.

**Comment by jasonrohrer** [comment]
Thanks for the report!  Will fix.
