### ISSUE TITLE
Mouflon and wolves tend to cluster on western end of badlands

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#306]
I'm not sure if it's limited to mouflon and wolves or if it happens to all animals. I and others have noticed it a lot with mouflon and wolves. After a long time with big badlands all the animals will be on the western end or in a western pocket.

**Comment by laccy** [comment]
all biome locked animals
it's since the change in loading screens, like it used to load a bigger map part and they start moving
now it loads your nearby tiles only
they used to go top i think, but we had bit more of them when he fixed the short items spawn bug

**Comment by jasonrohrer** [comment]
Hmm... I do see something strange in the code in that spot...
