### ISSUE TITLE
Incorrect bone piles

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#308]
Saw bone pile of twin sister when I was boy and definitely had no twin sister. 
Had a twin brother which might be a step to reproduce this issue.

**Comment by jasonrohrer** [comment]
Are you sure about this one?

The "twin" status is determined by how close you are born together, not whether you are actual twins or not.  If a mother gets a very short cooldown (can happen randomly sometimes), then you can have a twin sister as a boy.

**Comment by trevorhackman** [comment]
I didn't know that was how the twin status worked. I'm sure I saw such a situation, but it could've been from being born close together in time.
