### ISSUE TITLE
Shears are breaking on one use

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLife#31]
I put this here because the data looks fine, so it's probably something to do with the code changes made to preserve number of uses for the chisel et al.

**Comment by jasonrohrer** [comment]
Indeed they are breaking right away.

Very strange.

They don't break if used on a dead sheep, however.

Must have something to do with them being used on moving sheep.  That's right... only one usage number can be preserved per transition, and the sheep have their own usage count-down until they have a baby...

**Comment by jasonrohrer** [comment]
There's not a clean way to fix this in the code, and there is a risk of combinatoric explosion of two usage-objects are allowed in the same transition.  For example, the shears can be used 20 times, and they need to work on all 6 usage states of the moving sheep (leading up to the sheep having a lamb).  That would generate 60 transitions (for every combination of used-shears and used-sheep).  For other pairs of objects with even more uses, it will be even worse.

For now, I will just avoid making things like shears and mallets and smithing hammers (which are used on usage-objects) themselves usable.

Thus, content is fixed for shears here:

https://github.com/jasonrohrer/OneLifeData7/commit/fef4a886085d5bc4d646f6d873dec55f06b728d4
