### ISSUE TITLE
I can wear a gold ingot

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#310]
I can use smithing hammer on crown which I'm wearing. And crown becomes an ingot.
Also, the ingot can be made into a Tower Bell without putting it off.

**Comment by JustinLove** [comment]
This seems to work with with any clothing that has transitions. I can cut down a dress I'm wearing, or put on the skirt and make it pleated while wearing.

**Comment by jasonrohrer** [comment]
Yeah, this is a side-effect of the new support for being able to put a sword in the backpack and take it back out again, but NOT have it be in a slot.

You should be able to change clothing that you're wearing (like put a feather in your cap), but only if the result is still wearable.  Will fix it to check this.

(I do like the idea of trimming the dress that you're wearing....)
