### ISSUE TITLE
Home marker never changed 

### ISSUE THREAD

**Issue by Kaybr0** [jasonrohrer/OneLife#315]
My home marker is automatically set to wherever I’m born; every game. Not just as Eve, just near wherever I happen to be born (checked everywhere for an existing home marker in town the first few times, but there was none the direction of my pointer). Putting up and destroying a new one doesn’t fix it either. Can’t see any bells. Even when born as quads this happens, yet the other people in the quad could see the bell marker whilst mine was still near birth point.

**Comment by jasonrohrer** [comment]
Are you 100% sure about this?

I just played two lives as a baby where I had no home marker at birth.

This has happened to me a few times, but when I've looked very closely, I've always found the home marker.

The other possibility is that it was there when you were born, but someone removed it by the time you went looking for it.  In that case, setting one nearby and clearing it should work.  I'm testing this now just to confirm that it's working.

**Comment by jasonrohrer** [comment]
Just tested, and removing an "invisible" home marker is also working on my end.  You have a radius-7 window around the old marker, wherever it was, and if you place a marker in that window, and there's no longer a marker at the old location (a ghost marker removed by someone else), that old maker will be forgotten.

Also, on birth, the ONLY way a home maker is set for you, in the code, is if there's a home marker on the initial map that is sent to you.

Home markers are tracked client-side, and there's only two places in the code where they are tracked.

If this is still an issue, and it's really happening to you every life, this is some kind of major but obscure bug.  Please shoot a quick video showing it happening (maybe /DIE through a few lives and show that there's a home marker in each life, but that it's really not there).
