### ISSUE TITLE
Nineteenth cousin once removed shows up as no relation

### ISSUE THREAD

**Issue by Kiyin** [jasonrohrer/OneLife#317]
When in game, 19th cousins showed as related but their children, 19th cousins once removed, show as no relation.

**Comment by trevorhackman** [comment]
https://onehouronelife.com/forums/viewtopic.php?id=6716

**Comment by laccy** [comment]
my grandma was an Eve and i was named Blondin but from a different Eve, i succesfulyl dodged an old lady chasign me then went into middle city and had a few daughters, one of them had twins and quads who stayed so 6 girls, so we took over the city, dunno if shows as cousins but we were different family
