### ISSUE TITLE
Pathing: Can't pick up item in one click in certain setups

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#318]
In this setup the plate can't be directly picked up, 
https://puu.sh/Dz1JN/82c7d2a5c8.png

Clicking on the plate causes your character to move ontop of the plate, but not to pick it up. Once ontop of the plate you can click again to pick it up. When holding an item and trying to put it down in that same spot between the fences, you move onto the tile but don't put the item down. Must click again once on the tile to place the item down.

**Comment by jasonrohrer** [comment]
Great report!
