### ISSUE TITLE
Natural spring appeared and disappeared from time to time

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLife#319]
https://twitter.com/yoshio_ohol/status/1133989712396312581

If mapCache exist (its mean, second time you saw natural spring), outGridPlacement haven't setted to true. https://github.com/jasonrohrer/OneLife/blob/c964b815e94ecb955472b6b52635dbf33eba3986/server/map.cpp#L1021

In this case, natural spring were delete by semi-short objects in placed at south.
https://github.com/jasonrohrer/OneLife/blob/c964b815e94ecb955472b6b52635dbf33eba3986/server/map.cpp#L5193

So, you need to move mapCacheLookup() (in getBaseMap()) after gridPlacements checking.
Or, add gridPlacement(bool) for struct BaseMapCacheRecord.

**Comment by laccy** [comment]
i thought it's because the eve is alive
you cant put stone on it either
one life mom wanted to settle and lost 20 mi ncause of this
maybe some info that owned by Eve X

so it's cause we cut marker and leave it there?

**Comment by cloudiirain** [comment]
Can confirm if that I also experienced disappearing springs in this recent update too.

**Comment by AlecYawata** [comment]
@laccy 
What's your point?
I read source code and found cause of blinking spring bug.

If you said other reason has been, show me source code or some information of jason.
"We cant put stone to natural spring ownered by other eve" is not a truth.
No one said that. Its only your misunderstanding.

And cutting marker is no relation for this bug.
Blinking natural spring is unusable forever.

Dont remember, here is github.
If you want to talk about something, read source code or go to forum.

**Comment by laccy** [comment]
don't have to be a dick

and not true that is unusable , i was able to use the spring later and can be disappering for one player while the other sees it, generally when a kid born will not see it if you do and will see if you not
 and the ones with marker had eves starting there

was a question not a statement about skewers, again, get laid and calm down

**Comment by DougLefelhocz** [comment]
I've seen it at least two times now where I've seen a spring as an Eve.  I think it's a good spot.  I look around a little more to see how good.  I come back to the spot and it's gone.  I even go check 40 tiles away, and there's another spring there.  But, the spring at the good spot is gone.

**Comment by cloudiirain** [comment]
Another report from another user: https://onehouronelife.com/forums/viewtopic.php?id=6855

**Comment by AlecYawata** [comment]
https://www.twitch.tv/videos/437173129
I captured video of bug reproduction.
I talk with Japanese and English, please watch this, 7 minutes video.

Way to reproduce.
1. See natural spring, with some high height object in south at 1 or 2 tiles.
2. You can see natural spring, but its unusable.
3. Move to out of around natural spring, and come back to natural spring. Then natural spring has gone.
4. Friend walk to 256 tiles far at some direction(NEWS) from natural spring.
5. When friend arrived at 256 tiles far, reentering natural spring to screen, once more.
6. You can see natural spring again.
7. Friend does same things, walk just more 20 tiles to south, and come back to 256 tiles point.
8. After that, you can put stone to natural spring, yes you can use it.
9. And its turn to usable forever.

You can reproduce at position(40, 0) in test server.
Launch test server, with forceEveLocationX.ini 0 and Y 0. forceEveLocation.ini 1.
Born and walk right at 40 tiles, there is.

**Comment by jasonrohrer** [comment]
Excellent bug report!
