### ISSUE TITLE
Gates are hard to manage, possibly springy gates with family acces?

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#321]
it's a niche to make a locked fence for you or for some people you know
some people don't like it some like it, i don't mind

but on a city level, we need more support to make it useful

fences are ok protection against animals and other families
but they prevent scavenging
good example Bee town had only one gate, and we had 3 families inside and people always fixed every single fence preventing the making of a new gate, and while a spring was 20 tiles away, it became 100 tiels when you need to go out on top right and go al lthe way to middle left side of fence

so the less gates the less problem with giving acces rights, but we could have automatic family acces, so anyone from family can go out and come back and also decya only when everyone is dead inside of it (not sure what about the outposts, maybe it should need some repair each hour to signal you are still wantign that gate)
if you want other family have a gate, they should make their own entry/exit

also same as doors, they never stay closed, springy doors were useful, springy gates could be a thing, so people don't have to waste time with exit/enter  and if you fixed all fences, you can be sure that there is no weak point on defences and don't have to tell every 3 year old to close it after herself

people who are skilled to explore and know there is no threat are limited on going out, and people who just sit home and want to be secure block them, wanted to make popular the springy doors as one way exit but if we got a building, 7 doors 7 springs and a main gate is quite a big task alone, and i wont blame people not understanding my thinking of making the walls first and leave the buildings open, so some sort of cheaper springy gates would help secure towns to attackers/animals and would see more play

**Comment by jasonrohrer** [comment]
This is not a bug.  I'll be thinking about this in the future.
