### ISSUE TITLE
Perfect aim with shift click is dumb

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#324]
the game is unplayable this way

comes a bad intended kid and stabs everyone with a sword
comes a noob who is butthurt over something and stabs you with a knife

i was able to dodge low skill players all day
when even I die, daily 3 times then it shows how bad is the duel system, and any level of skill matters 0 in the calculation

what you call griefers dance, could be used against griefers as well
now we can blame it on lag maybe 20% of time but other than that, skill mattered on great scheme of things
i don't have the time to grab a weapon, i don't have any chance to dodge as a kid or if im hungry
i understand that multiple people should be able to kill one especially on murder cooldown
but this is too much
the previous system was simple but at least mostly balanced on defense and attack side
there is zero fun in getting stabbed by a noob while you are moving out of range
before i could be at least blaming myself if i was slow, but i had a great percentage of dodges, like always moved out of range and at least grab my weapon
and it's not about me, everyone
defending side is plain dumb, the attacker has the power of surprise and gives zero chance to the defender if reacts while 2-3 tile away

no way to play around it, got to take every thrash talker down, every other family, everyone with sword

on attacker side i was able to take 6 people down as eve very quick
possibly i could have done that without a magic aiming but would take longer

also makes no sense that a character stays aggro until it starves
should be at least a few seconds of cooldown and release arms for a few sec to be able to retaliate, also a bit of slow down whiel soemone appears on screen with a knife, same on defender side if grabs a weapon then slows down a bit

this one hit sistem with 90% chance for attackers is boring and gives zero satisfaction on kills
fencing a whole town ends up in gettign locked
lettign an eve inside maybe ok but some kid will always kill others, mixed families always die in like 40 minutes

either give us multiple hits or some chance of miss arrows or stabs cause this is plain dumb
even if you got weapon you die before pulling out cause they just run in screen and it's over

**Comment by jasonrohrer** [comment]
This is not a bug report.  I will be continuing to refine combat in the game in the future.
