### ISSUE TITLE
Server hiccups cause uncursable players. 

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#329]
When the ability to keep a surname alive regardless of someone else in the family having a last name a new bug was added. People are able to still permanently lose their surname when the server hiccups which causes uncursable players.

This has been going on since the hiccups first started but after the recent curse change it made it annoying enough to report.

**Comment by jasonrohrer** [comment]
What does a "hiccup" mean exactly?

I did fix it so that people without last names can be cursed.  But if there's still a bug causing last names to be lost, I should fix that too.

**Comment by ghost** [comment]
Whenever the server would disconnect for a few seconds you would start seeing the people the people without surnames pop up. I'm not sure if the bug was related to that or what you just fixed so I can't see if the root cause was the disconnects causing these players to permanently lose their surname or if the bug was whatever you just fixed.

**Comment by jasonrohrer** [comment]
I'm going to close this for now, assuming that it's fixed.  If there's any more info about this, please let me know.
