### ISSUE TITLE
Animal doesn't spawn in culled map.

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLife#332]
I found true cause of long term culling bugs.
Like this topic.
https://onehouronelife.com/forums/viewtopic.php?id=6816

If map object ID is 0 (means empty ground), culling doesn't work.
https://github.com/jasonrohrer/OneLife/blob/master/server/map.cpp#L7795

So, happening is no tree or no animals in around village, where culled by longTermCulling.
Animal always walk, and tree has been cutted and swamp has been removed, always)

This is reproduction video, please watch this.
(my testServer, what set server/settings/longTermNoLookCullSeconds.ini as 10, and server/settings/minActivePlayersForLongTermCulling.ini as 0.)
https://www.twitch.tv/videos/437587583

**Comment by jasonrohrer** [comment]
Nice find!

I will fix this soon.
