### ISSUE TITLE
Map reclamation can places items on roads

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#334]
Trees can grow in the middle of a road. You can decide if that is a problem. I could see that happening, but would it still be a fast road after removing the tree?

https://onehouronelife.com/forums/viewtopic.php?id=6940

**Comment by jasonrohrer** [comment]
Wow, cool find!

Yeah, I think I'll change it to clear the floor if some tile is going to be placed there.  That way, trees and milkweed and such would "break up" the road, which I think would be cooler.
