### ISSUE TITLE
Some transition by decay wont be fired until touch.

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLife#337]
I saw this problem in official server maybe bigserver2 with firing forge and milkweed.
So, first step, I captured video in my private test server.

https://www.twitch.tv/videos/439323038
https://www.twitch.tv/videos/439323435

Happen is, object stop transition of decay, some case.
And that continue when you touch.(Or maybe when somebody came to near, because getMapObject will be called)

I am on the way to find cause of bug from source now.

**Comment by jasonrohrer** [comment]
Thanks!

**Comment by jasonrohrer** [comment]
I see the proof in those videos.

I'm wondering if we can get some steps to reproduce.  Are you walking away and then coming back?

**Comment by TwistedHBG** [comment]
In my experience this happens when you walk away from the chunk and it gets unloaded, and it can easily be reproduced 100% of the time when hunting rabbits. Snare one, walk away, come back, and touch it to transition.

**Comment by ghost** [comment]
https://imgur.com/2GepxVc

**Comment by jasonrohrer** [comment]
Gif is interesting... hmmm....

In the modded client, it's no surprise that the thing "goes to sleep" when you're far enough away that you're not looking at it currently (it pays attention to what people can actually see, and only updates those things).

HOWEVER, when you walk back there, it should know that you're looking at it again, and cause it to start updating.

The rabbit is a great test case.  I'll try that today and see if I can nail it down.

**Comment by jasonrohrer** [comment]
YES!  I was able to reproduce this just now.  Thank you folks!
