### ISSUE TITLE
Log in key bug

### ISSUE THREAD

**Issue by Nuke41** [jasonrohrer/OneLife#339]
I bought One Hour One Life a year ago. Entered my email and product key to log in, worked great. But I recently got a new computer, and I installed One Hour One Life into my new PC. Entered my email and product key into the log in to log in and play, it said "Log in failed".
After several attempts and a second reinstall, same issue. But I tried manually typing my product key to see if copying and pasting was the issue, but then I notice the product key tab in the log in wont register the "1" key. One of my numbers for my product key has a number 1 in it, and the product key tab wont register the "1" key when I tried entering it. The email tab can register the "1" key, but not for the product key tab.
Since my product key numbers has a 1 in it, and the log in wont let me enter a "1", I cannot log into my account.

**Comment by Nuke41** [comment]
![One Hour One Life Login Bug](https://user-images.githubusercontent.com/51943272/59731581-8c68ad80-91fb-11e9-9f16-afadc6f514cc.png)

Here is a image of the number keys that the email registers, but the product key cant. I dont understand why it's like that. But I cant log in because of it.

**Comment by AlecYawata** [comment]
"1" is not used to account key.
Maybe you misunderstood some character as "1".

If still you have any proble, you have to mail to jason.

No change from 3 years ago.
https://github.com/jasonrohrer/OneLife/blob/master/gameSource/ExistingAccountPage.cpp#L51

No change from 7 years ago.
https://github.com/jasonrohrer/minorGems/blob/01cc4f4dbbf38e99c28e6cced9a7f0cb63ec1f5f/game/ticketServer/server.php#L28

**Comment by Nuke41** [comment]
> "1" is not used to account key.
> Maybe you misunderstood some character as "1".
> 
> If still you have any proble, you have to mail to jason.
> 
> No change from 3 years ago.
> https://github.com/jasonrohrer/OneLife/blob/master/gameSource/ExistingAccountPage.cpp#L51
> 
> No change from 7 years ago.
> https://github.com/jasonrohrer/minorGems/blob/01cc4f4dbbf38e99c28e6cced9a7f0cb63ec1f5f/game/ticketServer/server.php#L28

Hm, if thats so, then how the heck am I suppose to enter my key log in to enter the game? Looks like I'll have to email Jason about it then.

**Comment by jasonrohrer** [comment]
Yes, I'm guessing you're looking at your order number instead of your account key.  You should have gotten two emails, one from fast spring, the other from me.

The account key is 20 digits long with hyphens in it, like this:  XXXXX-XXXXX-XXXXX-XXXXX

If you can't figure this out, please email me:  jasonrohrer AT fastmail.fm
