### ISSUE TITLE
stuck on loading map screen on local server

### ISSUE THREAD

**Issue by FernandoGBR** [jasonrohrer/OneLife#34]
compiling latest server and client code
connecting to local server
client gets stuck on loading map screen

keeps receiving data, is connected to server, and if server shutdown client dies properly

all credit to UncleGus

**Comment by jasonrohrer** [comment]
Does the client have the full game data set installed?

It will need the objects folder, transitions, sprites, etc...

**Comment by FernandoGBR** [comment]
yes, afaik this is a whole client, with all needed data. Fresh clone from your repos.

**Comment by UncleGus** [comment]
What I did:
1. `git clone https://github.com/jasonrohrer/OneLife.git`
2. `OneLife/scripts/pullAndBuildTestSystem.sh`
3. In OneLife/server: `ln -s ../../OneLifeData7/dataVersionNumber.txt .`
4. `./OneLifeServer`
5. In OneLife/gamesource: `ln -s ../../OneLifeData7/dataVersionNumber.txt .`
6. `echo 0 > settings/fullScreen.ini`
7. `./OneLife`
8. Joined the server and got the bug.

I could see the messages being sent and received by the client and the server in the terminals' output.

**Comment by jasonrohrer** [comment]
Step 3 is already being done by the pull script, Gus...

Step 5 was indeed missing from the pull script, but I just added it in 9c202a46731cbde0ef648dd658cf882fd8974810

**Comment by jasonrohrer** [comment]
I'm not able to reproduce this on my end...

Steps:

1. git clone https://github.com/jasonrohrer/OneLife.git
2. mkdir testSystem
3. cp OneLife/scripts/pullAndBuildTestSystem.sh testSystem
4. cd testSystem
5. ./pullAndBuildTestSystem.sh

Open new terminal:
1. cd testSystem/OneLife/server
2. ./OneLifeServer

Open new terminal:
1. cd testSystem/OneLife/gameSource
2. ./OneLife
3. Enter bogus email and some random chars for key.
4. Click LOGIN


When I do this, I end up walking around in the game.  Gus, it sounds like your steps are pretty much the same as this.... I have no idea what the problem might be...

**Comment by FernandoGBR** [comment]
Issue seems to come from a data corruption. Bad from our side. SOLVED.

**Comment by UncleGus** [comment]
To be more specific, sprite 1007 and its txt file were moved from the sprites folder into the transitions folder.
