### ISSUE TITLE
Bare hand action can be caused from a distance.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#342]
You're holding Bow and Arrow.
Normally, clicking on any object which doesn't have transition of Bow and Arrow, you'll walk to nearby the object. so you can't open the door from a distance.
However, only client checks transition (can use Bow and Arrow for the object on the ground?). Thus using modded client, you can open from a distance. (Either changing code or adding transitions) 

Adding transitions (Bow and Arrow + Door etc.) and took a video in my private server (without modding server).
video - https://twitter.com/milkweed_ohol/status/1143083046066769922

**Comment by jasonrohrer** [comment]
A great bug report!  Thank you.
