### ISSUE TITLE
Bone piles can still show the incorrect name.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#343]
My grandmother died next to an existing graveyard while standing on a lone Flat Rock. When mousing over her bones immediately after she died, without ever moving them, they said 'Fresh Grave of Your Identical Twin Brother - Died Five Years Ago'

The weird thing is I never had an identical twin brother, so it's not like the bones inherited the wrong person's name. I did have a brother that was born soon after me (and immediately used the /die command), but the only way for him to be an identical twin should be to actually spawn in via the friend code. The family tree correctly shows him to as my little brother.

My layman's guess is that the problem lies in the SID bones which decay more quickly than normal bones.

**Comment by trevorhackman** [comment]
Might be the same case #308

**Comment by jasonrohrer** [comment]
Not sure about the identical twin thing.  What if he was born near the same time as you AND he looked just like you....

But yeah, sounds like her bones bounced off the flat rock to another spot that had other info lingering there....

**Comment by jasonrohrer** [comment]
Ah!  Yes, I was able to reproduce this just now.  Thank you!
