### ISSUE TITLE
Twin eves on bigserver still don't speak the same language

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#344]
Repeat of #314 - Language barrier on low population servers was fixed but language barrier between twin eves on high population servers wasn't. 

Larger problem is that twin eves aren't related and don't share the same family tree.

**Comment by jasonrohrer** [comment]
Yes, this is intentional.  They are Eves.  Each picks a family name, etc, just like real Eves.  They are separate families.
