### ISSUE TITLE
Game Crashing on Mac OS when I try to join a server

### ISSUE THREAD

**Issue by PinkCreeper727** [jasonrohrer/OneLife#346]
Whenever I attempt to join a server on One Hour One life my game crashes. I have deleted and reinstalled the game. It was working perfectly before the latest update where it kept repeatedly asking me to download the update and restart the game. I did this multiple times and when it finally seemed as though it had worked I was faced with this current issue of not being able to play the game. The game runs completely normally until I click login and am shown the loading screen as I am waiting to be born, it does this for about 3 seconds and then crashes, closing the app. My MacBook Pro comes up with the notice that "One Hour One Life" has quit unexpectedly. I deleted the game and reinstalled it, however this has not helped the issue.
I have also attached my log.txt file as well, hope this helps.
[log.txt](https://github.com/jasonrohrer/OneLife/files/3328563/log.txt)

**Comment by AlecYawata** [comment]
@PinkCreeper727 
`L4 | Mon Jun 24 07:47:03 2019 (555 ms) | general | OneLife client v244 (binV=243, dataV=244) starting up`
This is one line of my log.txt.

I though your client version is 216.
By `L4 | Mon Jun 24 14:06:11 2019 (379 ms) | general | OneLife client v244 (binV=216, dataV=244) starting up`
Old client will be crashed now.

Maybe you used old client like "OneLife_v217.app".
Find new version app like "OneLife_v243.app" from your game folder.
