### ISSUE TITLE
Creating multi use item with only 1 use is not working when new_agent is not 0.

### ISSUE THREAD

**Issue by FernandoGBR** [jasonrohrer/OneLife#35]
I know I already contacted you, but the bug is still there, and I think this is the right way to post the issue.

I want to create a dung pile in where stack up to 10 dungs. Is pretty the same than a stone pile but the dung is carried by shovel instead of hand.

1. I made a copy from stone pile. Set id = 30001, name = dung pile, and switching all sprite ids with the sprite of dung.

2. I made all transitions to make it work. All of them working pretty nice but one. 900_899 which is actually the creation of the dung pile.

900_899.txt contents:

`502 30001 0 0.000000 0.000000 0 1 0 1`

which as far as i understand is: when shovel with dung used on dung then gimme back a shovel, create a dung pile, and set the inverse use for target so it creates with 1 use instead of full.

If i change the 502 to 0 it works, but I lose a shovel in the way :)

Just in case it matters, here is the 900_899_LA.txt code:

`0 30001 0 0.000000 0.000000 0 1 0 1`

**Comment by jasonrohrer** [comment]
Are you using the editor for this?

I don't spend any time editing these values directly, so I'd have to check the code to find out which number does what.

You're dealing with something where both the actor and the target need to get used up in the process.  The check boxes in the transition editor would make all of this more clear.

**Comment by FernandoGBR** [comment]
Wasn't using, but now comparing in editor seems all exactly as rock + rock recipe.

Screens of both recipes mentioned in the former post.

![screen1](https://user-images.githubusercontent.com/18265220/40398851-5c41d956-5e3a-11e8-99f1-95e141d70d6b.png)
![screen2](https://user-images.githubusercontent.com/18265220/40398852-5c5f3bae-5e3a-11e8-8d49-c4420e06ecdd.png)

**Comment by jasonrohrer** [comment]
You can see why the shovel disappears in the first screen shot.

Empty shovel should go there in the new actor field.

**Comment by FernandoGBR** [comment]
It was a test, and i dint removed it, but that is the last action for the actor, so it is removing the shovel instead of making a broken steel tool. How is this interacting with the creation of the dung pile?

How can i make that the dung pile is not created on full quantity.

**Comment by jasonrohrer** [comment]
Sorry... but I don't have any more time to think about this right now.

I really need to focus on the actual game and bugs affecting it.
