### ISSUE TITLE
Cannot shoot from specific direction.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#350]
Cannot shoot objects or people from specific direction. (White area in third link.)
First link and second one are video that I reproduced them.
https://imgur.com/a/AlraTN1
https://imgur.com/a/fgEJ036
https://imgur.com/ifROMlN

**Comment by jasonrohrer** [comment]
There was a bug in my implementation of Bresenham's line algorithm.  The pseudocode shown in Wikipedia is incomplete and misses some cases.  Oops.
