### ISSUE TITLE
Road bouncing

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#352]
https://youtu.be/pCctzT9fvOw?t=425

Ok this is really weird the previous video link doesnt actually show the bug no idea why but go to the video at 7:10 and you should see it.

https://youtu.be/pCctzT9fvOw

Ok still doesnt work, i dont know why i saw it in the video then couldn't see it anymore for some reason, anyway maybe you will see it, it's supposed to show someone going on the road hitting the oil rig then going back and fourth on the same tile looking like the person has two body and face alternating left and right very fast.

**Comment by jasonrohrer** [comment]
I see it at 7:10 in that video.

Looks like having a blocking object on the road causes a problem.  Will check.
