### ISSUE TITLE
Force feeding breaks yum chain

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#354]
Someone feeding you breaks your yum chain

Maybe you could only feed someone when they are hungry or starving.

Having a starving emote would be nice to know when someone is hungry, especially useful since the fitness update to see if one your kids is starving.

**Comment by jasonrohrer** [comment]
Yes, we had a discussion about this via email (that was you, right?)

Anyway, the current idea is to make other people feeding you NOT break your Yum chain (but you still wouldn't get the YUM bonus applied to foods eaten that way, unless they were actually yummy to you).

**Comment by Dodg-e** [comment]
It wasn't me, not breaking the YUM chain is a good idea, could be abused to keep the YUM chain going before finding a new food but not a big deal imo.

I still think a starving face would be interesting especially since now having family members alive is more important.
