### ISSUE TITLE
Disconnecting then Failing Login Attempts

### ISSUE THREAD

**Issue by Kaybr0** [jasonrohrer/OneLife#356]
Occasionally I will attempt an action (ex: snaring a rabbit, picking milkweek, etc.) and it rubberbands for a few seconds before crashing. Then upon trying to log back in it keeps saying “Login Failed” so matter how many repeated attempts and opening/closing the game. 
I can only log back in when I have died and have to start a new life.

**Comment by jasonrohrer** [comment]
Is it actually CRASHING, or just getting disconnected?

The login failure after disconnect is likely the same as #345, which has been fixed now.
