### ISSUE TITLE
Oil Pumpjack Breaking Oddly Fast

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#359]
Dear Jason,
The "oil pumpjack with full tank" transitions like
50%: oil pumpjack
50%: exhausted oil pump jack

This implies that after ca 1/ln(2)=1.4..., so circa 1-2 uses, the newly with several iron made oil pump will break. 
I assume that you did not intend to implement that extreme inefficency and that this variable's value was an oversight.

**Comment by jasonrohrer** [comment]
Yes, I fixed it, sorry!

https://github.com/jasonrohrer/OneLifeData7/issues/397
