### ISSUE TITLE
Can escape at some distance after killing someone

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#362]
Move speed won't be updated until next action happens.
If I Shift + Right-Click someone and click at far place (using zoom out mod), I stab them and keep running normal speed.
https://imgur.com/a/L21UIG6

**Comment by be227** [comment]
do you think the zoom out mods causing these people to come after you because I seem to have that same problem too

**Comment by be227** [comment]
I do not accept this in the game it's bulshit You Only Kill For Fun get away from me
if the Creator put in the game you are going to use it as a cheat
