### ISSUE TITLE
Apocalypse marker is often missing during third tier and continues for hours after apocalypse occurs.

### ISSUE THREAD

**Issue by BlueDiamondAvatar** [jasonrohrer/OneLife#363]
Apocalypses occurred on Monday 7/22 and Tuesday 7/23.  See forum post https://onehouronelife.com/forums/viewtopic.php?id=7314

Two issues are occurring with the apocalypse markers and associated bell tones.  I have personally observed both of these problems.  I'm writing them up based on the order they occur in the apocalypse progression 1) In some cases, no apocalypse marker is available during while the third tier of the endtower is in its "unstable" condition.  2) In some cases, an apocalypse marker is persisting after the apocalypse ocurred, leading players to the location where the endtower used to be, and masking the development of new endtowers.

 I played a full game immediately prior to the apocalypse occuring on 7/23, as a member of the Ziv family. (Here's a link to this Eve Ziv http://lineage.onehouronelife.com/server.php?action=character_page&id=5014255).  I did not see an apocalypse marker at all during that life, which was unusual as I had seen one during most of my play time that day.   I was past age fifty when an apocalypse marker suddenly appeared 4.8 kilometers away.  Based on comments on the discord channel, my character passed immediately before the apocalypse occurred.  The ziv family had only been alive for three hours, meaning no ancestor had been alive when the third tier of the endtower was set.  I believe this is relevant - since both bell markers and endtower markers are passed down from the mother to her children.

An apocalypse also occurred on 7/22.  During play on the evenign of 7/22 there were at least two families still hearing the apocalypse bell.  As a baby, every new member of these families heard a nearly finished apocalypse bell, and gained a distant home marker.  If you follow this home marker, the site is vacant, and there is no apocalypse endtower.  
Here are the profiles for the two eves whose families are hearing the apocalypse bell.
http://lineage.onehouronelife.com/server.php?action=character_page&id=5007241
http://lineage.onehouronelife.com/server.php?action=character_page&id=5007676

Here is a screenshot I took of myself, standing on the spot my homemarker indicated was the endtower site.  I cut down the surrounding trees to convince myself there were no hidden endtowers. (hetuw mod indicates I am standing on the spot the homemarker pointed to)
https://cdn.discordapp.com/attachments/419395479420534785/603007189698871307/No_Apocalypse_Here.jpg

I later received a confirming note through DMS on discord.  See screenshots of the 7/22 endtower in  comment below.

This issue is being widely discussed on the forums, and the discord channel, and is affecting gameplay for many players at this time.

**Comment by BlueDiamondAvatar** [comment]
I received additional information confirming that the apocalypse endtower homemarker inherited by the Crystal and Flower families does point to the location of the endtower for an apocalypse that occurred hours before.  See screenshot of endtower immediately before the apocalypse occurred.  Note location of ice hole and big rock.  Post apocalypse a pine tree appeared two tiles north of the big rock, just below the endtower site.

https://cdn.discordapp.com/attachments/603090445765181446/603091563542872067/Apoc_22_July_2019-2.png

post-apocalypse screenshot of same people and location.  
https://cdn.discordapp.com/attachments/603090445765181446/603091592441495593/Apoc_22_July_19-3.png

**Comment by ghost** [comment]
Pretty sure what is happening is survivors of the Apocalypse are passing their bell markers onto their children which then produces the bing bong sound and leaves a phantom marker leading to wherever the Apocalypse was.

Honestly it's a pretty neat feature imo that survivors of the event end up haunted by some traumatic event that occurred before they were even born. Curse of the Apocalypse is definitely a neat fluff experience in game.

**Comment by DarkDrak0** [comment]
Adittional info on the marker-disappearence bug.
We created three apocalypse towers timed to go off in close succession. one was dismanteled almost right away, another one was dismanteled one life after (but also set up one life after).
The tower which was set up first did send a signal once, however it remained "invisible" and stopped sending allarms to people until the final block seeped in.
Theory: the bell markers override eachother, but once a tower gets dismanteled they disappear. the overriden bellmark however does not reappear and thus people are unaware of its existence.
