### ISSUE TITLE
new issue with game

### ISSUE THREAD

**Issue by be227** [jasonrohrer/OneLife#368]
OneLife. I am sorry about this but I had to bring up a new issue with game I have a problem with people's Killing In The Game it seems like that killing for fun not surviving they even killed their own family I can't take on the game until you fix this up with this killing problem. the second  issue The Game broke on me  

I don't even like killing in the game all I want to do is just survive and just learn but I can't even do that because they kill me I'm not even a threat to everyone I like helping up people

I don't like it when people follow me in the game it really scares me

I don't like it when player said you broke something but I was going to fix it anyways and then they kill me I really getting pissed off with players if this keeps up I'm not playing this game anymore and I want my money back if that's the case

**Comment by jasonrohrer** [comment]
I'm working on this!
