### ISSUE TITLE
Newcomen Engine Tower can not be removed.

### ISSUE THREAD

**Issue by DarkDrak0** [jasonrohrer/OneLife#369]
We had this issue before with Freestanding newcommen tower. Now it's the same issue, just with a few extra (easy) steps. Currently it's being used (has been used for at least half a year now, but never before as much as now) to block buildings, stuffing lots of stuff inside them beforehand.

Furthermore, all steps of freestanding newcomen tower and Newcomen Engine tower do not allow to walk on the tile to their right. I assume it's because Newcomen Atmospheric Core has to go there and it would look odd for people walking through it. However these structures do not have the core yet and the result is that a tile is magically unaccessible and thus can be and is being used to block off gates and doors.

**Comment by jasonrohrer** [comment]
Fixed.
