### ISSUE TITLE
Losing planes outside the rift

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#371]
With the recent change to prevent leaving the rift by plane, now when you fly a plane with no landing pad nearby, the player is left behind but the plane still goes outside the rift and becomes lost. This is a way to grief and a huge loss of resources.

**Comment by be227** [comment]
you know what that is true we need more resources my good idea is if we have some trees that we can grow

**Comment by jasonrohrer** [comment]
I'm not able to reproduce this.  If there's no landing pad, an Eve location is used for the landing, and if that location is outside the rift for some reason, the center of the map is used (0,0).

In any event, the player and the plane always end up in the same spot.

The player is in fact "holding" the plan at the very end of the flight, wherever they end up.

If you find that this is still happening, please re-open.
