### ISSUE TITLE
a ground tile that doesn't exist

### ISSUE THREAD

**Issue by Supercraft1273** [jasonrohrer/OneLife#373]
my game has been crashing at ground I figured out today it crashed because a ground type doesn't exist. please comment and tell me which of these aren't in your game if that game is the modorn version now. ground 0 ground_ 1 ground_ 2 ground _3 ground_ 4  ground_ 5 
ground_6 check your game file and go to ground to tell me which of these don't exist

**Comment by jasonrohrer** [comment]
Those are all correct.

Not sure what else is going on there to cause a crash.

Please email me if you are still having trouble:  jasonrohrer AT fastmail DOT fm
