### ISSUE TITLE
Young kids( And elders ) can pick swords up.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#378]
It happens when they swap swords( which cannot be held because of their age ) with sterile pads( which is permanent && having set-down transition ).

Video Link-https://imgur.com/a/IXnLXZH

server doesn't check **canPickUp** in this case.
https://github.com/jasonrohrer/OneLife/blob/1aed2d358e724f5fe6be99a87fa4ee12fe40b231/server/server.cpp#L15882

**Comment by jasonrohrer** [comment]
Thank you!
