### ISSUE TITLE
Reducing stagger/death time leaves held wound around after player death

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLife#38]
Since the decay transition is still set to the same amount of time, when the stagger time is reduced, the wound still exists after the player has died and is dropped on the ground.

**Comment by UncleGus** [comment]
Thanks Embeam and The Bean Buddha for finding this.

**Comment by jasonrohrer** [comment]
I don't think there is a decay time on any of the wounds, unless I'm missing something.

Also, I've done a ton of testing on this end, and wounds aren't getting dropped on the ground, in general, even if I shorten the death stagger through multiple wounds

There must be something else causing the wounds to get dropped on the ground.

I'm guessing that the normal medical procedures can be used to "clean up" the wound on the ground, right?

**Comment by UncleGus** [comment]
Sorry, I'll go back and try to get a repro. I was making an educated guess based on what I thought was how wounds were disposed of.

**Comment by UncleGus** [comment]
I have seen this happen again. What I noticed this time was that I clicked on a player to kill them, my player object moved towards them, they started moving just before I got there, then my player performed the "using" animation and the wound appeared on the ground space just vacated by the target player and the target player kept what they had in their hand.

Could it be something to do with the `killLater` stuff?

**Comment by jasonrohrer** [comment]
Oh, sounds like this has to do with how the server handles misses with a weapon.

It is possible that it leaves something on the ground (arrow, for example), but in this case, the wound is being left on the ground by accident.  I will look into it.

**Comment by jasonrohrer** [comment]
This is on an un-modded server with the current live data?

I'm having trouble reproducing this on my end.  When a murder attempt fails (knife miss), it looks like there's no wound left on the ground.

By the way, these commands are REALLY helpful on linux for testing:

// add 97ms latency to local loopback:
sudo tc qdisc add dev lo root netem delay 97ms

// clear extra latency
sudo tc qdisc del dev lo root netem


Adding 1000ms of latency makes it really easy to "miss" with the knife as someone walks by.

**Comment by jasonrohrer** [comment]
More testing, and the arrow is correctly left on the ground during a bow miss.

Tried it both when target person is carrying something and when not.

**Comment by UncleGus** [comment]
This was using modded data. I've since discovered that some transitions were set wrong. I think the wound was being treated as the embedded object, so when the player missed, it left the wound on the ground, or if it hit, the person didn't get the wound, but when they died, it was left in their grave.
