### ISSUE TITLE
 updates

### ISSUE THREAD

**Issue by be227** [jasonrohrer/OneLife#382]
I am getting sick and tired of the updates why I have to explain the problem to you in the game of One Hour One I like the zoom out mod now this is where the problem comes in with every update you make change is the zoom out mod and every time at the search for that mod it gets harder

I like to be posted on the update and the mob update I'll keep playing a game with those two things are there if not I had to rate your game as 0 I'm also a YouTuber and a game developer as well I don't want to say you're game sucks on YouTube

**Comment by jasonrohrer** [comment]
I update the game weekly.  Sorry if that causes problems for you.
