### ISSUE TITLE
Forum report: cursed players can reliably be born in rift as eve

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#383]
Consequence of fix to #377 

https://onehouronelife.com/forums/viewtopic.php?pid=73437#p73437

> This is only partially right as he made it where donkey eves spawn in the Hell Cell now. He ended up adding a sanity check last patch which makes sure all Eves spawn in the box (unless you're a tutorial Eve.) This means if you're down to two families in the rift and get cursed out of both you spawn inside the box AND end up as an Eve which is why one of the recent arcs ended.
> 
> This means as long as you have lives you're able to repeatedly attack towns the same way feral eves could around the time of the come together update with zero consequences. You can also spam yourself in with twins/trips/quads to produce up to four feral eves just set to attack villages because the donkey player will force everyone to be an Eve while the sanity check will force them into the box.

**Comment by jasonrohrer** [comment]
Yikes!  Nice catch!

**Comment by jasonrohrer** [comment]
Actually, the sanity check is NOT the problem here.

That sanity check is applied before the cursed status is factored in.

There's something else awry.

**Comment by jasonrohrer** [comment]
Checking the logs, there are actually no Eves being born inside the rift after the Eve window closes.

Any cursed Eves are correctly being born in D-town, 20,000 tiles away....

**Comment by jasonrohrer** [comment]
I made a bunch of changes recently that were related to this issue, or at least to player's perception of this issue.
