### ISSUE TITLE
Cursing useless to less active players

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#384]
A curse lasts a set amount of real time, 48 hours. If you curse someone, and then don't play for 48 hours, then your curse has no effect whatsoever. The effectiveness of your curse is directly tied to how active of a player you are.

**Comment by TwistedHBG** [comment]
+1

Cursing feels a bit pointless unless you every day. If the current area ban way of cursing remains it needs to last longer than just 48 hours. One week seems like a good number.

**Comment by jasonrohrer** [comment]
This change is live now.  Personal curses last 7 days.
