### ISSUE TITLE
Family Tree Glitches

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLife#390]
It's become increasingly common for me lately for some of my children to quite literally just.. not appear, at all, on the family tree. As if they never existed. 

I first noticed it a few days ago, when I only had a single child who decided not to suicide, rather late in age. I named her Zinnia Radish, was very careful to feed her berries when I went old, and she lived to 3 years old, enough to grab things. She set off to get some branches nearby and never came back.

I thought she'd died, so I starved, because every other kid I had suicided lol.. checked the [family tree](http://lineage.onehouronelife.com/server.php?action=character_page&id=3908300), she's not there. Figured she might've lived. Checked again next day, nope- it was like she never existed.

It happened to me once again last night. I had twin girls, named Rosie and Posy Ryman. I remember them, because one asked me where their names came from, and I told them I often named my girls after flowers. They lived to adulthood, because I also remember killing two of their babies to lineage ban them because they ran, rather than /died, and I didn't want them being reborn over and over to us. Rosie fed me on the murder cooldowns. 

Neither show up on the family tree. Not when I search their names, not on the family lineage [here](http://lineage.onehouronelife.com/server.php?action=character_page&id=3925643&rel_id=3925643), nowhere at all. It's like they didn't exist. 

I assume there's some issue causing the system not to record their lives. I don't know what's causing it. Asking around on discord, I've been told it's happened to other people too- both their children, and even themselves at times, simply not appearing anywhere on the family tree. All I know is that it's increasingly annoying.

**Comment by jasonrohrer** [comment]
I've put some stuff in place to catch these outages when they happen, to help me figure out why they happen.
