### ISSUE TITLE
Hungry work not calculating yum right

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#392]
So trees take ten food to cut, and you need five food leftover (why 5? seems excessive) or you can't cut. I've had 10+ food in yum bonus, but been unable to cut down trees. I think they're not taking your yum bonus into account when checking if you can cut down a tree or not. 

On a separate note, I've found many players to be confused when they try to cut down a tree, but can't. There's nothing in-game that signals when you can or why you can't cut down a tree.

**Comment by jasonrohrer** [comment]
Will think more about signalling.  Fixed the other two things

**Comment by jasonrohrer** [comment]
May think about signalling hungry work in future.
