### ISSUE TITLE
Lots of waste of food due to food value and drain

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#394]
Current food drain  and food values enables waste of food.

For example eating foods that give a good amount of pips like pies and stew when not hungry or starving especially before adulthood is creating a lot of overeating.

And at the same time the current food drain makes it so eating is a constant thing to do.

Proposed solution:

Dividing by 2 value from every food but also dividing by 2 the current food drain.

So food drain would be slower but the food value would be lower too, which enables the possibility to eat until full and have more time to do other stuff until having to eat again.

Since the food value is divided by 2 there is less waste because overeating is harder

Also this makes food with high value less bad since you dont have to wait until starving to eat them without overeating.

**Comment by jasonrohrer** [comment]
We could also block food consumption if you don't have room for it..... or if you don't have room for at least half of it, or something.

The server could have a TOO FULL message it sends the client, and then the client could pop the FULL banner, even though the pips aren't all full.

**Comment by Dodg-e** [comment]
Yes blocking food consumption if it wastes a large ammount of food would be nice and make sense (you cant continually eat IRL)

Or overeating could make someone visibly fat maybe a use for the pregnant belly: https://onetech.info/3046-Pregnant-Belly

A mix of both would be better imo, like eating/wasting way too much would be impossible but overeating constantly would make you fat. 

Regarding the rythm of the game is dividing everything by two (food value and food rate) would it really change the rythm? Since you have to produce the same ammount since it's half the value.

And if it did would it really be an issue?

With how the game is currently the rythm is fine but if at some point the game switches to needing more communication and cooperation to achieve things and even produce ressources like food then it would be more about strategy/organization and less about speed.

So in this case having a different rythm would make sense, the game would be harder in a sense more elaborate so having a slower rythm would be needed since failing to organize would have a lot more consequences and having a fast rythm at the same time would make it not enjoyable/unplayable or even impossible.

**Comment by jasonrohrer** [comment]
I've decided not to touch this for now.
