### ISSUE TITLE
Cant put clothes under apron

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#397]
Apron and medical apron dont have insulation and that's fair but you cant put clothes under the apron. Which makes you naked under the apron and not how an apron is worn, usually.

**Comment by jasonrohrer** [comment]
Well... the apron is a tunic.  You can wear pants under it, though.

There are only 6 clothing slots in the engine.  Hat, tunic, bottoms, backpack, left shoe, right shoe.

Maybe there needs to be a 7th one, like "belt" or something, that goes over the clothes.

But concerning the apron, there's also an issue with how it ties around the body. I worry that if you wear it on top of a flowing dress, it would look weird...

**Comment by miskas9** [comment]
have a naked torso with an apron is also weird, I would prefer the weirdness with the cloths on.
Belts also would be nice and even nicer if you could store something on them.
7th slot would be useful in the future.

**Comment by jasonrohrer** [comment]
I'm going to table this for now.
