### ISSUE TITLE
segfault on local system

### ISSUE THREAD

**Issue by tomberek** [jasonrohrer/OneLife#4]
When the client uses `echo 1 > autoLogin.ini` pointed at a local server with **no saved credentials**, the client segfaults. When autoLogin is disabled and you enter some fake email/key the game loads without issue.

- [x] tested on Ubuntu Linux
- [ ] test on other OS
- [ ] are we reading a file that doesn't exist?
- [ ] are we reading a 0-length buffer where the credentials should be?
- [ ] are we writing to an uninitialized buffer?

**Comment by jasonrohrer** [comment]
Perfect!  Thanks for finding this.  It's on my list of stuff to fix next week.

**Comment by jasonrohrer** [comment]
Fixed!  Thank you.
