### ISSUE TITLE
Issues with PVP system and possible solution

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#401]
Current PVP system has still issues, but basically the main complaint is getting randomly killed without having any chance to react to it fast enough or do anything about it.

What if there was a slight delay between when murder mouth is trigerred and when you can actually kill someone, this give the ability to someone targetted to have a few seconds to run away.

Also what if, if you are targetted you get visibly scared as an emotion "death stare", and you keep being scared as long as you are targetted, this gives the possibility to not only avoid random out of nowhere death but also to be able to counter attack when you're not targetted anymore.

More details:  https://onehouronelife.com/forums/viewtopic.php?pid=74257#p74257

**Comment by jasonrohrer** [comment]
Yes, the delay is fine.  I'll add that.

As for the visual face change, that's a bit more expensive to implement and test, but I'll think about it.
