### ISSUE TITLE
Names on graves still duplicate

### ISSUE THREAD

**Issue by ChickenBatnana** [jasonrohrer/OneLife#402]
![20190923225653_1](https://user-images.githubusercontent.com/55719034/65465553-e6ad8600-de5c-11e9-84dc-0b1d87561576.jpg)
![20190923225655_1](https://user-images.githubusercontent.com/55719034/65465561-ec0ad080-de5c-11e9-89b4-440a8c8b0f6a.jpg)
![20190923225657_1](https://user-images.githubusercontent.com/55719034/65465563-ef05c100-de5c-11e9-8690-aa22e4774228.jpg)
As you can see, the names on the graves are still duplicated. These three were next to each other, but I have also seen them far apart. This means that the cart fix is not working, or at least isn't the only thing causing the issue. If you ask me, we should be able to put bones in carts again. Towns are very cluttered now.

**Comment by jasonrohrer** [comment]
Well, putting bones in a cart would definitely trigger this, so at least that is fixed.

There's probably some other way to trigger this that I haven't figured out yet.



If I allow bones in carts again, I'll have to figure out how to make their names forgotten as soon as they are put in a cart.  I don't think players will like this (it will surprise them, when their mother's name is forgotten).
