### ISSUE TITLE
Rift wall doesn't block items flying over it. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#404]
![Over the rift](https://user-images.githubusercontent.com/53706597/65566341-7a945600-df20-11e9-93cb-f635260c7acf.png)

Can still launch items over the rift wall.

**Comment by jasonrohrer** [comment]
Yes, there was one last case of basket launching (if baskets have same number of items and are right-clicked to stack, the fling happens).
