### ISSUE TITLE
Outdated Tutorial

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#407]
The tutorial contains outdated information on cursing. Has the old curse-once-every-two hours-build-up-curse-score system explained.

It also contains no information about how property works. A pretty important system that new players won't have a clue about. How fences and gates work, and how ownership of gates work, and how ownership can be passed to others. 

Could also be good to explain hungry work in the tutorial.

**Comment by jasonrohrer** [comment]
Fixing it to reflect the latest curse changes.

The tutorial is not meant to cover everything.  Even the curse stuff is in the extra, optional hallway.
