### ISSUE TITLE
! appearance bug

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#410]
! appearing from a far away distance, reported to be visible from tutorial

**Comment by TwistedHBG** [comment]
It's coming from outside the rift. It's either just displaying for no reason, or it's coming from Donkey Town. It pops up sporadically and not at a constant rate, but it's very frequent.

Our town was on the south edge and the notification kept popping up in the top right corner. I ran towards it to investigate, and when I reached the NE corner of the rift the notification was still popping up in the top right corner.

**Comment by BlueDiamondAvatar** [comment]
Picture evidence of same issue
[picture](https://cdn.discordapp.com/attachments/498293923576283146/627993091214671901/donkey_town_is_spamming_us_with_yoohoo.jpg)

**Comment by jasonrohrer** [comment]
Thanks!

I'm having a lot of trouble reproducing this, even on the live server.

Any more clues?

Is the notification constant, or flickering?  Does it come and go?

**Comment by jasonrohrer** [comment]
Actually, I think I've tracked down the cause of this.

Thanks for the report!

**Comment by TwistedHBG** [comment]
This has not been fixed, it's still happening.

**Comment by jasonrohrer** [comment]
It has to do with players that are WAY out of range, so their coordinates are replaced with dummy coords.  Fixing it now.
