### ISSUE TITLE
Disconnect issues

### ISSUE THREAD

**Issue by hetuw** [jasonrohrer/OneLife#412]
It happens most often when i start a new life.
I get randomly disconnected in the first two years of my life.
When i grow up the disconnects get much less common.

It would be nice if the client automatically reconnects when a disconnect happens.
This would safe time that might be needed to eat a berry before starving.
I never want to not reconnect to the game after a disconnect.

**Comment by jasonrohrer** [comment]
Any clue as to what's causing the disconnect?

The reason it doesn't auto-reconnect is that disconnection is an unexpected condition that needs to be brought to the user's attention.

In all the games of OHOL that I've played, or that my children have played, I can't recall a single disconnect.

So there's either a rare bug in the client or some kind of networking issue on your end.

**Comment by jasonrohrer** [comment]
Closing for now, for lack of additional info.  Please re-open if you're still having this problem.
