### ISSUE TITLE
Screenshots in tga format

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#417]
Need to convert them each time to post screenschots

**Comment by jasonrohrer** [comment]
Gotta pick my battles here.

Changing this would have to happen pretty deep in some old engine code.  It automatically uses PNG if libpng is linked in, but I don't link it in on most platforms for simplicity's sake.

Switching away from libpng (to stb_image_write, for example) would involve quite a bit of error-prone coding.
