### ISSUE TITLE
Some issues with new tool tip

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#418]
The first recipe of the list doesn't show arrows, and pressing TAB goes to the next recipe, so if you want tips for the first recipe you have to go all the way trough the recipes and back to the first one.

But at the same time it should be needed to press TAB to show the arrows, otherwise holding an object would show arrows all the time.

So maybe holding an object wouldn't show the tool tip but just a text like "PRESS TAB FOR CRAFTING RECIPES" or just "TAB", this way the first recipe of the list would show arrows but simply holding an object wouldn't show anything.

It's an issue for objects that have only one recipes since you cant TAB trough them

<a href="https://ibb.co/SmtJrCj"><img src="https://i.ibb.co/NN97SBv/screen00128.jpg" alt="screen00128" border="0"></a>

Eating something doesn't update the arrow, for example eating a berry will still show an arrown on the flint chip even when there is no berry in hand anymore

Holding the secondary object doesn't show an arrow for the primary object, example with holding a bucket of water doesn't show where the bowl of water is

Note: it makes sense since it's not the right order but at the same time someone will run around trying to find an arrow and wont find anything. Maybe the arrow should be a different color or something else not sure

<a href="https://ibb.co/DCpVKN6"><img src="https://i.ibb.co/3Nzrhw8/screen00130.jpg" alt="screen00130" border="0"></a>

But then when you drop the bucket you have an arrow on the bucket but no arrow on the bowl of water. So you still dont know what to do with the bucket of water

<a href="https://ibb.co/Nt79Ck9"><img src="https://i.ibb.co/CmWb8Xb/screen00131.jpg" alt="screen00131" border="0"></a>

Maybe in this sorts of cases the arrow should be a number and there would be one number for the bucket and one for the bowl of water.

Over the bowl of water it would be the number "1" and over the (partial) bucket of water it would be the number "2"

So you know that the first one goes on the second one and not the opposite

But when you have the primary object in hand it would simply be an arrow.

**Comment by jasonrohrer** [comment]
Dodge, are you aware that you can SHIFT-TAB to go backwards in the list?

There has to be some way to make the arrows visible, and 

I think we discussed this in the forums.


The single-recipe objects are a problem, though, and many of the other issues you mentioned.
