### ISSUE TITLE
Error 1 opening Eve KissDB

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLife#42]
If the server is started for the first time and shut down without a player joining, the Eve db becomes broken. It is fixed by removing the db files and restarting.

**Comment by jasonrohrer** [comment]
I'm not able to reproduce this.

Steps that I tried:

1.  Delete all .db files
2.  Run server.
3.  Shutdown server (set shutdownMode.ini to 1  OR Ctrl-Z in console---tried both).
4.  Look and see various .db files created, including eve.db
5.  Start server again.
6.  Don't see any error messages about eve.db failing to open.

**Comment by UncleGus** [comment]
Might be only an issue after the first clone of the repo?
Or maybe there are some conditions on your dev machine that aren't in the git repo?
It still affects me and most people I've helped set up the dev environment have encountered it as well.

**Comment by jasonrohrer** [comment]
Are you running linodes?

Can you throw one up with a test server on it, get it to trigger this bug, and then give me root on it?

**Comment by UncleGus** [comment]
Not a linode server, but on Azure. Happens locally as well. I'll see if I can get a server set up for you to reproduce it.

**Comment by jasonrohrer** [comment]
Just cloned clean and ran a fresh server on Linode.  No error messages about eve.db after quitting and starting the server again with no connections.

How is this running on Azure?  Is MS running linux servers now, or did you somehow build this for Windows Enterprise Edition or whatever it's called?

I mean, the server SHOULD build and run on Windows.... I've just never really tested it there.

**Comment by UncleGus** [comment]
Not Windows, linux. Ubuntu 16 / 18. I'll try to set up a repro for you.
