### ISSUE TITLE
No delay on spoken text 

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#424]
Communicating with someone especially with limited charachters means that when you want to say a full sentence like "come over here i want to show you something"

Could become "come over here" "i want to show you" "something"

The issue is writing the next message overrides the previous one instantly

So someone trying to read could only have the time to read "something" when the other person finishes his sentences

There should be some delay for each spoken text so you are able to read the full sentence.

Maybe delay could depend on the lenght of text

**Comment by ghost** [comment]
There are 1 second delays

**Comment by jasonrohrer** [comment]
I'm not too worried about this issue.

As the speaker, you have the power to space it out.

Auto spacing would just be too clean of a way to "bypass" the character limit when young.  You could back log a long speech and just let it play automatically.
