### ISSUE TITLE
Able to interact with doors/gates while injured

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#427]
This is the only action able to be done while in an injured state which is likely an oversight considering you can't interact with anything else while hurt.

**Comment by AlecYawata** [comment]
Waking up a bear, is same.
Maybe scare rabbit in hole, and move minecart are same too.

**Comment by jasonrohrer** [comment]
You can't hold anything while hurt, but you can trigger these kinds of default transitions.  I think it's okay.
