### ISSUE TITLE
Clicking where windows taskbar is tabs out the game

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#429]
Clicking at the bottom off the screen where the windows taskbar is (or food bar in game)

Makes it tab out of the game

Happens since windows update, maybe related.

**Comment by jasonrohrer** [comment]
In fullscreen mode?

And the task bar itself isn't visible?

Are you running in real full screen or borderless?

**Comment by Dodg-e** [comment]
Issue is gone, not sure what caused it

I'll close the issue for now, if it comes back i reopen and note details.
