### ISSUE TITLE
Clicking shift doesn't lock movement

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#430]
When trying to aim at someone to murder, shift+right click still makes you move in the clicked direction

Trying to aim at someone running around while standing still like guarding an entrance or anything else forces you to move in a given direction.

**Comment by jasonrohrer** [comment]
It's a weird case, because many times, you do want to start chasing them.  When you click to kill, your character heads there and tries to kill.

However, I guess with the murder-mouth changes, and the waiting period, this no longer makes as much sense.
