### ISSUE TITLE
When updating the website version it automatically tabs out and locks the cursor until the program is closed and restarted.

### ISSUE THREAD

**Issue by SpiritBomb32** [jasonrohrer/OneLife#432]
When updating the version of OhOl downloaded from the website, it goes through the loading screens but switches to the desktop and keeps the cursor in a section, forcing the user to do Esc %. Once the program is closed and restarted, The program is updated and working. I do not know if this is a personal issue, or if others are experiencing it too.

**Comment by jasonrohrer** [comment]
Yes, I have seen this on rare occasions.

I think what's happening is that the game finishes the update and tries to restart itself, but then the restarted version is "minimized" or in a tiny window or something, so you can't see or interact with it.

Does this match your experience?

**Comment by SpiritBomb32** [comment]
Yes it does this for mine on occasion, When I click on the icon on the hotbar, it locks the cursor and I have to press the windows key or Esc %.

**Comment by jasonrohrer** [comment]
Unfortunately, because it's occasional, I really don't know how to fix it.  I think it's some kind of Windows glitch.

**Comment by Dodg-e** [comment]
"I think what's happening is that the game finishes the update and tries to restart itself"

Isn't it possible to make it not restart itself?

**Comment by jasonrohrer** [comment]
Not if there's a new executable that needs to be run, as part of the update.

**Comment by jasonrohrer** [comment]
Oh, you mean let the end user restart it manually?

That is an option, and it's what currently happens on Mac.

I could make it universal behavior.

**Comment by Dodg-e** [comment]
No idea but maybe it could act as a launcher like on steam and update in advance so there is not that issue, but seems like a lot of coding for an isolated issue.

Or maybe something like Noita where it restart all the time idk

**Comment by jasonrohrer** [comment]
Well, restarting itself here is the problem.

Somehow, Windows gets messed up occasionally when it restarts itself and starts the new instance minimized.

**Comment by Dodg-e** [comment]
Is it an issue with all games that restart themselves or only this one?

**Comment by jasonrohrer** [comment]
Not sure!

**Comment by jasonrohrer** [comment]
Closing for now.  If we ever get more information, we can take another look at this.
