### ISSUE TITLE
Still relatively easy to 1Vs1

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#433]
Shock emote face is not a big/relevant enough visual indicator and sometimes you can hardly see it before it's too late especially on dark skinned characters.

If someone tries to murder you your reaction is usually not "i'm shocked"

Screaming of terror would be more appropriate (might need some delay on ability to target someone to avoid spam if this is added)

Also current timer is not enough to run away especially from long range weapons like bows

**Comment by jasonrohrer** [comment]
I just upped it to 6 seconds instead of 3.

I'm working on a GASP when you are targeted.
