### ISSUE TITLE
I learned the pads without using them, just by picking them from a bowl. 

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLife#435]
Is this intended for a reason?

If it is, it means people won't be able to move 1 pad from one bowl to another bowl without using a tool slot

**Comment by jasonrohrer** [comment]
Yeah, this is a weird case.

It's putting it BACK in the bowl that counts as using it.  Hmm...

As far as the engine is concerned, that's a transformative action.  I may need to change it so that you must have something left in your hand, for hand tools, to count as using it.
