### ISSUE TITLE
Amazon gift cards cannot be used to purchase the game

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLife#44]
But people try and then join the discord server or post to the forum about how they bought a gift card to buy the game and now they can't buy it.

It might be a good idea to put a disclaimer/warning somewhere that gift cards can't be used for the purchase.

**Comment by mikekchar** [comment]
Out of curiosity, why do they think it will work?

**Comment by jasonrohrer** [comment]
I contacted FastSpring about this, and they added a little warning text below the Amazon radio button.
