### ISSUE TITLE
Foodmater overflow hacking.

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLife#440]
When FOODMATER capacity will be incresed with growing,
New FOODMATER is empty, so I have chance for overflowing eat 16 times(4 -> 20) when I was young.

**Comment by AlecYawata** [comment]
https://imgur.com/a/R3jeyzt

**Comment by TwistedHBG** [comment]
Can confirm, it's possible to get to +100 bonus food at age 20 fairly easily with this.

Possible solution: Newly gained pips start full if you have bonus food, and also reduce your bonus food by one.
