### ISSUE TITLE
Two people logging into the same account burns life tokens.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#443]
Ran into this one when I noticed my meme score was decreasing. 

Basically Player A is logged into the game playing
Player B attempts to log into the same account which boots off Player A.

Player B burns a life token when logging in and when Player A attempts to reconnect he will burn a life token as well doing so which boots off Player B which gives them a reconnect screen. These two can then cycle through burning life tokens until all tokens are gone which leaves the last person to reconnect in control.

Easiest way to replicate: 

Open two game clients and set to a specific server.
Have first client log in then second client log in with same information.
First client disconnects and asks to reconnect.
Press okay to reconnect.
Client two now disconnects and asks to reconnect.
Press okay to reconnect.
Repeat until all lives are burned out and you cannot log in anymore (you'll get the timer and everything.)

While this is a really fringe case it's probably not good to burn lives trying to reconnect to the game.

**Comment by jasonrohrer** [comment]
In testing, straight reconnecting over and over doesn't cause this problem.  You rejoin the same life, and burn no tokens.

What's going on here is that they are getting born again, as a new baby each time, I think.  Doing some more testing now.

**Comment by jasonrohrer** [comment]
No, they actually aren't born again.  They resume the same life as the other person was living.

Found and fixed this bug.
