### ISSUE TITLE
Score never go to negative number.

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLife#447]
new_score and old_score is unsigned, its ok?
https://github.com/jasonrohrer/OneLife/blob/master/fitnessServer/server.php#L387

I got error logs at fitnessServer. Please check your server logs too.

Anyway, I just want to know how do you alter table and change your code.
How did you change table structure in the past?

**Comment by jasonrohrer** [comment]
Ooops, yeah, I forgot to do this!  Thanks for catching it.

I'll post some code to update the database tables.

**Comment by jasonrohrer** [comment]
Repairing your live table can be done with these commands:

https://github.com/jasonrohrer/OneLife/blob/master/fitnessServer/databaseUpdates.txt

**Comment by AlecYawata** [comment]
Thankyou so much!!
