### ISSUE TITLE
Life tokens may need to adjust for average server lifespan

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#448]
I just watched a streamer burn through all her life tokens. Most of them weren't her fault. Several mothers abandoned, a few died shortly. The most promising life got stabbed for "not working" The rest were mostly not knowing how to find food, especially in overwhelmed towns.

**Comment by jasonrohrer** [comment]
I did up the tokens during this time, and the cap is now 24, and you earn them more quickly.
