### ISSUE TITLE
Food Waste Exists

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#454]
Streamer eats a mutton pie as a ginger child and only has +2 on her food bar.  Someone around 3:30 here for confirmation: https://www.twitch.tv/videos/513265965

**Comment by jasonrohrer** [comment]
Yes, this is intentional.  You're still vulnerable as a child.  I didn't want to completely undercut that with the overflow buffer, so the buffer grows in size as you get older.
