### ISSUE TITLE
BellTowers Not Sending Homemarkers

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#455]
Streamer gets born with a homemarker, which can have benefits.  But also, hears a belltower and his character's homemarker doesn't point towards the belltower location about 4:10 here: https://www.twitch.tv/videos/513265965  Also, the female character tries plants a homemarker, digs it up, and still doesn't have a belltower location.

**Comment by jasonrohrer** [comment]
Hopefully someone can confirm this or discover steps to reproduce.

In my tests, it seems to be working.  My guess is that there's some confusion about how to clear a home marker, and what counts as clearing it.

**Comment by DougLefelhocz** [comment]
There's two people reporting the same problem in this thread: https://onehouronelife.com/forums/viewtopic.php?id=8599 I haven't had the problem when being an Eve on a low pop server.

**Comment by jasonrohrer** [comment]
From that thread, sounds like it's working correctly but confusing for most people.  I'll work on making it better.
