### ISSUE TITLE
Biome restrictions on planting items can easily be bypassed

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#458]
If you right click the tile instead of the actual soil item you can plant any item in any biome.

Easy way to verify:

Get a rubber tree cutting and a tilled row in a non-jungle biome. Click on the row to plant and it won't work (as intended). Right click on the row's tile and you'll plant the cutting with no problem.

**Comment by jasonrohrer** [comment]
Thanks!
