### ISSUE TITLE
Ffwd playback

### ISSUE THREAD

**Issue by grokys** [jasonrohrer/OneLife#46]
It would be great to be able to ffwd/rewind playback of a recorded game, perhaps using the left and right arrows to move a minute at a time? As things currently stand, your entire session is recorded in a single playback session and if it contained many games that means a _long_ wait to find the part you were looking for!

**Comment by jasonrohrer** [comment]
Sadly, this is a consequence of how the playback system works.  It records UI events (keystrokes and mouse moves) and then actually SIMULATES those same inputs again in the game engine.  It records networking the same way, and simulates all the messages the server sent on playback.

This is great in that the file size is very small (relative to a video), and reproducible behavior is reproduced on my end in a fully debuggable form (I actually run the game and see you do exactly what you did---if I fix something, I can see that the fix "worked" by watching your recording again).

But, every frame of playback depends on the simulation of all previous frame.  Thus, no true fast-forward is possible.

However, if you disable vsync and "enableSpeedControlKeys.ini", you can use the ^&*() keys to control speed of playback somewhat.  If your GPU can handle it, the fastest speed ) is pretty darn fast.  Hundreds of frames per second.
