### ISSUE TITLE
Can't Till Two Piles of Soil.

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#464]
Its only possible to till one pile of soil/dirt at present.  Tilling two is impossible.  This bug has existed since the update made it so that tilling in the tundra was possible, and thus is probably related to the change that enabled tilling in the tundra to happen.

**Comment by jasonrohrer** [comment]
This is intentional.  See this commit:

https://github.com/jasonrohrer/OneLifeData7/commit/855a516749b9ba7a99a5722b54b085dcb6473908
