### ISSUE TITLE
Adobe Wall and berry bush removal

### ISSUE THREAD

**Issue by mithasorken** [jasonrohrer/OneLife#465]
Hello, when moistured, the adobe walls and berry bushes return to its original form as adobe wall or staked berry bush in very short time. therefore it is not enough for a single player to remove these. 
Thank you for the great game.

**Comment by JustinLove** [comment]
1. This is intentional to make it hard to quickly destroy these items
2. I've never taken down a wall, but I remove bushes by myself on a semi regular basis. It takes some mental and spacial preparation, and occasionally I still miss.
3. This would be OneLifeData7 issue anyway.

**Comment by DougLefelhocz** [comment]
I've removed berry bushes and seen others do it.  I also saw someone destroy an adobe wall outside of a tutorial area.  I have also destroyed adobe walls, though, indeed, it required careful organization and quick movement.  Adobe walls I did struggle with destroying more as I recall, but I did manage to do it a significant number of times.

**Comment by jasonrohrer** [comment]
Yes, intentional.
