### ISSUE TITLE
When learning a tool the name of the tool is not always shown.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#475]
I'm not sure if this can reliably be triggered with a specific tool, but sometimes the tool class name is not shown when learning the tool.

Example: I used a Shovel on a Dead Gooseberry Bush and a message popped up in the top left. The message said:

YOU LEARNED THE .
7 OF 10 TOOL SLOTS ARE LEFT.

**Comment by jasonrohrer** [comment]
Thanks!

Found the source of this bug.... if the object you're holding is in a partially-used state!
