### ISSUE TITLE
Game crashes when hovering cursor over person as they die

### ISSUE THREAD

**Issue by Kiyin** [jasonrohrer/OneLife#476]
Some people reported experiencing this when their babies /DIE. I have experienced this issue with both /DIE babies and elders dying of old age.

**Comment by jasonrohrer** [comment]
This is still happening?  Strange... there was a bug causing this before, but it was fixed.

https://github.com/jasonrohrer/OneLife/commit/a6b2138930a7225b6eb6aeac464b882b8cbb080e

Maybe there's something else triggering a similar bug.

**Comment by jasonrohrer** [comment]
Just checked this in the official client, and there's no crash in this case (the fix applied two weeks ago worked).

I'm wondering if this affects one of the mods, and they forgot to roll this change into their code.
