### ISSUE TITLE
Can't open doors/interact with items on a good tile in bad biomes.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#480]
Yes, I understand the point of this is to prevent people from basically making bridges to resources via roads to cut out needing other races (minus the initial road building) but it leads to really weird situations.

If a door is placed in a biome you aren't able to work in you can't open and close it along with take things out of shelves and various other things.

However, you're able to open and close doors while in the sick state which seems really backwards. I'm too well to open and shut the door or am I so sick I can force something open/shut that I normally couldn't. 

Just a  weird interaction with the biome thing being related to illness and what not.

**Comment by jasonrohrer** [comment]
I'm not able to reproduce this.

In a bad biome, I can NEVER open a door, no matter what state I'm in.  Standing outside the biome, I can't open a door on the edge of the bad biome.  Standing inside the bad biome, when I'm dehydrated, I can't open it.  Getting sick outside the biome (yellow fever) and then trying to open the door, I still can't, whether or not I'm standing in the bad biome while sick with yellow fever.

I.e., all actions in the bad biome are consistently blocked for me.

Am I missing something here?

Yes, I can open doors while sick or wounded generally.

But I can NEVER do anything in a bad biome.  It's more than wounding.  I'm not comfortable there, and I don't have the expertise to do anything there.  I'm not home.  I can't touch stuff, or open doors, or even get info about stuff there (mousing over doesn't even show object names).  I'm a total outsider there.
