### ISSUE TITLE
Small photograph icon doesn’t appear in family tree browser.

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLife#482]
For more details on this issue I refer to this thread I made on the forums:

https://onehouronelife.com/forums/viewtopic.php?id=8763

**Comment by jasonrohrer** [comment]
Aha!  Links to the photo server are missing the server_name parameter:

`<a href=http://photos.onehouronelife.com/server.php?action=photo_appearances&server_name=&player_id=2513317>`

**Comment by jasonrohrer** [comment]
This commit broke it:

https://github.com/jasonrohrer/OneLife/commit/0788e818548de469688f816b5c81c3a8759f8397#diff-b5b777390a7539e6abc5f5c7bab19f65

I'm pretty sure I did this to speed up queries.

I'll have to find another way to get the server name, besides the old JOIN method.
