### ISSUE TITLE
Items from horse cart lost in desert.

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLife#484]
Since only black people can access stuff in the desert it seems like a big bug that you can lose the stuff you put in a horse cart if it gets bitten by a snake. The broken horse cart will move out of the desert, but the items in the horse cart will be forever lost in the desert unless you are black. An example of this can be seen here:

![](https://cdn.discordapp.com/attachments/419395479420534785/652453297071980544/Screenshot_216.png)

**Comment by sigmen4020** [comment]
That isn't me in the picture. Just found it on the Discord server and reported it. So I'm unsure how it was done.

**Comment by jasonrohrer** [comment]
I don't think it's a problem to force-drop in the desert when you hit a snake.

If the cart ends up outside the desert like this, and someone can reproduce it, please open a new ticket.
