### ISSUE TITLE
Eves may be stuck going north

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#486]
Pull up life data around here:

https://onemap.wondible.com/#x=-59048&y=1792&z=22&t=1577979069

The recent update moved the eve grid position to a bell town about 2k north. As of the life shipping time, the north run of the grid line had gone farther than expected, and looking at the code, I suspect it may go that way forever.

```
  int lastRow = abs( oldY ) / jump;
  ...    
  else if( lastDir == 1 && lastRow == 0 ) {
```

The south run also uses an exact equal test, although it here it may have hit the positive value where it expected to hit the negative.

**Comment by JustinLove** [comment]
I think the maplog confirms this. We've gone from a off-the-grid bell town at Y 1680 to a settlement at 10680 in 24 hours. and some of that time was the initial downswing.

**Comment by jasonrohrer** [comment]
Yes, I see the problem.  There's no case to handle the situation where we're way off the grid.

Will fix it.
