### ISSUE TITLE
Eve march

### ISSUE THREAD

**Issue by unoriginalartist** [jasonrohrer/OneLife#487]
Eves seem to 100% be marching in one direction where as bells are anywhere from 1k-22k literally someone in discord right now is in a family 22k away from the bell, heres what they said UnocompToday at 3:52 PM
i'm currently in a fam that's 22k away from the bell
heading north

I know you dont care for suggestions but wouldnt it work easier if complimentary races spawned 1k away in any random direction from each other? Or near an unused well? like a black family has been spawned so a brown family spawns 1k away in any direction and maybe depending on how high the tech is a new race will spawn or even just when you need another eve ingame.

Because its near futile to find any other family thats the correct race right now unless you trek to a bell, where its often WIPED by griefers, I had someone in discord laughing how they were going to wipe bell town at least 2 times the next day just so they could play dress up with all the clothing by themselves, honestly its not even really fun to try to play the game and make tech because more often times than not you cant make anything cause no water, or everyone is dead cause you arrived just in town to a bell to find a griefer having murdered or murdering everyone. I dont even interfere anymore cause its an EVERY game occurrence, average is like 4-5 murders a life in a bell town, if I dont stay in a belltown I literally just wonder around in the wild or else someone will try to kill me. So.......I dont think its even fun to play past watching the mayhem while drinking wine in a corner of a building as an old person waiting for death.

**Comment by jasonrohrer** [comment]
Yes, there is a bug in the eve placement that suddenly started causing them to be spread to the north only.  It has been fixed.
