### ISSUE TITLE
Donkey town apoc trigger?

### ISSUE THREAD

**Issue by unoriginalartist** [jasonrohrer/OneLife#488]
People are talking about trying to apoc trigger in donkey town by asking ppl for curses every life, is it possible for a donkeytown person to trigger it? They also at one point were trying to use other families to bring them close to donkeytown somehow? by using bell towns bell to know direction? *Ive seen my fair share of lazy griefers, but this is insane for a griefer this is hardmode griefing* almost as bad as the people who cut all the maples in in rift. I dont know if they are succeeding or not but they were talking about doing it, is that even possible? If so isnt that an issue?

**Comment by jasonrohrer** [comment]
Yes, I think it is possible to build the apoc tower in donkeytown.... but very hard.
