### ISSUE TITLE
can't configure OneLife on Debian testing 

### ISSUE THREAD

**Issue by shirishag75** [jasonrohrer/OneLife#49]
```
~/games/OneLife$ ./configure
./configure: 7: ./configure: ../minorGems/game/platforms/SDL/configure: not found 
```

I am not sure what is wrong as I have both libsdl1.2debian-dev 

```
$ aptitude search libsdl1
i   libsdl1.2-dev                                        - Simple DirectMedia Layer development files

$ aptitude search libsdl2-dev
i   libsdl2-dev                                          - Simple DirectMedia Layer development files
```

I did look at  the documentation to see if I forgot any compilation notes or something but  didn't  see anything of the sort .

**Comment by jasonrohrer** [comment]
You need minorGems too.

cd ~/games
git clone https://github.com/jasonrohrer/minorGems.git

Then:
cd OneLife
./configure

**Comment by shirishag75** [comment]
umm... I got this but  don't see where the binary is built  - 

~/games/OneLife$ ./configure
select platform:
  1 --  GNU/Linux
  2 --  MacOSX
  3 --  Win32 using MinGW
  4 --  Raspbian on Raspberry Pi (experimental)
  q --  quit

> 1

shirish@debian:~/games/OneLife$ ls
build  commonSource  configure  documentation  gameSource  lineageServer  no_copyright.txt  reflector  scripts  server

**Comment by jasonrohrer** [comment]
It's down in gameSource.

But there are some other steps you need to do to get the game running. If you bought the game, the unix source bundle automates all of this for you.

If you didn't buy the game, there's no tech support included.  Maybe ask in the forums?
