### ISSUE TITLE
Putting Kindling on hot coals makes you learn Hot Coals. No one wants to save the fire

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLife#494]
It's pretty annoying especially as a blacksmith when I need all my toolslots but no one else is taking care of the fire

**Comment by jasonrohrer** [comment]
As annoying as this might be, it's working as intended, in that you can't do everything by yourself.

You're busy smithing, and someone else should be taking care of the fire.  How to convince someone else to do do their part and take care of the fire is the actual heart of this game.
