### ISSUE TITLE
No Curse Token For Twins?

### ISSUE THREAD

**Issue by Candygirl777** [jasonrohrer/OneLife#495]
Been meaning to report this bug(?) for awhile now.  If I play by myself, I get the curse token.  When bf & I play, neither of us ever get the curse tokens.

**Comment by jasonrohrer** [comment]
Yeah, I guess I'm going to leave this alone for now.

Twins, trips, and quads ganging up on someone doesn't seem like a great idea to me.  It's risky to open that door.
