### ISSUE TITLE
Bug: Bodies floating everywhere

### ISSUE THREAD

**Issue by Munchkinbrie** [jasonrohrer/OneLife#497]
I don't know what happened. I downloaded the game yesterday and played all day (Loved the game by the way). Was very excited to play again today but when i load the game, i can't move and there are female 001d bodies floating everywhere around my screen. I uninstalled the game and re-installed it to see if that would fix the issue but it didn't. Also, for some reason I can't take a screen shot with alt-print screen to show the problem... please help.

**Comment by Munchkinbrie** [comment]
![Bug](https://user-images.githubusercontent.com/60020579/72652419-eec98e00-3943-11ea-9999-c1ad5eb10555.PNG)
I figured out how to take a screenshot! Hope this helps to find the problem!

**Comment by Tarr-OHOL** [comment]
This got fixed. Basically steam deleted like 2500 objects in the object folder so all this funky stuff happened.
