### ISSUE TITLE
Baby clothing deleted?

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#498]
https://steamcommunity.com/app/595690/eventcomments/3949028569234488750#c3949028569234730017

"There is still also a baby glitch where if a baby is trying to remove their clothing and gets picked up at the same time, their held item will be deleted if their tile is occupied by a preexisting item."

**Comment by Tarr-OHOL** [comment]
That's not true. The games just displaces it to an open tile a bit further out. This is one of the biggest false flag reports that occur due to either players on default zoom not seeing where it goes in clutter or players not checking further around them.
