### ISSUE TITLE
Badges changing color

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#499]
Started life with blue badge, turned pink, then green etc...

**Comment by Tarr-OHOL** [comment]
This occurs when you change factions. If you followed someone and they then followed someone you'd change from blue to pink. If they then changed their mind and followed someone else it would change colors (or if their leader followed someone else).

Probably not a bug so much as people deciding to swap who they follow.

**Comment by Dodg-e** [comment]
That's the thing i didn't follow anyone, when i was born i was just following someone by default, i never said "I FOLLOW X".

**Comment by Tarr-OHOL** [comment]
My guess then is someone instead followed you and unfollowed you which potentially what was potentially the issue. No real idea unless I take the time to test the idea out.

**Comment by jasonrohrer** [comment]
No, when you were born, your mother was following someone, and you auto-followed her leader.

Your badge color would change whenever your leader followed someone else.

The badge color is determined by whoever is on top of the tree.
