### ISSUE TITLE
Cows can cross closed doors

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#504]
Works with spring doors and cows and calf too, havent tested other doors or other animals.

**Comment by DougLefelhocz** [comment]
I've seen horses do so also.  They didn't use to a while back, but I've seen horses escape buildings more recently.

**Comment by jasonrohrer** [comment]
Yeah, this is a side-effect of these doors not being blocking so you can auto-walk through them.

They should at least auto-open when an animal passes through.

Or maybe block animals as a separate property.
