### ISSUE TITLE
Got 6 Rubber Tires Instead of 8 From 2 Buckets of Rubber Dough

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#506]
Playing on server12 I got two buckets of latex, cooked palm oil, and then made two buckets of rubber.  I cooked the tires and I only got 6 rubber tires from the two buckets total.  No one else joined me, nor did I see anyone else, so I'm doubly sure that someone else didn't touch buckets of rubber dough.  I think, but am not sure, that one of the buckets only gave me 2 rubber tires, instead of 4 rubber tires.  One of the buckets was on a badlands tile and one a tundra tile.  I think also that the bucket which only gave 2 tires was on a tundra tile.

**Comment by jasonrohrer** [comment]
I dunno... just tested it, and got 8 tires from two buckets.

Can you experiment some more and see if you can get it to happen again?

Or find reliable steps to reproduce?

**Comment by DougLefelhocz** [comment]
I went back to the spot and got 4 rubber tires from the tundra tile that I had used before, and then cooked 8 rubber tires from the two tiles that I recall using before.  So, I'm closing this.

**Comment by DougLefelhocz** [comment]
Sorry about this one.  Not sure what happened here.
