### ISSUE TITLE
Lineage Browser: Improved links to graphical family trees

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#509]
Some time ago, you [added links to wondible's family trees](https://onehouronelife.com/forums/viewtopic.php?id=7762), however the system was not designed with external links in mind and non-default servers typically do not come up.

A little while afterwards, [extensions were made to better support linking to arbitrary information](https://onehouronelife.com/forums/viewtopic.php?pid=72625#p72625) given only basic facts.

> Okay, this now works (I did have to refresh)
> 
> https://wondible.com/ohol-family-trees/#server_name=server4.onehouronelife.com&birth_time=1543180314&lineage=289005
> 
> Either `playerid` or `lineage` may be specified. playerid will work for any family member and cause all instances of that account to be highlighted. lineage is the eve player id and will not be highlighted.
> 
> Server may be specified as
> 
> `server_id` as per http://ohol-data-cache.wondible.com/servers
> `server_name` e.g. bigserver2.onehouronelife.com
> `server_short` e.g. bigserver2
> 
> Internally the database uses `epoch` to distinguish duplicate playerid/lineage, but this has little relevance outside. In order for the system to find the proper life for epoch lookup, one of these other distinguishers may be used (times in unix seconds):
> 
> `birth_time` - must be exact
> `death_time` - must be exact
> `start_time` and `end_time`- for an inexact range around the birth time
> 
> As to the exact times (as published in the lifelogs) it's still possible I overprocessed something somewhere, but I've already been through one round of correction there.

**Comment by jasonrohrer** [comment]
Worked out with wondible that link should look like this:

https://wondible.com/ohol-family-trees/#server_name=server4.onehouronelife.com&start_time=1543180314&end_time=1543250314&player_id=289005

Start time and end time can be very loose window around birth (end_time can be death time, and start_time can be death time - 2 hours).
