### ISSUE TITLE
Bear Caves

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#51]
There is no age limit for poking bear caves, which makes a popular and less punishing way of griefing by running away as a baby and clicking on any nearby bear caves until the baby starves. This leaves towns with bears to deal with and no way to tell who did it.

**Comment by jasonrohrer** [comment]
I was on the verge of fixing this.  It's not hard to fix (set a min age for these kinds of default interactions).  But there's nothing stopping an adult griefer from doing the same thing, right?  If no one sees them do it, then no one sees them do it, regardless of age.  There are other ways for a village to solve this problem without my intervention here.
