### ISSUE TITLE
Joining forum is complicated if even possible for steam users?

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#516]
The game was on sale twice on steam, lots of new players but the forum is still pretty inactive.

Do steam players even have access to the forums?

Wouldn't it be possible to add a "Forum" button on the main screen to easily be able to subscribe to the forum with your personal key?

Having new members would make the forum more lively but also maybe we could find some new talented people that could improve the game in who knows what way.

**Comment by jasonrohrer** [comment]
Hmmm... interesting question.

The forums in the past have been overwhelmed with spam, which is why they are hard to join.

I will definitely make a sticky post on Steam with detailed instructions.
