### ISSUE TITLE
Waste of food still possible

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#520]
Babies and kids dont have the food owerflow enabled (or only small) i'm guessing it's to avoid feeding babies pies of feast meal and be "done" with the parenting feeding part, not sure why it extends to kids though?

But the point is you could empty 10 feast tables(or any other food for that matter) and waste copious ammounts of food.

Babies should not be allowed to be fed "big foods" either any food that overflows at all or only allow a small overflow otherwise deny food, as for kids maybe allow a bigger limited overflow and if the food is over that limit,"too big"then deny consumption.

**Comment by Dodg-e** [comment]
Or and i dont know if that's possible but maybe a food item could have it's food value be dynamic, so for example you feed a baby/kid a feast plate (or pie or wathever) he only eats as much as he can (x number of bars) and the rest of the value is still in the food item, so with a pie for example if he eats less value than a slice it wouldn't visually consume it but the value of it would have decreased.
Or with a banana it wouldn't actually consume the item but the food value of it would be reduced.
Like eating bites of food in other words

**Comment by jasonrohrer** [comment]
Well, they have small overflows.

But yeah, I guess you could be hard-blocked from eating anything that you don't have overflow room for.

**Comment by Dodg-e** [comment]
block is not good because then you could be in a scenario where you try to feed a baby pie or something like that to avoid them starving but couldn't feed them.

Is the dynamic food value even possible?

**Comment by jasonrohrer** [comment]
Dynamic food isn't possible.

Objects don't track a "how much food is left" state.

Blocking big foods for BB does make some sense, because they're simply too small or young to eat that big food.

**Comment by Dodg-e** [comment]
Yeah but irl they would only eat a small portion of the plate/food...

And not starve because they cant eat the entire portion in one bite

Too bad for the dynamic food, i dont see any other solution, here it's either allowing food griefing (might become an issue if at some point food becomes a precious ressource) or allow a baby/kid to die because he cant eat the entire food, tricky...

The only solution i see is a weird one, like birds regurgitating food to feed their offspring, passing down some of your excess food bars, maybe we can imagine that excess food bars are not actually consumed but that the player still has the food on them.

Then you could give some of your excess food to a generic object named "food", like a one bar of food object a "bite of food", that you could then feed to someone.

Seems complicated, could work, but then there is the issue of making that "one bar food object", could be a command? idk

**Comment by jasonrohrer** [comment]
I'm going to leave this alone for now, unless it becomes an issue.

In a pinch, you can feed a baby a feast plate.  That's fine.
