### ISSUE TITLE
remembering your own tools

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#522]
easy to forget what tools you used in a life, typing /tools could display temporarily the list of tools learned

**Comment by JustinLove** [comment]
I've also got visual tool slips in my mod. Visible only when holding a tool, in the style of yum visible when holding food.

https://github.com/JustinLove/onelife-client-patches/blob/master/show-learned-tools

**Comment by jasonrohrer** [comment]
When holding a tool, you can tell you know it b/c you're not holding it backward.

Seems like dodge is asking for a list of tools that you do know, even when not holding them.

**Comment by jasonrohrer** [comment]
This could be requested by the client and delivered via a DING message from the server.

However, the list can be pretty long (12 tools max, currently).

The problem is: where to have room in the UI for such a long list.

**Comment by Dodg-e** [comment]
It could just be a message (like the one in top left corner) that temporarily gives the list of all the learned tools when entering /tools or something, message goes away after x seconds

**Comment by jasonrohrer** [comment]
Yeah, but it could be a long list, right?  Currently 12 max.

That would require a big piece of paper covering a good portion of the screen.

I'm thinking about maybe breaking it up into multiple DING messages from the server (like 4 tools per DING or whatever fits).  But that could be annoying too...

**Comment by Dodg-e** [comment]
Yes ding would be annoying

Would it really cover a big portion of the screen?

i guess with tools like "NEWCOMMEN ROLLER" or "DIESEL WATER PUMP" it could

lowering text size is not an option right?

Maybe it shows 4 tools then you can "TAB" manually trought the pages and last page closes the text window (it would overide priority of the "TAB" from tooltip)

**Comment by miskas9** [comment]
Wondible has done a nice thing presenting the learned tools with icons. 
It shows all the tools as icons on top of the screen, Could we have that?
http://prntscr.com/qy1n0l
the list could show up every time you learn a tool or typing /tools

**Comment by jasonrohrer** [comment]
Yeah, that is really nice!

However, my hands are tied aesthetically, because I'm sticking to "real pen lines" everywhere, which means that I never shrink sprites like that.  The hatchet isn't too bad, but the kiln would be really blurry.

The entire screen is supposed to look like it was drawn by hand, every line of it.  That's why the pencil tool tips "erase" instead of disappearing.  That's why papers shuffle when text needs to change (like the recipe hints) instead of the text flashing away.

I mean, I could draw a to-scale "icon" for each tool category (some have more than one tool).  But that also adds labor when I want to add new tools in the future.  Right now, it's pretty flexible to put +tool in the object description and not think twice about it.

Those little slips could have text abbreviations on them... like:
HTC
SHV
NDL
HTC
KNF
NWC
SMT


Hmm...

**Comment by jasonrohrer** [comment]
Currently considering using the tool set name (+tool_Choppers) as a shortand for use in some kind of learned too listing.

There are only 12 of them, so they would fit together in one DING message.

Probably a command like /tools to get the reminder.

DING

You know:  CHOPPERS, SHEARS, KNITTING, BORE, DRILL, SMITHING, ....


There are a bunch of tools that have no tool set name, like shears, but I'd have to add one for everything.

**Comment by miskas9** [comment]
Please no more Ding sounds, they have got annoying. Also the same sound notifies for so many different things and has a lost its meaning. 
Btw sometimes I find it deficult to read and follow the notifications. (Orders)
Could we get a different sound for tools and orders?

**Comment by JustinLove** [comment]
Small side note about "just 12": if you lowpop, you "learn" *all* tools. I know I'm early on server1 when I get a tool icon popup (my mod) on birth. One of the reasons I went with separate slips is that they can overlay to compress in extreme situations.

It's true you can see "this tool" by holding it already. I was going for something like the yum slip that was only visible when needed. The tool slips hide the rest of the time so they aren't in the way. You can usually find a tool somewhere nearby if you want to know if you have slots left.

**Comment by JustinLove** [comment]
On reflection, this might be useful feedback: the thing I'm checking most often by picking up a tool is how many slots I have left - can I learn this, and how much flexibility would that leave me?  Such as "could I still be a smith this life"

When the notices come in, I'm usually in the middle of using the tool. If I even see it, then there is the memory problem.

**Comment by jasonrohrer** [comment]
I'm still pretty stumped by this one.

I experimented with short, abbreviated names for each tool, suitable for presentation in some kind of message or list, like "You know hammer, hatchet, lasso, oven, car, and loom".

The first problem is that some of them can't be abbreviated into one word (like newcomen hammer vs smithing hammer).

But even if that wasn't a problem, seeing a long list of words isn't going to be that helpful for jogging the memory.

Using icons REALLY breaks down for the larger machines (like a tiny Newc Hammer and a tiny Newc Bore isn't going to look that different).


There's no room for more text on the screen.  Maybe temporary text somewhere that goes away after a short while.

**Comment by jasonrohrer** [comment]
Maybe Justin is right, and the main thing we need to remember from moment-to-moment is how many slots are left.

Maybe that number just needs to be in the UI panel somewhere, like:
0/8 
or
5/8

or 

8/8 when full
