### ISSUE TITLE
Characters jumping around and changing directions

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#525]
Several people have been having problems with character movement since the last update

https://onehouronelife.com/forums/viewtopic.php?id=9014

I didn't notice much on my private server, but had lots of problems in a built up town on BS2

Reverting 47f60c6372c39a1058fbe98dae55395bc3b991cb seems to fix it for me, have investigated further.

**Comment by TwistedHBG** [comment]
Can confirm.

It's happening constantly, several times per minute, and it's really frustrating

**Comment by jasonrohrer** [comment]
https://youtu.be/HJILt3J0N_A
