### ISSUE TITLE
Hoe only tills full soil pile

### ISSUE THREAD

**Issue by dogwolf12** [jasonrohrer/OneLife#526]
The hoe only tills a soil pile if it has three units of soil in it or if the hoe is on its final use. This problem is the same for stone hoes, as well. You can see this on onetech here (last two uses and uses 6-7) - https://onetech.info/1101-Fertile-Soil-Pile

**Comment by DougLefelhocz** [comment]
Hoes also till one soil instead of needing three: https://onetech.info/1138-Fertile-Soil

**Comment by jasonrohrer** [comment]
This is intentional.  If you till 3, it produces a deep row with only one tilling, saving tools and wasting soil.  It also allows you to till rows in the arctic, which require more soil.
