### ISSUE TITLE
Mod integration

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#527]
Noita (and probably lots more games) has this cool feature where mods can easily be integrated and even stacked if they are compatible. this would make modding much more accessible to regular players especially those who keep asking the game to be translated to japanese,chinese,spanish etc when there is probably a mod around that does it.

<a href="https://ibb.co/X3Tmvrn"><img src="https://i.ibb.co/jWF71PC/Sans-titre.jpg" alt="Sans-titre" border="0"></a>

**Comment by jasonrohrer** [comment]
Yeah, I could go off for a month and implement this....

But I do need to pick my battles.
