### ISSUE TITLE
Slight improvement 1 vs 1 killing

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#528]
Still getting some easy kills with knife but especially with bow.

Doubling current kill timer BUT if someone (non twin,trip,quad of course) says "I JOIN YOU" timer goes instantly to 0 so as soon as someone joins the posse you can instantly kill.

Maybe even shorting the phrase to simply "JOIN" would be even better since time is of the essence in these types of situation, or maybe "KILL"

**Comment by jasonrohrer** [comment]
Well, I would probably just increase the time, if that needs to happen...

I don't necessarily want anyone killed without warning, so I wouldn't make posses insta-killers.

**Comment by Dodg-e** [comment]
Yeah insta kill is probably not a good idea, i think the "gasp" is just not strong enough as an indication that "you are in danger and about to die", maybe some visual effects that represents danger or fear/death would be strong enough but for now innatentive players will just get stabbed/shot.
