### ISSUE TITLE
Reconnecting after a disconnect should not spawn you as a new baby if your old you is dead

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#531]
This is a very tiny issue that will very rarely affect anyone, but it's still probably unintended so I wanted to report it.

I was almost 60 years old and I was at the end of my final song. All of a sudden I get disconnected. The "CONNECTION LOST" screen shows up and my only option is to click OK to reconnect. It takes me a second or two to realize this isn't actually the death screen, and then I instinctively quick the OK button to reconnect (which is the only thing I can click). However, instead of putting me back into my old life I get spawned as a new baby, which means I didn't really reconnect - I spawned in anew.

I was faced with a choice here - live out the entire 60 minute life, or type /die to stop playing and lose points. As I didn't have an hour of time to play I had to /die to save my mother from losing points from my early death.

**Comment by jasonrohrer** [comment]
Good point!
