### ISSUE TITLE
Distinct badge for players with no leader

### ISSUE THREAD

**Issue by Kinrany** [jasonrohrer/OneLife#534]
A player that has followers but no leader is the head of that hierarchy. This is important information, because usually that player is the one who's actually working on creating that hierarchy and the one issuing orders.

I suggest giving them a distinct badge. Something like a tiny crown or a star, in addition to the regular badge.

**Comment by jasonrohrer** [comment]
Distinct badges are quite a bit of work.

The changes which point you to your leader, and inform you of their death, go live this week.  Let's see how they help, and re-open this issue later if it is still a problem.

**Comment by Kinrany** [comment]
> Distinct badges are quite a bit of work.

Oh, they are?

I was thinking of another small image that merely sits on top of the existing badge and is visible when the player doesn't have a leader. No complicated graph traversal would be necessary.

But I'm probably underestimating the time this would take, or missing other complications, sorry D:
