### ISSUE TITLE
Discrepancies in follower and leader locations

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#537]
Playing around on my local server and client, it seems like leader messages are pointing the wrong way, perhaps to absolute coords relative to that player, where as follower messages seem okay. Weirdly, leader code seems to adjust the coords, whereas follower does not.

I was reconnecting to the same characters repeatedly

Not fully diagnosed, but perhaps something to check before release.

**Comment by JustinLove** [comment]
Birth notices are definitely borked too. 9k west on BS2, which is essentially the global offset.

**Comment by TwistedHBG** [comment]
Can confirm, if you're close the the newborn baby it will work fine, but if they are offscreen it will show a massive number pointing in the wrong direction

**Comment by jasonrohrer** [comment]
Fixed!  Going live soon.
