### ISSUE TITLE
Curse radius still appears to be 32

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#538]
As stated in commit 9247bf794880a206f8fcbad01c9572d298440dfb the curse radius was upped to 200. Earlier today I tried to curse a player that was just murdered and ran out of town, and the curse failed. I ran a few tiles north and it succeded.

I found the player's body and it was around 33 tiles from the tile I was standing on when I tried to curse the first time, just out of the old range but within the new range.

**Comment by jasonrohrer** [comment]
On my test server, seems to be working from 110 tiles away...

This update didn't actually go out until Saturday night, Los Angeles time.

Please try again and re-open if you're still having trouble.

**Comment by TwistedHBG** [comment]
The curse change from commit 9247bf7 that I'm referring to is from January 21st, so it should have been live at the time when I encountered the bug.

Keep in mind the player I was trying to curse was in fact dead - I was trying to curse their bloody bones. It might be that dead bodies have a different curse range and I'm just not aware of that fact.
