### ISSUE TITLE
Ding sounds turning streamer insane

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#542]
https://www.twitch.tv/videos/551471015?t=1h24m54s

I dont mind having a notification sound but the ding is very annoying could it be replaced by something else?

Maybe it's a good occasion to use the poll feature and ask other players if they also find it annoying.

**Comment by jasonrohrer** [comment]
Got bigger fish to fry.  That streamer was just speed-running the tutorial, which is why they were getting so many DINGs....
