### ISSUE TITLE
Lag when leader/relative dies?

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#545]
Needs to be tested further but i had big lag just before i got the message that "LADY" died not sure if she was the current leader and also not sure if maybe the lag is related to calculating score because family member died or if related to calculating leadership stuff.

I think she was my grandmother at that time (not sure)

**Comment by jasonrohrer** [comment]
What kind of lag?

FPS lag?

Network lag?  Where you could walk around, but started bouncing when trying to interact with something?

**Comment by Dodg-e** [comment]
Freeze iirc

**Comment by Dodg-e** [comment]
hasn't happen recently i'll close it for now and reopen with more details if i see it again
