### ISSUE TITLE
Issue with Frame Rate

### ISSUE THREAD

**Issue by AprilSmith2020** [jasonrohrer/OneLife#548]
We purchased the game online and downloaded it, we did check to see if we were capable of running the game via system requirements before we purchased the game and we did meet the requirements given. We first could not get into the game because of some issues with VSYNC? We had a friend come over and they helped us with downloading drivers and updating our system, hoping that would work. It helped but did not fix the issue. We can now get into the tutorial but the game is so laggy we can not move hardly at all. We have an integrated graphics chip(s) with no VSYNC option available to us. We have tried to change target FPS and it helped a very tiny bit but still unable to play the game. We have reached out via email multi times and no reply. Also, we notice when going into the tutorial there is a black out box over the feet of the character and over the temperature gauge in the tutorial, not sure if that helps.

**Comment by jasonrohrer** [comment]
I didn't receive any emails from you.  For future reference, you can reach me here:

jasonrohrer AT fastmail DOT fm

Sounds like some sort of fundamental graphics card incompatibility.  I'd be happy to send you a refund.  Please contact me at the above email.

**Comment by AprilSmith2020** [comment]
I sen you two emails, here I print screened them for you.
*NailArtMaddness*
