### ISSUE TITLE
Can't respawn as an Eve on low pop servers

### ISSUE THREAD

**Issue by MrsDuckGirl** [jasonrohrer/OneLife#549]
I can no longer spawn as an Eve on low pop servers when there's another player (fertile woman). Before, I would /die once or twice before respawning in my town as an Eve. Now I can /die dozen of times, I'm still born as a baby to the other player.

I asked to my mom to curse me, so I won't get born around her anymore. It worked for one life, then next life I reborn in DK (some other players had joined her, I guess they cursed me too, or had cursed me previously, whatever). I suicided and logged back when the server was empty, obviously I had lost my town.

**Comment by jasonrohrer** [comment]
Hmm... not sure that /die has worked this way on low-pop.... not for a very long time.

Lineage limits do not have an effect on low-pop servers (so there's nothing preventing you from getting born in the same location over and over).

And /DIE on high-pop sets a lineage limit.  But obviously doesn't work on low-pop.

Looking into ways to make this work better.

**Comment by jasonrohrer** [comment]
Found a way to fix it.
