### ISSUE TITLE
Abandoned Well is misspelled as Abandonned Well

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#565]
I think the typo is in this commit: https://github.com/jasonrohrer/OneLife/commit/05c115ff88911c7a99d229abfb3dafd45ed6a611#diff-c1fa32f2545577bb0afb327526c35f6a

**Comment by jasonrohrer** [comment]
Fixed in 629129903cb6eda4214f3bf9bc1496d0ce4ae7d0
