### ISSUE TITLE
Probably a bug - Eves can't have kids.

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLife#569]
As Eve I couldn't have kids. Probably because I moved in homesick area (another family's town) at the beginning of my run. Even when I left the area I still couldn't have kids. Probably was stuck with homesick.
I made a well in the very last seconds of my fertility and I got a kid almost right after making it.

**Comment by jasonrohrer** [comment]
This behavior has been changed in 3593ccd901cf746d1d36f1871e8a5ef49c1830ad

Will go live later this week.
