### ISSUE TITLE
Destroying chest with steel axe deletes both.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#57]
Both the steel axe and chest vanish when using the axe on a chest to destroy it.

Same is true for marked graves being dug up with a shovel.

**Comment by jasonrohrer** [comment]
Are you sure about the shovel?  I just check, and it looks okay, and I tested digging a bunch of marked graves with the same shovel earlier today.

**Comment by jasonrohrer** [comment]
Tested the shovel just now, and it was okay.

Fixed the ax on the box/chest though.  Thank you!
