### ISSUE TITLE
one of your updates

### ISSUE THREAD

**Issue by be227** [jasonrohrer/OneLife#573]
bring back old killing update if someone stealing resources from you can kill them now the killing update it's so different now I don't even understand how it works now it was so much easier back in the day

**Comment by jasonrohrer** [comment]
If you are out in the wilderness, killing works the same as it used to.

But in a town, you need consensus.

When you try to kill, a little instruction will pop up telling you how big your posse needs to be.  Other people have to say "I join you" to join your posse and support your kill.
