### ISSUE TITLE
Reincarnation On the Same Family Tree is Not Possible/No Eve Button/No Born in Same Spot Button

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#577]
Both of these have apparently gotten requested as possible:

> 1.  Long-lived lineages that don't die out due to forces beyond their control, and permanent, every-growing, player-created buildings and transportation networks?

> 2.  Lots of Eve camps and a large variety of other towns at different levels of tech?

From [here](https://onehouronelife.com/forums/viewtopic.php?pid=90476#p90476)

A problem underlying this is likely that players don't have enough choice in their starting conditions.  Another problem underlying this is probably that lineages get restricted to players having birthed one another.

With an Eve button that puts players out in the wild if they use it, with another button that players can use to get reborn into the same spot (possibly under some qualifying condition to prevent abuse by those looking to annoy the same people over and over again), and with reincarnation putting players onto the same family tree as their previous life if they rebirth in the same spot (perhaps only if a lineage hasn't had any new children in say 120 minutes), 1. and 2. can get satisfied simultaneously.  Or at least such is a start.

**Comment by Tarr-OHOL** [comment]
You can /die back into a family with little to no issues. If you care about tool slots that's your own problem.

Eve button is dumb because then all the lineages would have 1-2 people per family unless the button required 100's of hours to access in the first place. Another dumb idea taking up space on the github.

**Comment by DougLefelhocz** [comment]
> Eve button is dumb because then all the lineages would have 1-2 people per family unless the button required 100's of hours to access in the first place.

You certainly don't know that all the lineages would have 1-2 people per family.  There's no telling how many players would choose to be Eve or reincarnate.

Edit: I've seen enough low pop lineages with more than 1-2 people per family.  And plenty of cases where people didn't choose to suicide to Eve in the low pop context when they could have and knew that they could have.

That said, there's really no telling what the frequency of players would be who would choose to use an Eve button out in the wild, a reincarnation button which puts the player back where they died, or just go with random birth.  And all claims of what the frequency would be lack a sound, empirical basis.

**Comment by DougLefelhocz** [comment]
Also, Tarr, this post talks about a problem, that apparently has connections with other problems.

Do you have any sort of suggestions to resolve any of the above problems, or further problems that the above problems suggest?

Or do you just want to reject that 1. and 2. not both existing, as a problem, when apparently many people have suggested both 1. and 2. existing as a problem for a very long time?

**Comment by TwistedHBG** [comment]
This github is for bugs with the game code, not for your rants. Please keep those on the forums.

**Comment by DougLefelhocz** [comment]
Twisted,

The post I quoted above says before 1. and 2. says the following:

> All that said, the game is not nearly as good as it could be, and I'm working on it and thinking about it night and day, but there are several hard design problems that don't have obvious solutions (and may not have ANY solutions, in the end).

1. and 2. above not existing simultaneously thus is a bug.  They likely don't exist simultaneously because of the bug of reincarnation not ever getting tracked, the bug of players not being about to start out in the wild by their own choice, and the bug of players not being able to reincarnate in the same spot.

This place is not a place for you trying to shut down discussion of bugs by trying to insist that reporting of several likely bugs is a rant.  

If you think the bugs are different, then by all means go ahead and state them.
