### ISSUE TITLE
Iron veins are not upgrading (and here's why)

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#580]
The update is fubar because the game is trying to look for shallow wells but isn't upgrading iron veins because when you create a well you make a family owned shallow well.

HOWEVER

If you reclaim an abandoned shallow well the game will actually upgrade all the iron veins like it's supposed to. 

This issue is leading to every single lineage being stuck on the stripped muddy iron vein unable to progress to get more iron.

**Comment by jasonrohrer** [comment]
This is fixed.
