### ISSUE TITLE
No Fathers.

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#583]
There exist several forum posts indicating this as a serious and longstanding issue.

**Comment by cordy-123** [comment]
Dude, do you have daddy issues? Or, I guess, "wanting to be a daddy" issues?

Jason has rejected this idea several times. Stop beating a dead horse.

**Comment by DougLefelhocz** [comment]
Cordy,

If Jason has rejected the idea several times, then it indicates that he keeps ignoring this longstanding issue with his game.
