### ISSUE TITLE
Marked Graves

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#59]
Shovel on marked grave deletes shovel

**Comment by jasonrohrer** [comment]
This is so weird... I'm unable to reproduce this on my end.  Are you sure about this one?

This is the second report that I've gotten about this.

Onetech is showing the shovel ending up in the hand correctly:

https://onetech.info/1849-Buried-Grave-with-Dug-Stone-origGrave

Maybe there's some other kind of bug here?

**Comment by Stylingirl** [comment]
I was just notified that it occurred same as how the axes would dissapear

**Comment by Stylingirl** [comment]
I'm looking at one tech and the dug stone transition seems to only appear on the mother grave.

**Comment by jasonrohrer** [comment]
Yeah, I'm not sure why that is.  OneTech may be behind the lastest transition-generating code for patterns.

Notice that the dead-puppy decay isn't showing up there either.

Has anyone confirmed that dead dogs are really decaying properly?

**Comment by jasonrohrer** [comment]
The ax thing was a real content bug, and it has been fixed, but is not live yet.

**Comment by jasonrohrer** [comment]
Tarr just confirmed that the shovel is working correctly.  Not sure what caused this report, but I'll close for now until more info arises about it.
