### ISSUE TITLE
Close Eve spawning leaves Eve's surrounded by dry well sites.

### ISSUE THREAD

**Issue by themattgoldfarb** [jasonrohrer/OneLife#594]
I've spawned as Eve twice in the past couple days.  Both times it was a struggle to find a well.  The first time by the time I found a wet natural spring I was already infertile.  The second time I gave up looking after 15 minutes and tried to revive a dead town.

With the Eve jump size at 50 and well tapout trigger at 160, you end up surrounded by dry well sites.  Also, many of the abandoned wells are secondary wells with no iron.  You can't take them over as an Eve because you won't get any iron.

What if you changed the tapout to be homeland based?  You get the same one well per homeland, but when the homeland is removed because a family dies off, the tapout trigger would go as well allowing new Eve's to build wells.

**Comment by jasonrohrer** [comment]
I think I've solved it:

Whenever a homeland expires (no baby born there in past hour), then any semi-primitive well (below newc pump) will go back to being an almost-finished well site there.  If a new eve finishes that well site, it will unlock more iron.

So in order to grief the land by permanently ruing iron sites, a griefer would need to build a newc pump at each site.

**Comment by jasonrohrer** [comment]
I've made this even better:

When a homeland expires and a primitive well collapses, the surrounding dry springs go back to being wet again, and sunken iron veins (which used to disappear, but are now permanent) resurface.

So Eve can have a full pick of all spots in the 320x320 area, and not just be stuck with the well as it sits on the original town's ley line.

**Comment by jasonrohrer** [comment]
Actually, I changed it so that only non-primary homelands (outposts) do this when they expire.  That prevents your from taking over an abandoned primary homeland by building a well nearby and unlocking 2x iron in that area.
