### ISSUE TITLE
Dry Family Wellsites can't get more iron

### ISSUE THREAD

**Issue by themattgoldfarb** [jasonrohrer/OneLife#596]
If you build a primary homeland wellsite, you get loose iron from the veins.  If someone builds a well nearby, it dries out your wellsite.  Then you can't upgrade the primary wellsite to a shallow well to unlock more iron and you can't build a new wellsite to get more iron.

**Comment by jasonrohrer** [comment]
This is true...

But I think it's also necessary.

You unlocked iron, and their well unlocked more.

We can't let you run off somewhere else and unlock even more iron.  If that were possible, you'd just rinse and repeat and unlock as much iron as you wanted.

You could, however, go nearby and make a well, and then remember where the iron deposits are.


The core problem is that the wellsite doesn't tap out other springs, which lets someone else build  a well site very close to you.  If they do that, they actually spoil part of their own homeland (your homeland is there first, overlapping with theirs).

But it seems kinda weird for well sites to dry up springs nearby.  I guess it's a little strange that they unlock iron....

However, I do want "tapping out springs" to be a slow-ish process (requires a shovel).
