### ISSUE TITLE
we have a problem in the game

### ISSUE THREAD

**Issue by be227** [jasonrohrer/OneLife#598]
I like the new issue is I was trying to help out a town that's ruin I was trying to help out the town I saw one player put out a knife and kill me of help out a ruin town I was so pissed off I broke my mic of ps4 sometimes I hate technology I want to kill update to be back to where it was there is too many griefers in the game

**Comment by jasonrohrer** [comment]
If you were out in a lonely place (just two people), then solo killing is possible.  But you do get plenty of warning and chance to run away.
