### ISSUE TITLE
No Leadership By Fathers

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#601]
Again:

> I want to make a game where anything is possible, in terms of social structure, and it's totally up to the players

https://onehouronelife.com/forums/viewtopic.php?pid=46738#p46738

Then leadership by a father, or in other words, a patriarchy needs to be possible.

So, then fatherhood needs to come into existence, and the lack of it is a problem.

**Comment by jasonrohrer** [comment]
Please stop harping on the father issue.

Fatherhood was intentionally excluded in my earliest discussions about the game design, 5+ years ago.

If you don't stop posting these issues about fatherhood, I will block you from posting issues entirely.
