### ISSUE TITLE
Donkey town apocalypse

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#603]
This happened 28 April 2020

Donkey town had 4 bells so they could navigate there.  Apparently Killian and Rey were there so they somehow managed this. This is not an issue.

But they made an apocalypse and cleared off the map.
Now even if people don't like the apocalypse, I acknowledge that it's a somewhat interesting interaction to make it or stop it.

But if they make it in donkey town, the distance of 20000 tiles is several generations to get there. I don't want to ruin donkeys gameplay but this is way too easy, they will all agree to wipe the map so there is no contest. If they would be able to get back to the middle of the map in several generations they would deserve it, but taunting the others to stop an apocalypse so far out is not okay.

**Comment by jasonrohrer** [comment]
Will make it so that donkeys and tutorial players cannot trigger anything that results in a monumentCall.

So they can't use bell tower to call people to them, and they can't build the various endtower steps that result in an end bell sound.

**Comment by jasonrohrer** [comment]
Fixed in:

https://github.com/jasonrohrer/OneLifeData7/commit/59fb041bc2024b502a6230a41b774a016bed419a
