### ISSUE TITLE
No Birth Control for Players/Far Too Many Players Starting as Babies

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#605]
Three recent posts on this longstanding problem:

[1](https://onehouronelife.com/forums/viewtopic.php?id=9596)

Testo remarks:

> Also having several babies that will eventually die young because of lack of food clothing and understanding of how to survive the early stages affects my gene score and toolslots. Not only I get hurt by my kids, but their kids as well. Which means I get to make a ton of work just to keep a line alive and I get to lose toolslots in the process.

[2](https://onehouronelife.com/forums/viewtopic.php?pid=95619#p95619)

> There's 62 people playing as I write this on bs2.  The math isn't that difficult.  If we have a server reset, then a new Eve will likely have upwards of 10, if not 15 children, since new Eves aren't spawned immediately and because there's only 4 families until someone reaches 40 generations.

> And that's *only* 62 people.  This game isn't capable of handling significant player growth on the same server, and that's a longstanding problem of how the game gets designed.

[3](https://onehouronelife.com/forums/viewtopic.php?id=9636)

Alontae Balasa remarks:

> I had to abandon so many babies, because we did not have enough food. We didn't have a well when I was born, we didn't have iron, and we didn't have a forge. I was generation 9! I ended up only keeping two kids (both girls of course). At one point, babies were popping out of me every ten seconds, and they did not use /DIE. I told my kids to say /DIE, but some wanted to play.

**Comment by jasonrohrer** [comment]
Settings adjusted in  e8b7f11bbc2f5c468097083b5142567cf650c9d0

We'll see how it goes this week.
