### ISSUE TITLE
No Bans for Serially Destructive Players

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#606]
Bobo Bill's [videos](https://www.youtube.com/channel/UCdp4UAE6gXXY_QAqKoZvW0w/videos) indicate why best, since it demonstrates that such destructive players can and will adapt outpacing any attempts to stop them.

**Comment by jasonrohrer** [comment]
Murder rate and victimization rate is extremely low right now---lower than it has ever been.  But I'm still working on the problem, to prevent small unilateral groups from killing whole towns like this.
