### ISSUE TITLE
Reincarnating as Eve Never Puts Someone On the Same Family Tree

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#609]
Someone can't use a private server to go and simulate conditions with respect to how much they need to eat individually during later generations of a family, because reincarnation as an Eve doesn't put someone on the same family tree, and thus doesn't increase the generation number of the character.

This isn't an assertion that pip value should decline on all servers with increased generation length though.  It's just that it's not possible to simulate conditions of later generations, because of the longstanding problem of reincarnation never putting people on the same family tree.

**Comment by jasonrohrer** [comment]
Yeah, the single-player game on a solo server is a non-intentional side effect of having many servers to handle (possible) loads if the game ever becomes very popular.
