### ISSUE TITLE
BUG: Posse-Exile

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#612]
From: Arcurus  (https://github.com/jasonrohrer/OneLife/issues/610)
> 
> There seems to be also a bug that exile does not count if the posse is declared before the exile.
> 
Sorry, I don't know if you notice this one sentence in the previous github report. I don't think you replied to this issue. So I just wanted to post it, in case you didn't see it. 

If you start the posse before exiling the person, the posse won't work ... even if you exile the person in the middle of the process of posse-ing. You need to stop then restart the posse to kill the exiled person.....which confused a lot of people. Coz the changes said if you exile someone, you can kill that person.

More experiences like this are posted in:
https://onehouronelife.com/forums/viewtopic.php?id=9685

If this is not a bug and is intended, alright. :)

Thanks!

**Comment by jasonrohrer** [comment]
Well, it's not a bug, exactly.... the required size is set when the posse is first formed.  It doesn't change later.

For example, if you chase someone out of town with a posse, the required size doesn't change, even though the population decreases (in the old mode where population mattered for posse size).

I can see how it's confusing, though...

But the idea is to exile someone BEFORE forming a posse.

If you target them before they are exiled, it will tell you about how big the posse needs to be.
