### ISSUE TITLE
Need shortcut commands in case of child king

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#613]
Lol, became king and and a crown with three in the first life after the update. Was a funny experience.

Would be nice to have a short version of the following command, so you can make one king / queen until you get older, something like:

FY = i follow you
FM = I follow myself

For sure both should be in, so you can make yourself king again, just in case....

by the way thx for the update!

**Comment by cordy-123** [comment]
property is currently inherited by the fittest close relative, with a minimum age of 14 (according to the code)

i think leadership is the same? idk. 

or do you mean that someone followed you? not that you inherited the leadership?

EDIT: Well, I just inherited gate at around 7. And someone inherited leadership at around 8.

I thought the code/update said:
"// find most fit offspring over 14 years old
// (old enough to manage ownership of property)"

**Comment by Arcurus** [comment]
no i inherited it, hope this was not a dream..... property i dont know, but i could not say i follow you thats for sure, was kind of fun. Maybe i was not exactly three since i dont use mods to see, for sure i could pick up stuff...

With a two letter follow and unfollow command age 2 would be enough (i guess one year gives one letter?) since then you can one make king who takes care of exiling....

**Comment by Arcurus** [comment]
looked at the changes:
Removed            if( age > 14.0 && 
And replaced with    f( otherPlayer->fitnessScore > fittestOffspringFitness ).

So it looks you can be even 0. I thinks its nice, why not, at worst you have little bit anarchy until the king becomes two and gets the shortcut commands. And at worst they can simply follow some one else if needed. Not a big thing just a nice thing to have the shortcuts.

**Comment by jasonrohrer** [comment]
Yeah, I'm going to implement an age gate on inheritance now, for this reason.

**Comment by Arcurus** [comment]
gate you mean age restriction where you can become leader? That would be sad, was so funny to be king with 1 years. With above shortcuts you could put in a regent in in case if needed.  And at worst they can make an new king by following others, i mean in real life succession to an infant was an little risky period, would be sad to loose it.

**Comment by jasonrohrer** [comment]
Hmm.... as I think more about this, I think that a "child king" is actually a cool thing to happen sometimes.

As in real life, the child will lack the ability to lead for a while, and people under that child will have a choice to make (keep this fit individual as king, or pick a different leader now to take over).

It's not hard for me to solve this problem for you (by ignoring possible heirs under age 11), but that's one less wrinkle for you to deal with sometimes.

**Comment by Arcurus** [comment]
yes please let child kings its so fun! the shortcuts i suggested where just meant that you can then put an regent in place. But no need to get rid of child kings even if you dont have the short commands its fine.
