### ISSUE TITLE
Currently it is near impossible to see / help a relative before he starves to death

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#614]
With the current gene score now getting so important its even more important to help your relatives. But currently you get no warning if a relative from you is close to starve to death. Especially new players, fresh from paradise, with the new harder food system could need help before they starve to death since the main thing they know is how to eat berries.

The following could help:
1) If in range, you get a warning if a close relative or a allie has only 2 pipes of food left (no warning for babies) and you get a pointer to the starving relative / allie. The starving person may also have a sad face expression. 

2) There is no in between state of starving to death and just starving. In true life, your body goes into energy saving mode if it starves and can sustain for a while through saving energy. This could be simulated the following way:

Reduce movement speed X 0.8 if starving (can be scaled with the food pipes left) but also reduce food consumption  to X 0.5

If starving to death (0 food pipes left) Reduce movement speed X 0.5 if food pipes below 0  but also reduce food consumption  to X 0.25

**Effect:
This would give some more time to help starving people while encouraging them through speed reduction not to starve**. Especially this would give new players some extra time to react which is quite needed since they need quite some time to learn yuming. In average starving players would save more food, but they would loose speed for that, which is a big encouragement not to starve.

**Comment by jasonrohrer** [comment]
Regarding the warning.... I feel like it would get overwhelming if you had a lot of relatives, and they were all starving.

I also don't want to adjust the rate at which people starve just now, because that throws the balance off in the food system (like, how long food lasts, etc.)  As a simple example, expert players who were working close to home might opt for the movement slow in order to save food while smithing.  It's a pretty delicate thing.

While I do appreciate the impact of new players on your gene score, you do get a notice every time one is born, with an arrow pointing toward them (at most one notice per minute).  You can walk over to them at that point and find out whether they are new.

And if they ARE your baby, you will get very specific notice if they are new, so you can keep an eye on them.

I'll think about some kind of "STARVING" emote that you can watch for, at least.  So if you're keeping an eye on them, you will know if they're in trouble.

**Comment by Arcurus** [comment]
yea starving emote would be great! was thinking about if the /ill could be used, just in dark blue or something, its super visible...

couldn't the starving warning be like the "!" marks that appear just in an unique color for starving? the "!" are not that much distracting and very easy to follow.

To the food, yea for sure should be thought through it with care, i think most vets currently so or so use the milk yumming and therefore have no problem with food during smithing, and since they click with felt 100 clicks per seconds, they go through smiting like anything, so the movement speed would still be the mayor restriction for them. I think the biggest difference would be for the people on the fire which wont move / are AFK. i think having a buff like the starvation change would be great to have, since force feeding AFKs would then be easier, since its not fair, that they pull you down when they go AFK, so currently you need to be around them all the time to force feed them which is not a nice player experience...

With new people, the last food updates made it quite hard for new players and also for players in general except the yam vets who know the milk trick. The hardness can be seen on the time how long families life in average.  Before they needed simply go to the next berry bush and eat, and that they learnt in paradise, but now in one life you need to teach them at least how to eat 10 different yam things, thats quite impossible to learn in one life. The last new player i wanted to teach died before i could show him the way from berries to stew. I think players would very much appreciate to have some kind of relaxation on the food issue. Better to buff food and nerf iron then the other way round.

If the hole idea is that different food should be crafted, then i think we could use solutions like seasonal food, which changes every three years or so. since a yam chain will never reach all kind of foods, the yam chain will be always quite the same. with seasonal food you would have more time to craft it, even if its a food which is normally not used. Also the season could be semi random, so not every life would be the same food wise, early generation could have more the raw foods as seasonal food while older generations would get more advanced seasonal food.

Yaming could be also connected to other stats, like movement speed, or max age. like the basic food value of nej food would keep you alive, but it wont keep you healthy.

For example movement speed could be 1% plus for yam and 1% minus for eating nej food.
Age one extra year for eating yam, one year less for eating nej. since there is a limit to yam, there would be a limit to max age, and default age could be set that still with yaming you reach 60 in best cases.  I guess many vet players would do anything to show that they can live longer then others, even if its just few years.

I think the main point is, currently there is no in between starved to death and running super healthy around. In our life being healthy and being alive are two different thinks, disconnecting this two could enrich the player experience.
