### ISSUE TITLE
Commands stop function sometimes

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#616]
Sometimes commands stop function, see here:

https://youtu.be/sy3S-mMXrEw?t=1137

Also for me at one point naming child's did not work anymore.

**Comment by cordy-123** [comment]
If you still have the pursed lips from previous whistling, you can't whistle until it goes away.

I believe the trick here is to alternate from /yoohoo and another emote...if you don't want to wait for the pursed lips yoohooo to go away. iirc.

-------

If children are 4.9 and below, pick them up to name them.

For 5 and above, just say you are ___ but you cannot be holding a kid while doing this....coz the game thinks you are trying to name the child in your arms.

**Comment by jasonrohrer** [comment]
Yeah, there is a cooldown on whistling, so you don't annoy people too much.

If you can get a video showing you being unable to name a baby, please re-open.
