### ISSUE TITLE
Food Issues since the Food update

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#618]
In higher generations foods like berries and higher foods like pies will have the same value which seems not logic.

The new player difficulty is now much higher then before, since learning YUM needs some time

Yumming stuff like Milk becomes overpowered

**Possible solution:**
- Set max Yum bonus to double the initial food value (maybe even better just give double initial food value for YAM, no need for overpowered chains)
- Set min Food value to at least halve the original food value

Optionally: If people eat three time NEJ food that has the lowest possible food value in a row (eating Yam in between will reset), give them ill emote and block them from eating for 10 seconds low rated NEJ food and a movement malus of X 0.5 for this time

**Effect**
This will help especially noobs to learn something else then berries in higher towns. Additionally it would help to reduce berry and carrot eating griefing.

Optionally Give additional boni for eating YUM. Eating Yum could be for being healthy while eating NEJ makes ill
Give a light 1% movement speed increase if eating YUM and 1% movement decrease of eating nej
Give one year extra if eating yum and one year less for eating nej (MAX still 60 and Initial time to live 50 so with 10 more yum then nej they reach 60)

**Comment by jasonrohrer** [comment]
I don't think the initial premise is true.

The eat cost is max 5 (so at most 5 is subtracted from a food in late generations).

Even Carrot pie is worth 2 food per bite, late generation, where berries are only worth one.

Some of this stuff will be adjusted in the future, but I think it's all in a pretty good place for now.

Players do get a DING message informing them that their baby is new, so they can have a chance to teach them well.
