### ISSUE TITLE
Not Anything is Possible In Terms of Social Structure

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#622]
> I want to make a game where anything is possible, in terms of social structure, and it's totally up to the players.  This makes for a huge variety of dramatic stories.  

-[Jason Rohrer](https://onehouronelife.com/forums/viewtopic.php?pid=46738#p46738)

It's simply not the case that anything is possible in terms of social structure.  There is no possibility of a patriarchy, or a system where fathers have social authority in game.  It doesn't matter how long that has stood.  It's simply necessary that for anything possible to exist in terms of social structure, fatherhood in game by the players would have to come as a possible, so that patriarchy could be a structure that _the players_ could choose.  And the range of dramatic stories is not huge, in part, because of the lack of fatherhood in the game.

**Comment by Krammy** [comment]
![no](https://media3.giphy.com/media/12XMGIWtrHBl5e/giphy.gif?cid=ecf05e47e5fa2abc01eb4d6d9a994feabdedb753adafab94&rid=giphy.gif)
https://github.com/jasonrohrer/OneLife/issues/601#issuecomment-620248479
