### ISSUE TITLE
Players should be able to turn around on the spot

### ISSUE THREAD

**Issue by Krammy** [jasonrohrer/OneLife#623]
When you're a kid standing near a fire, I find myself always having to turn towards who I'm speaking to. Maybe it's another child, maybe it's the mother.

It's especially annoying having to move off the square you're on and then back on to the square in order to turn your player around, and it doesn't feel good either. I think being able to left click on the side of the square you want to face would be great for immersion.

**Comment by Krammy** [comment]
It would also help in the scenario where you're locked in a 1 by 1 fence. Being able to turn on the spot lets you move your camera to view the other direction.

**Comment by hetuw** [comment]
Or maybe instead of clicking, the player will automatically face the direction your mouse is.
So if your mouse is on the left side of the screen it will look left, if you then move the mouse to the right side it will change direction and look to the right. There could be a small delay so people cant do it very fast.

**Comment by Krammy** [comment]
That could also work, though I don't know if it would be as practical. It would be harder to take another player by surprise if you wanted to grab an item from a stash behind you, for example.

Then again, it could be cool to see people looking around in the village you're in. I like the suggestion @hetuw. :)

**Comment by jasonrohrer** [comment]
Funny thing... facing-direction isn't tracked server-side at all.

That's a client thing.... the client determines your direction based on your movement.  I.e., facing direction is "fake" and part of the presentation only.

In fact, two clients might disagree about a player's facing-direction.  If you're born into a situation where everyone is standing still, they will all be shown facing right (the default).  Other people, who saw their moves, might see some of them as facing left.

I made a decision long ago that position mattered, but facing direction didn't really matter.


That said, the server could transmit a message to the client telling them that some character has faced left or right.

And following the mouse might make the characters feel more alive.  So this is a good idea!
