### ISSUE TITLE
The starving emote seems to be still there if you breast feed a child with hair

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#626]
The starving emote seems to be still there if you breast feed a child with hair

https://youtu.be/-H_lJ-8dWxw?t=1463

another question to the "off-screen H sound:
The current sound looks like a speak, can we have it in a different color like dark blue and disappear only if dead or not starving anymore? 

Here how the "h" sounds looks currently:
https://youtu.be/-H_lJ-8dWxw?t=2544

Also if starving to death the last 5 seconds or so, can we make them slower, so that its more easy to catch them like Twisted tried:
https://youtu.be/-H_lJ-8dWxw?t=2383

**Comment by jasonrohrer** [comment]
Will fix the breastfeeding older kid issue.

There are lots of off-screen sounds that look like speech.  Only the murder ones are red.  I'm going to leave that part alone, and not get too colorful here...
