### ISSUE TITLE
Current gene score rewards having less kids / relatives

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#629]
Problem:
The current gene score rewards in average having less kids / relatives instead rewarding having more..

Taking care of only yourself is lot more easy then taking care of other people. So in average each additional relative pulls you more down then up.

Genetically it should be exactly the other way round, since you reaching 60 alone has done nothing while having 3 kids even if one dies early did at lot.

Another issue is with grandkids and grandgrandkis often you cant do much about their life. A fair thing would be if they would be rated more positive then negative, since having grand kids is already a success.

**Possible solution:**
To balance this therefore i suggest to count yourself only negative,  and all grand and grandgrandkids double positive. All other would be counted normal.

Effect:
This would reward to have more kids not less and make gene farming more difficult, since you need to have lot relatives.

**Comment by Spodnie** [comment]
Actually you can get lots of points if you have many offspring.

**Comment by Arcurus** [comment]
> Actually you can get lots of points if you have many offspring.

yes you can, but you can also loose lot of points if you have many offspring, and since taking care just of you is more easy in average you will loose, except for not skilled players who dont know how to survive.

Letting the gene score decay per time lets say 0,1 years every day if over 30 and or giving a fixed cost of half a year every life would also help to reward people with more offspring.

**Comment by jasonrohrer** [comment]
I don't necessarily want to reward more offspring at any cost.

People should be trying to ensure the survival of the offspring that they do have.
