### ISSUE TITLE
Everything

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#63]
Apparently something is extremely wrong with the code. Reports of berry bushes turning into hatchets, walking bowls of butter turning into calves, piglets turning into boars, carrot rows giving berries, and domestic pigs killing players.

**Comment by Stylingirl** [comment]
Wild squash turns into seeding cabbage when picked, a stack of two baskets turns into a semi-tame wolf, sheep randomly turns into butchered sheep but still walks around, a pile of two stones turns into five stones, and stacking floppy baskets together makes a key and lock.

**Comment by Stylingirl** [comment]
User Awbz discovered objects folder is missing 1850-1852.txt files in the client, causing sprites to shift and bug out.

**Comment by jasonrohrer** [comment]
Thank you for this report!  Putting it on GitHub brought it to my attention quickly, and I was able to scramble to put out a patch update to fix this.
