### ISSUE TITLE
Fixing the unlimited iron through family mines

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#630]
>The goal here is to make iron a more precious and carefully-managed resource, instead of one that is practically infinite as it is scattered randomly around a practically infinite map.  This also reduces the "wander around searching" gameplay pattern.

>This is a huge change, because iron is something like the spine of the tech tree.  Some adjustments will been needed over the next few days and weeks.

The family iron system did the opposite then intended. Instead of making iron more rare it made it more abundant, since each eve family can spawn new iron, while before even with an unlimited map there is a limited lifespan to travel to bring iron to a town. 

Further the current family iron system discourages offspring villages / migration since you will only get new iron through taking over from eve families.

Also it reduces the gameplay by limiting the need for exploration and competition for new iron mines and discourages to use roads to connect the iron mines. Placing the mines on a grid further discourages exploration and road building to mines.

Without new iron through new spawned eve family mines older towns would need to get the iron from more far and far away, thereby naturally increasing the challenge over time.

Last family iron mines are kind of magic and not intuitive to handle / have a high additional complexity which only vets understand fully.

**Possible solution:**
- Distribute iron semi random on the map, but make it more rare before the family update (if a higher challenge is wanted).
- limit the amount of iron you can get out of a mine for mines with engines
- nerv horse wagons like being slower with loaded trailer to make it more difficult to bring iron from far.

- consider first fixing eve placement, since currently eves are spawned in exhausted areas which will be then worse if iron is also exhausted.

**Comment by TwistedHBG** [comment]
I appreciate what you're doing as some of your suggestions have been pretty good, but I feel like this github is more for actual bug reports rather than suggestions and mechanic tweaks.

Also, you're suggesting a return to infinite iron, and unfortunately I don't think that's in the cards.

**Comment by Arcurus** [comment]
what i try is to outline the current issues in the gameplay mechanics as best as i can. If Jason wants to keep them, im fine with that, at least i tried my best to help and will try not to report twice the same issue once i got a statement or found Jasons statement in the forum / github already, unless the circumstances changed.  


>Also, you're suggesting a return to infinite iron, and unfortunately I don't think that's in the cards.

**Thats to opposite of my suggestion. My suggestion is to switch from infinite iron to limited iron.
As said, even if iron is in theory infinite on the map, its finite for a given town, since people have a limited lifespan to bring it. Limiting iron on the map is very easy.** 

**The issue is with the family mines, it does the opposite what Jason intended it to do,  Since eve spawn is very close, they will always bring new unlimited iron.**

Jason may have a better way of fixing that issue, but i think above suggestions for fixing it are quite straight forward and reduce even lot of complexity of the code / keep it simple always wins.

To the other promise, that it limits the explore and search game play, yes it does, but i dont understand the benefit of limiting the explore gameplay yet, maybe some one can explain it.

To quote you from the forum:
> TwistedHBG "The iron change is really bad, I agree"

Since felt 100% of the community agrees with that i posted the issue here.

Fixing it, can do a lot to increase the gameplay experience and makes it even less complex. So at least i try to do my part.

**Comment by jasonrohrer** [comment]
I think it's generally working well.

In terms of this creating infinite iron, there's a lot less iron available than before.

In order to achieve something similar through random iron in the map, the scarcity would have to be very high, making it almost impossible to find.

**Comment by Arcurus** [comment]
>In order to achieve something similar through random iron in the map, the scarcity would have to be very high, making it almost impossible to find.

If the amount per mine is limited and or its more difficult to transport iron, then there is no need to limit the amount of iron mines, so they should not be harder to find, just provide less iron.

Interesting would be if rails would be the best way to transport iron, then it would be worth to build long rail systems to the iron mines.
