### ISSUE TITLE
Some characters are not being added to the website family tree

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#632]
example (thanks Bsod): http://lineage.onehouronelife.com/server.php?action=character_page&id=6277598&rel_id=6277839

People on Discord mentioned that it seems to happen when people say long sentences near the end of their life, so it's probably related to their last words being longer than expected due to the char limit change.

My layman's guess is that it has something to do with line 346 in https://github.com/jasonrohrer/OneLife/blob/master/lineageServer/server.php ("last_words VARCHAR(63) NOT NULL,".)

**Comment by jasonrohrer** [comment]
Yes, it is probably that line!

**Comment by jasonrohrer** [comment]
Yes, I can see in the logs that "data too long for column last_words"

**Comment by jasonrohrer** [comment]
Fix is live.
