### ISSUE TITLE
Propertygate with Unknown Person as owner

### ISSUE THREAD

**Issue by MrXIX-OHOL** [jasonrohrer/OneLife#636]
This won't point to an owner and can't be removed.
Not being able to reproduce yet due to the difficulty of testing, but it exists.

**Comment by Spodnie** [comment]
Probably happens when an unnamed person gets the ownership.

**Comment by jasonrohrer** [comment]
Can we get a screen shot?

A location on the map would also be good, if you can get that.  Either through a mod that shows coordinates or by looking at relative coordinates in stdout.  If you give me your player ID (the ID in your PU messages) along with the relative coordinate on the map of this gate, I will be able to get the absolute coordinates and visit that gate as VOG to see what's going on.

**Comment by MrXIX-OHOL** [comment]
There were a few in the batman family. That should not be hard to locate.
(If the batman family is still alive when you read this)
Four out of five gates on this screen are Unknown Person: https://onemap.wondible.com/#x=-5542&y=-231&z=30&s=17&t=1593127661

**Comment by jasonrohrer** [comment]
Thanks for those coords!  I'll jump in as JASON and take a look.

**Comment by jasonrohrer** [comment]
Yes, I see that these gates are stuck.... they should have collapsed when the last owner died.

Thanks for doing the leg-work here to help me locate them.

I'll see if I can reproduce this on my end.

**Comment by jasonrohrer** [comment]
Aha!  Was ale to reproduce it on my end.

The findHeir code, when you die, isn't skipping players that have an error condition.  So if your kid dies a few seconds before you do, they will still be in the system, and found as an heir for your gate.
