### ISSUE TITLE
When you have high yum, but eat a low food count food you still hear the dinging forever even though you're fine"

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#637]
From the forum:
"When you have high yum, but eat a low food count food you still hear the dinging forever even though you're fine"
https://onehouronelife.com/forums/viewtopic.php?id=9914

Possible solution:
yum pips could just add up as normal pipes and go over the max...  sadly then you could eat less yum in a row, but hey one price you need to pay...

**Comment by Spodnie** [comment]
Suggested solutuon: 
Starving dinging would happen only if total pips are 4 or below (pips plus bonus pips from yumming).


Offtopic: Would be also great if foods were showing how many pips they will fill you, when you are holding one.
I know this was already suggested https://github.com/jasonrohrer/OneLife/issues/591, but if server could send all food values to the client when connecting to the game, I think it could work. 
People would love it for sure.

**Comment by Arcurus** [comment]
> Would be also great if foods were showing how many pips they will fill you, when you are holding one.

that would be great!

with the yum not counting to the food pipes, the problem is also, that it still says starving even if you are not. This is not very intuitive.

**Comment by jasonrohrer** [comment]
Fixed.
