### ISSUE TITLE
Exile and posse issue

### ISSUE THREAD

**Issue by MRGold777** [jasonrohrer/OneLife#638]
Today i was playing ohol we were going to kill an griefer but then someone possed on them before they were exiled and we could not kill them because because the game did not know that they were exiled. Pretty weird and it's a big issue mostly when they are part of your family and someone posses on them and nobody can kill them.

**Comment by jasonrohrer** [comment]
Yes, the posse size is set by the person who starts the posse.... which is a little weird.

I guess that means that a griefer's friend could protect them by forming a posse on them before they are exiled.
