### ISSUE TITLE
Minecart more difficult to use.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#64]
I know they're generally only used to move one type of item at a time but since the update you can only put items into them by right clicking. Left clicking with an item in hand will cause the cart to be pushed instead of the item going inside. 

If different items are put into the same cart you will proceed to just swap them around endlessly. The only way to left click put different items into a mine cart is to shove it forward and chase after it.

**Comment by jasonrohrer** [comment]
Hmm.... this is a consequence of the "being able to open a door with something in your hand" changes that alleviated the need for teleportation.  As a side-effect, you can "kick off" the cart with something in your hand.  Will fix this.
