### ISSUE TITLE
Genetics get stuck

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#640]
My genetics are stuck after being nameless child, last life before was:
[url]http://lineage.onehouronelife.com/server.php?action=character_page&id=6334734[/url]

After that life (nameless child) i got disconnected from the server and could not reconnect. Happend now two times. After that genetics where stuck.

**Comment by Arcurus** [comment]
seem to work now again with sever bug solved.

**Comment by Arcurus** [comment]
seems like my daughter Alina Clea got now reported as niece. I was Lu Clea.

I will keep an eye on it, but i definitely had a daughter and a son, so i guess there is some bug

**Comment by jasonrohrer** [comment]
Servers were crashing and all wonky that day, so who knows what was happening.  A bunch of lives weren't reported to the family tree or fitness servers.

Yes, please see if you can find an example of it happening now, with stable servers, and then re-open.
