### ISSUE TITLE
Craving a food which has a +yum*** can't be satisfied

### ISSUE THREAD

**Issue by MrXIX-OHOL** [jasonrohrer/OneLife#641]
Encountered this problem with:
Snipped cucumber, turkey broth bottle and berry bowl.
So it's fairly likely this is the culprit.

**Comment by TwistedHBG** [comment]
Can confirm, had a craving for a Turkey Broth Bottle and I was stuck on it.

**Comment by Spodnie** [comment]
Yeap.

**Comment by Arcurus** [comment]
same for me with bowl of goose berries

**Comment by jasonrohrer** [comment]
Okay, will fix this today.  Unfortunately, servers will need to restart to fix it...

**Comment by jasonrohrer** [comment]
I mean, I have to fix this asap, or else families will be stuck on a craved food forever...

**Comment by FeyFre** [comment]
place in code where it gets broken:
server.cpp line 7028, function updateYum. eatenID gets replaced with yumParentID (e.g. bowl of berries with berry), and then this new value (instead of original eaten) is compared to craving food id,
```c++
        int eatenID = inFoodEatenID;

        ObjectRecord *eatenO = getObject( inFoodEatenID );
        
        if( eatenO->yumParentID != -1 ) {
            // this may or may not be a valid object id
            // doesn't matter, because it's never used as an object ID
            // just as a unique food ID in the yummyFoodChain list
            eatenID = eatenO->yumParentID;
            }

        inPlayer->yummyFoodChain.push_back( eatenID );
        
        if( eatenID == inPlayer->cravingFood.foodID &&
            computeAge( inPlayer ) >= minAgeForCravings ) {
```

**Comment by jasonrohrer** [comment]
Yes, was able to find and fix this.  Thanks for locating the problem.

**Comment by TwistedHBG** [comment]
I think the ideal solution would be to never offer +yum foods as cravings. That way you can satisfy your berry craving by either eating them from hand or bowl, or your milk craving by drinking it either from a bowl or bottle (which makes sense).
