### ISSUE TITLE
Offspring appearing as nephew

### ISSUE THREAD

**Issue by MrXIX-OHOL** [jasonrohrer/OneLife#642]
I (Miles) played a game as twins.
http://lineage.onehouronelife.com/server.php?action=character_page&id=6345948

My brother (George) didn't get the gene-score for his mother (Lela) and his mother got gene-points for Georges death as nephew.

Album with screenshots because leader board link will expire.
https://imgur.com/a/oC0xv7o

(This all happened long after the table server crash fix went live)

**Comment by MrXIX-OHOL** [comment]
It looks like this has nothing to do with being a twin or not since this issue also appears in this lineage:

http://lineage.onehouronelife.com/server.php?action=character_page&id=6346048

https://imgur.com/a/TfM0XiR

**Comment by MrXIX-OHOL** [comment]
http://lineage.onehouronelife.com/server.php?action=character_page&id=6347072

https://imgur.com/a/F75HQVo

Same issue here. Mother gets gene-score for her daughter tracked as niece. Daughter does not get gene-score for her mother.
(Very recently)

**Comment by jasonrohrer** [comment]
Aha!  I see the problem.

At the moment you're born, if your mother is childless, she is recorded as your aunt (she's a childless woman at that moment).

The first-born twin is thus seen as a nephew.

Will fix.
