### ISSUE TITLE
Mother - Aunt Leaderboard Score Bug

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#643]
Sometimes, your mother's score doesn't count towards your own. 

I assume this is connected to last week's "childless woman" gene score change.

Example, as you can see in the screenshot below...Hope Kai had a son named Tom Kai

![](https://cdn.discordapp.com/attachments/691122070465019974/727218838420324533/IMG_20200630_014751.jpg)

But Tom Kai's leaderboard does not show his mother there.
--- Hope Kai did not die early so that is not the problem. (Mother's score doesn't count if they die before you are 3 years old.)
--- You can also see the player (Tom Kai) did not play other lives within a few hours. (Discounting the your mother's score does not count because your mother was your daughter in a previous life thing.)

![](https://cdn.discordapp.com/attachments/691122070465019974/727215589256462456/IMG_20200630_013447.jpg)

You can see below, Tom Kai counts as NEPHEW to Hope Kai. (Hope Kai did not have any siblings.)
--- which is why I assume Tom Kai's leaderboard score did not count Hope Kai....because the system viewed her as an AUNT.

![](https://cdn.discordapp.com/attachments/691122070465019974/727215589633949867/IMG_20200630_013426.jpg)

Just a guess on why it is happening. I'm pretty sure this bug did not happen before last week's update.

Thanks!

**Comment by cordy-123** [comment]
Oh, just checked, Hope Kai had another son, Nick Kai.

As you can see, in Nick Kai's leaderboard score....Hope Kai shows up as his Mother.

IDK. 

![](https://cdn.discordapp.com/attachments/691122070465019974/727219846156386394/IMG_20200630_015153.jpg)

For Hope Kai's leaderboard score....Nick Kai counts as a son. But Tom Kai counts as a nephew.....    

Probably only affects firstborns???

![](https://cdn.discordapp.com/attachments/691122070465019974/727215589633949867/IMG_20200630_013426.jpg)

**Comment by Arcurus** [comment]
yea, have similar bug with daughters beein reported as nieces:

Was Daisy Drow and had a daughter Secora Drow, but  Secora Drow was reported as niece not as daughter (she died before me).

http://lineage.onehouronelife.com/server.php?action=character_page&id=6346731

**Comment by jasonrohrer** [comment]
Turns out that someone has a "\" in their email address.  Whenever this person is your offspring, the report gets screwed up (because that's an escape sequence in SQL).  So those lives don't get recorded correctly.

**Comment by jasonrohrer** [comment]
I think this is related to what Arc reported earlier about gene scores not getting recorded sometimes.

**Comment by MrXIX-OHOL** [comment]
I hope that's it, because these cases are found very frequently.

**Comment by jasonrohrer** [comment]
Yes, it's actually TWO different problems.

First of all, the \ in the email address.

AND a bug in the server code about how your mother is counted as an ancestor for you.
