### ISSUE TITLE
If your gene score is low , you can just AFK some lives to leech Gene score from others

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLife#646]
AFK people should not gain gene score. They can still count for others but they should get nothing,

**Comment by miskas9** [comment]
I think The practice goes like this , people that /die a lot and their gene score is below 5 or more to raisee their gene score they spawn and stay afk immediately. The propability is that they will spawn to a caring mother and she will feed them long enough even to adulthood cause she cares for her gene score.

**Comment by jasonrohrer** [comment]
Thinking about this, it's a messy problem.

If we were to "punish" the AFK person in some way, the most obvious methods would also harm the person who has been so diligently taking care of them.  Essentially, you want them to "count" for their caretaker, but not for themselves, or something.

And having them count for their caretaker only isn't fair either, b/c that means the caretaker is indentured to their care, and will be punished for letting them die young, while their life doesn't count for them.

So, I think I'll leave this alone for now...
