### ISSUE TITLE
Fix to exile / posse issues

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#648]
Currently there are many edge cases and many shortfalls, but mostly the system is very complex and un-intuitive, even vets struggle with it as outlined here:

https://onehouronelife.com/forums/viewtopic.php?id=9921

Possible quite simple solution to make posses more easy to use and allow to fight back against posses and evil leaders:
Let the posse need always 3 people but allow "murderer" / people who attacked / hit somebody to be attack able them self. 

I think this would be a quite simple solution to many posse / exile problems like an evil leader. Instead bringing the leader to exile him you could also form a posse of three, So you would have more options which solves many edge cases like the leader is not reachable or just too far away.

Also attacking one person outside of the village should be allowed if he has equal allies. This would allow more stories outside of the village.

**Comment by Arcurus** [comment]
Above suggestion would not completely fix group like combat / war. in theory posses could be used to fight against each other in groups, but this seems far more complicated then needed. Of course a system where the leader first need to declare war could be used. But maybe the easiest of all would be to allow single combat again.

To make single combat less deadly the first wound could be made a light wound which let you still pickup stuff and heals after 1 year. Additionally the attacker could be automatically exiled if some ally of the victim saw it (same system like with orders, but reverse).

And / or an instinct based round away could be used where one runs by default away if an enemy with weapon is in range.

Posses could still be useful for the speed boni / to hinder use of horses for the victim.

**Comment by miskas9** [comment]
Ι really like the idea of the person that holds a bloody weapon to be vulnerable to a Solo attack.
This vulnerability would work as a reality check that indeed the killer has the approval and support of his community.

**Comment by jasonrohrer** [comment]
Yes, this makes quite a bit of sense.

I will do it based on a timer....  you are vulnerable to being solo killed for 60 seconds after killing.  This will cover the sword too, even if you drop it.

Live by the sword, die by the sword.
