### ISSUE TITLE
Please allow us to paste the email in the off-steam version

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLife#649]
My email to log in off steam is like 20 random numbers I have to type in myself. The key has a paste feature, please allow emails to be pasted too

**Comment by JustinLove** [comment]
Not sure how it interacts with steam version, but you may be able to to just copy or edit your settings/email.ini as a workaround.

**Comment by jasonrohrer** [comment]
Yeah, I see the problem here.

Most people don't have trouble typing their own email, which is why I don't have paste functionality for it.  But the "steam" email is a fake one that is just a 64-bit number.  No fun to type that.
