### ISSUE TITLE
Since the generational food update survival for noobs is super hard and noob berry munching is like locusts swarms 

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#651]
From the forum:
https://onehouronelife.com/forums/viewtopic.php?pid=99693#p99693

Possible solution: i would suggest to give a person who eats three times in a row a not yum one pipe food an /ill emote and make them slow x0.8 for 20 sec and hinder them to eat other one pipe food in this time.

To let them not starve to death all at once i suggest to slow movement speed down x0.5 if you are 30 sec close to death, but give them halve food need.

So they have actually 60 sec instead of 30 sec to death. Also the speed reduction helps other to catch them and feed them.

Of course the speed reduction could scale according to how close you are to death....

in practice this is very hard, since if you plant too less berries, you have none for compost or sheep or pies. If you gate them, then you have lots of extra work to give access, open / close gate, and collecting berries is very time consuming task which normally is good for noobs to do. If tons of berries are there, then they just eat them all up and so or so die like flies since they give nearly zero food. On top of that all the water is then wasted. So in game there is no good way to solve it if there are tons of noobs. And shouting on them all the time is also not very helpful.

**Comment by Arcurus** [comment]
In twisted new video you see how hard it is to teach yum. He spend tons of time on it, and for the noobs was hard to see if its yum or meh. I guess twisted played not in the American time zone where all the noobs join, because there with the summer sale he would have then two or three noobs at the same time to teach, which is quite impossible.

here the video:
https://youtu.be/ZW9jIJtzaeI?t=1108

Maybe something like /ill could come for 1 sec already if you eat the first one pip meh food. This would clearly make visible if the food was meh.

Also babies could be allowed to pickup but not eat food, then you could also teach them yum and meh when there is nothing else to do.

Same is with the backpack (as you see in the video), it needs some time to get used to, babies could learn this in the first 3 years if they would be allowed to.

**Comment by jasonrohrer** [comment]
I'm not too concerned about this.  They will learn.

You can also fence the berry bushes to save them for more useful purposes other than noob munching.

Give each baby a backpack full of pies, that kind of thing.
