### ISSUE TITLE
Some table issues:

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#655]
1. would be nice if you could directly add / remove items from a basket on a table without the need of putting the basket first on the ground.

2. If you right click on an item on an table, items can jump and switch their order. I guess thats normal for a container, but in case of an container like table it would be nice if the items behave exactly like on the ground / dont jump. If there is no item on the table position you clicked, then it should behave as if you clicked on an empty ground.

3. Some crafting results like made tool parts on a flat stone would be big enough to fit on a table, but they cannot currently be on a table, so you cannot do smithing and other things on a table. If these small enough crafting results could be on a table, tables could have even more use cases to reduce clutter.

4. We all know that pumpkin cake is not allowed to be on a table except if it is the first item. Since pumpkin cakes are quite common to make in kitchens, wouldnt it be possible to use a rose or some other decoration like table cloths, at best one unique item for feast table,  as first item that you need to make a feast table? Then pies could be on the table like all others.

Admin edit:
Task list:

- [x] Rose to get feast table started, so pumpkin pie can be stored on table.
- [ ] Investigate direct insert into basket sub container.

**Comment by jasonrohrer** [comment]
Yes, good idea about placing something on the table to get the feast started!

--Smithing on the table?  Like on a wooden table?  It would burn through.  You need a rock or metal surface for those red-hot things....

The other ones are quite a bit harder.

--The underlying database engine treats containers as stacks, and there can't be empty spaces in the stack.  This would be pretty painful to fix, for such a small benefit (stuff not moving on table when you work on it).

--It might be possible to click a basket on a table (or in a box) and add stuff too it.  However, I worry about confusion between the various mouse clicks.  Inserting vs swapping.  I'll look into it.

**Comment by DiscardedSlinky** [comment]
So feast table is blacks only now. Nice. thanks for this

**Comment by jasonrohrer** [comment]
Can you grow roses without snow?

**Comment by jasonrohrer** [comment]
I looked into the "insert directly into a sub-container" thing, and it was way too complicated.  There are all these nice "swapping" behaviors that currently work on non-sub-containers, and getting that all working well was a ton of work back in the day.  Getting that working for sub-containers....  I need to pick my battles at this stage of development.

**Comment by DiscardedSlinky** [comment]
A RED ROSE TOO? holy shit this is going to be impossible
