### ISSUE TITLE
Homeland Lingerance after death of family 

### ISSUE THREAD

**Issue by Lava6** [jasonrohrer/OneLife#658]
I’ve seen this bug a while and it’s really been a big hassle. When the family dies. It still retains its homeland under its OWN family name rendering it useless to colonize then it goes under the tag “unnamed family owns this” which also makes it impossible for town to be claimed an populated only after 10-60minutes will the well go abandoned which is really annoying for any new eves looking to repopulate towns.

**Comment by jasonrohrer** [comment]
Yes, you're right!  I'm able to reproduce this.  Will fix.
