### ISSUE TITLE
Website and ingame gene score leaderboard positions don't match.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#660]
Both images taken at the same time.

Website:
![image](https://user-images.githubusercontent.com/43919541/87966457-95dade00-cabd-11ea-8915-579b05a2d862.png)

Ingame:
![image](https://user-images.githubusercontent.com/43919541/87966492-9ecbaf80-cabd-11ea-90f2-d822cc562916.png)

It's not just a one time thing, I've noticed the discrepancy several times where I'm 18th ingame but 19th on the website or something similar.

**Comment by TwistedHBG** [comment]
Four hours later, the rankings changed a bit but the discrepancy is still there

Website:
![image](https://user-images.githubusercontent.com/43919541/87988280-5c679a00-cae0-11ea-8ded-b9593c3d86cb.png)


Ingame:
![image](https://user-images.githubusercontent.com/43919541/87988317-68535c00-cae0-11ea-8992-0f45c4df8c71.png)

**Comment by jasonrohrer** [comment]
Nice catch.

**Comment by jasonrohrer** [comment]
Aha!  It's a floating point rounding error in MySQL.

I ask it to count all players with scores greater than yours, but due to rounding errors, your score is sometimes seen as greater than yours.

Fix is simple, but it's a weird issue.
