### ISSUE TITLE
Inefficient memory allocation on cache creation

### ISSUE THREAD

**Issue by hetuw** [jasonrohrer/OneLife#661]
i added this printf statement:
`printf("expandMapSize to %i, inActor %i, inTarget %i, newActor %i, newTarget %i\n", newMapSize, inActor, inTarget, inNewActor, inNewTarget);`

here https://github.com/jasonrohrer/OneLife/blob/OneLife_v350/gameSource/transitionBank.cpp#L2502
this is the output:
```
...
....
expandMapSize to 9508, inActor 9507, inTarget 3076, newActor 0, newTarget 495
expandMapSize to 9509, inActor 9508, inTarget 3076, newActor 0, newTarget 495
expandMapSize to 9510, inActor 9509, inTarget 3076, newActor 0, newTarget 495
expandMapSize to 9511, inActor 9510, inTarget 3076, newActor 0, newTarget 495
expandMapSize to 9512, inActor 9511, inTarget 3076, newActor 0, newTarget 495
expandMapSize to 9513, inActor 9512, inTarget 3076, newActor 0, newTarget 495
expandMapSize to 9514, inActor 9513, inTarget 3076, newActor 0, newTarget 495
```
if a new item is added to the arrays the memory only increases by 1 element, which means it will have to do the same thing again at the next item. This causes a lot of memory reallocation and copying which takes a lot of time and even makes windows computers get stuck.

In 2HOL they have more transitions and this causes serious issues, i assume it will also cause serious issues in vanilla in the future.
I only looked at the transition loading code, this might be also a problem in other areas.

Possible solution is to allocate 50% - 100% more of the current array size instead of 1 element, or to know exactly how many transitions will be loaded.

I did not read all the code so i am not sure exactly how everything works and what the problems are.

**Comment by jasonrohrer** [comment]
Thanks for finding this!
