### ISSUE TITLE
Race Discrimination

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#666]
In a recent video as an Eve Twisted ended up craving a cactus fruit as a ginger.  He wasn't able to satisfy the craving and it wouldn't have been reasonable for his character to satisfy the craving due to the race restriction on his character.  Nor is it the responsibility of only black people to supply cactus fruits to the world.  Nor is it the responsibility of non-black people to obtain cactus fruits from blacks.

The game at present has racial expectations (not biome expectations) and that in turns creates race discrimination.  Such racial discrimination doesn't work well with expanding content in the game like peppercorns, which *increased* the expectation of racial discrimination, as browns had a new responsibility put on them which no one else had.

**Comment by jasonrohrer** [comment]
This is working precisely as intended.

Twisted's character has a quest:  to go find a desert village and recruit them to help gather cactus fruit (maybe in exchange for oil).  Then Twisted can bring the fruit back to his village and satisfy everyone's craving.  He will be a hero.

This is not "racism", but a classic tale of a journey to a foreign land to gather things that you do not have access to in your homeland.
