### ISSUE TITLE
Trucks can be picked up from outside a fence.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#669]
Before:
![image](https://user-images.githubusercontent.com/43919541/93646704-02fbe880-fa07-11ea-9da0-ce2efd89cca7.png)

After:
![image](https://user-images.githubusercontent.com/43919541/93646713-08593300-fa07-11ea-9978-5e8376940585.png)

**Comment by DougLefelhocz** [comment]
Them's some mighty strong hands, son.
