### ISSUE TITLE
Game is not able to handle steam sales... too many noobs at once

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#672]
The food update made it lot harder for new players to survive. Before they just need a berry tree to life quite well, now they need all at once to learn yum and learn how to eat all the different stuff, which needs lot more time to learn then just to learn how to eat berries.

Here a nice picture that shows the situation:
https://onehouronelife.com/forums/viewtopic.php?pid=101025#p101025

A possible solution that came up in the forums would be to half food need in the first X lets say 10 hours of play. This would give lot more time for them to learn and reduce frustration.

Additionally generally a mechanic that allows a "starving state" state between dead and fully healthy would be great to have. In this starving state your movement speed would be halved, but also your food need. Ideally this state would be some seconds before the hungry emote comes, so people are encouraged to eat before the hungry emote shows up.

**Comment by TwistedHBG** [comment]
+1

**Comment by Arcurus** [comment]
I look forward to your video Twisted, i guess its racing with a sport car through towns with tons of dying noob babies....

**Comment by Arcurus** [comment]
by the way,  setting the starting gene score for new players to zero or something very low would be more realistic and also encouraging to see an increase not decrease in the beginning.

**Comment by Arcurus** [comment]
another thing, that could help, that new players wont eat up all the food could be the following:

Only if you are in the starving to death state with half speed you can eat 2 pip or less meh food. But if you eat while in this starving to death state, it gives one more pip.

**Comment by DougLefelhocz** [comment]
Slower speed when starving would be a death sentence.  All of a sudden, when you needed it most, you couldn't reach the food that you needed (or knew how to eat)!

That said, the idea of some indicator before the starving tongue isn't a bad idea.  It just shouldn't be something that makes it harder for the player to eat.

There also is already a chime for starvation, and a visual indicator for it.  Perhaps it's not well placed being in the corner of the screen though.

**Comment by Arcurus** [comment]
@DougLefelhocz slower speed would be balanced with more time to life. so the chance to survive as individual is same, but there is an higher chance that some one else can help you.

Maybe its even fine to make speed reduction only x 0.8 and food use x 0.5 so you would "save" some food in starvation mode, but have reduced life quality.

By the way Jason, please fix the mushrooms, its no fun to get stuck for one hour on craving mushrooms when you need it most to build up the eve town for all the noobs. otherwise cravings are useless for the first hour... and that is when you need it most....

**Comment by DougLefelhocz** [comment]
> By the way Jason, please fix the mushrooms, its no fun to get stuck for one hour on craving mushrooms when you need it most to build up the eve town for all the noobs.

I know I made a Github [report](https://github.com/jasonrohrer/OneLifeData7/issues/872) about that.

**Comment by Arcurus** [comment]
> I know I made a Github [report](https://github.com/jasonrohrer/OneLifeData7/issues/872) about that.

me too 👍  [report](https://github.com/jasonrohrer/OneLifeData7/issues/842)

Maybe it would be possible to postpone biome locked stuff and mushroom craving to gen 10 or so.

Its just currently all the time you are stuck on mushrooms, never had recently a live where i was not stuck on it. I even stopped looking at the craving at all at one point.

**Comment by jasonrohrer** [comment]
Food decrement rate was reduced dramatically, and the "eating cost" that creeps in over time was turned off.  I think that this helped with the "frantic" feeling quite a bit, and a brief tour of the world just now showed some thriving villages.

I also added some server code (not live yet) to make the game easier for new players.  They burn food more slowly, and have an extra eating bonus, that wears off the longer they play the game (half life 10 hours of total playtime).

With the update this week, these "new player help" settings will be enabled, and the original settings will be restored (so experts will still need to balance their food carefully, but new players will have more cushion time to learn).
