### ISSUE TITLE
The property fence mechanic is more complicated then it needs to be...

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#673]
Why not allow with a tool (sharp stone) somebody to put down a property fence. Once hit with the tool, the fence could go into an "damaged" state, that allows it to be removed after 5 minutes passed (it goes into Shaky Property Fence). The "attacker" of the fence would be made kill able for some time same way if he attacked some body.

The owner of the property and the leader of the owner of the property could get a message that some one tries to put down his property.

With above mechanics in place we could simplify the fence mechanics and by default let property fences not decay anymore, which would make them much more useful.

**Comment by Arcurus** [comment]
More ideas how to improve property fences:

by the way i know it can be tricky to implement because of pathing but auto open / closing gates would be great to have (like spring doors).

Further the "you own this" command could be restricted to be used only by the main owner. Also the main owner should have a command to remove ownership. Alternative add an "you can use this" command that gives only use rights but no ownership passing rights.

A command "village owns this" could be added  to allow all the allies to use it. Of course for that to work the allies mechanics would need to be changed, that there is a grace period for "outsiders / not yet allies" that join and the leader is informed about it, so that he can exile or approve.

**Comment by Arcurus** [comment]
same system like described above for property fences could also be used like for an engine on an well. It goes into an state where it cannot be removed unless hit by a tool like described above. If so after 5 minutes it can be removed. Like with fences, "attacker" would be killable and leader gets an message.

Same could be used to reduce sheep killing griefing (the last two sheeps)....

**Comment by jasonrohrer** [comment]
The problem with auto-open is that other people could sneak through, I think.  I'll give it a try, though, and see how it feels.

There are already commands to pass ownership to your family or offspring (MY FAMILY OWNS THIS and MY KIDS OWN THIS).

I don't think it's such a problem to repair a fence once every two lifetimes.  If people really want to have it around, they will take care of it.

**Comment by jasonrohrer** [comment]
Oh, I found the problem with auto-open gates...

The spring doors work by automatically opening and then closing after some time has passed.

If you open the spring door manually, it also closes after some time has passed.


With gates, sometimes you want to LEAVE it open (to let other people through, or make an area public temporarily.

Maybe there would have to be some way to "prop open" a gate, if it automatically opened and closed.

But in general, it feels less secure to have it spring open like that.  I don't envision property fences being used for "casual" spaces that you go in and out of constantly.

They are meant to lock up something valuable.
