### ISSUE TITLE
Racism in the Game

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#675]
There exist a bunch of reviews pointing this out, as documented in a comment by [DestinyCall](https://onehouronelife.com/forums/viewtopic.php?pid=101095#p101095).

Players are expected to do things like provide cactus fruits, bananas, make an oil rig, get latex, etc. based on their race.  Such is NOT family specialization, since it's not based on family.  And the game discriminates characters based on their race.  Often times players just dump race restricted items outside of a desert into badlands, as I've seen streamers do.  It is no hero's journey.  It is just the tale of someone who never had a choice in life, because they were artificially limited in what they can do, because of their race.

**Comment by DougLefelhocz** [comment]
Also, in the other issue I had said that:

> In a recent video as an Eve Twisted ended up craving a cactus fruit as a ginger. He wasn't able to satisfy the craving ...

Jason, you responded by saying:

> This is working precisely as intended.

> Twisted's character has a quest: to go find a desert village and recruit them to help gather cactus fruit (maybe in exchange for oil). Then Twisted can bring the fruit back to his village and satisfy everyone's craving. He will be a hero.

No, he won't be a hero.  As the ending screen to every life makes clear with it's "you died", his character is dead.  Reincarnation doesn't create that same scenario over again for the player, and can't do so.  

Also, if it were working precisely as intended, there would have existed success instead of failure in terms of satisfying the cravings, or *an attempt* at success, instead of not caring on Twisted's part, because the craving suggestion just wasn't reasonable.

Exchange for oil for cactus fruits from what I've seen is frankly horribly unrealistic.  Horses get put into the badlands en masse.  Palm kernels end up dumped in piles.  The only report of players trading that I am aware of comes from the first week when such restrictions existed.  How in the world is such a system encouraging trading if it's simple not happening?

Also, the original purposes were described [here](https://onehouronelife.com/forums/viewtopic.php?id=8377)

No, it does NOT work as family specialization as intended.  It isn't specialization based on a lineage, but rather on race.

No, it does NOT 

> ... partially model a beautiful facet of the real world, where different people from different areas specialize in different things

and never did, because OHOL people all have the same biomes that they live in the first place, in effect meaning that they live in the same geographical area.  

It just models how people stereotype real people into different groups without considering them as individuals.

**Comment by Arcurus** [comment]
at least biome locked and mushroom cravings should start after some generations. Its not realistic that an eve generation has time to travel to fulfill a biome locked craving or look for some village that has already mushrooms.

**Comment by jasonrohrer** [comment]
This is working as intended.

A craving is a bonus.  It may take several generations to fill it.
