### ISSUE TITLE
Tutorial Has New Player Trap in Teaching Berry Munching

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#676]
Since this [issue](https://github.com/jasonrohrer/OneLife/issues/668) was closed apparently with no changes, nor notes about upcoming changes, I'll try to explain this again.  Note, this WAS an issue before the recent sale this weekend and before new player settings were planned to get implement.

It's not recommended to eat berries until one is full even when moving about in the wild.  Experienced players will tell you that it's better to eat a variety of different foods, that way one can increase one's yum bonus earlier, and one has more potential for more yum later on.  One can't increase one's yum if they are full.  Eating until one is full as a child is not recommended even while yumming, because of food waste, and there is no explanation of how food waste works depending on one's age. 

The difficulty is particularly pronounced in a later generation family if players has a deficit of at least 6 pips and is in the wild.  Eating until one is full, can mean that the entire bush is consumed.   It's generally recommended to leave the last berry on a bush in case of an emergency, unless watering the bush, instead of consuming until one is full.

In towns the "PICK AND EAT MORE UNTIL YOU ARE FULL" line parallels new players ending up in a town (they often don't understand the difference between a domestic and wild gooseberry bush, and if I recall correctly, no domestic berry bushes exist in the tutorial area), and then mass consuming berries, instead of looking around for other foods or asking other players 'WHAT CAN I EAT?' or trying to cook or grow other types of food.

Since most players first get born into towns with domestic berry bushes already existing, this means that new players end up consuming berries until they are full.  Then sometimes, as I've seen on stream, they get scolded by more experienced players for eating so many berries at once, as they realize how inefficient that is water and soil wise.

**Comment by Arcurus** [comment]
yea, they learn that and then "in real life" they are attacked for eating berries.... 

i would suggest to change the tutorial to teach eating any other stuff, for sure better then berries...

Also we should redesign generational food reduction. If cravings are proper done for early villages, we could just generally have lower raw food values plus we could give more bites / portions to hunted stuff to balance it. Then a berry would always be the same food value of 1 and all bushes in the paradise tutorial should be destroyed for ever! this is no joke we dont need them there...

**Comment by jasonrohrer** [comment]
Fixed in 04cc1c6d6b2b6a80ac8a283804ed0e3675fd0427
