### ISSUE TITLE
Race System Too Complicated For New Players

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#678]
The (old, not upcoming) tutorial area says near it's start:

> FAIR WARNING THIS WORKS JUST LIKE THE REAL GAME

It also has a stone after a bit which says:

> ... PUT SOME FOOD IN THE BASKET TO TAKE WITH YOU

After that point, it seems that one is expected to carry the basket, until one reaches the area near the snake pit.  Going through it as a Black Eve, to be as sure as I could, I carried the basket through the tundra.  My character did NOT drop it.  Also, no matter one's race there have existed cactus fruits ready to get picked in the desert area in the tutorial.

Later I went in as a Ginger Eve.  The basket I held didn't drop in the desert.  I was also able to pick the cactus fruits.

Both of the above were on bigserver2, on 9/22/2020 and 9/23/2020.

So far as I know, the tutorial has been this way since the race system got introduced.  So far as I can tell, it has not worked like the real game for a server with at least 15 people on it, in that if one was carrying one's basket, one would not drop it based on what sort of dropsy one's character had, and one could always pick the cactus fruits.

In contrast, if I recall correctly, the stones by the desert and tundra areas got changed shortly after the temperature overhaul.

One interpretation of this state of affairs is that the race system is too complicated to explain to new players.

**Comment by Arcurus** [comment]
the current biome implementation is not only too complicated for new players it is not logic.

Dropping stuff in another biome is not how our world works. 

In our world the main difference is the skin color, which is mainly related with sun protection (black) vs more vitamin D (white). Everything else is more a cultural adaption if you live long enough in the same area.

I would suggest to drop the dropping of stuff and instead give some boni, like if a jungle person picks a banana he has 50% chance to get another banana. And if it is not your biome the movement speed is 80%. Jungle people may be more resistent or even immune to mosquitos.
