### ISSUE TITLE
 Massive abuse by Griefers - possible solution better property fences and efficiency of curses

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#682]
For more information about the griefing and the frustration of the player base since defense against it is currently quite bad see here:

https://onehouronelife.com/forums/viewtopic.php?id=10114

Possible solution better property fences:
Currently the effort to fence everything is quite more harmful then its useful. We had it at a time with fenced berries, such a pain.

The fences could be implemented better. Like auto open / closing doors and a possibility to remove one from the access.

A fence around the village with auto / open gates which all allies by default have access could work to stop big part of griefing. 

With exile you could then remove one from having access and since the doors are auto opening / closing you wont waste much time passing them.

So to stop a griefer you only need to exile him. then he is either trapped inside or outside the fence. Inside it should be quite easy to kill him once he is exiled...

Also curses could be improved:
After receiving X curses in one month, your speed could be reduced up to 20% - the more curses you got the less speed so you would be easier to kill and your ability to curse could be removed too. Also you could become by default visible as cursed (just with the color, not with the name) so that you know its not one you cursed.

Curses should also be changed from:
I dont want to play with you to: I dont want to play with you and i want this family protected from you.

this could be done by counting curses you got from this family 5 times for above (speed limit and visibility as cursed / chance to incarnate in this family).

**Comment by Arcurus** [comment]
To balance above curses there could be also some automatic "blessings". A blessing could be if you have been proper buried with a grave stone in this life and you lived at min 30 years.

So the curse count could be something like: curses - blessing + InThisFamily (curses - blessings) X 5

**Comment by jasonrohrer** [comment]
The new ally auto-gates (with exile by leader to instantly block someone from gate) should help with this problem a lot.  Will revisit in the future as-needed.
