### ISSUE TITLE
Car Serial Number changing

### ISSUE THREAD

**Issue by AcorpBG** [jasonrohrer/OneLife#683]
I have found that car numbers are changing
Example in the logs
`68151.55 -76422 44 4684v12 3339761`
`68172.37 -76422 44 0 3339761`
`68439.57 -76728 -119 4684v13 3339761`
After a lot of tries to reproduce the bug I found the reason.
Every time you do a roadkill with the Sports Car the number is increased.

**Comment by jasonrohrer** [comment]
Nice find.  Will check it out.
