### ISSUE TITLE
Horse Exile Terrified Glitch

### ISSUE THREAD

**Issue by Lava6** [jasonrohrer/OneLife#684]
For some reason when you exile someone as leader and make them terrified, they are STILL able to go on horse. I tried this yesterday on a friend while I was leader, I exiled her and chased her with bow and she was able to get on horse while terrified. You drop most items when your terrified but you somehow don’t drop the horse.

**Comment by Arcurus** [comment]
Interesting. Do you need actually now a posse to make some one terrified or is exiling enough?

Dropping the horse seems quite harsh, since he wants to escape, but maybe make it slower if he is terrified? And give the ability to hit one down from the horse...

**Comment by jasonrohrer** [comment]
Exiling reduces the required posse size to 1, usually.

So the person becomes terrified if there's even 1 person with a weapon chasing them.

Will check out the horse glitch, thanks!

**Comment by jasonrohrer** [comment]
Weird, I can't reproduce this on my end.

If you're on a horse, and terrified, you hop off.  And you can't get back on while terrified.

Assuming it was a one-time glitch, or a confusion of timing or posse size.

If you can catch this on video, please re-open.
