### ISSUE TITLE
Forced to spawn in wilderness tutorial area despite normal tutorial completion

### ISSUE THREAD

**Issue by bpskotch** [jasonrohrer/OneLife#685]
I was attempting to have a friend join me on a low population server, preferably born to me but could also help them get their eve to me if needed. Any spawns attempted resulted in an eve, which after checking with expert waystones, occured over 5m tiles out east. I checked their waystone when they did normal tutorial, and it was roughly the same positioning, leading to my conclusion of wilderness tutorial.

To verify that it was just not a stray eve spawn location, I had another person join the server, and their eve spawn was only 400 tiles northwest of me, which was completely normal.

My friend verified that they took the shortcut exit on tutorial, taking the door south and lighting the torch, then suicide via snakes. Yet somehow, they are bugged into the wilderness tutorial spawns. I am presuming that the game may be coded to require wilderness completion before normal spawns, but I could be incorrect.

**Comment by FeyFre** [comment]
Not a bug. There are 2 tutorials. You have to pass both (even quick pass).
1st tutorial (old one in building to light the torch) quick pass is 'door south' torch+snake suicide.
2nd tutorial (wilderness, survive until 60 years) quick pass is 'door east' torch+snake suicide.
Your friend haven't done 2nd tutorial neither properly, nor quick pass.

**Comment by Arcurus** [comment]
i wonder how many people are stuck now in the wilderness tutorial?

**Comment by DougLefelhocz** [comment]
Did your friend keep on clicking on the 'reborn' button?  Or did they use the 'login' button?

**Comment by bpskotch** [comment]
As Feyfre stated this was not a bug, it was a misunderstanding on my part on how this new tutorial works. Friend was completing original tutorial but did not complete second one, didn't realize it was mandatory. Closing this.
