### ISSUE TITLE
New ally gates seem to work only for your followers not your allies

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#688]
Currently you need to give the leader ownership that the gate work for allies.

Same happens also if the leader follows some one else and makes him leader.

A solution would be to give the new leader ownership or alternatively make the ally gate to an ally gate and not a follower gate.

Additional the open state should close after max one minute, otherwise people forget to close it.

There is also a problem with usability of fences in general. They decay much too fast to be a consideration for a bigger town fence.

A possible solution:
- Instead of 60 min let the property fence go into rickety state after been hit with a sharp stone or an axe 
- the rickety state can then go into Shaky Property Fence after 5 min. 

Above would make the fence only decay if one wants intentional to remove the fence.

There is also a "bug" with the ally system, that an foreigner can become ally without approval.

Some one reported also, that any follower can knock the ally gate down (more details see below the link to the forum post). It should be only possible for the leader...

**Comment by JustinLove** [comment]
Confirmed in code. It walks up your leader chain to see if any of them own the gate. It's a follower gate, not an ally gate.

**Comment by Arcurus** [comment]
thx for looking it up

I guess it would work to give the top leader automatic ownership to the ally gate once build.

By the way, with currently the outsiders being as hostile as insiders, it may be more logic by default deny only access to exiled once.  Maybe a command like exile / redeem all families could help to set how outsiders are treated?

**Comment by Arcurus** [comment]
Here more from the forum: https://onehouronelife.com/forums/viewtopic.php?id=10172

"A member of a black family can ride into the town of the ginger family, follow the gate owner of the fenced in area, destroy the gate with an axe and can take the valuable stored in it.

Anyone who follows the gate owner can destroy the gate"

**Comment by jasonrohrer** [comment]
Yes, will change the name of the object to "Follower Gate".

The fact that anyone can follow you is kinda part of the point.  People can go in and out freely, but you can exile people to stop them.  I mean, someone can be born into your town too, and they will auto-follow you.

The problem of them destroying the gate is an interesting one...  thinking about that.

**Comment by DougLefelhocz** [comment]
> The fact that anyone can follow you is kinda part of the point.

So if someone decided _by their own self_, requiring no consent from you, to follow you in the real world Jason, they could break into your house _legally_ and steal your *or your families* possessions?  Or if someone decided to follow a political leader by their own self, requiring no consent from the government, they could _legally_ steal anything locked up in a vault that the government had stored away?

And so what if anyone can follow you?  That doesn't mean that such a person is trustworthy to have access to your family or friends objects.  One would hope that players would have to *earn* such status and access.  

And NO, I don't think that anyone can follow you was the original reason.  I think they were called ally gates for a reason.

**Comment by jasonrohrer** [comment]
The follower (or ally) gates were not meant to simulate personal property.  That is what the regular gates are for.

They were meant to permit exiling someone from an area.  That is all.

So you build a fence around your village, and let everyone in, but then you can exile someone when the need arises.

Like the gate at Disneyland.  Everyone can come in, but if they kick you out, you stay out.

If you want to have someone "earn" access, then use regular gates.  You want fine-grained control over who can come in?  You already have that.

Follower gates are meant to solve a different problem:  where you do not want fine grained control (you don't want to hand-approve everyone), but you do want to be able to block someone in the future.

This is the way Discord and many other services work.  Everyone is allowed in by default, but there is a way to remove trouble-makers when the need arises.

**Comment by DougLefelhocz** [comment]
> The follower (or ally) gates were not meant to simulate personal property. 

Nor did I assume that they were.  I included talking about your families possessions, and talked about the government.  Neither of which involve only one's own personal property.
