### ISSUE TITLE
Normal property gates are working like Ally gates.

### ISSUE THREAD

**Issue by AcorpBG** [jasonrohrer/OneLife#689]
Normal property gates are working like ally gates, whenever leader own a property gate(normal one) all his follower get access to the gate, the sprite is the same as normal gate no skewer was added to it. 
Can be reproduced everytime.

**Comment by DiscardedSlinky** [comment]
I've been experiencing this aswell. I've been able to open every gate I've seen despite it not being an ally gate. I saw a truck get stolen last night because of this.

**Comment by jasonrohrer** [comment]
Yikes!  Fixing this.
