### ISSUE TITLE
Iron System Needs Reworked

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#691]
Playing on a low pop server a few months ago, I tried once to get to an engine on just one iron vein.  After the mine exhausted, I realized that I wouldn't make it.  No doubt, in the larger population context, one iron vein wouldn't suffice to even make one engine for a family.

I've also scouted looking for at least two veins on low pop servers a few times.  It requires at least 80 tiles of travel, even if born near a well site, and though I usually make the three primary tools first, my estimate is that I'd be lucky to have a found a spot with two veins by the time I'm 25.  That's not even considering finding a spot with clay locally.  And I've been doing this using a mod with a zoom feature.  This sort of running around just doesn't work well with Eves trying to feed all of their children, especially during a server restart, and after a server wipe even more so, where the 4 child per mother limit doesn't apply, right?

A day or two days ago I end up in a family and end up checking in both directions for iron.  There's one vein.  No doubt that family got plenty of iron/iron based resources from locations where no one lives any longer.

After that I ended up in another family, where I end up going right along the well fault line looking for veins.  The second or third spring has stakes pointing southeast.  So, I follow them and end up mining in some location by some location with no one around and a shallow well.  It's not that unlikely that it took me longer to get to that spot than traveling around did under the old iron system.  It was also more dry, since it was more predictable, and involved less time scouring the badlands where wolves or bears might show up.

Today I got born as [Pota ](http://lineage.onehouronelife.com/server.php?action=character_page&id=6663963).  We were on the edge of a swamp in a grassland.  There was a ready well site.  Alright, so my "mother" had trouble feeding me.  

I logged back in, hoping to go to that place and help out, and was [Alyssa Tear](http://lineage.onehouronelife.com/server.php?action=character_page&id=6664119).  I eat some in town and then get moving left, find a desert, and head to the new black family.  I end up finding a horsecart, and then also a spot with no one living there, and import some things to the blacks.

I don't see any iron on the right side of the fault line of the ready well site.  I talk to some man in town and he says he didn't find any iron far around.  I did look some on the left side of the fault line of the well site, and it didn't seem like any iron existed on that line also.  So, I end up exploring, and then convince blacks to move to another site where several muddy iron veins are on the same fault line.  Swamps seemed kind of far.  When the well site got made though by some member of the Choi family apparently, no iron got unlocked from the veins (though maybe some iron got recovered there later by someone else?).

The iron mechanics aren't also likely to get picked up by new Eves, in game especially, and others on the discord have said that "pros" are mostly making sites first and then moving people in later.  The current iron system involves substantial running around in the early game, instead of more or less just setting up locally as once was possible.  I'm not arguing that complete reversion to the older system would be ideal, but the current system seriously needs reworked or abandoned in favor of something else, so that Eves aren't likely to abandon their "children" for rational reasons and so that it's possible for families to get resources, instead of dying out, because of, from their perspective, who knows why?

**Comment by DougLefelhocz** [comment]
Addendum: Next life I got born as [Berry Tear](http://lineage.onehouronelife.com/server.php?action=character_page&id=6664537).  The black family that couldn't do much in another spot due to an iron issue and had resettled a town that I had played in earlier.  The mines on the fault line had collapsed, so I just found an abandoned town south and mined from their fault line.

**Comment by DougLefelhocz** [comment]
I played as [Justine Burns](http://lineage.onehouronelife.com/server.php?action=character_page&id=6668148).  The pump's fault line had either sunken iron veins or dry springs.  I ended up taking iron from the fault line of a dead settlement.  Others had brought in iron during my lifetime also from somewhere off their fault line.

**Comment by DougLefelhocz** [comment]
Also, there's another thing which goes on, which one might call The Ginger Delivery.  Basically some ginger(s) will drive up to a town with an engine or two, some crude tanks of oil or refined kerosene, and then put them in some property fence.  Town might be on a shallow or deep well.  This is very strange in a game that is about rebuilding from scratch in a group context.

Awbz told me that while playing Terraria, he'd often encounter players throwing advanced sorts of objects where he was, with things that one shouldn't be able to get at that early.  The Ginger Delivery is probably something that a player like Awbz would not enjoy.  

But, it's hard to rationally put blame on players for taking part in a Ginger Delivery since with the current iron system, The Ginger Delivery can be necessary for a town/lineage to survive.

**Comment by DougLefelhocz** [comment]
I played as [Pepper Jobbins](https://github.com/jasonrohrer/OneLife/issues/691).  The town was midway through a charcoal pump (at least, I don't think it was kerosene pump).  There was an engine in town with tanks of kerosene there.  Someone ends up using that engine and the kerosene to get iron.  

My questions are, did that location even have enough iron to make an engine in the first place if they had started from scratch?  And how did that kerosene end up there?  It's likely someone just threw tanks of kerosene there.

Also, let's even suppose that the person decided to mine iron using kerosene and a chisel, to avoid hungry work (which can be annoying, because one has to stop after each use of the mining pick).  I'd guess that hungry work on iron mines got motivated in part so that miners would be more likely to value food more, and thus have a better link with the food system at home.  Also, so that they value the food content more than before hungry work on mines existed, right?  But any expected advantages that hungry work is supposed to result in for a player at the stage of a newcomen pump, aren't all that conceivable if one's mining strategy is to just use kerosene.

**Comment by DougLefelhocz** [comment]
So, after I played with the white family (Stars, I think) as Dhiya Rose as described [elsewhere](https://github.com/jasonrohrer/OneLifeData7/issues/895), I check the onehouronelife.com before I log in and guess that the Stars had died out. I got born as [Jace Alon](http://lineage.onehouronelife.com/server.php?action=character_page&id=6685678), and start running left.  I get 2.8k for the white family at one point, and then find a horse cart.  I manage to find the Eve, [Eve Pickens](http://lineage.onehouronelife.com/server.php?action=character_page&id=6685654), and she has 9 stones on a natural spring.  I scout along the ley line in both directions, and there's ONLY ONE iron vein.

I come back to her well site, fed her as she almost starved, and move the rocks off of the natural spring with 9 stones on it.  I find another spot and lead her to a spot in a swamp, which has at least two iron veins along the ley line (arguably, I'm cheating, because I'm using a horsecart).  I bring her stones, place them in a pile, and she places them on the natural spring.  NO IRON got unlocked.  I guess someone else had completed the well site elsewhere?  Her last words 'prolly' were, I think, a response to me asking her: "I guess someone else completed the other well site?" or something like that.  But, when I went back and looked at that natural spring, it was dry.  I didn't think of it during my life, but did I mess up their well sites entirely by removing stones from their original natural spring?  Edit: There was 4 iron at the single iron vein along ley line where the Eve had placed stones.  But, the corresponding spring was dry.  And the other spring said (which didn't unlock any iron) "Pickens family well site" or something like that.

If someone like myself who bought the game in December of 2018, follows the updates, experiments with it in a relatively relaxed environment, has this many problems with it, I have to wonder how much worse it is for players being an Eve this first or second, or probably even 10th time.

**Comment by DougLefelhocz** [comment]
Also, I found this [old forum post](https://onehouronelife.com/forums/viewtopic.php?id=9412).  

I quote:

> I played 3 days on an empty server to learn on my own a diesel engine and all the stuff to get there + oil. (unlucky 7 pipes to brake the oil open big_smile or is that normal? idk i never done that before) i only mined one mine from scratch. after i had kerosine i had clearly 0 iron left. i done only to must have to my town so i havnt biuld many tools + i hadnt biuld newcommen well. 

Since one mine won't work on a solo play server in some cases, how can it work with a similar variance of iron from the mine on bigserver2?

Basically, plenty of families these days are NOT rebuilding from scratch.  They often loot from dead towns.  This is NOT families earning their engines or oil rigs as they once did.  The iron system, things like The Ginger Delivery, makes this sentence from the steam [advertisement](https://store.steampowered.com/app/595690/One_Hour_One_Life/) ridiculously bad:

> Leave a legacy for the next generation as you help to rebuild civilization *from scratch* [emphasis added].

**Comment by DougLefelhocz** [comment]
Someone on discord made the following comment:

> so i just got a taste in just how close you cut it with only 1 iron mine for a family
if youre pumping oil yourself, and making your own engine. everything from scratch
had only 6 iron remaining, never even made a single hoe, and only multiple i made was pickaxes to clear the mine

I talked to this person some more and she told me that she did NOT make a charcoal pump or tanks for using that charcoal pump (at least 4 iron).  She did make shears.  She did make multiple mining picks.  She did NOT make replacement tools: only one axe, and one shovel.  She says she thinks she made scrap metal twice, but didn't need the second.  On bigserver2 there would likely exist replacement tools made, along with a few steel holes, and maybe an extra chisel, adze, or froe also.  

Maybe the average numbers look alright and are not buggy, I don't know.  But, there's also the variance.  And the variance looks rather bad, even if the average is correct.

Edit: I talked to her some more.  She got her oil rig to gush on the first pipe!  Her town would even be more short of iron if on bigserver2 than the above suggests.

Edit2: She shared with me a picture of what her camp [looks like](https://cdn.discordapp.com/attachments/767443153556734003/767746362304757800/unknown.png):

**Comment by DougLefelhocz** [comment]
Playing as [Michael Winter](http://lineage.onehouronelife.com/server.php?action=character_page&id=6700343), I went and helped out the [Castles ](http://lineage.onehouronelife.com/server.php?action=character_page&id=6700309).  I did check the full 160 tiles in both directions, and they had but one mine on their fault line.  Someone was using a truck, but without enough iron for a family to make their own engine, such a family having the ability to rebuild from scratch is out of the question.

**Comment by jasonrohrer** [comment]
On the main servers, not having enough iron (because of a bad choice for the primary homeland) should motivate trade, so that's fine.

On low-pop, I'm guessing that most players are more experienced, and that they will choose their primary well sites carefully.
