### ISSUE TITLE
Can't find ingame recipe for a net.

### ISSUE THREAD

**Issue by Keriew** [jasonrohrer/OneLife#692]
Usually you can get instructions on how to craft an item in the game by typing /[name of the item].

However, /net is a special command that displays the connection details.

**Comment by Arcurus** [comment]
please give us the in game graphical crafting book like 2hol has. For sure it would solve this kind of problems and still would be ages better then using an external website or the current very unpractical ingame crafting guide (stopped it using ages ago). And also beauty wise ages better then the current text based system.

**Comment by DougLefelhocz** [comment]
> please give us the in game graphical crafting book like 2hol has.

Of course, this isn't meant literally, but a similar graphical crafting book.  Also, this comes from a modded version of Hetuw mod and isn't part of the default 2HOL client.  As the saying goes, a picture is worth a thousand words.  A graphical crafting system would help new players a lot.  As nice as it can be to explain things the hard way at times, many, and probably most of them won't ask questions, and time is fleeting.

**Comment by JustinLove** [comment]
Workaround: leading space, "/ net"

**Comment by jasonrohrer** [comment]
Yeah, /net is a funny one for sure!

**Comment by jasonrohrer** [comment]
I'll change it to /network to fix it.

**Comment by jasonrohrer** [comment]
Unfortunately, this is a client-side change... fix won't go live until I return home, probably more than a month.
