### ISSUE TITLE
When parking van in small biom bordering inhospitable biom it's possible to get locked out of van.

### ISSUE THREAD

**Issue by daftfader2006** [jasonrohrer/OneLife#694]
When parking van in small biom bordering inhospitable biom it's possible to get locked out of van even when it's on accessible tiles. Due to the fact you can't stand on the same tiles as the van, if you park the van in a small patch of biome that borders a biome you can't carry stuff in on the side you normally get in the van from, it stops you entering the van, even though the van is in a "good" biome as you are forced to walk into the "bad" biome to get to the side of the van the games wants you to be on.

I'm not sure if this is intended behavior (I know you changed it before to stop people hopping fences into a van - so maybe an unseen side effect of this?), but it doesn't seem right to me, if you park it on tiles you can pick up stuff on, you should be able to get back in your van, even if it is bordering with a biome you are not able to use.

**Comment by daftfader2006** [comment]
Here's a screen shot of the scenario outlined above

https://steamuserimages-a.akamaihd.net/ugc/1662350611264294124/88A757364020C01581123CB2B73D10966E39BD0B/

You'd clearly assume you could park here (as I did), but nop.

**Comment by daftfader2006** [comment]
sry this was meant for the main onehouronelife game, this is the first time I've used github for this game, so thought this was the right place! maybe you can move the thread jason?

**Comment by jasonrohrer** [comment]
Yes, I see the problem here.  The van blocks walking, and blocks you to the left of its location, so that's why you have to enter the van from a particular location (so you don't "walk through" the back part of the van in a weird way).

Not sure how to fix it, but I'm looking into it.

**Comment by daftfader2006** [comment]
I'm not sure if this is possible with it being a topdown 2d game, but maybe
you could walk along the front side of the van on the same tiles only once
you have clicked to enter? (like an animation, you're considered already in
the van once you reach it or something). Or would this have it's own
issues?

**Comment by jasonrohrer** [comment]
Figured out a way to stop you from setting it down in that kind of location.

**Comment by daftfader2006** [comment]
That works,a quick and simple way to deal with it too. Thanks! I was so sad
when I lost that van haha.
