### ISSUE TITLE
Race Restrictions Confusing For New Players

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#696]
I watched a Twitch streamer named Sans596.  On his second or third life where he did not use /die, as a ginger lady, she (his character) walked into a jungle and tried to pick a banana.  Soon enough she got bite by a mosquito and shortly thereafter died while still in middle age.  It was remarkably similar to what I saw happen with [thomasgovens](https://github.com/jasonrohrer/OneLife/issues/679).

There is no explanation of how race restrictions work for new players in the tutorial.  And no jungles.

As things stand right now, race restrictions may well setup new players for failure.  One might even wonder if it's possible for them to succeed in such a situation.

**Comment by jasonrohrer** [comment]
All they have to do is ask someone in their village:  why can't I pick a banana?

Also, it's not like there is absolutely no feedback.  When they step into the jungle, they get sweaty, red, and make a noise.
