### ISSUE TITLE
Any Tech Tree Doccumentation?

### ISSUE THREAD

**Issue by ryanpeach** [jasonrohrer/OneLife#7]
I would like to generate a .dot file, or maybe a dash application, with a tech tree for this game, and I would like to do so by scanning some file with a python script which contains the x + y = z documentation in the <Tab> window. Where is all that stuff?

**Comment by jasonrohrer** [comment]
It's in the transitions folder in OneLifeData7

A + B is in the file name.
C + D is inside the file, along with some other numbers which specify flags on the transition.

Also, some file names have some other flags and stuff in them.

You may need to look at gameSource/transitionBank.cpp source code to really make sense of it.

**Comment by ryanpeach** [comment]
Great, thanks! I'll have something working soon.

**Comment by ryanpeach** [comment]
If you're interested:

https://github.com/ryanpeach/OneLifeData7

Just run main.py after installing dependencies:

```
pip3 install -r requirements.txt
python3 main.py
```

**Comment by ryanpeach** [comment]
I don't have a full working understanding of your transitions. I'm assuming that if the filename is a_b*.txt and has the numbers "c d e ..." in it then a + b = d. Anything more complicated and I'll work on it later.

I ignore ID's 0 and -1 for graphing purposes. Maybe later I'll add "number of each item needed" to the edges as weights.

This could easily be turned into a website with some polish.

What is c?

**Comment by jasonrohrer** [comment]
A is the actor, B is the target  (actor is what you're holding in your hand, target is what's on the ground)

C is the new actor (what's left in your hand)  D is the new target (on the ground)

**Comment by ryanpeach** [comment]
Thanks, I may add those descriptions to the edges at some point.
