### ISSUE TITLE
Leadership Gets Inherited Outside of Homeland/Too Far Away

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#700]
I've traveled to other towns a few times, mostly after checking the onehouronelife.com and finding a new camp.  In my recent life, as [Dhiya Rosa](http://lineage.onehouronelife.com/server.php?action=character_page&id=6685227) to an Eve camp of whites.  In a way, it's sort of like overcoming racism at an individual level, or at least I suppose one might think so.  I got told that my family was restarting the town, which spreads families out more and isn't rebuilding from scratch (me traveling with clothes and leaving them at a new family is closer to rebuilding from scratch than resettling an old town).  So, it sounds even more suitable that I left home.  

The issue is though, I ended up inheriting the leadership position I think in my 40s, and this isn't the first time something like that has happened.

The problem I see here is that since I've become the leader for my family, there's a sort of power vacuum going on at home.

Or, I suppose whoever is at the top of the hierarchy at home should probably be easily recognizable.

**Comment by jasonrohrer** [comment]
The people there can pick a new leader if the "auto" leader is too far away.  This is working as intended.
