### ISSUE TITLE
Closeness of Families Impossible to Make Consistent With Rebuilding From Scratch In A Persistent World

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#702]
I've seen trucks come into camps still on a shallow well.  I've seen kerosene tanks and engines in towns on a deep well.  Those objects are not a result of the family's efforts.  Nor were they traded for.  Biome changes won't change this sort of situation either.

Even if such resources had gotten traded for, it wouldn't be all that interesting either.  In one life, after talking to other players using Hetuw chat about the Ginger's rubber situation (I think I was a Burns) with the town on a charcoal pump, I drove to a brown's town using a racecar with a tank of kerosene in it (the racecar there is already a signal of things being far away from rebuilding from scratch).  I got informed by the players there that there wasn't anything they needed.  They put some sulfured latex, and palm kernels in a rubber tire horsecart.  I talked to them and said I'd leave the car and take the horsecart and even asked "deal?"... I think both on paper and using Hetuw chat (I used paper, because one player didn't have Hetuw mod).  I probably didn't need to bring the tank of kerosene even.  I got a response of "deal" in Hetuw chat.  Such lead to thoughts like "the price of something is whatever someone is willing to pay for it" and "a sucker is born every minute", neither of which are all that interesting.  They are more like sterile truisms.

Rebuilding from scratch with other players in contrast feels empowering as a gamer.  Rebuilding from scratch is also how the game gets advertised on Steam.  Rebuilding from scratch is also what new players would have to do were the servers ever to become full.  Trading isn't how a group of mostly new players would go about developing towns were all of the servers ever filled with players.  There wouldn't be enough time for that, and instead there would be looting... which takes gameplay further away from rebuilding from scratch.  There would be gifting, which can and often does also take things further away from rebuilding from scratch also.

It also does not take all that many players to gift or loot resources so that rebuilding from scratch becomes impossible for the group.  Closeness of families along with how human psychology works ensures that such will happen, and thus rebuilding from scratch gets drifted away from substantially, if not becoming meaningless.  It is simply not possible to have families close, no way for players to rebuild from scratch by their own choice away from other families, have a persistent world, and game play work out that players can rebuild from scratch.

**Comment by DougLefelhocz** [comment]
I played as [Sunshine Neger](http://lineage.onehouronelife.com/server.php?action=character_page&id=6704617).  The camp was on a shallow well and had _grown_ maple trees.  The Eve, who was alive during my life, had found a starting camp.  At one point someone comes along with a truck and starts throwing backpacks and clothing by the fire.  Later, since he was brown, he made a few complete stacks of bananas in town.  I read a map at some point, and my final words were: "Spare iron mine one more to west of this point and one more east".  The arrow pointed *up* not along the ley line of our well.

Players are using trucks to import resources to families that haven't earned anything like a truck, because of race restrictions, closeness of families, the pip drain rate, the iron system, and probably much more.

_I do find in-game evidence of some players wanting to rebuild from scratch, as I have found kilns on bigserver2 out in the middle of nowhere with a fire bow drill, stone hatchet, and maybe a little something else, but little to no crops grown._  Also, some people still come to the reddit or discord wondering how they can play as Eve.

The game is rather far away from rebuilding from scratch, and unless families get substantially spread out or weekly wipes become the norm, the game's advertisement on Steam can easily get regarded as false.

**Comment by jasonrohrer** [comment]
The video never says "EVERY EVE IS REBUILDING FROM SCRATCH."

It says, "AS WE REBUILD CIVILIZATION FROM SCRATCH, TOGETHER."  As in, all of us, together.

The video also talks about a shared PERSISTENT server.

Thus, there will be stuff that other people built on the server, over time.

We start "from scratch" whenever there is a server wipe.  The last wipe was on October 29, 2020.  We've been rebuilding from scratch together since then.

**Comment by DougLefelhocz** [comment]
> The video never says "EVERY EVE IS REBUILDING FROM SCRATCH."

> It says, "AS WE REBUILD CIVILIZATION FROM SCRATCH, TOGETHER." As in, all of us, together.

> The video also talks about a shared PERSISTENT server.

Well since it's a shared server, with all players having the same objective, fences and city walls don't make any sense at all.  I mean they both contradict the concept of everyone rebuilding from scratch in a collective sense.
