### ISSUE TITLE
Biome Band System Likely Diminishes Some Content

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#705]
Ice cream will only get made near one type of family.

The same holds for tattoos.

Snowmen, like the one I saw as [BB Rabbit](http://lineage.onehouronelife.com/server.php?action=character_page&id=6707226) won't get made anywhere but near one type of family.

**Comment by TwistedHBG** [comment]
The entire point of stuff like tattoos is that they only get made near one type of family.

**Comment by DougLefelhocz** [comment]
> The entire point of stuff like tattoos is that they only get made near one type of family.

That's a very strange to believe Twisted.  Tattoos have existed on a server with less than 15 players on it before, and can happen again.  Also, when tattoos got released, they could get made near any type of family.  So, I don't see how that could have been their original point.

**Comment by TwistedHBG** [comment]
> To go along with these changes, some new content has been added in these biomes, with a new biome-locking feature ensuring that you have to visit those biomes to interact with that content.  For example, you have to visit the jungle in order to get a tattoo, and only a jungle specialist can perform the procedure for you.

Direct quote from the Tattoo update post.

You need to stop spamming stupid nonsense on github. The github is for reporting bugs. If you want to spam go somewhere else.

**Comment by DougLefelhocz** [comment]
> Direct quote from the Tattoo update post.

None of what you quoted Twisted speaks to the purpose of tattoos.  Also, the quote is not correct if it were intended for all conditions, and I doubt what you quoted was intended for all conditions.  Tattoos could even get performed by someone on bigserver2 who didn't have any "jungle specialty".  Did you not undersatand what happened with the last update Twisted and how low pop conditions existed on bigserver2?  Do you not understand or have forgotten what happens during children of men mode and how the player population necessarily gets below 15 players during that time period? 

It isn't too hard to imagine that someone during an update could get start near a jungle with tattoo items prepared.  Heck, since Eve spawning is deterministic and the code is public, someone might even plan to do a tattoo on bigserver2 before 15 players were on it and not be a "jungle specialist".  Or during children of men mode on bigserver2 someone could do a tattoo and not be a "jungle specialist", when there exist less than 15 players on it while the update system is in progress.  And as I write this, the even number servers are offline, indicating that soon bigserver2 will have less than 15 player on it.  Furthermore, it was documented on the discord a few months ago by some players that bigserver2 had 15 players on it at one point around 4:00 - 6:00 A. M. EST.  Within this past month, if I recall correctly, again around 4:00 - 6:00 A. M. EST someone documented that bigserver2 had 16 players on it.  It isn't all that hard to conceive that bigserver2 could have less than 15 players on it sometime during that time period in the future.  And then, some character who is NOT a jungle specialist could do a tattoo.

Also Twisted, since cravings exist I think it's rather clear that all of the food content is intended to get explored by players overtime.  Likewise, I would think that all of the existing content is intended to get explored by players... perhaps even the radio telegraph.  Thus, if the current system has made it more likely that players won't explore some content than they were before, then it is bugged.

**Comment by DougLefelhocz** [comment]
On the other hand, it seems like some things like sealskins are easier to get now.
