### ISSUE TITLE
If one becomes a follower he could open the follower gate and allow others also in at once

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#706]
Wouldn't it be then better to only allow the owner to manually open the
gate? Since the only reason to open it is to let an exiled one out...

**Comment by jasonrohrer** [comment]
The point of these gates is to generally allow everyone in, unless someone ends up being a problem.  Then you can chase them out and prevent them from ever coming back in again.

If the owner had to manually open the gate, that would mean that the gate would be inconvenient for all of the "good" people.  We only want to make it inconvenient for the bad people.  For the good people, the gate should essentially not exist.
