### ISSUE TITLE
Natural springs right in bands borders

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLife#709]
I think it would be better to remove natural springs from bands borders.
Some people try to form multiracial towns by making well just in the border. New people could be confused why they keep seeing "+HOMESICK+" every moment when they cross center of the town (well).

Haven't seen a town like this yet, but I heard there were some.

**Comment by jasonrohrer** [comment]
Yeah, weird.... I'll take a look.

Can probably fix it by making the bands the right width so that they never "line up" with the well lines.
