### ISSUE TITLE
Impossible To Have A Baby For Some Players Their First Life 

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#711]
The [Steam advertisement](https://store.steampowered.com/app/595690/One_Hour_One_Life/) clearly says:

> Live an entire life in one hour. Have babies of your own in the form of other players.

Using the leaderboard, I found [this player](http://onehouronelife.com/fitnessServer/server.php?action=leaderboard_detail&id=49058) who was [Chicago Sun](http://lineage.onehouronelife.com/server.php?action=character_page&id=6731748) their first life and thus was male.  I can tell that that player's first life was as Chicago Sun, since that consists of the first time their genetic score changed.  But, since the character was male, males are never fathers, and males cannot have babies, there was no way for that player to have a baby on their first life even if their character had lived to 60.

Another example is [this player](http://onehouronelife.com/fitnessServer/server.php?action=leaderboard_detail&id=49066) whose first life was as [Jino Moni](http://lineage.onehouronelife.com/server.php?action=character_page&id=6731908).  Had that character lived to 60 their first life, he couldn't have had a single baby.

There's also the issue of players having their first life when the servers are in children of men mode, and no player can have a baby.  I suppose that could get solved by children which are controlled by a program, and die off when all human players have exited the server.

**Comment by jasonrohrer** [comment]
Men can't have babies, obviously.

**Comment by DougLefelhocz** [comment]
> 
> 
> Men can't have babies, obviously.

Plenty of people in the real world speak of men having babies, such as when some women refer to their self and their male partner as "having a baby".  Or when a man says of himself and his female partner "we're having a baby".  It's simply not obvious to plenty of people who haven't played this game that men can't reproduce.
