### ISSUE TITLE
No Reachable Experts For Objects From an Inhospitable Biome

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#712]
I just played as [Watie Sahara](http://lineage.onehouronelife.com/server.php?action=character_page&id=6757088).  Our town had a completely dry deep well when I was born (and no cisterns).  I go find a jungle waystone, and there's no experts for inhospitable jungle.  I double check with Hetuw mod and sure enough, having played earlier in the day and recognizing Kraut and Baddick family names, there's no experts for inhospitable jungle alive.  I talk to my leader and she says to go "looting" dead towns.  That isn't rebuilding from scratch.  I guess it's scavenging.

   Then a few minutes later, there's a jungle expert, but they are in donkeytown, some 28k south of me.  There's later a [Cowan](http://lineage.onehouronelife.com/server.php?action=character_page&id=6756915) family, but they don't last long and I don't manage to get anything from them, as they wander around and that's about it.  Later there's a [Jungles ](http://lineage.onehouronelife.com/server.php?action=character_page&id=6757054) family.  That family wanders around similarly, and isn't responsive at all, despite that I had two buckets, two wet clay bowls, and a knife.  I might have brought them cactus fruits, but my memory is hazy on this.

   Someone else on the discord recommended that I would have done better to suicide at that point, become the child of the brown Eve, and do the latex and palm oil myself.  But, that's not a one hour one life experience for sure.  The player population during the aforementioned time period about 40 players on bigserver2.  It was about 4:00-5:00 P. M. EST on a Wednesday.  At night (eastern standard time like 2:00 A. M. - 5:00 A. M.), as often seen from screenshots on discord, server population often gets under 20 players, and probably hovers around 20 players.  Families die out, [like this one](http://lineage.onehouronelife.com/server.php?action=character_page&id=6756194) rather quickly sometimes.  So, this sort of thing can easily happen, probably has happened before, and hasn't gotten reported or fixed.  Pein did make some comments on this issue on the forums a while back.

**Comment by DougLefelhocz** [comment]
Friday at 5:02 P. M. EST someone posted [this image](https://cdn.discordapp.com/attachments/328215300279500800/779466693764317244/unknown.png) on the discord showing the closest jungle expert in a tutorial area.

**Comment by jasonrohrer** [comment]
Yes, this can happen sometimes.

OHOL is about working with the situation you are given.  That can mean scavenging, sometimes, or surviving on wild foods for a few generations, or whatever it takes to survive.
