### ISSUE TITLE
New Players and Gene Score/Only Negative Gene Score After Living to 60

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#713]
I've spent two lives yesterday and one life playing deliberately on server1 when it seemed like there would be at least 15 players playing on it.  In my last life I logged onto server1 when it had around 25 players as [Mika Aries](http://lineage.onehouronelife.com/server.php?action=character_page&id=6818981&rel_id=6818378).  My mom Eve Aries gets bite by a boar before I'm 3, and I have to scramble to find my sister to stay alive.  I play things out and live to 60.  

During that time, I get the new player popup for my last daughter Lovely Aries.  I'll add that I did a little teaching and my other family members were teaching her also even more than I was after I told them that Lovely was new.  She also asked "what do I do?" after seeming to run around confusedly.  By the time I was dead, there were less than 10 players on the server... I think it was 9 (I was using Hetuw mod).  This leads to the first issue:

1. No credit for some new players on an "overflow server" is possible.  I mean, shouldn't new players have the possibility of getting credit for playing?  Also, Lovely Aries lived to 60.  But, from the looks of it checking the reflector again, she got no gene score points at all.

I check my leader board [name](http://onehouronelife.com/fitnessServer/server.php?action=leaderboard_detail&id=55) after my character dies from old age.  I have one change _only_ with respect to my gene score, even though my character is dead.  The death of my mother drops my gene score by -0.354.  This leads to the second issue:

2. It's possible to complete a life starting as a child *and* live to 60, and only get a negative change in gene score.

**Comment by DougLefelhocz** [comment]
Later on I played as [Dani Liz](http://lineage.onehouronelife.com/server.php?action=character_page&id=6821039&rel_id=6821039).  I taught someone how to cook some pie at the end of my life who said she was new.  She lighted the oven  once or twice curiously without cooking any pies, before I helped her to make some pie.  I got positive gene score from how long my grandmother lived and that's it, even though we were in the same family.

**Comment by jasonrohrer** [comment]
There have to be at least 15 players on the server at the moment someone dies for their death to count toward your fitness score.

This is the simplest way to do it, and it does the right thing most of the time.

**Comment by DougLefelhocz** [comment]
> 
> 
> There have to be at least 15 players on the server at the moment someone dies for their death to count toward your fitness score.
> 
> This is the simplest way to do it, and it does the right thing most of the time.

Then it still does the wrong thing here and also during a server update which is worse, since one could somewhat predicabtly kill elder relatives to maximize their gene score.

Also, isn't the game getting designed with the intention that more servers get used?  But that would mean an overflow server in somewhat constant use, with its population likely dying out during lower population times.
