### ISSUE TITLE
Bear grieving with horses is far to easy

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#715]
https://www.youtube.com/watch?v=rkmEeoblLz0

Possible solution: 
Make the bear return after 1 minute to his origin.
Make people on horses vulnerable to bears / boars.

**Comment by jasonrohrer** [comment]
Seems like there are a bunch of ways to solve this problem already.

Where's the town fence/gate?

This guy was not from the victim village.

**Comment by DougLefelhocz** [comment]
> Where's the town fence/gate?

Good players don't make them.  They are a waste of time and prevent outside help from coming in.
