### ISSUE TITLE
Gene Score During An Update Period on Server1/Fertility During An Update

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#716]
Please pay close attention to the part in italics in the following.

I deliberately logged onto server1 after I had seen that bs2 had players on it after the update had gotten applied.

I ended up as a ginger who didn't get [named](http://lineage.onehouronelife.com/server.php?action=character_page&id=6840782&rel_id=6840882).  I used Hetuw mod to keep track on the number of players on the server while I played.  In principle, I could have used the default client and pinged the reflector for the same information while I played.  It was myself, my mother, iirc Lais Sage, and Livia Sage.

One of my relatives asked me HAVE YOU HAD A CHILD? or something similar.  I told her that we were on server one, and it wasn't likely that I would have any children.  I would think this sort of situation unexpected to new players since the Steam advertisement says:

> Live an entire life in one hour. Have babies of your own in the form of other players. Leave a legacy for the next generation as you help to rebuild civilization from scratch. 

The first death in the family during my life happened when the server was at exactly 15 players, with two other family relatives alive.  The latter two relatives consequently didn't get any gene score changes, with at least one of them playing their life out until 60 and the other one living until 59.  It seems very dubious that these players deliberately logged onto server1 like I did, even if that matters, and I don't see why it would.

_Also, when I saw the player count somewhere in the 20s, it crossed my mind that it might be beneficial to my gene score to kill one of my family members.  These were all constructive players.  They farmed, had some clay plates, cooked pies, and one made some adobe walls.  But, it seems that there existed some points in time where it would be beneficial to my gene score to have my Great Aunts, if not my Mother also die from a bear or boar attack or some other means that I would have caused_.

More than one server is required with people still playing in order to do an update, correct?  The update situation and the overflow situation isn't players Eve chaining on back end servers, tutorial Eves, or donkey town Eves.

What if instead of a threshold of players active on a server to determine if gene score calculations applied, all players starting as babies could have their gene score change?

**Comment by jasonrohrer** [comment]
Yes, there are always going to be some oddities during these transitions.

I'm not going to design the game around these rare (once a week at most) edge cases.

This game already has one of the most seamless server update processes in existence for any online multiplayer game, with no wipes, and no disruption to the play experience.
