### ISSUE TITLE
Truck/Horsecart Babies

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#717]
I [got born](http://lineage.onehouronelife.com/server.php?action=character_page&id=6838494) to Lilianna who was out by an oil rig with a truck.  She drove away and I starved.  I can't imagine that happening as a positive experience for new players, and plenty of players on the discord were not happy with NoTruePunk a few days ago who ended up starving babies a few days ago also on a trip out of town.

Well based homelands are still active when a server has less than 15 players on it.

If a server has at least 15 players on it, and a family has a well or pump, could both being inside of a home band _and_ being inside of ones family's well/pump radius be a requirement for fertility?

**Comment by DougLefelhocz** [comment]
Mango from the discord, 12/10/2020:

> Accidentally popped out a baby while doing oil. And I tried to do the right thing. Ask bb if they wanna walk? They say Y. So we walk... 12 more bbs on the walk home
> Only four made it home
> Dunno if ima do that again :triumph:
> No wait I’m sorry. I had 14 babies total on the walk home
> both who starved were probably new players who didnt know the F thing
> i did say "F for food" quite a bit but at that point im not sure which bbs saw it and which didnt
> i felt so bad when the one said F and i was running his way and he died instantly
> its tough. i want to be a good player. a good mom, i guess. but i also want to work on oil because it's what i enjoy in the game
> it was my mistake by popping into biome briefly but i tried to do the right thing
> in the future i will set up my tarry's better, put essential items in the homesick zone for example

Family tree [image](https://cdn.discordapp.com/attachments/328215300279500800/786508623933210624/unknown.png) for that life.

**Comment by IIRC-IDK** [comment]
The return of the homeland radius could be an easy fix to this issue. An auto whistle or notification when we have a child would be nice as well. Its easy to miss babies while traveling especially if they pop behind trees.

**Comment by DougLefelhocz** [comment]
> 
> 
> The return of the homeland radius could be an easy fix to this issue. An auto whistle or notification when we have a child would be nice as well. Its easy to miss babies while traveling especially if they pop behind trees.

I know I've missed babies while riding a horsecart on a road.  I'm pretty sure some others have missed a baby or two when riding a horsecart not on a road.

**Comment by jasonrohrer** [comment]
This is meant to be a funny part of the game.  The baby does make a "POP" sound when appearing.

The fact that mothers didn't need to worry about having babies when far from home was an unintentional side-effect of the well-based homelands.

I always liked the idea of a mother having a baby far from home and having to make a hard choice.  Leave the truck or the baby?  I can always come back for the truck later.  Deciding to keep the baby makes a really great story.

And there are plenty of reasons in the game, currently, to keep the baby (gene score, keeping offspring around so you can return to your town next life, etc.)
