### ISSUE TITLE
Eve Spawning and Rebuilding from Scratch

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#722]
The Steam advertisement talks about rebuilding from scratch:

> Leave a legacy for the next generation as you help to rebuild civilization from scratch. 

I played as a white [Eve Spoon](http://lineage.onehouronelife.com/server.php?action=character_page&id=6897782&rel_id=6897782).  I kept seeing marked springs for a while running left.  I finally found a natural spring in a swamp.  Some of my children found some town.  I wanted to rebuild from scratch, and I told them also that I wanted the iron unlock.

The spring I found was some 750 tiles left of my initial spawn point.  There did exist two muddy iron veins left.  But, the iron vein 40 tiles right of the spring I choose was sunken.  So, in order to have only fresh spots, I would have had to have gone 4 more springs/veins left.  That makes for ((4x40)+750) = 930 tiles from my spawn point.

A few weeks ago a veteran on discord, who goes by bpskotch on the forums, told me that he had an Eve spawn where everything was used up in his area.  Some Eves just resettle towns.  It makes for a more sensible situation when Eves can rebuild from scratch without having to move too far.

**Comment by jasonrohrer** [comment]
This is necessary to sometimes have Eves in nearby areas so they aren't always too far away to interact with other towns.

**Comment by DougLefelhocz** [comment]
> 
> 
> This is necessary to sometimes have Eves in nearby areas so they aren't always too far away to interact with other towns.

There is nothing about interacting with towns in the Steam advertisement or on onehouronelife.com .  There does exist talk of rebuilding from scratch.
