### ISSUE TITLE
Notifications for Leadership AND Ownership

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#723]
When a player gets BOTH leadership and gate ownership, they only get the "You inherited property." notification. So they don't know that they are the leader.

Since notification can be on the upper left and upper right, would it be possible for you to change it so that players get **BOTH** notifications. One on the upper left and the upper right.

Or some other solution.

Thank you.

**Comment by jasonrohrer** [comment]
Yes, I think that both are sent to the client, but the second one immediately replaces the first.

The server should detect this condition and hold off on sending the second message until the player has had time to read the first message.
