### ISSUE TITLE
Posse vs Hostile Biome

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#724]
Code Change

Being part of a full-sized posse prevents biome sickness while chasing victim (victim can't hide in bad biome to make you drop your weapons).

https://github.com/jasonrohrer/OneLife/commit/2275e342ab1b3a298184f901dd8ea714e8345770

-----------

Question....

A few times I've been in posses where the person I'm trying to kill has been exiled beforehand. And I couldnt cross the hostile biome while targeting/in the posse. But I'm not 100% sure that my memory is correct. IDK.

The question is....is this dev change working?

**Comment by jasonrohrer** [comment]
So in this case, you were in a "posse" of one person, because they were exiled?

I'm not sure if the part of the code that bypasses biome sickness is aware of exile status.  I'll check that part of the code.

**Comment by jasonrohrer** [comment]
Tested and seems to be working.

If the victim is terrified, and you can kill them, you don't drop your weapon in a bad biome.  Even if your posse only has one person in it (if they are exiled, or solo in the wilderness).

If you can find a video of incorrect behavior here, please re-open.

Also note that you must form a new posse AFTER they are exiled.  If the "required posse size" is computed at the moment when the first person targets them.
