### ISSUE TITLE
Language Fam Fertility North of Arctic and South of Desert

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#725]
I dont know if you changed your mind about it or if it is a bug. But currently, language fam is fertile north of the arctic homeband and south of the desert homeband.

From: https://onehouronelife.com/forums/viewtopic.php?id=10205

"Beyond that, further to the North and South would be the end of the specialty biomes entirely.  So Gingers or Desert folks wouldn't have "bigger" homelands than anyone else.  In those regions, there will just be mountains in the "highest spots" in the topographical map.

White folks would only have their official homeland in the middle, even though there ARE mountains in the "no man's lands" further North and South." - jasonrohrer

**Comment by jasonrohrer** [comment]
Whoops, if it works this way, it's a bug.  Will take a look.

**Comment by TwistedHBG** [comment]
Can confirm it works this way, language family can have babies outisde the homeland zone
