### ISSUE TITLE
Connection Lost vs Old Age

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#726]
I've noticed while watching streamers, that instead of the 

YOU DIED
AGE: 60 YEARS
CAUSE: OLD AGE

you get the "Connection Lost" page.

Then they quickly click trying to connect again. But they still died of old age in actuality.

This has sporadically been happening the last few weeks/months. (IDK what the cause is.) 

For me and I suspect many longtime players, this is not a problem/issue. We just accept that it happens sometimes. It's not a big deal.

I assume this is only an issue for newer players or people who think it is satisfying to see the you died of old age page.

Just posting to report it. Feel free to ignore if hard to fix/find the root of the problem.

**Comment by jasonrohrer** [comment]
Hmm... yeah, I've seen this myself sometimes.  I'll look into it.

The server should send the YOU DIED message, and then keep the connection open for a while.  That's how it's supposed to work, anyway.

**Comment by jasonrohrer** [comment]
I'm going to double the time that the server keeps the connection open after telling them that they died (from 5 to 10 seconds) to give even more time for the message to make it through before the connection is closed.

Please keep an eye out for this issue this week.  If it's still happening, there must be another bug.

**Comment by JustinLove** [comment]
Just saw this happen on a stream.

https://www.twitch.tv/videos/847915585?t=3h9m37s

**Comment by cordy-123** [comment]
Yeah, it still happens but I guess Jason can't fix it.
