### ISSUE TITLE
Apoc Monument bug?

### ISSUE THREAD

**Issue by sporeburst** [jasonrohrer/OneLife#730]
I created an Apoc monument with 1 Endblock.  6 hours later, there were no notifications that there was one.  

After looking at your code, it looks like it is configured to only alert if there's 3 there.  I can only understand LUA well so reading this is kinda rough for me though:

void monumentAction( int inX, int inY, int inObjectID, int inPlayerID,
                     int inAction ) {
    printf( "Monument action happened.\n" );

    if( inAction == 3 ) {
        monumentCallPending = true;
        monumentCallX = inX;
        monumentCallY = inY;
        monumentCallID = inObjectID;
        }
    else {
        // log it
        FILE *f = getMonumentLogFile( inX, inY );

------------------------------------

I'm not sure if it's intentional or not, or if I am reading the code wrong but the server population was not notified of an Apoc Monument when the first endblock was placed.

**Comment by cordy-123** [comment]
Someone made a github issue about it. (https://github.com/jasonrohrer/OneLifeData7/issues/155)

So the dev changed it.....

Content Change

No long-distance monument call (home arrow) for first two stages of seeping end tower.  Now you only get the call when the tower is getting close to complete.  Fixes #155

https://github.com/jasonrohrer/OneLifeData7/commit/af72bc386a5a617f410e9d76056fbf6497301ddc
