### ISSUE TITLE
No Genetic Score Change When Less Than 15 Players Living on a Server

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#731]
It happened during the player count increase from, as I recall, Saturday until Tuesday if not Wednesday, that players not checking a custom server would end up server1.  Player count would get into the 20s or 30s, then be back down to below 15 later on.  Those players didn't get any genetic score credit.

The same issue happens every update period during children of men mode to some players on bs2.

The same issue happens every update period when players get redirected to server1.

Genetic score is fundamentally broken during time periods like these, because there exists motivation for players to kill well intentioned, well meaning, and productive older "relatives" before population drops.  Any numerical threshold for genetic score suffers from a similar issue and isn't consistent with playing for the survival of others in such situations, and instead motivates _against_ playing for survival of others.

**Comment by cordy-123** [comment]
Of course, there is no gene score change when the server is low pop.....if there was....then everyone would just farm gene score in low pop servers.

**Comment by DougLefelhocz** [comment]
> 
> 
> Of course, there is no gene score change when the server is low pop.....if there was....then everyone would just farm gene score in low pop servers.

The first player on the server is an Eve.  I would guess it a simple matter to disable genetic score based on generation number.    Or to disable genetic server based on the server getting used.

Also, so what if everyone would farm gene score in low pop servers?  There's nothing wrong with things being easier for players and things as more dependent on their own individual efforts of players.  The scoring system is supposed to depend on players efforts alone and not involve any elements of chance.  Scoring systems are supposed to work as easy for players to understand how to work towards bettering their score.  Genetic score, or some alternative, in low population servers would work that way.

**Comment by jasonrohrer** [comment]
It's a server setting that can be adjusted.  It's currently set at 15, which is pretty low.  I will revisit this in the future, if pops ever drop below 15 consistently.
