### ISSUE TITLE
Fertility Active Far Away From Home

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#733]
Homelands made for an improvement, because of the fertility control that it enabled for players.

I saw a Hetuw user by the name of IDance comment on how they got abandoned by a mother on a truck or horsecart the other day.  One minute one life is not interesting.

It also makes for a poor story getting raised by a mother out in the wild in the majority of circumstances.  If one doesn't make it back to town, the player will likely be naked, and likely not live very long.  Getting raised in an area with some heat and possibly clothing is more interesting.  Someone on the discord had this to say:

> reptasaur Yesterday at 11:31 PM
I wish you could choose what family to be born to because i keep getting shitty kingdoms that are like 3 people who ran off to start again
And you die really young because of zero food

Having babies in such a situation also isn't useful to players, as indicated by how often horsecart and truck babies get abandoned.  There exist plenty of reasons for players to just not have them when far away from home.

**Comment by jasonrohrer** [comment]
Homelands weren't meant to limit fertility to prevent wilderness babies.  They were meant to concentrate populations around town centers and prevent people from easily perma-settling in another family's village, which would eliminate the need for travel and trading.

Now the same thing is achieved by the homeland bands, while also still allowing fertile outposts within a given band. 

Wilderness babies will always be part of the game.  They even occur in the trailer.  Every streamer has showcased hilarious moments when they were born to a mother being chased by a bear or whatever.

Riding a horse through the woods and a baby pops out.  There's nothing more OHOL than that.
