### ISSUE TITLE
Bears Decrease Family Survival Prospects Only

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#734]
This is a survival game.  Bears do not whatosever increase a families survival prospects, as the insulation from bear skins is not useful.  There exist fewer one hour one life experiences for players, because of bears.  Unlike wild hogs which come as a predecessor to a food which can enhance survival prospects, bears don't enhance anyone's survival prospects.

The game would work better with bear caves entirely removed from the game as it stands at present.  There would exist more one hour one life experiences for players without bears.  There would exist more tales of survival without bears.

Stories of early deaths to bears are boring.

The game would be more of a multiplayer survival game without bears in the game.

Other than having bears removed entirely, the other alternative would have some practical use for bears such as bear based clothing.

**Comment by jasonrohrer** [comment]
Uh... bears are a hilarious and amazing part of the game....
