### ISSUE TITLE
Gene Score Tends To Penalize Players For Having Larger Families

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#736]
Gene score is supposed to reward players for having more of a survival impact.  That entails that the greater number of players in one's family should more often than not in one's family be beneficial to gene score.  But, it's often the reverse.  The more players in one's family tends to result in weaker gene score and weaker gene score prospects.

An alternative idea to gene score would be just to drop all the penalizations, other than keeping /die penalizations, and reward players for how long they survived if they didn't use /die, which might get called "longevity points".  That would incentive playing with more players and playing for the survival of as many of them as possible.  It would also tend to result in the most experienced players having the highest score.

**Comment by jasonrohrer** [comment]
The top player on the leaderboard, currently, has been playing the game for over 5 years and has logged over 900 games and over 2000 lives.  They are definitely not an inexperienced player.

There is certainly some luck/variance in gene scores.  However, if you take care of everyone in your family, and ensure that they all live to old age (which is hard), your gene score will go up.

**Comment by jasonrohrer** [comment]
But reading that thread about how to farm Gene score, I do see the problem here...  setting up a situation where you have only one baby is something of a guarantee of positive points, with no chance of negative points.  But it's also an extremely slow way to get genetic score...  so that's kindof okay.
