### ISSUE TITLE
Gene Score Motivates Killing of Constructive Players In Some Situations

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#737]
Killing of a player trying to harm other players is one thing, since it can in principle if not in practice also, result in more players surviving or living longer.

But, it appears that [cordy and others have figured out](https://onehouronelife.com/forums/viewtopic.php?pid=104844#p104844)t that gene score motivates killing of constructive players, in particular immediate family members, in some situations, which isn't consistent with players playing a game of multiplayer survival or a family survival game.

Rookwood:

> Now, sometimes it doesn't work out and you have unaccounted for relatives... what do?  Well your score account is always leader... you can just kill them...  So kill any fertile females you don't have control over.  Careful though, that's a good way to get cursed.

The issue also comes as likely to exist, if not existing, when a server has a change in population like during children of men mode, when odd numbered servers become the default servers during an update, **and** given that there exist enough players for _just one_ server to end up as an overflow server, [as talked about here](https://github.com/jasonrohrer/OneLife/issues/731).  Updates are supposed to be weekly, and thus the problems there make for a regular occurance.  The overflow server issue also would work as a daily issue, if again, at least one of the 15 overflow servers were in constant use.

**Comment by jasonrohrer** [comment]
You currently can't kill your own mother, younger sisters, or nieces.

So he must be talking about killing your own older sisters?

**Comment by jasonrohrer** [comment]
Had some discussion with the community on discord, and it doesn't seem like this is an issue that needs fixing.
