### ISSUE TITLE
glitching out items random glitchy children

### ISSUE THREAD

**Issue by ClarkCollide** [jasonrohrer/OneLife#740]
So, I was playing one life and me and another player were starting a new town everything went wrong so I was heading back to the co-existing town but on the way, I found a small base while running from a bear suddenly my child got bit by the bear and died and as soon as they died a pond attached to my face and so did a lot of things near me and then a child came out and its face was a weird panel and its body was a farming lot and when it died It became a carrot. I found this really weird and creepy so I've decided to report the bug thanks you for reading

**Comment by JustinLove** [comment]
You ate a psychedelic mushroom. The effect is temporary, though if you die while high you will get stuck; restart the client to fix.
