### ISSUE TITLE
Tool slots active for players who survive an apocalypse

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#741]
Discord reported that tool slots were active following an apocalypse.

It looks like everyone learns all tools when "not active" (setupToolSlots), but the apocalypse then removes all the learned tools (backToBasics)

**Comment by cordy-123** [comment]
Probably connected to this.

Code Change

Apocalypse clears your tool learning slots.

https://github.com/jasonrohrer/OneLife/commit/03e606244d03ee0be52b5555ad47e495cc45150a
