### ISSUE TITLE
Motherhood System is Over Powered 

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#742]
The vast majority of time when I've played on bigserver2, it's been simply too easy to have a child.  Since female characters have been fertile by default, one only needs to survive during one's fertility period usually in order to have a child.  It's also been far too easy to have a child as an Eve during server restart.  There exists little possibility of failure in having a child.  There exists little need to do a ritual to become fertile, to have a social interaction with another player to become fertile, or, perhaps even to compel another player to become fertile.

_Because of fertility being soooo easy and not requiring social interaction to get enabled, teamwork in this game remains poor_.  If players needed to negotiate with each other for fertility to exist, then they would need to have more of an attitude to cooperate with someone else in order to have a family.  If players could compel another player to become fertile, that opens up the possibility of (unknown to them perhaps) slavery.

> To give you rich, interesting, and weighty choices to make in each life.

If players were not by default fertile, and needed another player to become fertile, then they would have the weighty choice in many lives of bringing a child into the world when they fully realize that she or he will die.  It would also be a weighty choice to have another mouth to feed in town, or to risk the family dying out due to a lack of children if one does not become fertile quickly enough. 

> To ensure that each life really is different.

If one needed to negotiate or coerce or cajole another player in order for fertility to exist, then every life would be more different.  For not only would the possibility of failure of having children come as more likely by failing to engage in desire-able behavior to another for those who wouldn't want to coerce or cajole another in some "mating" practice, each life would be more distinct since talking with players usually differs life to life.  And since each person playing the game is a unique individual.

> To force you to study and understand the most pressing problems facing your village now, and the problems it will likely be facing in the near future.

If fertility was not coerced by the code onto living players in a region by default and required actions of two players, it would make for a pressing problem for a family to study that problem now, since they would have a fertility problem now, and likely have that fertility problem in the future.

 > To enrich player interaction, communication, and cooperation, and short-circuit the tendency to "just do it all yourself" instead of coordinating your efforts with others.
 
**Currently, motherhood as it stands encourages the "just do it all yourself" tendency in the first place**.  Worse, fertility by default feeds players having a sense of entitlement of having children.  Needing two parents for a child would likely do wonders on this point.

> To encourage trade between players.

If players were not fertile by default, and it required two players for fertility to become active, I'd think trade would be more likely to happen.

> To increase the importance of communication between village adults and incoming children.

The child would know the mother by popping out of them.  But, who was the father?  Or if two women could reproduce without a father, who was the other mother?  Or if two men could reproduce and the child spawned from a male player, who was the other father?

> To add an additional constraint to the game, because constraints are generally good.  More constraints leads to more meaningful choices.

Needing two players to do something whether that's talk in a certain way or engage in some button click or needing one to coerce the other via an action, would make for an additional constraint on the game.

[Source](https://onehouronelife.com/forums/viewtopic.php?id=8181) of the above quotes.

It is also too easy to start as an infant of a _human_ player or too difficult to start as a male or female who can feed their own self.

If players would start as a male or female who can feed their own self more often, there would also exist fewer instances of /die!  And perhaps even if players knew that their parents needed to work as a team for them to start as a baby, they would feel less inclined to use /die, because then they might think of what other people did for them to be a baby in the first place.

**Comment by cordy-123** [comment]
This is all well and good now. When we just came from sales and tiktokapocalypse and it's winter holidays.

But remember. Just 2-4 months ago several towns/fams were dying everyday because of no girl kids. This kind of suggestion just makes it harder when player count goes down again.

**Comment by cordy-123** [comment]
Plus, this is just another roundabout way for you to ask for fathers ingame again.

**Comment by DougLefelhocz** [comment]
> This is all well and good now. When we just came from sales and tiktokapocalypse and it's winter holidays.
> 
> But remember. Just 2-4 months ago several towns/fams were dying everyday because of no girl kids. This kind of suggestion just makes it harder when player count goes down again.

I made an edit:

> But, who was the father?  Or if two women could reproduce without a father, who was the other mother?  Or if two men could reproduce and the child spawned from a male player, who was the other father?

So, no, the idea here doesn't entail fatherhood.

**Comment by cordy-123** [comment]
But the original idea did.

Plus what happens when player count goes down to 20-40 in bs2 again. And we need baby girls. This just makes babies harder to spawn.

**Comment by DougLefelhocz** [comment]
> Plus what happens when player count goes down to 20-40 in bs2 again. And we need baby girls. This just makes babies harder to spawn.

If you were the last player in an area, you go to another area and try to interact with them.  Again, you wouldn't neccesarily need baby girls under this idea, given that two adult male characters could enable fertility by their own selves.  

Babies, from human players, are supposed to be difficult to spawn sometimes.  The current system feeds into players having or developing unearned entitlement complexes of reproducing, while needing two parents doesn't feed into an unearned entitlement complex so much.  Players decisions on how to interact with other players should matter at all times.  Under the current system, how players interact with other players doesn't matter with respect to fertility at all, and thus their social decisions barely matter at all with respect to "reproducing".

**Comment by DougLefelhocz** [comment]
Also, there's _much_ more control genetic score wise as a woman in this game than as a man.  A woman can go to her band border, have one child, and never look back.  A man either has to live with his sisters having children or kill his sisters wisely.  This isn't balanced whatsoever.
