### ISSUE TITLE
Do children and grandchildren of twins get curse tokens?

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#743]
Got an email report about this, need to look at code and see what's going on.

**Comment by cordy-123** [comment]
yes, they do get curse tokens. checked it twice. (yes, i also double checked that the mom was an actual twin, not just an accidental twin).

yes, i did get a curse token after i expended my previous token (that i already had from a previous life).

both times that i was a twin's kid....i cursed 3 people. 

case closed.
