### ISSUE TITLE
Genetic Score Forces Conditions by Itself Resulting in More Uses of /die

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#747]
I found this reddit post with someone asking how to [lower their genetic fitness score](https://www.reddit.com/r/onehouronelife/comments/l2cwn3/how_can_i_lower_my_genetic_fitness_score/?%24deep_link=true&correlation_id=fdd8166c-a2bc-4bb1-a759-555c22def3cd&ref=email_digest&ref_campaign=email_digest&ref_source=email&%243p=e_as&%24original_url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fonehouronelife%2Fcomments%2Fl2cwn3%2Fhow_can_i_lower_my_genetic_fitness_score%2F%3F%24deep_link%3Dtrue%26correlation_id%3Dfdd8166c-a2bc-4bb1-a759-555c22def3cd%26ref%3Demail_digest%26ref_campaign%3Demail_digest%26ref_source%3Demail&_branch_match_id=764974864688318390).  Somewhat predictably, they were advised, to use /die to lower their genetic score, and the person appreciated the advice which signals that such a person has been using /die.  The baby bones are a mess for players that they don't want, and picking up a baby character to have it die instantly isn't an entertaining use of time in the vast, vast majority of cases.  This is a lose-lose situation for both the babies using /die and the mothers.

If players could just disable having the ability to get leadership, become Eve, or get bonus pips before playing they wouldn't feel a need to use /die to avoid getting leadership, etc.  And fewer players would have /die children.  Sounds like a win-win for both parties.  Or if players would need to enable those as possible before playing, that would also make for a win-win for both parties.

**Comment by cordy-123** [comment]
you can disable the ability to get leadership by doing /unfollow

you can hug a wolf when you get Eve

doubt anyone cares to have LESS bonus pips
