### ISSUE TITLE
Pickles are missing in wiki

### ISSUE THREAD

**Issue by mejem** [jasonrohrer/OneLife#749]
Pickles, dill, bay, cucumber - plants and food added in version 343 are missing in wiki.
https://onetech.info/versions/343

**Comment by DougLefelhocz** [comment]
The wiki is separate from the game.  I think you can edit it, if you like.

**Comment by jasonrohrer** [comment]
I'm not sure what happened with Onetech during that update, but all those things seem to be in there now.
