### ISSUE TITLE
Planes Likely Impossible Without the Existence of Tans/Race Restrictions Nearby

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#751]
The non-existence of one of the racial based families keeps on happening with hour to three hour long gaps (as Slinky found).  I think there was one on Sunday March 29th for about an hour, but at the time all towns were living on kerosene for their water supply, so I didn't mentions such previously.

Today after gingers ended up 8-9k from all other families, I got born to [Libbys](http://lineage.onehouronelife.com/server.php?action=character_page&id=7233120&rel_id=7234634) a second time.  I saw wings in the vault early.  I went looking for the new well I had dug up in the previous life later, and getting lost, I instead found old white towns that I had played in on Saturday and Sunday.  There was still an engine on the well, so I drained it, and brought the engine back thinking I might complete a plane so resource exchange might still happen.

Then I check the wings and realize that I hadn't checked to see if the wings were rubberized, and that planes need *liquid* latex to make, and recalled how I fumbled that in low pop when first making a plane.

Planes needing liquid latex thus signal a huge conflict with race restrictions and families not existing of all relevant races.

_Family spread before and now would not have been an issue (or so much of an issue) a few weeks ago and now if all families could get at resources independently of other families even if they had unequal abilities in doing so_.

**Comment by jasonrohrer** [comment]
It's okay if some stuff is impossible to make for a short while.  There is a grand-scale world-management challenge going on too... which is what players are coordinating on Discord.  "Wow, we really need a tan family, so let's coordinate to make sure that happens."  Also, creating a plane during fat times, just in case you need to use it during lean times to trade, is a reasonable long-term strategy for survival.
