### ISSUE TITLE
Well Tapout Is Not Good Especially With The Iron System

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#752]
I had an [Eve run](http://lineage.onehouronelife.com/server.php?action=character_page&id=7243469) this morning.  I walk something like 1800, maybe even 2000 tiles left before I find a spot that looks like a fresh spot with natural springs and iron veins which can get unlocked.  I find and spot and settle down.  I'm fairly happy, as my children seem aware of what to do.

I go to dig up the well where I had placed stones making a ready well site.  Some are missing.  That sometimes happens in Eve camps, so I drop the shovel and go out for more stones.  I come back to the site with stones and the shovel is gone (Hetuw has a search function... I didn't see the shovel on the ground and couldn't find it using the search function).  I make some order asking where the shovel is.  I give a nice order at the end, as other than the shovel and well issue I had been happy with that life.  I die at 60.

I get reborn as [Alice Spoon](http://lineage.onehouronelife.com/server.php?action=character_page&id=7243480&rel_id=7243480).  My mom doesn't manage to feed me, but whatever, it happens.  I see that the spring is now a dry spring with stones on it, and realize someone has dug up a well in the area, but not in the area where that spring was.  I note the spring was close to ponds.

I get born as [Adam Angel](http://lineage.onehouronelife.com/server.php?action=character_page&id=7243546) the next life.  I walk back to the Spoons.  None of them has figured out that they need to move.  I tried to explain the situation to Popcorns, a Hetuw mod user, but he didn't quite pick up on things.  That signals how complicated of a mess this is.  I find the well close that someone has dug up.  _It's in the jungle band out in the middle of nowhere with nothing around it_.  It wasn't like the family could move there, and even if they did, iron would no longer be on the same ley line as the well, increasing travel time to get iron, and possibly causing confusion later on.  I did dig up a well elsewhere, but moving people, as expected didn't work out so well.

Well tapout is not a good system for this game.  Nor is the current iron system and iron tapout.

**Comment by DougLefelhocz** [comment]
DragonGamer, a long time veteran, had this to say on discord:

> that well tap-out is bad and tap-out in general is such a old problem, we always say it, firstly cause towns block each other, but mainly cause thanks to both tap-out and the biome strips making tarrys accelerate a lot faster west then towns itself

And he isn't commenting on how things work with a server that is even half full of players, more like 40-60 players and sometimes less.

**Comment by DougLefelhocz** [comment]
A well tapout of the decided on spring by a Ginger family named [Milks](http://lineage.onehouronelife.com/server.php?action=character_page&id=7903100) I saw happen again today.  It wasn't good, and the family had to move to a worse spot.  Likely, there will exist confusion in the family about where iron is.

Edit: Milks ended up moving some 5k east back to an old town, which isn't surprising either.

**Comment by jasonrohrer** [comment]
Having to move because of such things is an interesting story, and a great challenge for a family to face.  It's not supposed to be straight-forward and the same every time.

"We had to leave a ghost town behind because the well done gone dry."  That's great and dramatic and interesting.

Of course, in the moment, the players wish it wasn't happening.  But that doesn't mean it shouldn't happen.
