### ISSUE TITLE
Whites Not Understandable With Server Population Between 15 and 30

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#753]
Whites lose the translator ability when a server has less than 30 players, but all players have translator ability when a server has less than 15 players on it.

**Comment by Glaise5** [comment]
The Language Fam can't speak all language below 30 and other fams have to write down what they want to say on paper and pencil or radio in order to understand each other, when Language Fam can speak above 30 people on server.

**Comment by jasonrohrer** [comment]
Yeah, this is an inconsistency.  Looking into it.
