### ISSUE TITLE
Spawning/Overall Gameplay Issue! 

### ISSUE THREAD

**Issue by Nom682** [jasonrohrer/OneLife#755]
Hi! I bought this game about a few months back and i've come to really enjoy it! Besides the occasional griefer or two... Well, tonight while I was playing. After I had died in a life, I wanted to go back to the place to try all over again and hopefully do better this time but I ended up spawning as a 14 year old who would randomly saw " X DEVIL WINE X " over and over again. I tried restarting my computer multiple times and nothing seemed to help. I also looked everywhere for some sort of explanation but I haven't been able to find one. PLEASE HELP ASAP! I want to get back to hunting and cooking :( I have provided a clip down below to show you what has been happening!

https://user-images.githubusercontent.com/82070606/113800279-ab179b80-9724-11eb-89b3-1e1589ba3624.mov

**Comment by DougLefelhocz** [comment]
You had gotten cursed to the point where you couldn't spawn as the baby of anyone, and no more Eves were called for by the server in the main play area.  So, you ended up in Donkeytown.
