### ISSUE TITLE
Families Spread Out In Distance/Race Restrictions/Families Aren't Independent In Terms of Water Resources

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#757]
Some Eves go left towards fresher areas.  Some go right back towards older areas.  Even when it's not Eves doing so, the descendants of Eves might go back to old towns, or if they have iron unlock and it's not too late, some players will go towards newer areas and try to develop new places.  Neither set of players is destructive.  The point here lies in pointing out that _both sets of players will continue to exist_ (at least so long as players exist).  This, along with tapout, _and_ how families die out at different times, all contribute to how families on the server get spread out horizontally.

Now the game worked fair well 2 years ago and even 3 years ago for both sets of players.  _Family spread was not a problem at all in 2018, nor through much of 2019_.  

What solutions exist to the problems above which satisfy both sets of players allowing some players to go left and others to go right?

If there were no race restrictions (inability to access objects in some biomes on the basis of character's race given a certain server population), players going in different directions wouldn't pose any problems at all.  _And both sets of players would be satisfied_.  If race restrictions weren't also connected to water resources, the above wouldn't pose as many problems as it does.

I suppose another solution could involve natural/low-technology teleporters between family locations.

Another might be fairly frequent arc resets.

**Comment by jasonrohrer** [comment]
The difficulty of trade and keeping things going can get harder and easier over time.  And players can choose where to settle to mitigate this.  It's possible for Eve to visit some expert waystones before she settles.  There's nothing wrong with expert players needing to engage in this kind of next-level thinking.
