### ISSUE TITLE
Died High, Was Reborn High

### ISSUE THREAD

**Issue by Mashimaro7** [jasonrohrer/OneLife#761]
Pretty self-explanitory, but i died from eating two mushrooms, was reborn permanently high. Typed /die to try and fix it, was still high. Restarted the game and it fixed it.

**Comment by HimitsuGato** [comment]
This is a feature not a bug.

**Comment by Mashimaro7** [comment]
Oh, really? Being rebirthed high after dying high is a feature? well, it's not a big deal, and pretty funny if it is lol

**Comment by jasonrohrer** [comment]
Did you really die?  That's the question...
