### ISSUE TITLE
leader command

### ISSUE THREAD

**Issue by unoriginalartist** [jasonrohrer/OneLife#764]
The leader command only finds top leaders, if you follow someone in a following themselves it only points to their leader when you type /leader instead of the person you followed.

**Comment by jasonrohrer** [comment]
Thanks for posting this!

**Comment by jasonrohrer** [comment]
Hmm... discussing with community, it seems like there are some conflicting desires here.  Most players want to find their top leader, and leaders often delegate authority by following someone else before leaving town.  If /LEADER pointed to your immediate leader, it would still point to that out-of-town person.

Also, I know that a small group of players use /follow for coordination... like two people going out foraging together, and they don't want to lose track of each other.  However, this is a bit of an off-label use of this feature.  The main use is to find the top leader to exercise leadership duties.  Exile requests, group orders, etc.

So, for those people who want to use it for coordination, they should both unfollow the real leader before leaving, so there is no top leader.
