### ISSUE TITLE
inheriting 

### ISSUE THREAD

**Issue by unoriginalartist** [jasonrohrer/OneLife#765]
Leaders *and gates* are inherited via gene score however leaders and *gate owners* are being picked thousands of tiles away when towns branch off or females get lost in the wild, inheriting leadership and gates in a range would be preferred instead as lost family members could even have a chance of finding their way home and towns might stop branching off as easily and dying due to a newer player wanting to pseudo eve. As if your not near the last leader you do not have a chance to inherit it and keeps the leaders in town more.

**Comment by DougLefelhocz** [comment]
I agree Uno.  This is [a](https://github.com/jasonrohrer/OneLifeData7/issues/915) [known issue](https://github.com/jasonrohrer/OneLife/issues/700).

**Comment by DougLefelhocz** [comment]
I finally realized that this issue is [even worse](https://github.com/jasonrohrer/OneLife/issues/775) than I thought before.

**Comment by life4ants** [comment]
Isn't there a distance limit on following now?
