### ISSUE TITLE
Not Exactly Clear When a Player is an Eve and Not in a Tutorial Area

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#766]
One player got Eve four times in a row and thought she was in a [tutorial area](https://www.twitch.tv/videos/1136298857) (she starts at about 5:30 in the video).  She said that the game would put her in a tutorial before, suggesting that she had been an Eve before and thought she was in a tutorial area.

**Comment by jasonrohrer** [comment]
Seems like this was a one-time fluke.  The video isn't available anymore, so I can't study it.

If it happens again, I will take another look at it.
