### ISSUE TITLE
Iron System Flawed

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#768]
I just played as [Lora Zaagman](http://lineage.onehouronelife.com/server.php?action=character_page&id=7666222 ).  I got born an we had a well site, but no well.  There's only one vein.  So, it's literally having to carry a pick by hand without a cart.  I have the new player popup twice with my children, but there's basically no time to teach, since I'm busy trying to get food to do hungry work on the mine.  It's impossible/not feasible to make the tools for a cart before one has to use a mining pick for a town with one vein.

Earlier I had played as a nameless daughter of [Eve Eva](http://lineage.onehouronelife.com/server.php?action=character_page&id=7666094&rel_id=7666080).  The Eve was newish (she only had gene score of 26 or 27 when she became Eve... probably because other moms were on birth cooldown).  So, she didn't look veins.  I was playing with three other people on stream, and we didn't try to get mom to move to another location, so she could learn.  My only child was a Hetuw user by the name of "Meow".  He decided to first put stones on a natural spring 160 south of where were setting up in the mountain band, while we were Ginger.  He also searched on default lay line.  I think he was trying to get iron from both ley lines, because he clearly feels that there isn't enough.  Anyways, that family will have to run around a whole bunch to get iron and where iron is there probably will get lost.

The day before I played in the [Snow](http://lineage.onehouronelife.com/server.php?action=character_page&id=7664782) family.  We only had one vein.  Someone eventually did an oil style oil rig.  After the vein was exhausted (_and before we had oil_) I ended up going at least 300 if not 400 tiles right to some vein in the mountain band to use the vein.  That was a bunch of time running around, instead of crafting, building something, or interacting with other players.  Additionally, such a place would NOT work on an arc reset, since 1 iron mine is probably usually, if not always, not sufficient to make a town, make a diesel engine, and make an old style oil rig.

Also, there are often ONLY two families on bigserver2 these days.  One could be ginger and the other black.  Trying to get iron from another family really isn't a viable option, and hardly even every happened when four families on the server were the norm.

The current system also doesn't allow much for content expansions.

**Comment by jasonrohrer** [comment]
These all sound like interesting unique challenges and stories to me.  Sometimes you need to go on a long journey to save your village.  Sometimes you don't.  That's all okay.

"Survival" means dealing with unforeseen problems as they arise, and persevering at all costs.  The game should be throwing stuff like this at you from time to time.
