### ISSUE TITLE
Mean Pitbulls Are Deadly And Dogs Are Useless and Counterproductive

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#769]
I just played as [Love Benick](http://lineage.onehouronelife.com/server.php?action=character_page&id=7668050).  One of my slightly older relatives was making dogs around the main fair out in the open soon after I was born.  I tried to get a bow and arrow while young (I thought I had the bow in my backpack, but didn't).  She didn't just make one, and had bread a german shepherd.  She said "SOO CUTE" I think at some point.  There were two dogs still nursing a bit later.  I took the puppies and threw them out so that they would die.

This is supposed to be a multiplayer survival game.  In order to protect players from the deadly effects of mean pitbulls, it's in the advanced player's best interest to discourage dogs sooner or later, and to prevent breeding of all dog types.

If pitbulls weren't deadly, there's not as much reason for an advanced player to throw puppies out on the ground so that they starve (though there is the issue that they take up space *and* there's nothing that can fit on a tile with a dog).

Dogs come as counterproductive.  They eat up some of the town's food, which is need for the players to survival.  Pitbulls are deadly.  Having dogs around is a genetic score threat, if not a detriment.  If dogs had uses, it would be a more complex decision about what to do when someone makes dogs.

But as it stands now, advanced players have very good reason to get rid of them quickly, since they positively hinder town productivity and are anti-multi player survival.

**Comment by jasonrohrer** [comment]
Also an interesting stories!

For a game that seeks to have thousands of objects representing many different spheres of human activity, not all of the objects in the game are going to be useful for survival.
