### ISSUE TITLE
Babies which die with worn equipment + content while being hold don't drop  their stuff to a nearby empty tile and it disappears

### ISSUE THREAD

**Issue by FerhatCatak** [jasonrohrer/OneLife#772]
When the baby you are holding dies out of whatever reason and was wearing stuff like cloth and and backpack with stuff inside of it....
it will still turn into a hold skeleton baby without any stuff on it or dropped near by like when dying on occupied tiles like a berrybush where your stuff get teleported to the next free tile. It would be nice to have that same fix for hold baby player that dies with clothes and backpack + content, ty.

### **Steps to reproduce:**
spawn as a eve mom and a baby of that eve mom. Baby gets clothes and other stuff from eve mum then baby disconnects.
I recommend to be 2 players using a specific empty server for this test or a private server.

**Comment by jasonrohrer** [comment]
I can't reproduce this.  I've tested it under various conditions, and the stuff the baby is wearing always drops correctly.

In the case of SIDS (/die), the baby skeleton is left in the parent's hand, and the worn stuff appears at their feet.

In the case of a non-SIDS baby death, the grave appears at the parent's feet, full of the worn clothing.

If the tile is blocked in either case, the stuff (or grave) is pushed to nearby tiles.

There were some issues like this, but they were fixed long ago.  See:

https://github.com/jasonrohrer/OneLife/commit/980f363d72de91f8ee4fa6e69eb68c5b759e0a89

If you're still able to reproduce this bug, please post a video so I can study it.
