### ISSUE TITLE
Prebuilt Mac OneLife app fails to launch due to 32 bit app compatibility with macOS High Sierra 10.13.4 and later

### ISSUE THREAD

**Issue by dougnukem** [jasonrohrer/OneLife#774]
Downloading the prebuilt MacOS binary fails to launch on MacOS Monterey on an M1 arm64 macbook.

> **“OneLife_v217” needs to be updated.**
> The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.
<img width="260" alt="Screen Shot 2021-12-31 at 11 53 29 AM" src="https://user-images.githubusercontent.com/56662/147834672-196c5241-5185-4f36-bb4d-2c116687b622.png">

- https://support.apple.com/en-us/HT208436
> 32-bit app compatibility with macOS High Sierra 10.13.4 and later

I was able to get it to compile from source code, but there are some game display scaling issues.
- #773

**Comment by jasonrohrer** [comment]
Yeah, apple broke backwards compatibility with loads of stuff... again.

I don't have a new Mac on which to compile this, and I decided it's not worth it to keep chasing Apple.  I've spent my life as a programmer doing this.

Meanwhile, my oldest games still run fine on Windows and Linux...

So, Apple is no longer an officially supported platform for OHOL.  I'm still building the 32-bit Mac binary, mostly out of habit.
