### ISSUE TITLE
Leadership Can Get Inherited in Tutorial Areas or DonkeyTown

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#775]
Kilian figured this one, and I saw the far away leadership also.  It's super easy to due this when an Eve is alive or the leader is streaming the game live, since the name is easy to figure out.  It probably also isn't all difficult for someone with two accounts to use one to /die to figure out some family's leader name and then log into a tutorial area or donkeytown with the account with higher genetic score.  It would be even worse with one player sitting in the tutorial area or donkeytown with leadership and someone else trying to kill everyone in the family using conventional tactics.

It likely applies to property gates also.

**Comment by jasonrohrer** [comment]
This has been fixed by these two changes:

https://github.com/jasonrohrer/OneLife/commit/f314f32390a572590764a1c621da00854dba98b3

https://github.com/jasonrohrer/OneLife/commit/cb5e16f7d1d31f52342bb8becea749a2ef96dbe2
