### ISSUE TITLE
/Die Babies Make Bone Clutter

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#776]
A few days ago I'm playing with someone else smithing and a baby pops out of them.  The baby uses /die fairly quickly and the bones end up on a flat rock or clay bowl or clay plate, blocking it from getting used.  This does happen in other stations, but it's the worst in the smithy since it's time intensive.

**Comment by jasonrohrer** [comment]
Sometimes stuff like this happens.
