### ISSUE TITLE
Deep Roots/Lineage Depth Only For Characters With Children

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#778]
How long immediate descendants live gets tracked for male characters via the genetic score system.  It also gets tracked for female characters who don't have children.

However, a character can be a 2nd or 3rd generation male (or long living childless female), make an early contribution to the development of a camp, a family survive a long time, and there's no suggestion of their impact at all, unlike what holds for female characters with children.  They can also feed babies.  Since many female characters die before 14 or don't have descendants that live to 14, this certainly isn't consistent with genetic score, since clearly the male's impact could be greater than the female's impact.

**Comment by jasonrohrer** [comment]
Yeah, genetic score isn't meant to handle every edge case.

It works well for most cases.
