### ISSUE TITLE
Client crashes on /LEADER if leader is out of range

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#783]
If a custom server send PLAYER_OUT_OF_RANGE (PO) for the leader, the client crashes if /LEADER is used.

Since no errors message is given Client seems missing exception heandling for /LEADER crashes

**Comment by jasonrohrer** [comment]
I'm not able to reproduce this.

The server actually sends the map location of your leader, whether or not they are out of range, so the client's knowledge about the leader isn't necessary to show the arrow.

Please re-open if you have more information.
