### ISSUE TITLE
Lanuage Barrier Still Present in a Hierarchy

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#786]
I played a few days ago, and if I recall correctly I was some tan lady (or maybe I was black).  My leaderboard has gone beyond it, but at the time there was an [Eve Ginger](http://lineage.onehouronelife.com/server.php?action=character_page&id=8656298).  When I find her (I had unfollowed my leader and followed her) I find her and her daughter Scarlet I think in the tan band.  Scarlet dies, and I get a message saying that I now follow Eve Ginger (implying she had followed Scarlet).  I get her to her band, but no luck with another child for her.

At some point, she follows me.  At one point I put stuff out so that she can make a basket from straw and a skewer, but it's a slow process, since I can only move things.  I had tested a year or few months ago, and found that if you have a leader not of your race, you just end up with apparently unintelligible nonsense.

I've become leader when I've traveled to other villages occasionally also.  I've haven't thought about issuing any orders, but why would I, since the language barrier prohibits intelligible orders within the context of the game?  The language barrier still existing with leadership definitely could be unfortunate for anyone seeking direction, and willing to ask their leader for direction.

At the very least, the language barrier shouldn't exist in a hierarchy, if the language barrier should exist at all.

**Comment by jasonrohrer** [comment]
This is correct and intended behavior.

This person is from another distant culture, and people can learn their language over time, through multi-generation exposure.

Simply following someone doesn't make you suddenly speak their language.
