### ISSUE TITLE
Inherited Property From Far Away, Loss of Arrow Before Reaching Location

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#800]
When you inherit a property fence from far away, the arrow only lasts a short amount of time.

Suggestion:
/prop or /property to give arrow to the nearest property. 

(Does NOT solve the problem if you have another property in town. 

Though technically, you could axe your "in-town" property gate and have a trusted person make another gate there.)

**Comment by jasonrohrer** [comment]
Good idea!

I have it working so that /property gives you a temp arrow to your most recently-acquired property...

But I'm wondering if that's the best way for this to work.  It could also cycle through them somehow.
