### ISSUE TITLE
cursing multi account users

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLife#801]
As it is it's become popular for people to dodge the curse system by cycling multiple accounts. Or even in some cases twinning with themselves to cause issues while using the presence of two characters to influence the killing ally mechanics.

I think it'd be a net benefit if curses propagated to accounts connected from the same ip address or with the same billing info. That could still be dodged with a vpn, however it'd raise the level of effort.

**Comment by jasonrohrer** [comment]
Yeah, I've decided to not compete in this arms race.  It's always a losing battle.  The harder you make it, the more determined people are to bypass it.

It's easy enough to buy each account with a VISA gift card that can be bought at any drug store.  And VPNs are easy to use as well.
