### ISSUE TITLE
Can't Browse Through Older Photographs

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#802]
On Recent Photographs page (http://photos.onehouronelife.com/server.php?action=front_page), you can only see the most recent 10 photos taken.

Could you add a Next Button? 
(to see older photos)

(Yes, you can click on the little photo icon in the individual person's family tree webpage. Even on older lives. But that would require knowing the person's name.

Since you ALREADY store old photographs anyway [Not just the most recent 10 photos.] .....

Why not allow people to view older photographs in http://photos.onehouronelife.com/server.php?action=front_page ?

It won't take up more storage space. And will give a nice visual history of ohol.

It would also encourage people to take up photography more if their photo can be seen for more than a week or so.

**Comment by jasonrohrer** [comment]
Yes, this was an oversight on my part.  There should be a next button.  Adding one now!
