### ISSUE TITLE
No Vision For A Game on Serious Players Side

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#807]
This is a _one life_ game, where it comes as entirely suitable to judge the game on the experience of one life only or on the last life that a player plays.

It comes as entirely possible that a player gets eaten by a bear without any way to have prevented that bear from eating by the mother (nor by the player whose character got ate).  It has happened many times before.

It comes as entirely possible and has happened many times before that players have gotten born in the wilderness by a mother on a horsecart or driving a truck who can't even observe that the baby got born.  It has happened many times before, and there is no possibility of survival for the baby.

There is no opportunity for the player playing as a baby in either situations.  It ends up an entirely boring and predictable life of a quick death.  There is nothing funny for any player in such a situation as that baby, if they have a "one life" perspective.

It comes as wild misnomer to call a game a "survival" game, when instead it clearly favors the death of it's players.  Such situations show that there is **no vision at all** of players survival being achievable because of their own efforts.  It is boring to have a situation where achievement is not possible, because the system is against you and dooms you.

**Comment by life4ants** [comment]
Survival is a team effort. The first three minutes of your life you can do little or nothing to affect your survival. You cannot control the circumstances of your birth. And that is part of the interesting stories Jason wants to happen. 
There is already a solution to horse cart and truck births - stay at home if you are fertile. 
I agree that there needs to be more uses for bears to offset the huge threat and griefer tool they are. Hopefully Jason has plans for that in his big update.

**Comment by DougLefelhocz** [comment]
> The first three minutes of your life you can do little or nothing to affect your survival.

As a general rule, this is not true.  Players can as a rule run around and find someone that will feed them, even without using something like PXChat.  I personally remember getting born to some player who fed me once who said "I don't need you" and then did some rather destructive behaviors.  I managed to run away and find other players who were willing to feed me.

> You cannot control the circumstances of your birth.  And that is part of the interesting stories Jason wants to happen.

As a rule, he doesn't play his own game.  If those were interesting stories and he had reason to believe that interesting stories were going to emerge from such, then he would have long ago been playing his game on a regular basis and also sought how to make those stories happen more regularly.

Edit: Also, there exists plenty of counter evidence to the proposition that "not controlling the circumstances of your birth" creates interesting stories for people.  The counter evidence lies in that plenty of players, both inexperienced and experienced, use the '/die' command.  Were it the case that players had reason to believe that such would create interesting stories, they would almost never use '/die'.

Conclusion: "not being about to control the circumstances of your birth" is a boring concept for many players.  Many players find control interesting, and find the concept of "accept it and deal with it" boring.

> There is already a solution to horse cart and truck births - stay at home if you are fertile.

No, that's not a solution for all mothers.  It doesn't work for people making oil.  It also doesn't work for any female road makers who make long paved roads in their own band.

Also, and more importantly, it is no solution for the player as the baby.  Claiming that it is a solution basically implies that the perspective of the player playing as the baby should get ignored.  Ignoring the perspective of those most vulnerable is simply not a good idea.
