### ISSUE TITLE
No Permanent Banning of Accounts of Serially Destructive Players: No Equivalent of The Death Penalty

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#808]
This issue got reported [here](https://github.com/jasonrohrer/OneLife/issues/606) with reference to Bobo Bill.

It got reported [here](https://github.com/jasonrohrer/OneLife/issues/744) at the time when Milkman and Post were acting destructively.

Recently, on the discord there have been many reports of Kilian acting destructively.  The [lathe issue](https://github.com/jasonrohrer/OneLifeData7/issues/1003) has gotten reported to have resulted, because of Kilian.  This person has even made [promises](https://onehouronelife.com/forums/viewtopic.php?id=10282) to reform their behavior, which in retrospect veterans have little choice but to regard as false promises.

Of course, such players could buy a new account if an account got banned permanently.  However, is simply false that they rely on one account to begin with.  Already having multiple accounts, they rely on the timing of curses to become inactive with a group of accounts.  The lack of constructive players having the ability to ban a single of their accounts permanently means that those players lack any method to ban a single one of these accounts and the destructive players account number can remain small, and there does exist a number of accounts which can suffice for their destructive purposes.

Were it the case that permanent banning of serially destructive players did exist, there likely would not exist a perceivable number of accounts that the destructive player could have to continue to act destructively.  It would also mean that constructive players would have a method to give those players an equivalent of "the death penalty", because the multilife "projects" of serially destructive players could get made impossible since they might not have the means to purchase an unknowable number of accounts.

Edit: It would also mean that players would have the ability to seriously judge other player's actions as meaningful or not.  There is a serious problem when people get discouraged from becoming judgmental.

And really, it should be up to players discretion whether or not _movement of players to donkeytown by ip addresses_ should or should not occur.  Players need that sort of ability to have REAL _decision_ making ability.  They need that sort of ability to exercise moral judgment.

It is also a rather boring story as it stands. The story for serially destructive players goes something like this:

"Accept that there will be these types of people"

or

"Deal with those types of people."

Yawn.

There is no possibility of the community ever having a basis for developing a story like this:

"You, Kilian, have repeatedly violated community standards.  You have repeatedly lied with false claims to the community.  We condemn your actions and since you have shown yourself a liar repeatedly, we have no choice but to condemn you.  Perhaps this is a God who will have mercy on your soul.  But, as far as many of us are concerned, we believe that there is a God who will make you rot in Hell."

Only some critic has said that, **AND OUTSIDE OF THE GAME**.

**Comment by jasonrohrer** [comment]
When you curse someone, they won't be born near you for 90 days.

Thus, each player, individually, can decide what behavior counts as "destructive" and what they don't want to be around.

Of course, there's no way to ban someone who is using multiple accounts.

If we try to do it by IP address, they will just renew their DHCP lease to get a new address, or use a VPN to disguise their address.
