### ISSUE TITLE
Curse Logs Issue

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#809]
You know how people time and again keep saying, I don't know why I'm in Donkey Town, I only got a few curses! Curse logs only show 5 curses. (or something similar).

There's a reason for that.

Because when they check curse logs. Or have the program check their curse amount....the data is NOT complete.
(Sometimes, they ask vet players (usually Methman) in discord to check their hash and curses.)

'Curse my baby' curses **_DO NOT_** show up in the curse logs.

For example, some user I know asked Methman how many curses she got using the hash checker app/program, it said only 3 curses. And the person was in DT. (This example was from a few years ago.)

It's coz that person is a frequent SIDS-er.

And the 'curse my baby' curses don't show up in the logs.

When I first discovered this, I decided to check the curse logs (for the first few times) when I saw a female use 'Curse My Baby'. Every time, the curse WASN'T in the curse logs. I've also checked it myself by using 'Curse My Baby'. Nothing.

**Comment by jasonrohrer** [comment]
Thanks!  Looking into this.

**Comment by jasonrohrer** [comment]
Ah... I'm seeing now that there's no such thing as a "curse score" anymore.

Individual players curse someone which essentially says, "Don't let that person be born near me for 90 days."

You only go to d-town if enough people have cursed you so that you can't be born anywhere.
