### ISSUE TITLE
Knife used to remove arrowhead or treat snake bite deadly.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#81]
Knife - surgery (the knife after removing an arrowhead from a wound or after putting an antivenom knife into a snake bite) is deadly. Produces no wound, no murder cooldown, is essentially a three second butter knife.

**Comment by jasonrohrer** [comment]
Fixed here:  https://github.com/jasonrohrer/OneLifeData7/commit/ef1ef5eeff34296ec7a09dc08295dac8c88907e0
