### ISSUE TITLE
Visual Loss of Curse Token Icon When Reconnecting

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#821]
![image](https://github.com/jasonrohrer/OneLife/assets/61180955/98d7033d-dcf9-429f-a46f-f29e6c60f83c)

When you disconnect and reconnect (or when you close then reopen the game), the Curse Token Icon (see picture above) doesn't show up anymore. 

But you are still able to curse (i.e. you still have your curse token).

But of course, players do NOT KNOW that they still have their curse token since they rely on the visual cue.

**Comment by jasonrohrer** [comment]
Looking into it.  Thanks for this report!
