### ISSUE TITLE
2 Servers Active, 2 Lives At The Same Time: Confusing for Newbies

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#822]
Occasionally when TWO servers (bs2 and s1) are active (usually when a tiktok / youtube video goes viral or when there's a steam sale), you would get a rare question on discord....

Why did they spawn as a baby (when reconnecting after disconnecting) when they were an adult when they got disconnected?

Or the reverse, why are they an ginger lady when they were a jungle boy when they got disconnected?

-----

Apparently, the game doesn't AUTOMATICALLY reconnect you to your life when there are 2 servers active at the same time.

And since the game (afaik) randomly chooses which of the 2 active servers you login to, it may result in you logging in to a different server as a baby.

(New players don't have 'Use Custom Server' checked. So they bounce from one server to another.) (Most of the casual players also don't have it checked. Since usually, the game only has 1 active server.)

(Technically, I've never actually experienced this myself. So, I'm not actually sure. 

But I'm speculating the cause of the issue is that the game doesn't AUTO-connect you to the same server you were on before disconnecting. Instead, I'm guessing it randomly places you in one of the 2 active servers.

I don't actually know if it happens only if you go to the main menu of the game to login or this also happens on a regular disconnect-reconnect. 

Never tested it. Can't test it now since there's only 1 server active.) 

-----

Not a big problem. Only happens when a video goes viral. Just slightly confusing for newbies.

**Comment by jasonrohrer** [comment]
Looking at the code, it seems like the client will auto-reconnect you to the same server again when you press OK after disconnecting.

However, if you actually quit the game (or the game crashes) and you come back in, the whole connection process will start over.  You ask the reflector where you should go, and it tells you.

The reflector is separate from the game server, so it doesn't know whether you're still alive or not.  But it is currently re-rolling the dice each time you ask it for a server.  This change was made on purpose back in 2019:

https://github.com/jasonrohrer/OneLife/commit/9ced1fb43d768aaf214dc881ad46a744dcbc169b

It used to seed its random number generator just with your email, which meant that under similar server conditions, you'd go back to the same server over and over.

I'm not sure what the motivation for this change was...

**Comment by JustinLove** [comment]
The reasoning at the time - which you can certainly re-evaluate - was that players tended towards a certain server (this was in the early days of 4ish servers), and new players might always end up on a peak capacity server, never seeing the established towns on the lower servers.

**Comment by cordy-123** [comment]
Hmmm....I think NEW players would be impacted the most by the change / loss of a life they lived. 

Coz they have the most innocent view of the game. 

And are the most likely to be attached to their mother/child/etc. in their gameplay.

This issue doesn't really affect long-time players like myself. 

And since this issue occurs when there are a lot of new players..........

**Comment by JustinLove** [comment]
We are definitely living in different times and a change may be good. But I looked at news posts dates from around that time and found the original explanation if you want more context.

https://onehouronelife.com/forums/viewtopic.php?id=4930

>"logic in the player distribution code tries to make sure a given player always plays on the same server, whenever possible.  So, depending on the time of the day that you play, and the luck of the draw, you might get stuck always being born on an overflow server right before a population downturn"

**Comment by jasonrohrer** [comment]
Keep in mind that the "new player" issue we're talking about is hopefully very very rare.

It only happens if their game client actually crashes, which it should never do.  If it crashes, we should fix that crash.  And if it's crashing enough for new players to affect them, it should be crashing frequently for veterans too, so they should be able to help us track down and fix the crash.

If they simply disconnect due to a network outage (cat pulls the cord), they will be able to reconnect to the same server again (because the client remembers where it connected last and tries to reconnect).  Of course, network outages our outside our control---we can't fix them---but the game currently handles them intelligently.

The other way this can happen to a new player is if they quit the game entirely, on purpose.  In that case, they may be shocked if they're sent to a different server and don't resume the life they quit.

But why are they intentionally quitting the game anyway, if they are so attached to this life?

I suppose it's still worth fixing, in that very rare case...  I'm thinking about a way to do it.

**Comment by jasonrohrer** [comment]
Yeah... looking at the reflector code, it would require quite a lot of complex engineering work to have it communicate with the servers to check if a player is still alive.... and also a new game-server protocol message to securely check on the "alive" status of a given account (we don't want that being checkable by the general public).

The dumb version of this would be to have the reflector remember each player who was sent to a given server less than an hour ago, and re-send them back to the same server again (regardless of whether they were still alive there or not).  But this suffers from the other problem, where a new player who is dying young over and over keeps getting stuck on the same server, and doesn't get to experience the full variety of situations in the game.

So it seems like a full day or two of work to fix correctly, which probably isn't worth it for such an extremely rare issue.
