### ISSUE TITLE
I got it running on mac, but no sound

### ISSUE THREAD

**Issue by askilada** [jasonrohrer/OneLife#823]
Hi 

This is an information and maybe a help for others with Mac

I'm running a MacBook Pro M1 and got the game up and running. One caviar tho, there will be no sound.

Steps:

1. Run `./pullAndBuildLatest`
2. Run `./runToBuild 2`
3. Edit `OneLife/gameSource/Makefile`

Add the following to `PLATFORM_COMPILE_FLAGS` 
* `-arch x86_64` This is because the SDL library does not support arm
* `-I/Library/Frameworks/SDL.framework/Headers`  If you place the `SDL.framework`-file in `/Library/Frameworks` (which it should be) (SDL.framework can be found in previous versions of `OHOL.app/Frameworks`
*  `-F/Library/Frameworks` Framework search path

5. `cd OneLife/gameSource`
6. `make`
7. Navigate back to project and run the following 

```bash
echo "Making directories"
mkdir -p graphics
mkdir -p otherSounds
mkdir -p settings
mkdir -p languages
mkdir -p reverbCache
mkdir -p groundTileCache

echo "Copying items from build into directories"
cp OneLife/gameSource/OneLife ./OneLifeApp
cp OneLife/documentation/Readme.txt .
cp OneLife/no_copyright.txt .
cp OneLife/gameSource/graphics/* ./graphics
cp OneLife/gameSource/otherSounds/* ./otherSounds
cp OneLife/gameSource/settings/* ./settings # There is no -u argument on cp mac, so this is removed
cp OneLife/gameSource/languages/* ./languages
cp OneLife/gameSource/language.txt ./
cp OneLife/gameSource/us_english_60.txt ./
cp OneLife/gameSource/reverbImpulseResponse.aiff ./
cp OneLife/gameSource/wordList.txt ./
```

# To build .app

1. `cd OneLife/build`
2. `mkdir -p mac/<version>`
3. `./makeDistributionMacOSX <version> onelife /Library/Frameworks`
4. the finished product can be found at `OneLife/build/mac/OneLife_<version>`

# Audio error message

```text
Unable to open audio: Failed to start CoreAudio: AudioUnitInitialize
```

**Comment by jasonrohrer** [comment]
I'm guessing that the audio issue is something that has changed in CoreAudio since that version of SDL was last built.

Thanks for posting this.  I will leave it up for now to help other mac users.

**Comment by askilada** [comment]
Yeah you are right. For what I could figure out it looks like the de deprecation of SDL1.2 which causes this issue.

I understand you want to focus on new features and bug fixes. Maybe the community could come together and upgrade the SDL, if you are up for that tho. 

If so, what do you think we could do to ease this process for you?

**Comment by jasonrohrer** [comment]
Oh boy, that's a huge task.

It's not just about switching the code to use SDL 2.0, which is hard enough (there are many little peculiarities to SDL 1.2 that the code currently works with/around.... and there will be a whole set of different peculiarities in 2.0)....

It's also switching the build process on all the supported platforms, which itself is very complicated.

It's essentially oodles of technical debt from a 7-year dev process.


It would probably be easier to fix SDL 1.2 to work on Mac than to fix the entire OHOL stack to work with SDL 2.0

I'm guessing that getting the sound working in SDL 1.2 for mac would be a few lines of code changed deep down in SDL somewhere...


But also... did you somehow get a 64-bit or M1 build of SDL 1.2?  Where did that come from?

I thought Apple had dropped support for 32-bit stuff...

**Comment by askilada** [comment]
Yeah that's a good point bringing up, I'd properly look a little into how SDL1.2 does the sound for mac in the coming week. 

I actually got the x86_64 from you
This is from the SDL version you are shipping.

```text
file /Volumes/One\ Life\ v217/OneLife_v217/OneLife_v217.app/Contents/Frameworks/SDL.framework/SDL
/Volumes/One Life v217/OneLife_v217/OneLife_v217.app/Contents/Frameworks/SDL.framework/SDL: Mach-O universal binary with 3 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386Mach-O dynamically linked shared library i386] [ppc:Mach-O dynamically linked shared library ppcMach-O dynamically linked shared library ppc]
/Volumes/One Life v217/OneLife_v217/OneLife_v217.app/Contents/Frameworks/SDL.framework/SDL (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/Volumes/One Life v217/OneLife_v217/OneLife_v217.app/Contents/Frameworks/SDL.framework/SDL (for architecture i386):	Mach-O dynamically linked shared library i386
/Volumes/One Life v217/OneLife_v217/OneLife_v217.app/Contents/Frameworks/SDL.framework/SDL (for architecture ppc):	Mach-O dynamically linked shared library ppc
``` 

This is not for the arm version but, m1/m2 should be fine emulating x86_64, I'm running M1 without problems

**Comment by askilada** [comment]
It was actually quite easy to fix the sound. Just had to download the SDL1.2 change some build settings for XCode and it builded fine, and I now have sound.

This is a patch to the [SDL1.2 ](https://github.com/libsdl-org/) 
```patch
diff --git a/Xcode/SDL/SDL.xcodeproj/project.pbxproj b/Xcode/SDL/SDL.xcodeproj/project.pbxproj
index 7563a6b6..e079753b 100644
--- a/Xcode/SDL/SDL.xcodeproj/project.pbxproj
+++ b/Xcode/SDL/SDL.xcodeproj/project.pbxproj
@@ -1703,7 +1703,7 @@
                00CFA621106A567900758660 /* Release */ = {
                        isa = XCBuildConfiguration;
                        buildSettings = {
-                               ARCHS = "$(ARCHS_STANDARD_32_64_BIT)";
+                               ARCHS = "$(ARCHS_STANDARD_64_BIT)";
                                DEPLOYMENT_POSTPROCESSING = YES;
                                GCC_ALTIVEC_EXTENSIONS = YES;
                                GCC_AUTO_VECTORIZATION = YES;
@@ -1737,12 +1737,13 @@
                                HEADER_SEARCH_PATHS = /usr/X11R6/include;
                                INFOPLIST_FILE = "Info-Framework.plist";
                                INSTALL_PATH = "@rpath";
+                               MACOSX_DEPLOYMENT_TARGET = 11.0;
                                OTHER_CFLAGS = "$(OTHER_CFLAGS_$(CURRENT_ARCH))";
                                OTHER_CFLAGS_i386 = "";
                                OTHER_CFLAGS_ppc = "";
                                OTHER_LDFLAGS_ppc = "-prebind -seg1addr 0x30000000";
                                PRODUCT_NAME = SDL;
-                               SDKROOT = macosx10.8;
+                               SDKROOT = macosx;
                                WRAPPER_EXTENSION = framework;
                        };
                        name = Release;
@@ -1801,7 +1802,7 @@
                00CFA627106A568900758660 /* Debug */ = {
                        isa = XCBuildConfiguration;
                        buildSettings = {
-                               ARCHS = "$(ARCHS_STANDARD_32_64_BIT)";
+                               ARCHS = "$(ARCHS_STANDARD_64_BIT)";
                                GCC_ALTIVEC_EXTENSIONS = YES;
                                GCC_AUTO_VECTORIZATION = YES;
                                GCC_ENABLE_CPP_EXCEPTIONS = NO;
@@ -1831,11 +1832,12 @@
                                HEADER_SEARCH_PATHS = /usr/X11R6/include;
                                INFOPLIST_FILE = "Info-Framework.plist";
                                INSTALL_PATH = "@rpath";
+                               MACOSX_DEPLOYMENT_TARGET = 11.0;
                                OTHER_CFLAGS = "$(OTHER_CFLAGS_$(CURRENT_ARCH))";
                                OTHER_CFLAGS_i386 = "";
                                OTHER_CFLAGS_ppc = "";
                                PRODUCT_NAME = SDL;
-                               SDKROOT = macosx10.8;
+                               SDKROOT = macosx;
                                WRAPPER_EXTENSION = framework;
                        };
                        name = Debug;
```


I'm running MacOS 12.6 M1.

**Comment by jasonrohrer** [comment]
Well, I don't have the ability to build 64-bit stuff on Mac...

But also, I imagine that if I incorporate your 64-bit SDL build into my Mac OHOL distribution, it might break on the few Mac platforms that it still runs on.  I.e., someone has a 64-bit MacOS with Rosetta working on it, that can run the 32-bit binary, but still use the 64-bit SDL library?  Maybe?

Wondering... if you're a mac dev, is there some way you can set up some kind of automated cron-job type thing on a server somewhere that would watch github for version tags and make these 64-bit builds?

Then there would at least be a source for them.

The hard part is the auto-update stuff, which will try to download the 32-bit mac version, but I suppose people could turn that off somehow.  But they'd still need to get the content updates, just not the binary updates.


I guess the only fool-proof way would be for a cron job to build the whole thing each time, including when the content changes, and serve that.  So poor 64-bit mac users would have to download the whole DMG again each time, but it's better than nothing.


Finally, while 64-bit code is running on the M1 now.... given Apple's track record, I bet it won't be working for very long.  In my lifetime, they have switched chip architectures 4 times, and offered backwards compatibility for only a short while after each switch.

OHOL is currently broken b/c of the switch from 32- to 64-bit, and the dropping of Rosetta for backwards compatibility.  And look, they've already moved on from 64-bit already to the M1!

**Comment by skps2010** [comment]
Use SDL library instead of SDL framework also solve the no sound problem.
You can get the library by `brew install sdl12-compat`

In the Mac OS X makefile `Makefile.MacOSX`, replace `-framework SDL` by `-lSDL`, then you can comepile it.
