### ISSUE TITLE
The /DIE command no longer kills the player

### ISSUE THREAD

**Issue by tommai78101** [jasonrohrer/OneLife#828]
Right now, in the latest stable release on Steam (I believed it's Update 123, the Rail Buffer Update), when you type `/DIE`, instead of killing the player (and thus returning the player to the main menu after an early death), it loads up a tooltip prompt mentioning how you can make a single [die](https://onetech.info/1956-Die).

This is an issue when the player is currently playing the Tutorial, and they wanted to go back to the main menu early during their play session by dying an early death, but they can't jump back to the main menu because of the `/DIE` command not killing the player.

**Comment by cordy-123** [comment]
The slash die command only works if you are under 2 years old.

Therefore, it won't work in tutorial.

**Comment by tommai78101** [comment]
I see. In order of precedence, does it kill you first, or displays how to make a single die in the tooltip first?

**Comment by jasonrohrer** [comment]
All the slash commands take precedence, and if none of them match (for whatever reason), then the slash triggers tool-tip filtering.

In the case of /die, it stops matching after 2 years old, and then falls through to being used as a filter.

**Comment by tommai78101** [comment]
Thanks for clarifying this.
