### ISSUE TITLE
Knife cant mash stuff in bowls

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#83]
Not sure if intended but:

Bowl of Rabbit
Bowl of Gooseberries and Carrot
Bowl of Carrot
Bowl of Gooseberries And Rabbit
Bowl of Rabbit and Carrot
Bowl of Gooseberries, Rabbit, and Carrot

Cant be mashed with the knife

**Comment by jasonrohrer** [comment]
Yeah, I think the sharp stone is a more appropriate mashing tool for now.

The knife is really about cutting stuff.
