### ISSUE TITLE
Problems with passing gate ownership

### ISSUE THREAD

**Issue by lorocyproca** [jasonrohrer/OneLife#831]
If there are multiple property gates owned by a player: any phrase that passes ownership including "you own this" "my family owns this" or "firstname lastname owns this", will only pass ownership of the gate closest to the speaker. If the phrase is repeated, it will not pass on any gate other than the gate closest to the speaker. Additionally, if the gate is axed down, that gate will exist as a phantom that counts as the closest gate, thus preventing passing ownership of any other gate further away.

**Comment by cordy-123** [comment]
Can you just not walk to the other gate to give ownership?

Usually, the gates in town are within a couple of tiles to each other.

**Comment by cordy-123** [comment]
Most towns only have a few gates.


The town property that holds the most important stuff (trucks, oil tanks, engines) usually only have 1 to 2 gates. The most is maybe 3.

Plus, if the person you are transfering the gate to already owns one of the gates of the property, they don't need another one anyway.

**Comment by jasonrohrer** [comment]
This is working as intended, to avoid confusion.  Whatever gate you are standing closest to is what is assigned, even if it's already assigned.

However, the "phantom gate" issue is one that I will fix.

**Comment by jasonrohrer** [comment]
Ah, there's another issue, where if you smash a gate and then build your own in that spot, the previous owners retain ownership and can open your new gate.
