### ISSUE TITLE
Gate Ownership Transfer Problem

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#832]
The command radius for property gate ownership transfer is **TOO LARGE**.

----

In two ways.

1. You can give the gate to someone who is thousand of tiles away.

2. Even if you (the owner) are thousand of tiles away from the town gate, you can give ownership of it to other people from that far away.

----

This has been used to grief by veteran griefers. 

For example, you own gate to the arctic town's property fence. 

You go the desert fam and get a name there. 

You can give the arctic town gate to that desert person. 

(You **DON'T** even have to return to your arctic town to give the gate away. Since you (as the owner) can give away your gate ownership even though you are thousand of tiles away from the actual gate.)

So now the desert fam owns the arctic town gate. 

With the use of the hetuw mod, you don't even need to go to that fam to get a name for a desert person to pass the gate to.

----

It takes too long to undo. Especially if you use vanilla mode.

Let's say the two towns are 2 thousand tiles away.

You see your arctic town gate is owned by a desert fam person.

Memorize the name. 

Go there with pencil, paper, rubber ball.

You have to find the expert waystone, go 2k, and find the gate owner and have him pick up your note and have a 5-10 minute paper translation conversation with him.

(And that's the easy version.
Sometimes, they don't pick up your paper note. (It happens.)
Maybe the person is a noob and can't understand the problem/mechanics.
Maybe the person is NOT in town and is travelling.
Or it is very plausible that while you're travelling 2k to their town, the desert fam gate owner died on your way there. And now, you have to go back to your town to find out the name of the new desert fam owner.
Etc.)

----

Real example:

http://lineage.onehouronelife.com/server.php?action=character_page&id=9267882 (this life is from an alt account of a prolific griefer.)
Female Starlin's final words : "Mary redhead owns this"

-> as you can see here (http://lineage.onehouronelife.com/server.php?action=character_page&id=9267993), Mary Redhead was of a different race

----

The **solution** is probably to have **BOTH** the gate owner **AND** the person receiving gate ownership be within a couple hundred tiles from the gate itself.

----

**Comment by jasonrohrer** [comment]
So people are doing "Bob Jones Owns This", and it's finding the closest property.... as long as you only have one, it assigns whatever one that is, no matter how far away?

Yeah, that doesn't make sense.... it should really only work if you're standing very near the gate.  Will fix.

**Comment by teliot** [comment]
Needs a bit more IMO.
Additionally the griefers are making remote all gates property perimeter to secure their target area. Then when they need to access that gated area they kill off that family so the gates will fall, and then make new gates with a new family once they have finished their activities.
With this new commit they can still do this.
This first picture shows an area that a griefer can regain access to once them and their team kill off 2 very far away families.
https://cdn.discordapp.com/attachments/328215300279500800/1099765424264065107/Screenshot_20.png
https://cdn.discordapp.com/attachments/1055586873885605928/1118612247493754881/image.png
https://cdn.discordapp.com/attachments/1055586873885605928/1118265982658556054/Screenshot_2023-06-13_at_1.52.34_PM.png
https://cdn.discordapp.com/attachments/1055586873885605928/1114743789668544614/image.png

**Comment by cordy-123** [comment]
Question?

In your fix (https://github.com/jasonrohrer/OneLife/commit/b4813a800014319ba26d613ea6d8354e55818fa7), it says "You have to be closer than 20 tiles away from a gate to assign ownership of it to someone else."

This does NOT address half of issue above wherein the owner can give ownership to a person who is thousand of tiles away?

(Sorry, if it already addresses it, I can't read code. :D )
