### ISSUE TITLE
Server 13 currently unplayable.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#834]
When you did the test for the posse client crash you changed the settings to force all people to spawn at 0,0 and all players to spawn as Eves. 

Someone decided to put up walls around the Tarr Monument on that server so everyone spawns at 0,0 and starves.

**Comment by jasonrohrer** [comment]
Whoops, yeah, I left server 13 hanging!

**Comment by jasonrohrer** [comment]
Fixed
