### ISSUE TITLE
Donkey Town Cursed Players Can't Be Born Together

### ISSUE THREAD

**Issue by ShadyCantCode** [jasonrohrer/OneLife#835]
The issue is that cursed players that are in donkey town are homesick and can't have cursed babies on the north or south side of donkey town. This makes donkey town more like a (90 day solitary confinement) for anybody who has been cursed to donkey town. I'm not sure if what's preventing this is the homesick barrier or if it's the thing that allows donkey town players to see each other's names.

![image](https://github.com/jasonrohrer/OneLife/assets/136979737/12d356ce-d08e-40a3-ae37-99dcab618e63)

**Comment by cordy-123** [comment]
Not having children in DT is intended.

------

Regarding your title "Donkey Town Cursed Players Can't Be Born Together", you can be born together technically. You can twin together in DT.

**Comment by jasonrohrer** [comment]
Yeah, if it's intentional, I can't recall the reasoning.

DT is supposed to be something of a penal colony...

I'm looking into this.
