### ISSUE TITLE
Fed mouflon lamb does not cross biome border

### ISSUE THREAD

**Issue by MrXIX-OHOL** [jasonrohrer/OneLife#836]

**Comment by TheMingo888** [comment]
This is going to be a problem if horses are able to flee into restricted biomes now. This should still be prevented.

**Comment by cordy-123** [comment]
> This is going to be a problem if horses are able to flee into restricted biomes now. This should still be prevented.

Not really, since you can chase horses from inside the hostile biome to the nearby mountain biome since you can enter (though not touch anything) hostile biomes.
