### ISSUE TITLE
Can't pass ally gate when the leader follows me

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLife#840]
I could pass ally gate, but once the leader followed me and I became Baroness, I couldn't pass it anymore.

**Comment by cordy-123** [comment]
Probably coz it's a follower gate? (It used to be an ally gate before Mr. Rohrer changed it here https://github.com/jasonrohrer/OneLife/issues/688, https://github.com/jasonrohrer/OneLife/commit/e4c99404cb68a8016539f4fd4fe29f363c4a22d4)

You would have to follow the owner of the gate.

**Comment by jasonrohrer** [comment]
Yes, I tested this behavior, and it's true that it works this way.

The person who created the gate is the original owner of it, and it's a Follower Gate, so their followers can go through it.

If they follow one of their own followers, that person moves *above* them and is no longer their follower (so they can't go through the gate), and the original owner still owns it.

However, all that the owner (the Lady) has to do is say "You Own This" to the Baroness.  Then the gate has TWO owners, and all of their followers can go through.  This allows the Baroness to go through.
