### ISSUE TITLE
Eve spawns out of control

### ISSUE THREAD

**Issue by SelfSealShelf** [jasonrohrer/OneLife#841]
The current eve spawns system is generating 14.7 new eves per day, an average of 71 horizontal meters apart. The distance wouldn't be an issue if it weren't for that being just the horizontal component. The actual distance is much further when accounting for the 200 meters between each band.

1km per day is too much to keep up with. In the past the eve spawn mechanics were much more lenient, snaking around at a leisurely pace. While we now have trucks and roads to help transport things it's much too difficult to keep up with new eve spawns. Even the longest roads fall short, and no town can last any notable length of time as the distance from new spawns grows.

A good example of this is the bell tower. If an eve camp starts working on their bell tower 2 hours after the eve spawns then it won't be finished until _at least_ 27 hours into the lifespan of the village, during which time the eve spawn will have advanced 1,170 meters. Most players wouldn't be able to make that trip on foot if the family that built it dies and rings the bell to attract the new eve.

I'd like to suggest each of the bands get two spawn tracks. Instead of eves spawning directly in the center of their band they should spawn 50 meters from the border, and alternate sides. This should allow eves to pack into the band a little tighter without them spawning less than 100 meters from where any other eve spawned. The horizontal westward direction can then be reduced.

[Here is the analysis for where I got the numbers in this report](https://onehouronelife.com/forums/viewtopic.php?id=10276)
Some of the info there may show other useful peculiarities about the eve spawn that I haven't gone over here.

**Comment by jasonrohrer** [comment]
This was so long ago that I suspect things are different now.  Please open a new issue if this is still a problem.
