### ISSUE TITLE
Separate client and data versions

### ISSUE THREAD

**Issue by selb** [jasonrohrer/OneLife#845]
It would be nice if the server sent the required data and client version numbers after the current combined value in the SN message. This would allow modded clients to distinguish between "modded client needs an update" and "data files need an update" and give appropriate guidance to the user when there is a mismatch. It may also allow modded clients to use the vanilla update functionality in cases where the data is what's out of date.

The main issue is that these two cases of "old version" have very different resolutions when using mods, but users end up conflating the two for lack of accurate feedback from the client. The most common "old client" fix is to bump `dataVersionNumber.txt` to override `game.cpp:versionNumber` and bypass the check until the mod is updated; on its own, this works well most of the time. However, this backfires badly when mistakenly recommended in the "old data files" case: for non-Steam users, data updates get skipped, which can then go unnoticed over multiple updates if data updates are minimal enough, resulting in a confusing, near-unfixable mess of an install directory that can't even run vanilla anymore.

**Comment by jasonrohrer** [comment]
Hmm...  I don't want to spend time trying to officially support mods (it's enough for me to worry about keeping the official version of the game working well).

It seems like this is something that the mods could handle on their own, somehow, using github maybe?

Like... they can just use HTTPS to pull this file, correct?

https://raw.githubusercontent.com/jasonrohrer/OneLifeData7/master/dataVersionNumber.txt

Likewise, the mods could look here for the binary client version number:

https://raw.githubusercontent.com/jasonrohrer/OneLife/master/gameSource/game.cpp


Then, the mods could display an appropriate message to the user, based on whichever case applies.

**Comment by selb** [comment]
Yep, that would work fine! Definitely understand not wanting to support mods, but I figured I may as well ask before trying too hard. :)
