### ISSUE TITLE
Missing Grandmothers

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#846]
After the last update, grandmothers are **NOT** showing up on people's leaderboard scores.

(Presumably **GREAT** grandmothers and **GREAT GREAT** grandmothers are missing too. 
Harder to find instances of great grandmothers so I didn't bother looking for it to actually confirm that.)

I checked THREE different leaderboards, all of them have their grandmother missing from their score (even if they lived to 60).

----------

Example I found from fam tree: 

As you can see in the screenshot below, Sally Burke's grandmother does not show up in her gene score. 

![image](https://github.com/jasonrohrer/OneLife/assets/61180955/78d60f31-4d02-4aa4-8c98-d48305cd5ec1)

--

And here, you can see that grandmother died 44 MINUTES before Sally Burke. Both lived to 60.

(Meaning that Sally Burke was 16 years old when her grandmother died. 

Therefore, the rule exception of your grandmother's death does NOT give you gene score if the grandmother dies before you are 3 years old is NOT to blame for the missing grandmother gene score in the leaderboard.)

![image](https://github.com/jasonrohrer/OneLife/assets/61180955/e14b1959-d804-4523-99f2-ea815bbf1b21)

**Comment by jasonrohrer** [comment]
Great find...

... are we sure that grandmothers were correctly showing up in the leaderboard scores before, though?

**Comment by jasonrohrer** [comment]
Interesting... the "granddaughter" relationships aren't showing up either...
