### ISSUE TITLE
Babys dissapear

### ISSUE THREAD

**Issue by BriNaners** [jasonrohrer/OneLife#847]
me and 3 others maybe 5 baby's jus disappeared after mom put us down. one died eventually and showed back up another grew up quite a bit then was visible again. I had to quite game couldn't move or interact with anything also couldn't see myself. unless someone accidently picked me up. somone could see us that wasnt our mom but after we wer picked up couldnt see us anymore when we wer put back down.

**Comment by BriNaners** [comment]
Well you probably don't know how to play the game!

**Comment by cordy-123** [comment]
Any chance it's due to bad internet connection?

**Comment by BriNaners** [comment]
nah, it happend to me and atleast 3 others was a game error.

**Comment by BriNaners** [comment]
plus it wasnt just me not seeing us mom couldnt and another person could see us at first then couldnt after mom found us and put is back donw. i shut down my game and restarted it. i was the same person like 15 when i came back and everything was fine. def weird game glitch tho

**Comment by jasonrohrer** [comment]
Thanks for this report!

Hopefully someone can catch a video of this at some point so I can track it down.

However, it sounds like a pretty rare issue, so I will close this for now until we can get some more info.
