### ISSUE TITLE
the linux (ubuntu) version has all the text upside down and sometimes blank version v377

### ISSUE THREAD

**Issue by Nika50501** [jasonrohrer/OneLife#848]
I ran a fresh install and followed the steps listed exactly as they are listed but all the menus and text related items are broken. Some of them are upside down and some of them are just blank. it was the same way (upside down) for the last weeks version too.

I'm not sure what could be causing it but when you run the installer it gives the following types of warnings 
" ../../minorGems/graphics/RGBAImage.h:224:22: warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
224 | register int i = 0; "

**Comment by jasonrohrer** [comment]
Yeah, I've heard reports of this from time to time.

It works on all of my Ubuntu machines (Ubuntu is my daily driver that I use to develop the game).

I'm pretty sure it's some kind of graphics card or driver issue.  The fonts are all texture maps, after all.  That's all my own code which leverages OpenGL triangles and texture maps to render the fonts., not some kind of platform-based font stuff.  So it should work identically on all machines.

But the fact that they are upside down makes me think that your graphics card is inverting an axis, or something.

What kind of GPU do you have?

Do textures look weird inside the game itself?  Like are parts of characters updside-down or missing?  And how do the in-game fonts look?  Like the hand-written fonts (pen and ink).

Can you provide some screen shots?

**Comment by Nika50501** [comment]
It's not the gpu's fault. The tga files inside the graphics folder are upside down for some reason Those files include text items and menus which are not rendering properly (files in other folders are correct side up and display correctly too). If you flip them over manually and replace them they display correctly. I've attached the screenshots below.

To fix my game I copied over the graphics folder from the prebuilt v217 linux binary into my game folder and it works fine now. note that using the graphic folder from this github repo gamesource folder didn't work and just managed to crash the game, probably because of different compression types. 


![Screenshot from 2023-07-03 17-16-48](https://github.com/jasonrohrer/OneLife/assets/41132232/9714de6b-0cc9-493a-a420-6c7cba55bed8)
![Screenshot from 2023-07-03 17-16-57](https://github.com/jasonrohrer/OneLife/assets/41132232/1699754e-c910-4ec8-bd62-b5e8c6984e21)

**Comment by selb** [comment]
Just to be clear, I think you're using the UnixSource download, not the prebuilt Linux version.

I can confirm that the first screenshot exactly matches my experience when using the UnixSource download on Ubuntu 22.04.

The good news is that the OneLifeApp binary built by the UnixSource download is perfectly fine. I downloaded the Linux package, replaced the 32-bit OneLifeApp with the UnixSource equivalent, and everything worked as expected.

(edit: Sorry, I'm dumb. You already said basically all of this... well, at least I helped confirm the issue? :|)

**Comment by selb** [comment]
I think there's more going on here than just UnixSource vs. Linux. Here's the tutorial with the UnixSource binary on the Linux download's directory, after data updates:

![image](https://github.com/jasonrohrer/OneLife/assets/741853/8561fcd3-7d50-4927-90e3-73dcb8aaa2ba)

I'm almost certain I've seen someone complaining about this exact issue (skintones graphic showing up) on the discord. The same UnixSource binary, but running in the directory of a Windows download (extracted on Linux with `7za x`), after doing updates via wine:

![image](https://github.com/jasonrohrer/OneLife/assets/741853/c49a728b-2288-4c58-98ea-da55cb25ab66)

This issue doesn't show up against a Steam install directory, either. There really seems to be something wrong with the Linux distribution's data files as well, even if it's not as bad as the UnixSource build's issues.

**Comment by Nika50501** [comment]
The pre-compiled version of Linux has the old version of the game, the two images right above are the result of some sprites missing. You just need to download and compile the game from source to get the most recent version.

**Comment by selb** [comment]
I do understand that. These are both running the same newly-compiled binary. The top one is running on the Linux .tar.gz's install directory. The bottom is on a Windows install directory.

**Comment by Nika50501** [comment]
Can you double check the version number and post it? its next to the download link 
> I do understand that. These are both running the same newly-compiled binary. The top one is running on the Linux .tar.gz's install directory. The bottom is on a Windows install directory.

**Comment by jasonrohrer** [comment]
Aha!  This is a really interesting issue.

If the TGA files themselves are upside down, it must be imagemagick's "convert" command that's causing this.

Check out the PNG files in the graphicsSource folder.... do they look okay?

At the very end of the build process, "convert" is invoked like this:

```
convert graphicsSource/font_32_64.png -type truecolormatte graphics/font_32_64.tga
convert graphicsSource/font_handwriting_32_32.png -type truecolormatte graphics/font_handwriting_32_32.tga
convert graphicsSource/font_pencil_32_32.png -type truecolormatte graphics/font_pencil_32_32.tga
convert graphicsSource/font_pencil_erased_32_32.png -type truecolormatte graphics/font_pencil_erased_32_32.tga
convert graphicsSource/hungerBoxes.png -type truecolormatte graphics/hungerBoxes.tga
convert graphicsSource/hungerBoxFills.png -type truecolormatte graphics/hungerBoxFills.tga
convert graphicsSource/hungerBoxesErased.png -type truecolormatte graphics/hungerBoxesErased.tga
convert graphicsSource/hungerBoxFillsErased.png -type truecolormatte graphics/hungerBoxFillsErased.tga
convert graphicsSource/hungerDashes.png -type truecolormatte graphics/hungerDashes.tga
convert graphicsSource/hungerDashesErased.png -type truecolormatte graphics/hungerDashesErased.tga
convert graphicsSource/hungerBars.png -type truecolormatte graphics/hungerBars.tga
convert graphicsSource/hungerBarsErased.png -type truecolormatte graphics/hungerBarsErased.tga
convert graphicsSource/chalkBlot.png -type truecolormatte graphics/chalkBlot.tga
convert graphicsSource/pathMark.png -type truecolormatte graphics/pathMark.tga
convert graphicsSource/ground_t0.png -type truecolormatte graphics/ground_t0.tga
convert graphicsSource/ground_t1.png -type truecolormatte graphics/ground_t1.tga
convert graphicsSource/ground_t2.png -type truecolormatte graphics/ground_t2.tga
convert graphicsSource/ground_t3.png -type truecolormatte graphics/ground_t3.tga
convert graphicsSource/guiPanel.png -type truecolormatte graphics/guiPanel.tga
convert graphicsSource/guiBlood.png -type truecolormatte graphics/guiBlood.tga
convert graphicsSource/tempArrows.png -type truecolormatte graphics/tempArrows.tga
convert graphicsSource/tempArrowsErased.png -type truecolormatte graphics/tempArrowsErased.tga
convert graphicsSource/notePaper.png -type truecolormatte graphics/notePaper.tga
convert graphicsSource/fullSlip.png -type truecolormatte graphics/fullSlip.tga
convert graphicsSource/hungrySlip.png -type truecolormatte graphics/hungrySlip.tga
convert graphicsSource/starvingSlip.png -type truecolormatte graphics/starvingSlip.tga
convert graphicsSource/instructions.png -type truecolormatte graphics/instructions.tga
convert graphicsSource/hintSheet1.png -type truecolormatte graphics/hintSheet1.tga
convert graphicsSource/hintSheet2.png -type truecolormatte graphics/hintSheet2.tga
convert graphicsSource/hintSheet3.png -type truecolormatte graphics/hintSheet3.tga
convert graphicsSource/hintSheet4.png -type truecolormatte graphics/hintSheet4.tga
convert graphicsSource/bigPointer.png -type truecolormatte graphics/bigPointer.tga
convert graphicsSource/cellBorder.png -type truecolormatte graphics/cellBorder.tga
convert graphicsSource/cellFill.png -type truecolormatte graphics/cellFill.tga
convert graphicsSource/homeArrows.png -type truecolormatte graphics/homeArrows.tga
convert graphicsSource/homeArrowsErased.png -type truecolormatte graphics/homeArrowsErased.tga
convert graphicsSource/homeSlip.png -type truecolormatte graphics/homeSlip.tga
convert graphicsSource/homeSlip2.png -type truecolormatte graphics/homeSlip2.tga
convert graphicsSource/hiddenFieldTexture.png -type truecolormatte graphics/hiddenFieldTexture.tga
convert graphicsSource/yumSlip1.png -type truecolormatte graphics/yumSlip1.tga
convert graphicsSource/yumSlip2.png -type truecolormatte graphics/yumSlip2.tga
convert graphicsSource/yumSlip3.png -type truecolormatte graphics/yumSlip3.tga
convert graphicsSource/yumSlip4.png -type truecolormatte graphics/yumSlip4.tga
convert graphicsSource/photoBorder.png -type truecolormatte graphics/photoBorder.tga
convert graphicsSource/hintArrow.png -type truecolormatte graphics/hintArrow.tga
```

For some reason, on your Linux, this results in the TGA files being upside-down.  We have to figure out why.

**Comment by Nika50501** [comment]
The png files in graphicsSource folder are the correct side up

**Comment by jasonrohrer** [comment]
This seems to be a known issue with certain versions of image magick, see:

https://github.com/ImageMagick/ImageMagick/issues/3844

https://github.com/ImageMagick/ImageMagick/issues/3061

It seems like the "-auto-orient" option to convert may fix this.

Can you test this on your end:

1. Go to your UnixSource distribution.
2. cd OneLife/gameSource/graphics
3. confirm that the tga files are upside-down
4. rm *.tga
5. cd ..
6. edit Makefile as follows

Change this:

```
# 
# Generic:
#
# Map all png files into .tga files
#
# $@   represents the name.tga file
# $<   represents the name.png file
#
graphics/%.tga: %.png
	convert $< -type truecolormatte $@
graphics/%.tga: graphicsSource/%.png
	convert $< -type truecolormatte $@
music/%.tga: %.png
	convert $< -type truecolormatte $@
```

Change it to this:
```

# 
# Generic:
#
# Map all png files into .tga files
#
# $@   represents the name.tga file
# $<   represents the name.png file
#
graphics/%.tga: %.png
	convert $< -auto-orient -type truecolormatte $@
graphics/%.tga: graphicsSource/%.png
	convert $< -auto-orient -type truecolormatte $@
music/%.tga: %.png
	convert $< -auto-orient -type truecolormatte $@
```

Then run:
make

It should rebuild the tga files.

After that, look in the OneLife/gameSource/graphics folder.  Are they still upside down?

**Comment by Nika50501** [comment]
it wouldn't let me rerun the makefile (everything is already compiled) so I ran this instead and it gave the correct result
`convert ./bigPointer.png -auto-orient -type truecolormatte ./guiPointer.tga`
The suggested edit in the makefile should fix the issue
