### ISSUE TITLE
Falling Gates

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#850]
For the past couple of weeks, I've noticed that the town property (where we keep oil, etc) gates would sometimes fall down and become a Proposed Property Gate. 

One minute it would be there and then when I look again, it would be down. 

After trying a bunch of different stuff, I found the cause.

If you (as the only owner of the gate) die too far from the gate itself, the gate will fall.

Tested it twice in bs2. 

Both times, the gate fell immediately when I died.

The second time I tested it, I died around 300-400 tiles from the gate.

But presumably the distance that triggers it is at more than 200 tiles.
(It could be any distance, I don't know. 200 is just a guess. Could be more, could be less.)

Because the probable cause of it is this fix https://github.com/jasonrohrer/OneLife/commit/d0fd566cb7f6a4e216d3ee0f7f64b9346e61564a, where you posted "
When finding heir for property, we first search for fittest offspring within 200 tile radius. If not found, we then look for fittest offspring at any distance. If not found, we then search for fittest relative within 200 tile radius. If not found, we then finally look at fittest relative at any distance. Distant folks no longer inherit property unless there's no closer choice. "

I'm **NOT SURE** that that fix is the cause though coz there were a lot of fixes/updates pertaining to property gates in the past few weeks. **Could be a different fix/update caused it.**

**Comment by jasonrohrer** [comment]
Yeah, this also reminds me that this new code is kinda dumb...

It finds the fittest offspring/relative that is within 200 tiles of YOU... not of the gate in question.  It should find people who are near the gate.  So if you skip town and start a new family in another town, your offspring in the other town don't keep inheriting your gate in the old town.

**Comment by jasonrohrer** [comment]
Ah... I think I found it...

If you have no *offspring* yourself, then it seems like finding your closest relative to use as an heir isn't working.

I just died, and my property was not passed to my sister.
