### ISSUE TITLE
Why are d-town locations outside of biome band regions?

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#856]
This might be vestigial.  Take a look.  Why can't D-town Eves just be placed in biome bands as usual?

Also, how is d-town Eve's race selected?

**Comment by lorocyproca** [comment]
Access to the jungle biome gives ability to create endstones and endtowers.

**Comment by cordy-123** [comment]
Giving access to latex/sulfur, gives them a way to come to regular spawns by using a truck/sports car.
 
And with donkeys now being able to give birth (recent update), they can chain into regular spawn, even with horse. (You'd have to adjust it so they can only give birth in DT.)

--------

Sports Car with **NO** Road

.1 minute = 110 tiles
1 minute = 1,100 tiles

20,000 tiles (which is the spawn location from regular to DT) = 18 minutes

------

Truck with **NO** Road

.1 minute = 75 tiles
1 minute = 750 tiles

20,000 tiles = 26 minutes

----

So you can definitely make a truck/sports car and oil beforehand and respawn in DT again to make the trip.

And yes, they will definitely do that. Not often. But to say that they've done it and that they conquered DT. Then yes, they would do that. 

If you're asking how could they reach towns? Just have their alt ring the belltower in regular spawn.

Or use expert waystones (presumably DT biomes will have that)

-----

If you are gonna ask if griefers will do that, yes they would.

Example, in regular spawn. 
A few months ago, Quirkysmirkyian griefed the ginger fam by moving it 50k EAST. 
He did this multiple separate times, around 50k east each time. Different fams but arctic fam each time (coz gingers are needed for oil).
He used his alts to spawn himself to chain lives.

**Comment by teliot** [comment]
> Access to the jungle biome gives ability to create endstones and endtowers.

https://onetech.info/2478

In one tech it shows the item as '+normalOnly', tutorial and donkey lives are not +normal so they cant endtower.

**Comment by TwistedHBG** [comment]
If you place DT Eves in the biome bands you'd be placing them in an area where Eves would eventually spawn (I think DT is 20k away?) which would give them a good opportunity and plenty of time to mess up future well sites/natural resources, so you'd have to either greatly increase the DT distance so the areas regenerate by the time the Eves get there (like 1 million tiles), or have a secondary, separate line of bands for the DT Eves

**Comment by squishysquid** [comment]
it might be easier just to punt them to one of the other servers, like declare server3 donkey town. eg a punt the cursed player redirect setting. If someone's running a private instance and someone gets cursed out, you probably wouldn't want them connecting.

For the main service, well if someone's somehow cursed out of 12 servers.. well that'd just be silly

**Comment by jasonrohrer** [comment]
Well, there's no reason that it can't be much further away... like 200 million.

I didn't realize it was only 20k.  That's kinda dumb already, because we get there eventually with regular Eve spawn...

**Comment by jasonrohrer** [comment]
endtower stuff is locked to +normalOnly, which means d-town players and tutorial players can't build it.  Double checked this by testing it, and it works.  D-town player can't stick a bloody knife in the dark nosaj

**Comment by cordy-123** [comment]
Oh yeah, I forgot about planes. :D
