### ISSUE TITLE
Log forgiveness alongside curses

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#857]
Currently, the curse log on the public data website contains entries for when someone is cursed, but not for when they are forgiven. This makes it difficult to determine the total number of curses a player has, as well as who in particular still has them cursed. Given the recent changes to curse length, having accurate data here is going to become more important.

There is an entry (starting with S, not sure what that stands for) under each curse that shows the total amount of curses for that player, but this number seems to reset to zero with every server restart, so it is not very useful. Perhaps this could be addressed too?

**Comment by jasonrohrer** [comment]
Yeah, the S is meant to be the total curse count...  Looking at why that resets to 0...

**Comment by jasonrohrer** [comment]
Whoops... see:  d7e614bcf699c27aaf6526e8a360ae95023305d4

Still looking at what this setting is supposed to do.
