### ISSUE TITLE
last slice of turkey 

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLife#859]
I'm just forwarding this off the discord https://discord.com/channels/328215300279500800/498293923576283146/1127069983176921229

when a turkey is down to the last slice, you can't get it onto the plate while the turkey is on a table and instead need to put the turkey on the floor to get it. 

I don't think it's intentional behavior, because you can do the other slices from the table.

**Comment by cordy-123** [comment]
Already reported. https://github.com/jasonrohrer/OneLifeData7/issues/873

+contFoodDish is needed for an item to go on the food table. 

It doesn't have that tag.

**Comment by jasonrohrer** [comment]
Thanks for flagging the duplicate!
