### ISSUE TITLE
feature: single signon

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLife#860]
You reminded me I wanted this in discord a bit ago. But if you have an ohol adjacent service it would be useful to be able to tell this is a real ohol user. I'm not sure if this is present.

Typically this comes with someone writing a modded client or something so there's a degree of trust associated. I'm not sure if pure OAUTH or saml is fully appropriate, because you don't always have a fully trusted client like a browser.

However the ability for the client to spit out a short lived token that an external service can send to main ohol and verify "this is a valid ohol user" and maybe a link to there leaderboard so the identity is persistent would be useful. Perhaps making sure all of that is just jammed into one file so you can quickly read the code and reasonably check if someone is being silly.

An example of this being a problem that currently exists for a third party is for instance what phex (the modded client chat service) currently does. They hash your account key and email then use that hash as your unique user id. A custom compiled client can just jam whatever in there and it has no way of knowing. A bad user could just hop IP addresses spitting new garbage in for the credentials all day spamming viagra ads or whatever if they wanted.

**Comment by jasonrohrer** [comment]
Interesting... but how would the client "spit it out" and where would it go?

Like it's something that the end-user generates on purpose (by pushing a button inside the game) and then they copy-paste the token manually into the third-party service?

I'm trying to figure out if there's a way to do this already, at least for the clients that use phex...  I think maybe the ticket server can verify a hash currently.  Will report back.

**Comment by jasonrohrer** [comment]
Ah, yes, the ticketServer does support this currently in a limited way:

```
// verifies a hash using a user's secret ticket_id as the key
// this allows remote checking of download codes without sending them accross

server.php
?action=check_ticket_hash
&email=[email address]
&hash_value=[hash value]
&string_to_hash=[string]


Return:
VALID
-or-
INVALID


string_to_hash must contain only the charcters 0-9, A-Z, and a-z

hash_value is computed on both ends with:

HMAC_SHA1( $ticket_id, $string_to_hash )


Where $ticket_id has hyphens removed and is all uppercase.


Note that string_to_hash should not be re-used for subsequent checks to avoid
replay attacks.  HOWEVER, the ticketServer does NOT track this or prevent
replays.  It is up to the other server to handle this.
```

The one weakness here is that the ticket server doesn't check that the string hasn't been used in the past, so it's subject to replay attacks.

But Phex itself could provide unique string each time, and make sure the string is NEVER reused (it could just use a counter that counts up for each verification that is performed).  And use "phex835"... to make the counter unique to phex (so you can't replay across services).

So client wants to connect to the Phex server.  The following steps are used:

1.  Client asks Phex for a unique string counter.  Phex returns  phex349381
2.  Client computes  HMAC_SHA1( $ticket_id, "phex349381" )
3.  Client sends this hash to Phex along with client email address
4.  Phex sends email and string counter and hash to ticketServer for verification
5.  Client is now verified with Phex.

I guess Phex could then return some kind of token to client, which client could use along with each future message to identify itself to Phex.  Or if it's socket-based, this would be done once at the beginning of the socket being opened, and then Phex could trust that client socket after that.

**Comment by jasonrohrer** [comment]
Granted, this does not work with third-party services that aren't integrated into the client.

It wouldn't be hard to basically build a "manual mode" for this into the client, where you can paste a string in, and get the HMAC out.  So if there was a third-party service, it would provide you with a challenge string, and you'd come back and give the hash for that challenge string.

But what service currently needs this?

**Comment by squishysquid** [comment]
none yet, was thinking of doing my own phex implementation, simply because the current one seems to crash 5 times a week for unknown reasons. So I've been slowly passively reverse engineering that protocol.

As for web services I bet simple data viewing tools like wondible could use it for basic ddos protection, why does someone not playing want to look at the data, that's an awfully big page request. 

You could also hook it up to the discord using a bot to reduce sock puppets/banned accounts coming back.

Also comes up in your self hosted server idea, if someone does want to do that and not have pirates.

I think that end point might do what I'm looking for I'll try to make a little test call script for it.

**Comment by squishysquid** [comment]
keeping something like a counter on the third party for replays doesn't seem like a big ask.

My one concern would be seems like it could be rainbow tabled by a malicious service feeding the secret. I trust myself not to do that. Someone might be crazy, I guess being able to write something like that negatively correlates with strange desires to hoard a bunch of ohol keys though. 

had a brief worry about that with current phex implementation, took a bit to notice they include the email which brings it out of the danger zone, but without that the keys themselves are within a decently predictable 20 characters, alphanumeric all caps set so 36 symbols.

**Comment by jasonrohrer** [comment]
Doesn't a rainbow table depend on the shortness of the passwords being hashed?  I haven't looked into RTs in a long time, so I don't remember the details.

But in this case, we're hashing a completely random 20-character string.

And we're effectively "salting" things whenever we create the HMAC (we're not just hashing the account key itself and using that for anything).  Yes, a rogue service could send the same "challenge string" to everyone, and build a rainbow table around that.  But the RT only produces SOME string that hashes the same way.  It doesn't produce the actual password.  And just having SOME string that hashes the same way for a fixed HMAC challenge string isn't going to help someone break into an OHOL account, b/c the real OHOL server is challenging you with a different sequence number each time you log in.

B/c for rainbow-table vulnerable services, the password itself isn't needed to log in.  Just some password that hashes the same is needed.  So the rainbow table finds some string that produces the desired hash.

In our case, since every time you log into OHOL, you are challenged with a new sequence number to HMAC, having some string that collides with your key one time (for one particular sequence number) won't help, since it won't collide again when other sequence numbers are used.

**Comment by jasonrohrer** [comment]
Anyway, I'm implementing a SERVICES screen inside the OHOL client that allows you to generate a hash from a challenge.

**Comment by squishysquid** [comment]
sha1's up to about 50 trillion a second on consumer gpus, http://project-rainbowcrack.com/table.htm the hardware's catching up.

with a known salt and a typical gaming computer, that's probably like about a day to crack.
