### ISSUE TITLE
Trust Radius

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#864]
There's a LACK of max radius that 'trust' can be given.

Tested it a while ago, I 'trusted' someone who was more than 1000 tiles away.

Yes, I'm sure they were more than 1000 tiles away. 

Because I tested it on the leader and I did /Leader before I uttered the trust phrase. 

It worked, the leader had the + + sign when I came back.

**Comment by jasonrohrer** [comment]
Is this a problem?

**Comment by cordy-123** [comment]
> Is this a problem?

Hmmm....not really afaik.

Just weird.

You could be thousand of tiles away and say I trust John Smith and it would work. 

It's also inconsistent with other 'I blank John Smith' phrases. 

But I guess, it's not very abusable.

**Comment by jasonrohrer** [comment]
Yeah, those used to be infinite as well, but they were limited specifically to eliminate abuse.  Like being able to track someone anywhere on the server after you followed them, etc.

Trust doesn't do anything other than put + around their speech.
