### ISSUE TITLE
Empty maplogs

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#866]
The most recent maplog represented approx 5 hours, and had no data entries.  You can see the file size in the index:

http://publicdata.onehouronelife.com/publicMapChangeData/bigserver2.onehouronelife.com/

**Comment by MrMendeleev2** [comment]
Big server 2 was offline, and under maintenance for all this time. I suppose it called logger twice anyway, but nothing was going on. 
Empty logs are to be expected, imo.

**Comment by JustinLove** [comment]
Eh, I scanned discord and didn't notice anyone talking about it, I guess it's just too busy to find things.

**Comment by jasonrohrer** [comment]
Yeah, sorry about this... I was working on BS2 yesterday, and it ended up being offline way longer than I planned.
