### ISSUE TITLE
Service feature will not work with steam ids.

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [jasonrohrer/OneLife#869]
Cannot change the email with a steam id and the steam id based accounts use the steam id with steamgames.com domain which I don't think we can access.

**Comment by jasonrohrer** [comment]
This shouldn't be a problem.

People just need to give the third-party service their account email address, whatever it is.  The "email" is how the account is identified by the OHOL ticket server.

For Steam accounts, we don't have a real email for each customer, so we make up a unique one using their Steam ID.  It's a fake email address (they can't receive email there), but it works for unique identification of each user.

**Comment by jasonrohrer** [comment]
I'm pretty sure it's working as intended.  Please re-open an issue if I'm missing something here.
