### ISSUE TITLE
Donkey Town Gate-keeping

### ISSUE THREAD

**Issue by lorocyproca** [jasonrohrer/OneLife#873]
After all the work done to make Donkey Town playable for people who are cursed there, the same handful of players who have ruined the main game for months have now begun gate-keeping Donkey Town by not allowing any other players to survive when born there. They can check the curse name and only allow themselves (3-4 people) to survive as babies, thus claiming the entirety of DT as their own personal area. There ought to be an automatic Eve birth enabled after several short lives or deaths from starving/murder so that other DT players can at least go and form their own villages, or scrap the idea of having kids in DT as Donkeys are obviously not able to play the game as intended.

**Comment by Tarr-OHOL** [comment]
No honor among thieves friend. 

Kind of hilarious the first thing the trolls do when shoved into their own playpen is to kick out the other trolls they don't care for. Probably need to have some sort of safeguard such as the bad mother rule kicked in for donkeys so they're not being starved constantly by reformed and company. Hell, maybe the donkeys can play their "pvp" game mode with Eves trying to take over the town in a sort of capture the hill sort of thing. 

Of course then they'll build fences and none of the donkeys can get in. Maybe make it so donkeys can't make property?

**Comment by TwistedHBG** [comment]
We need a DoDonkey Town for people who you don't want to play the game with in Donkey Town, and then a DoDoDonkey town for people who are jerks in DoDonkey town.

It should be Donkeys all the way down, first person to get to DoDoDoDoDonkey town gets a cookie

**Comment by Tarr-OHOL** [comment]
As hilarious as the gatekeeping is there really should be a means to keep the donkeys from keeping other donkeys from playing like that. If they don’t get raised just spawn them as an Eve and then they can walk over and shoot each other or whatever.

**Comment by Tarr-OHOL** [comment]
Also if they’re curse checking each other just remove their ability to curse
