### ISSUE TITLE
Donkey Town lives should not affect gene score

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#874]
Now that there are babies in Donkey Town, it is possible to gain and lose gene score from lives played there. This is undesirable for two reasons:

1. Right now, due to the recent DT changes, DT is "popular" and a core group of griefers have been [committing infanticide](http://lineage.onehouronelife.com/server.php?action=character_page&id=9608061) on any players with unrecognized curse tags (see #873). While this is somewhat amusing, during hours of low population it is possible for regular players to end up in DT from only two or three curses. These players should not be further punished by also enduring massive hits to their gene score, which they may have worked hard to maintain.

2. More concerning than the first issue is that it is now possible for DT to be used to grind very high gene scores. This will likely become possible sometime in the near future when the novelty of the new DT wears off and it returns to being mostly unoccupied. Since the most prolific griefers are know to have several alt accounts, they can chain births to themselves using these accounts and build up high gene scores that are difficult to obtain in regular gameplay (due to a constant stream of newer players that die to wolves, bears, and starvation).

    These accounts would then become "ticking time bombs": if they ever escaped DT, they would be able to easily inherit property and leadership and cause further harm. Furthermore, they would occupy top spots on the leaderboard website, which would be misleading since they aren't playing in the regular area.

**Comment by jasonrohrer** [comment]
Yes, I will fix this.
