### ISSUE TITLE
Tooltips don't work in other special biomes even when they are not active

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#876]
When the server population falls below 30, special biomes deactivate and anyone can use any biome. However, this does not fix the tooltips; someone from the White family will still see everything in the arctic as "Frigid Arctic" instead of the actual object.

**Comment by TwistedHBG** [comment]
I _think_ this tag is sent to your client on login, so if you relog mid-life it would start showing properly

**Comment by jasonrohrer** [comment]
Yes, Twisted, you're right about this.  Still, if the condition clears, the Bad Biome message should be sent again to clear it client-side.  So it's buggy...
