### ISSUE TITLE
Waystones don't work when special biomes are not active

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#877]
When the server population falls below 30 and special biomes deactivate, expert way stones stop pointing to other villages. This makes it very difficult to find other towns without using third-party mods. Even without special biomes, there are many reasons to visit the other families. Examples include:

-  The Black family runs out of kerosene for their well and needs to locate the Ginger family to trade for more. It isn't feasible for them to pump their own oil since the arctic is far away (and the process takes long enough that within a few hours/minutes, the special biomes will probably reactivate anyways from more players coming online).
- Languages stay in effect until the server population falls below 15, so if a translator is needed it is necessary to find the White family. This is very difficult to do while the server has between 16 and 29 players.

It would also be nice if the expert way stones excluded tutorial and donkey town players. Sometimes I'll get a result several million tiles away.

**Comment by TwistedHBG** [comment]
IMO a good QoL tweak for this would be to have different triggers for entering and exiting lowpop. If the server gets to 25 it enters lowpop, and it stays like that until there's 35 people again. This would prevent the server from flip-flopping between lowpop and normal pop several times per life

EDIT: Just realized my comment is basically a copy of #878

**Comment by jasonrohrer** [comment]
Those waystones are supposed to be specifically for finding experts when you need them.  You go into the jungle, can't do anything there, and then see a waystone that helps you find an expert.

I will definitely fix them to not point to D-town or tutorial players.

But they really aren't meant to be a way of finding people generally, when there's no need for experts.

Hopefully, people will use maps and waystones for that.

And I see the other issue about flip-flopping states.  I will fix that as well.

**Comment by jasonrohrer** [comment]
Oh, the language effect is interesting... hmmm...
