### ISSUE TITLE
Server flip-flops between activating and deactivating special biomes

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#878]
Often times during the night for NA, bigserver2 has ~30 players online. Sometimes slightly more than 30, sometimes slightly less. This causes the server to keep activating and deactivating the special biomes over and over, leading to very frustrating experiences. Consider this scenario:

You are born in the Black family. Rubber tires are urgently needed to run the Newcomen well. There is no latex. Because there are only 28 players online, you take a knife and walk north into the Jungle, slash a rubber tree, attach the bucket, and go looking for some food. When you return, you are unable to retrieve the bucket of latex because three new players have logged in since then, raising the server population to 31 and reactivating the special biomes. You go looking for a Jungle Expert Way Stone, but by the time you find one it doesn't work because two players have died, lowering the population to 29 and deactivating the special biomes (per #877). Do you keep waiting by the way stone hoping for one more player to login? Or do you risk walking back to the latex bucket hoping nobody else logins so you can retrieve it?

Since the standard OHOL client doesn't provide the server population anywhere, the above scenario is worsened for those without mods to check this. Ideally, once a character gains the ability to work in any special biome, they should keep this ability until their death, regardless of the fluctuations in the server population. However, this solution may be technically difficult to achieve.

I propose an alternative solution: instead of enabling and disabling the special biomes whenever the server population rises to or falls below 30, create two separate thresholds for when they are activated and deactivated. Replace `minActivePlayersForSpecialBiomes` with a lower bound that determines when special biomes should be deactivated, and an upper bound that determines when they should be activated. These bounds should be sufficiently far apart so that it isn't likely that the server will flip-flop within short time periods.

For example, if the lower bound is set to 30 and the upper bound is set to 45, the server won't deactivate special biomes until less than 30 players are online, but once it does, it won't reactivate them until 45 players are online.

---

It is also my understanding that `minActivePlayersForSpecialBiomes` is used to force Eve spawns when one race is entirely extinct. Changing this to use the same threshold as above would be an improvement, too, as it is very common for the server population to inch above 30, forcing an Eve spawn, and then dip below 30 again. With so few people online, these low-pop Eve families often fail, even if they do well with food, since there are not enough children to sustain them and the other existing families. Moreover, many people playing during low-pop are being reborn to their descendants in other families, further reducing the number of possible children the new family can have.

The result of this is new Eve spawns being pushed thousands of tiles West during low-pop hours. When the server population eventually rises back up in the day and the new Eve family can sustain themselves, the new town they build is very far West from existing towns that survived through low-pop hours. This makes trade much more difficult.

---

This idea of replacing a single value with upper and lower thresholds is probably also applicable to things like languages and whether or not players must be in their band to have children. However, since those are always enabled above 15 players, and since I have not seen the server dip below 15 players (outside of restarts), it has not yet proven to be a problem.

**Comment by squishysquid** [comment]
the flip over not having a buffer really messes with eve spawns. The natural nothing much is going on 3am low pop seems to hover right at that 30 line. It kind of fixes itself when there's larger population of active player events, like the recent youtube video or the current updates, but when the games hanging in maintenance on a weekday it hits about there.

And when it's cruising like that for hours you get this weird thing where an eve spawns, it's low pop so don't really get kids, eve dies(a disappointing venture for the eve), eve line moves 200, and it repeats 10 times, moving the line 2000, so the next day you log in and all the old towns are a 10-15 minute walk.
