### ISSUE TITLE
Unfinished stew crocks movable, partial sauerkraut not.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#88]
Seems silly that you can carry a crock full of stew around uncooked but the second you shred a cabbage the crock becomes unmovable. 

Please make things consistent between the two filled crocks and make partial sauerkraut movable like stew or make stew not portable anymore.

**Comment by jasonrohrer** [comment]
Not silly.

We make kraut every year in 5-gallon crock, just like it's shown in the game.

After the cabbage is in there and stomped, it is HEAVY.  It takes two people to move it.  When the weight is on top, there is no way to move it, at all.  So you really make it in place.

The stew is similar (would probably be too heavy to move 5 gallons of stew).  However, you have to move it to get it on the fire.  It's really a placeholder for a pot, which will be added someday.  You wouldn't make stew in a clay crock in real life.  It wouldn't conduct heat very well.
