### ISSUE TITLE
viewing old messages

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLife#881]
I'm forwarding this, because I don't know if you check the reddit.

https://www.reddit.com/r/onehouronelife/comments/152ic26/recall_order_notification/

They're worried about occasionally missing orders, and want a way to recall them.

They suggest a /order command. Could put them in the up arrow chat log too I guess. I'm just forwarding the suggestion guys stuff since I saw it.

**Comment by jasonrohrer** [comment]
Yes, I can do this.

And it is very helpful to have the best things from Reddit brought here.  Thank you for doing this!

**Comment by squishysquid** [comment]
there's a whole suggestion tag, I mostly covered the recent ones, because they see you're back making updates so posted some it's usage upticked. but there's a longer list going back months. Not all well thought out, but could be interesting. https://www.reddit.com/r/onehouronelife/search?sort=new&restrict_sr=on&q=flair%3ASuggestion
