### ISSUE TITLE
I think this guy wants instruments

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLife#883]
https://www.reddit.com/r/onehouronelife/comments/153vjdx/add_sound_recorder_sound_player_musical_instrument/

At least that's what I think he wants. but well making a point of forwarding the suggestion tags. I think he wants an "instrument" object where certain letters said are translated to musical notes played while holding. 

which hey that'd be a game feature that'd check phonographs off that weird group of objects from the 5 year old demo video people obsess over.

**Comment by jasonrohrer** [comment]
It seems like papers already handle his "sound recorder" idea, which is basically just a way of recording spoken words.  Might as well write them down and let people read them out loud later.  I get that he wants to record multi-person plays, etc...

The musical instruments is a great idea, but pretty tough to do correctly... at least in a way that won't end up sounding like crap.  Restricting players to saying notes is a great way filter out spammy "bang on the keyboard" non-music.  But actually getting pretty music out of CCGGHHG-FFEEDDC is hard.  There are octaves to consider (which I see he is handling with "H", strangely), and note durations... I see a rest in there, but there's more to it than that.  But also expressiveness.  Piano would be easiest, but even there, without variable "touch" on the notes, it's going to sound very robotic and lifeless.

Any other instruments (like sax, violin, guitar) are just non-starters as "sampled" instruments.

For what it's worth, all the music in OHOL was recorded by me on a real wooden piano with a microphone.
