### ISSUE TITLE
The @ button on email change menu is too close to the genetic fitness.

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [jasonrohrer/OneLife#885]
I have noticed on my 1080p monitor that the @ button to help with putting in emails is very close but not quite overlapping with the genetic fitness button. There is enough empty room to the left to move it over a few pixels.

**Comment by QuirkySmirkyIan** [comment]
Oh and the resized don't edit account unles you.... should be a few pixels above the 48/48 lives left... That resize is more close together than the @.

**Comment by jasonrohrer** [comment]
Strange... for me, it looks like this, with the GENES button down to the right.  Can you post a screen to illustrate what you're talking about?

![Screenshot from 2023-07-25 09:06:35](https://github.com/jasonrohrer/OneLife/assets/12563681/a0d189b8-f184-440d-84cf-7eaeb5a2a6fc)

**Comment by jasonrohrer** [comment]
Also, the "Don't edit account" message has its top line aligned with the SERVICES and TUTORIAL button text.  That same "status message" area is used for other single-line messages, and it's good to have those centered.

![Screenshot - 07252023 - 09:11:10 AM](https://github.com/jasonrohrer/OneLife/assets/12563681/576cc05c-29e9-4fd0-93c1-acc9a8b4818a)

**Comment by jasonrohrer** [comment]
Just realized that maybe you're talking about the Genetic Fitness display?  But that is also nicely positioned, as far as I can tell.

![Screenshot from 2023-07-25 11:18:14](https://github.com/jasonrohrer/OneLife/assets/12563681/23f1d10d-2a9c-42ae-9031-74ada9a0db62)

**Comment by jasonrohrer** [comment]
Ah, but maybe the problem happens when your place is much bigger?  Like a 3-digit place?

**Comment by jasonrohrer** [comment]
Yes, I see the problem now:

![Screenshot from 2023-07-25 11:28:00](https://github.com/jasonrohrer/OneLife/assets/12563681/87657ad0-c802-4a0e-aac8-45c9c03f234d)

**Comment by jasonrohrer** [comment]
Okay, I've moved the @ button to a better place.

Still there's another placement issue that you mention above.  I will leave this open for more info about that.

**Comment by QuirkySmirkyIan** [comment]
The dont edit area was a mod issue.

**Comment by jasonrohrer** [comment]
Thanks for the clarification!
