### ISSUE TITLE
Suggestion RE: leadership

### ISSUE THREAD

**Issue by SharpieSharps** [jasonrohrer/OneLife#886]
Problem - Sometimes people become leader when they are not able to for IRL reasons. While having a high genetic score, they might have to leave early or not be able to lead for any reason. Yes, they can make someone else leader. However if you don't know the town enough you mind not know who is trustworthy

Suggestion - Allow leaders to abdicate their position (/ABDICATE or /RETIRE) to let the game immediately pick the next leader based on the genetic score.

**Comment by jasonrohrer** [comment]
I like forcing them to decide who is trustworthy.  That's a juicy and drama-soaked decision.  I don't want to automate things too much for people.

**Comment by SharpieSharps** [comment]
That's an understandable decision too! The game truly has a strong potential for juicy drama, haha. It's why I keep coming back to it!
________________________________
