### ISSUE TITLE
Special biome buffer not being considered when spawning Eves

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#887]
As per you fix to #878, you added a 10 player buffer to stop the server from constantly toggling the special biomes on and off as the server population hovers around 30. This is great, but the `minActivePlayersForSpecialBiomes` setting is also used in `server.cpp` on line 9407, where it controls whether or not a new Eve will spawn, without considering the buffer or whether special biomes are currently active or not.

The consequences of this are illustrated by the following example:
1. There are 20-something players online in two different families
2. The server population rises slightly above 30
3. Two new Eves are spawned since we are missing two races
4. The server population falls again into the 20s
5. There are now not enough people to sustain all four families, so the new Eve families will run out of babies and vanish (most players are respawning to their descendants in the established families instead).

This Eve spawning logic should only apply if special biomes are actually active and their specializations are needed, else there is no reason to force players into a doomed Eve family when the server does not have enough players to support them.

**Comment by jasonrohrer** [comment]
Nice catch!  Fixing this now.
