### ISSUE TITLE
Add Books and Lecterns

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLife#890]
https://www.reddit.com/r/onehouronelife/comments/157comw/add_books_and_lecterns/
Forward my suggestion here.

__Problem:__
1. Papers can't contain too much messages.
2. Papers are too easy to get lost and disorganized.

__Solution:__

Add books and lecterns.

A book is made up by several papers. Left click to pick up and read a page, right click to turn a page.
A book contains a title and an author, which is at page 0.
A book contain a cover, which contains a letter and a color, so you can identify books by a look.

A lectern can hold a paper or a book, you need a special tool to take it away.
When it holds a paper, left click to read.
When it holds a book, left click to read a page, right click to turn a page.

**Comment by jasonrohrer** [comment]
This has been suggested a few times in the past, and it's a fine idea.

However, the way that notes/papers are implemented is already pretty complicated (there's a separate database that contains this metadata, and the ID that's actually stored in the map is a compound-id that specifies both the object ID (like for a notepaper) and the unique metadata ID (which allows us to look up the text message stored).

There's currently only one of these metadata IDs per map object.

And note that there are only 16,383 *total* possible pieces of metadata on a given server.  After we run out of slots, we wrap around and replace the text in the old ones.  This means that very old note papers can sometimes "magically update" to have the same content as newer ones.

Having multiple "pages" attached to a single object would require a complete overhaul to how this works.

That said, it could be possible to have some kind of special container that can only contain note papers.... that could be a book-like thing.  But it wouldn't have any of the convenience features that you're describing here.


As for WHY it's implemented like this, remember that OHOL inherently supports an practically infinite map full of an arbitrary number of player-created objects (as well as a natural world with 2^64 pre-defined features).  This is done efficiently by having a single 32-bit ID number for each map location.  Usually, this represents one of the 3000+ objects in the game.  The metadata system builds on top of this to allow text to be attached to objects without hampering the efficiency of the whole enterprise.
