### ISSUE TITLE
Make it obvious when you are in Donkey Town

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#893]
As part of you fix to #873, your curse words no longer appear above your own head, nor is your speech bubble black, when you are in Donkey Town. This makes it really difficult to tell whether you are a legitimate Eve in the main game or a donkey Eve millions of tiles away from everyone else. I suggest restoring this functionality, but only for yourself.

An alternative solution could involve a little pop-up message (like in the tutorials) letting the player know that they have ended up in Donkey Town due to being cursed out of every family (as I don't believe Donkey Town is actually explained anywhere in-game).

**Comment by jasonrohrer** [comment]
Yes, a DING pop-up message is a great solution here.

**Comment by new2pcs** [comment]
It is obvious you are in donkey town. No curse token on the right side of the HUD, Its replaced by a number 1 below it.

 Jason, with how little you know about your game people might start questioning its origin.

**Comment by TheMingo888** [comment]
This is very subtle and not at all obvious, except to players that have been to Donkey Town many times before. Plus, there are other reasons why the curse token might be missing (e.g. you cursed someone towards the end of your previous life).

**Comment by jasonrohrer** [comment]
Yeah, that's right.  The number 1 indicates your current curse status, which is some legacy thing left over from how the curses used to work.

**Comment by jasonrohrer** [comment]
A DING message still makes sense
