### ISSUE TITLE
Yo photos don't work!

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [jasonrohrer/OneLife#894]
The photograph object does absolutely nothing even on vanilla. Checked for a popup and or a difference in pixels on the photo does none. Some of the normal photos taken weren't even showing on the website. On the stage where you retrieve the photo from the camera it was briefly saying NO INFORMATION then I went to vanilla and it gave steps but no photograph.

**Comment by selb** [comment]
The photo update involves a client-side change in the process of taking the photo. Did you take a photo in vanilla, or did you take it in a modded client and only review in vanilla?

**Comment by jasonrohrer** [comment]
Whoops... I forgot to update the photo server itself.

Fixing that now.

**Comment by jasonrohrer** [comment]
Yes, fixed the photo server.  It's working correctly in the vanilla client now.
