### ISSUE TITLE
Issue when swapping item for basket

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#896]
Hey. This has been grinding my gears for a while now, so thought I might as well report it. Seen lots of new players not understanding what they are doing wrong either.

Normally when you right click an item while holding another item, you swap the item you are holding for the one on the ground.
This is not the case for baskets. Baskets are apparently impossible to swap for, as you just place the item you hold into the basket when both left and right clicking.

This forces you to find an available tile and put down the item you are holding before being able to pick up the basket.

I don't know if this is a bug or a feature. But thought I might as well report it.

PS: Thanks for making this game, ily.

**Comment by TwistedHBG** [comment]
If you have a large item and right click the basket it will swap. If you're holding an item that can fit into a basket, right clicking the basket will swap the item in your hand with the item in the basket. This is consistent behaviour for all containers.

If right click instead swapped the held item with the actual basket item, it would be impossible to shuffle items within the basket.

You could argue that right clicking on an empty basket should swap the basket since there's nothing inside the basket to shuffle, but then you'd end up with the weird inconsistency of right click doing entirely different actions depending on whether the container is empty or full.

**Comment by TheMingo888** [comment]
I think the idea is that right-clicking on the ground near the basket (and not on the basket itself) should always swap what you are holding with the basket (or whatever container it may be). Right now, if I hold a small item and right-click the ground near the basket, it behaves identically to right-clicking on the basket (and just shuffles the items around).

I think it would actually be nice to be able to distinguish between these two actions, and allow swapping small items with containers depending on where the click occurred.

**Comment by jasonrohrer** [comment]
Distinguishing based on ground clicks is an interesting idea.

However, I wonder if it will screw someone up who has grown accustomed to "sloppy right-clicking" the basket to put things in there.

Currently, if you sloppy-right-click a tile around a non-container object, it picks up that object or swaps what you're holding with the object.

But a basket is a big enough target... seems like supporting sloppy-clicking isn't necessary here.

Twisted?

**Comment by TwistedHBG** [comment]
I just right click anywhere on a tile when I want to pick something up, and I aim directly for the object when I want to put stuff in/shuffle the items so I think it'd work - but I'm just talking from memory it might not be the case in practice.

I'm indifferent towards the potential change, I think it wouldn't affect me negatively but even if it does I think I'd get used to it, buuuut I also don't think it would be that useful. Hard to tell though.

**Comment by DopiePanda** [comment]
It would only change how you interact with baskets. When right-clicking on or around basket with in ex. a bowl, it should swap the bowl for the basket. 

As it is now, it will always place the bowl inside the basket, no matter if you right-click the tile or the basket. 

And left-clicking should of course put the bowl into the basket as expected.

**Comment by jasonrohrer** [comment]
Well, left-clicking on the ground makes you walk there.  There's already that distinction in place.

**Comment by jasonrohrer** [comment]
Very strangely... right clicking on the ground around a wooden storage box drops the held item at your feet.

**Comment by jasonrohrer** [comment]
Even stranger, right clicking on the ground around a wood box with a basket next to it drops the item in the basket!

**Comment by DopiePanda** [comment]
The left-clicking functionality works as it should when it comes to the basket atleast. 

Left-clicking on the basket from two tiles away makes you walk over and then places the item directly into the basket.

Left-clicking the tile only makes you move to that tile, like expected.

But right-clicking either the tile or basket always places held item into the basket, rather than;

Right-clicking basket places/shuffles held item
Right-clicking tile switches held item for basket/picks up basket/picks up basket.

Awesome that you uncovered more unexpected behaviour when doing some testing :) But of course, your word is always the last on if these are bugs, or simply just features 😎
