### ISSUE TITLE
Add race information to public life logs

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#897]
Right now, there is no way to tell the race of a life purely from the public data. You can get the name of a life and use that on the family tree website, determining the race by looking at the death portrait, but this is cumbersome and doesn't work for nameless lives. A simple letter on each birth line would be sufficient, such as A, L, J, D (arctic expert, language expert, jungle expert, desert expert).

Alternatively, you could just add the name of entire character model for that life to the logs instead. This would provide identical information to what is already provided on the family tree website.

**Comment by cordy-123** [comment]
> Right now, there is no way to tell the race of a life purely from the public data. 

Check the latitude part of the birth tile.

**Comment by TheMingo888** [comment]
> > Right now, there is no way to tell the race of a life purely from the public data.
> 
> Check the latitude part of the birth tile.

This is only applicable for servers that are in special biome band mode and have more than the minimum number of players to activate birthlands. It isn't true on the smaller servers nor on bigserver2 when the population is low (such as after a reboot).

As well, the order, thickness, and centers of the biome bands are customizable in the server settings, so even if the above two conditions are true, it still isn't sufficient.

**Comment by jasonrohrer** [comment]
Yes, I will add this.

**Comment by jasonrohrer** [comment]
Old:
```
B 1691677855 39263 test@test.com F (0,0) noParent pop=1 chain=1
B 1691677951 39264 test@test.com F (0,0) noParent pop=1 chain=1
B 1691678181 39265 test@test.com F (0,0) noParent pop=1 chain=1

```


New:
```
B 1691680217 39267 test@test.com F (0,0) noParent pop=1 chain=1 race=C
B 1691680337 39268 test@test.com F (0,0) noParent pop=1 chain=1 race=F
```

**Comment by jasonrohrer** [comment]
These race letters match what's shown in the editor.

A darkest
C brown
F ginger
D white
