### ISSUE TITLE
Unix Self-Compiled Client Won't Auto-Update

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLife#899]
I compile my OHOL client using Unix source code from here:
http://download1.onehouronelife.com/downloads/OneLife_Live6_UnixSource.tar.gz

My computer is Ubuntu 22.04.2 LTS (GNU/Linux 5.19.0-46-generic x86_64)

When a new update drops. I open my client and try to login, it shows that the client is getting updated and then back to menu. After that, I login again, and I am in the game.
The problem is that the client is in fact not updated. For example in this photo processing update (after it's fixed), I can't see the photo.
I need to remove every files and run pullAndBuildLatest again to compile again, in order to get the updated client (I can see photo now).

I suggest that maybe add the version number in the menu, so at least you know your version.

**Comment by jasonrohrer** [comment]
Weird... it shouldn't download an update like that.  It should show a message telling you to update manually.  I'll fix it.

**Comment by jasonrohrer** [comment]
This is fixed.

Note that to get it, you will need to run pullAndBuildLatest *after* the next update goes live (likely tomorrow, Friday August 11, 2023)
