### ISSUE TITLE
Could log with wrong version & Everything is a mouflon!

### ISSUE THREAD

**Issue by yquemener** [jasonrohrer/OneLife#9]
So I tried to log in on server3 but it failed with the red message "Server full", so I tried again, I assume it brings us to another server. Then, I had a weird bug: every partially full berry tree appeared as a mouflon, partially emptied ponds appeared as mouflons, partially pulled carrot fields as baby mouflons.

Logging out I see on the forums that a new version was out on the 8th. I had not updated. Usually login fails when I have not the latest version but this time it worked, maybe because of the fact I was first refused to login to a full server?

**Comment by bdjewkes** [comment]
The client doesn't download updates if `useCustomServer` is enabled; I suspect that was the problem.

**Comment by yquemener** [comment]
Ah yes probably. There is no mechanism for individual servers to ask a minimum version? If this is not  bug let's close it then.

**Comment by jasonrohrer** [comment]
Yes, this behavior is intended.

People can install custom data on their servers.  So there really isn't a "version number" that we can reliably talk about when dealing with a custom server.
