### ISSUE TITLE
Add Religion (Polytheism)

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLife#900]
Forward my reddit suggestion
https://www.reddit.com/r/onehouronelife/comments/15jkxl9/add_religion_polytheism/

**Problem**
- Every life is too similar. There should be something that leads players to do different things.
- The game lacks it. Religion is very important in human history, it gives people what they need the most. In the past, the world is full of unknown and danger. Without modern knowledge, people can only rely on religion to deal with it. For example, to stay safe when sailing, you have to pray to ocean god. To cure a disease, you have to pray to doctor god.
- Lacks of Asian culture.
- Players like to make gods in game, like “Goose God” or “Jason God”, but they are just pure role-play. Make them into real-play is better.

**Solution**

In the game, you can make any god you want. You can pray a god for a special buff, different god have different kind of buff.

Buffs example:
- Wisdom: Can type longer.
- Fertility: Can get yum faster.
- Agriculture: Can grow crops faster.
- Bravery: Can walk faster.
- Smithing: Adobe kilns burn longer.

The more believers, incenses and offering a god get, the more powerful it is (so the buff is stronger).

**Below explains in details, based on Chinese folk religion (my religion)**

**What is a god**

It has 3 parts: a shrine, zero or more incense burners, zero or more offering tables. Each of them occupy one block, in a 3x3 area with the shrine at the center.
- A shrine has something in it that represent the god, it can be anything, including a photo, a paper, or a statue.
- An incense burner is a pot with burning incenses. Incenses will burn out if you don’t keep adding more.
- A offering table is a table to offer food for the god. The god will consume them, so you need to keep adding food.

**How to pray**
1. Make an incense.
2. Lit it.
3. Hold it and click a shrine or an incense burner.
4. After that, you get the buff for 30 minutes, and you are the believer of it. If you pray a new god, old buff will be override.

**How to make a god**
1. Make a shrine.
2. Put something into a shrine that will represent a god.
3. Put a paper that has the god’s name.
4. Put a letter that indicate the buff (Like A for Agriculture).
5. Pray it (click it with burning incense) with 2 other people.

After that, a god is made. You can put incense burners and offering tables in 3x3 area around it.

**Extra info**
- Use /god to see where the god is.
- Use /believer to see believers under the same god.
- Some gods is stronger than others even in the same condition.
- Chinese folk religion is a religion that is believed by Han people. Mostly in China, Taiwan, South East Asia. It’s a polytheism that believes in everything, mostly people from the past or legend.

**Comment by jasonrohrer** [comment]
Something like this might be coming in the future....

... but your gods will be real....
