### ISSUE TITLE
Cursing after death is inconsistent

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#902]
After people die, my understanding is that you should be able to curse their grave for a short period of time. However, this does not always work as expected. Many times I have been unable to curse people a few seconds or minutes after their death. I suspect this may be depend on whether or not they enter into another life immediately after dying.

**Comment by jasonrohrer** [comment]
Hmm... just tested, and it works even if they're reborn, and even if they already have a new name.

Maybe the issue is caused by something else.  Looking into it.

**Comment by jasonrohrer** [comment]
Also works if they are reborn 1000000 tiles away.

**Comment by jasonrohrer** [comment]
Ah, I think I found it.

You are supposed to be able to curse them by name for 5 minutes after they die, if you're standing close to where they died.

There are two bugs here:

1.  If they are back alive again, their death position is ignored, and you can curse them from an infinite distance away from where they died.
2. If they die twice in a row, once close to you, and another time far away, while they are still dead from the second death, you can no longer curse them while standing near where they died the first time (only the most recent death position is remembered).

Case 2 can happen quite easily if they /DIE on the next life, which a griefer-type player is likely to do.  They might even /DIE before you get a chance to type their name for a curse.
