### ISSUE TITLE
Some large numbers do not display properly

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#904]
On occasion, I come across a number with a comma but only two digits after it. In the screenshot below, I was looking through the town graveyard and came across this old grave. I think the proper number is probably "1,054", but something is causing the 0 to get dropped so it shows up as "1,54".
![image](https://github.com/jasonrohrer/OneLife/assets/23004012/016c2e28-e35c-4aae-8020-4d3a2b4ba5c5)

**Comment by jasonrohrer** [comment]
Found the problem:

https://github.com/jasonrohrer/OneLife/blob/73af0ee08dbd7d5ba5541c6bfacb1f55df22054c/gameSource/LivingLifePage.cpp#L10660-L10678

This doesn't pad the various groups of digits out with zeros.
