### ISSUE TITLE
Player status when returning back into range

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#906]
Found this when testing today:

Walk away form an observer while holding a cart.  Walk out of range.  Set the cart down.  Now walk back into range.  You can hear the squeak of the cart approaching, and maybe even catch a glimpse of the cart in hand as the returning person appears on the screen, but then the cart suddenly disappears.

This may be because of a long MOVE chain that never gets interrupted by a PU message to tell you about their status change.

**Comment by TheMingo888** [comment]
This happens frequently with trucks. I will see someone moving very quickly across my screen, only for the truck to load in a few moments later.

**Comment by jasonrohrer** [comment]
Yeah... it's not that the truck hasn't loaded, but just that your client doesn't know they have the truck in their possession yet.

Very funny, though, imagining what that must look like!
