### ISSUE TITLE
Named cursing doesn't work for living players

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#909]
It seems to be impossible to curse living players by name at the moment. You can curse them by using "curse you", or you can curse them by name once they die (assuming you are close enough and it is recent enough).

I suspect this is related to 73af0ee08dbd7d5ba5541c6bfacb1f55df22054c. I'm thinking that maybe the `PlayerNameRecord`s aren't getting their `alive` field initialized to `true` in `logPlayerNameForCurses`, so the server thinks they are dead and checks the distance of the sender to 0, 0:
https://github.com/jasonrohrer/OneLife/blob/058f1a7014112295ae941199d4932fc59850ce5a/server/curses.cpp#L736-L747

**Comment by jasonrohrer** [comment]
Nice find!  This is critical enough that I will push out a fix today.

**Comment by jasonrohrer** [comment]
Hilariously.... this is working fine on my test map, because I'm always testing near (0,0)

This is why I didn't notice this problem when testing.
