### ISSUE TITLE
Family tree website missing ancestors

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#910]
The family tree websites seems to be having some trouble finding some dead ancestors, leading to messages such as "Mother still living" for people that died of old age, which is obviously impossible.

Take a look at: http://lineage.onehouronelife.com/server.php?action=character_page&id=9688425
At the time of writing, this is what the page looks like: ![image](https://github.com/jasonrohrer/OneLife/assets/23004012/6c20f383-c426-4906-83a9-283ce3b834ba)

If I follow the mothers back to the top, I eventually wind up here: http://lineage.onehouronelife.com/server.php?action=character_page&id=9687203&rel_id=9688425
![image](https://github.com/jasonrohrer/OneLife/assets/23004012/f73f97ea-5483-4332-a9f3-21e1218b9287)

It seems to be impossible to progress further to Maude's mother, which according to public data should be Hope Starlin (6556399). I can't seem to find Hope Starlin even when doing a manual search on the family tree website. Hope's mother, Zuzu Starlin (6556369), does appear in the family tree website, but Hope doesn't show up as one of their kids.

The has also happened recently in the Neff family: http://lineage.onehouronelife.com/server.php?action=character_page&id=9687941

**Comment by jasonrohrer** [comment]
This happens from time to time when the Lineage server goes down.

I got an email from Linode (the hosting company) a few days ago, saying that they had done some emergency maintenance on the lineage server, and they had to restart it.

During an outage like this, none of the lives that happen during the outage are recorded.

This isn't a bug, exactly, but just expected behavior from a cluster of 20+ task-specific servers.

**Comment by TheMingo888** [comment]
This makes sense. When I check the life logs, I can find a few others that died about the same time and are missing from the lineage server as well.

Perhaps, if someone dies and the lineage server is unavailable, we could save them to some buffer or file, and then once the server is back online we can empty this buffer or file to ensure nobody is missed?
