### ISSUE TITLE
New +containOffset and +containOffsetBottom tags preventing items from being contained

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#913]
This is noticeable with glass bottles, which could go into containers before the update but now cannot per jasonrohrer/OneLifeData7#1069.

I suspect this is due to the `containmentPermitted` function in `server.cpp`, which looks for any tag starting with `+cont` to restrict where objects can go.

**Comment by jasonrohrer** [comment]
Oh crap, you're right!  Nice catch.
