### ISSUE TITLE
Small bug with defaced bone piles

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLife#915]
Hey. Don't know if this was intended or not. But if you deface a bone pile, and pick it up and place back down with basket, the name is visible again and it's not defaced anymore.

**Comment by cordy-123** [comment]
Yeah, way before people (usually gravekeepers) would move bones from town using carts. But some code or bug would make them loose the body's name when placed in cart. Which of course, was weird coz the graveyard would be full of unnamed bodies. Not in keeping with burying beloved family members.

Mr. Rohrer's solution was that you had to deface the bones before being able to place them in carts. So you deliberately and knowingly did an action first before the body's name is lost.

That's the purpose of defacing bones. Not that they be defaced forever.

----

"Can now carry baskets of bones in carts, but must deface them first with a charcoal pencil. Placing them in carts causes their identity to be forgotten, and the charcoal marking makes certain that you know what you're doing (so grave identities aren't lost in a surprising way)."

https://github.com/jasonrohrer/OneLifeData7/commit/10483a3c2f6eceb0c21dffb8446a4b7e1b4dade5

**Comment by jasonrohrer** [comment]
It's still a little weird that the name disappears and comes back later (only if you dump it back in the same spot).

The problem with keeping it defaced forever (which would prevent the name from showing) is that burial and all the other transitions would no longer work on it (or if they did work, they might reveal the name again too).

So, for now, it seems best to just leave this little weird inconsistency in there.  If you re-drop defaced bones back in the same spot, they will pick up the forgotten name again.  There's something in the air in that spot...
