### ISSUE TITLE
Question regarding culling

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#918]
In jasonrohrer/OneLifeData7#1004, you mention that tiles that haven't been seen for 8 hours are culled unless they are in the noCullItemList. However, I have never observed this behaviour. Moreover, I believe you disabled it years ago in c1a5b0294cce19fbfe0f339770f1d311f7647a4e. Is it intentional that it is still disabled?

**Comment by jasonrohrer** [comment]
Indeed, it is off!

Thanks for pointing this out.
