### ISSUE TITLE
ZONE EFFECTS CLIPING INTO BUILDING

### ISSUE THREAD

**Issue by squeekyc1ean** [jasonrohrer/OneLife#919]
I WAS FROM JUNGLE FAM ATEMPTING TO LOOT SOMETHING FROM WALL SHELF FROM DEAD SNOW FAM TOWN AND THE WALL TEXTURE WOULD FLICKER REVEALING THE SNOW BIOME BEHIND IT AND WOULDNT LET ME INTERACT WITH ANY ITEMS ON SHELF.

**Comment by squeekyc1ean** [comment]
WALL SHELF WAS INSIDE A BUILDING

**Comment by jasonrohrer** [comment]
Can you catch a video of this happening?  Just pointing your phone at the screen and recording while it happens would be sufficient.

**Comment by jasonrohrer** [comment]
Going to close this for now.  Please re-open if there's more information.
