### ISSUE TITLE
Weird looking autofill of paved roads next to walls

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#921]
Autofill of floors near walls looks weird when paved roads are near a wall.

See picture.

![Screenshot - 06292023 - 01:35:28 PM](https://github.com/jasonrohrer/OneLifeData7/assets/12563681/cc42f9b1-0056-43ac-a1ad-5631627364eb)

**Comment by Forman9** [comment]
there's a similar effect when you have different tiles underneath walls
In particular, around doorways
