### ISSUE TITLE
Suggestion RE: Mother's location 

### ISSUE THREAD

**Issue by SharpieSharps** [jasonrohrer/OneLife#926]
Problem: The leader of the town is not always in town when new babies are born, so if a baby gets lost /LEADER is pointless.

Solution: Adding a marker for /MOTHER. This will also help new players to find their mother if they ever get lost. I've lost multiple kids I was teaching, because they got lost and couldn't find me anymore.

**Comment by jasonrohrer** [comment]
Great idea!
