### ISSUE TITLE
View rotation

### ISSUE THREAD

**Issue by wiogit** [jasonrohrer/OneLife#927]
It can be difficult to see something behind taller objects like trees. Generally you just have to know that something is there. It would be great if you could rotate the camera view 180 degrees so that you're looking south instead of north. Everything could still face the player and use the same sprites, but something that was previously behind a tree would be below it.

**Comment by is52hertz** [comment]
You can see a similar feature in **YumLife** - **[X]**, I think it's hard to implement camera selection, and the image will be misaligned during rotation.
Or maybe you should have @jasonrohrer  make the [X] feature back to make tall objects transparent. This feature is described in the tutorial, but not now.
_[Translated via DeepL]_

**Comment by wiogit** [comment]
I'm not suggesting a smooth, continuous rotation. It could be an instant rotation between north facing and south facing views. Also it would not rotate the sprites, it would only transform the positions of objects and the background tiles. A good example of what I'm talking about is in [this Don't Starve video](https://youtu.be/kXNwZ16zCCM?si=X2tQ_GsflsOyrSVA&t=209).

Games tend to have a step where they transform from world space to camera space. When the player/camera moves, the coordinates of objects have to be translated to screen relative coordinates. So what I'm asking is a rotation also be done (about the center of the player or screen) based on the whether the player is looking north or south.

Note: Don't Starve has north, east, south, and west viewing angles. This is a bit trickier to do in One Hour One Life because some sprites, like fences, have vertical/horizonal orientation. It is still feasible, but the vertical/horizonal oriented sprites would need to have respective horizontal/vertical oriented sprites drawn if the player is looking east or west.

**Comment by is52hertz** [comment]
Umm, It might be possible, but it sounds like the implementation would be difficult because of rotating the entire map's tuples. Let's see what @jasonrohrer has to say.

**Comment by jasonrohrer** [comment]
Yeah, such a thing would be possible... but it's a pretty difficult, deep change to make this late in the dev process.  So many aspects of the client assume North is North, etc.  Like... just flipping the view isn't enough.  There are also all the directional arrows, etc.

But beyond that, it would be hard to make it look pretty and not be confusing.  I see that Don't Starve actually "tweens" for a few frames, cross-fading between the two views.  This actually gives the visual impression that rotation is happening, even though it's only two views.

However, in terms of visual consistency, there's also something else different about OHOL vs Don't Starve.  OHOL keeps the hand-drawn-on-paper look very consistent throughout.  Don't Starve has a "hand-drawn-ish" look that it plays fast-and-loose with.  Objects bounce and wiggle, are scaled, etc.

OHOL is very much a "2D, hand-drawn world," or tries to be as much as possible.  The one lone divergence from this, that I can think of, is the way some sprites rotate, like the way a cart angles when you pick it up.

I've pretty much come to embrace the 2D nature of the thing over time... these are characters living in Flatland or something.  And yes, you can just hide something small behind a tree.
