### ISSUE TITLE
Mushroom Bug

### ISSUE THREAD

**Issue by wiogit** [jasonrohrer/OneLife#935]
If you die while you are suffering from the mushroom effect, the sprite swap seems to remain when you get reborn.

**Comment by cordy-123** [comment]
It's more of a feature now, instead of a bug.

To remove the effects...
... you can either restart your game client.
... eat another mushroom. (harder way as the sprites are swapped)

Read response of other people and the game developer here: https://github.com/jasonrohrer/OneLifeData7/issues/1056

**Comment by wiogit** [comment]
Oh, so I guess the bug is intentionally being left in? I don't really agree with the reasoning, because most newer players are going to see this as the obvious glitch that it is. Eating a mushroom to recover is also a weird solution, since you're tripping in order to escape a trip. Oh well.
