### ISSUE TITLE
New-ish Players Don't Realize That They are The Leader

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#936]
Currently, if you are the leader and you type /Leader, you see '+NO LEADER+' above your head.

-----

A lot of times, new / new-ish players get leadership.

Oftentimes, a new account (that doesn't SIDs and knows how to yum) might get to 50+ gene score by day 3 to 14 of continuous playing.

And that's fine. They got to experience leadership / learn how to do it sometime.

----- 

The issue is that for new player leaders, sometimes they don't realize that they are leaders. 

The responses you'd get when telling them that they are the leader or to tell them to do /Leader:
"I don't know who the leader is, it says 'No Leader'."
"We don't have a leader."
"No, I'm NOT the leader. It says 'No Leader'."
etc.

-----

Because when they see '+NO LEADER+', they think the town / hierarchy doesn't have a leader. 
(Because of course, they don't know the ins and outs of the mechanics of leadership, hierarchy, etc. yet.)

I'm proposing that instead of getting '+NO LEADER+', it should be '+YOU ARE THE LEADER+' or maybe '+YOU ARE THE HIGHEST LEADER+' would be more suitable or whatever phrase you think is appropriate.

-----

Caveat: I don't know if it would make sense for the message to be '+YOU ARE THE LEADER+' if a player is all ALONE in a hierarchy. Because they are, technically, not a leader as they do not have any followers. Maybe a different message. I don't know.
(Usual sample instances would be:
when you are Eve with no kids yet
when everyone else in your fam/hierarchy dies
when you type /Unfollow
etc.)

**Comment by ghost** [comment]
I think +NO LEADER+ would work best for the last caveat. If you have no followers and aren't following anyone, seeing +NO LEADER+ would hopefully encourage the player to either follow someone or get some followers of their own. Most people who use the "I follow myself" command do so knowingly, but I have seen new players tricked into saying it.

**Comment by jasonrohrer** [comment]
Yes, this makes sense!

I will fix it.
