### ISSUE TITLE
Pick Eves by randomizing races, not character models

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#938]
Right now, when a new Eve is placed but all races are already represented, a new Eve is chosen using `getRandomFemalePersonObject`. This is common behaviour immediately after a restart, since the sudden influx of players quickly overwhelms the few Eves that have spawned. The trouble is that `getRandomFemalePersonObject` does not take into account that some races have more character models than other races.

https://github.com/jasonrohrer/OneLife/blob/d3ac98f087708842d1c4cfa2064168f8a3225f9b/gameSource/objectBank.cpp#L5053-L5063

Right now, there are 3 Brown and White female objects but only 2 Black and Ginger female objects. This means that there are usually more Brown and White Eves than Black and Ginger Eves, which results in more Brown and White towns than Black and Ginger towns.

The best solution, of course, would be to create additional character models for the underrepresented races. Since this is probably a lot of work, a simpler solution would be to use a different algorithm that chooses a random race first and then a random character model within that race.

**Comment by jasonrohrer** [comment]
Ah, nice catch!

**Comment by NotSoShady116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/47ae5f37-a0c2-48b0-a544-169deea57437)
