### ISSUE TITLE
Fix server-side message flood check

### ISSUE THREAD

**Issue by selb** [jasonrohrer/OneLife#939]
Currently, `server.cpp messageFloodCheck()` only enforces the rate limit at the end of each batch. This allows for an unlimited number of actions to be sent as long as the user is fine with the minor inconvenience of reconnecting at batch end.

I believe that moving the `if( inPlayer->messageFloodBatchCount[index] >= maxMessageRate ) ...` conditional up a level will ensure that the intended action rate limit is enforced.

**Comment by jasonrohrer** [comment]
Ah, this is a huge improvement.

With a test client, that sends 1000 message batches repeatedly, I was able to send 12,000 messages in 5 seconds before being caught.

With the new code, it's caught 40 messages in to the first batch, and I'm disconnected instantly.
