### ISSUE TITLE
Curses Too Long

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#941]
The curses are five years making it so anybody who is trapped in donkey town after being mass cursed is stuck there for five years. This also gives no chance for redemption reducing the total player base to the dominating group of people enforcing their own playstyle and threating to send them to donkey town.

**Comment by NotSoShady116** [comment]
[Insert cocky comment here] (request for cocky comment denied)

**Comment by jasonrohrer** [comment]
No single person has the power to "send" someone to D-town.

Remember, you only go to d-town if there's no place left for you to be born, because you've annoyed people throughout the game.

And d-town for you will only last "five years" if you've annoyed so many people that there's no place for you to be born 24-7.  I.e., you've annoyed almost everyone who plays the game.

**Comment by NotSoShady116** [comment]
Oh I didn't even see this I was too busy working on my midterm study. I have so many god dam github accounts I'm not even sure where I started. Ok so yes what I was saying is if the consequences weren't changed like the tide on a beach during a Hurricane I wouldn't have done as I did.

**Comment by NotSoShady116** [comment]
The sudden change trapped everybody in donkey town, half the people who I know who didn't pay 100's of dollars on this game couldn't escape this and now can't do anything for five years. And I under

> No single person has the power to "send" someone to D-town.
> 
> Remember, you only go to d-town if there's no place left for you to be born, because you've annoyed people throughout the game.
> 
> And d-town for you will only last "five years" if you've annoyed so many people that there's no place for you to be born 24-7. I.e., you've annoyed almost everyone who plays the game. 

The new DT update soft locked people with a good amount of curses to be more specific. If the curse limit was reduced to something like 6 months or less if that's what you're thinking (because nobody is going to be playing this game for 6 straight months, besides the general player base) than it would be a win-win solution. The people down in donkey town for 24/7 would be reformed and less likely to grief, and the people in the people outside wouldn't have anything to complain about because nobody wants to not be able to play for half a year, rather than five years, or 60 months/1825 days. It makes the 14-20 dollars less wasteful. If I knew I was going to be not able to play besides in a place with 1-3 people on at a time I'd have just made an investment bank account for my future children's collage fund.
