### ISSUE TITLE
Make OHOL better. [in China]

### ISSUE THREAD

**Issue by is52hertz** [jasonrohrer/OneLife#944]
OHOL it's been a long time since an amazing update.
Does OHOL need to be better?
My opinion is published at https://github.com/jasonrohrer/OneLife/issues/931
I don't know if you have read it yet.

**Comment by is52hertz** [comment]
I'd like to know how you're doing with OHOL.

**Comment by NotSoShady116** [comment]
I'm not sure how ohol's been doing, I've been spending about 8 months in a place with no people, no settlements, nothing. No company, no conflicts, just a boring place with a biome that has tree, rock, biome i can't go in, the end... Nothing really fun

**Comment by is52hertz** [comment]
I know, I mentioned that those suggestions are too lame and too hard to realize.
I think this way, OHOL should focus more on China:
There are a lot of players in China who love OHOL as a game, but OHOL has always been inactive in China and ignored the Chinese players, resulting in a player flow.
I know it's hard to access China's internet in a proper way, or not familiar with China's internet way characteristics, causing OHOL to be underwater.
So I want to do something for OHOL in this area.
I want to act as a "proxy" for OHOL in China.
I will do so:
- Chineseize OHOL (steam).
- Chineseize OHOL tutorials and such.
- Actively collect opinions from Chinese players and submit them to you.
- Or whatever you want me to do in China.
Extra:
- Allow me to do something useful for updating OHOL by assigning hard labor to me.
Because I am Chinese and I really love OHOL.
Eagerly waiting for your reply, can you give me your contact info?
Please.

**Comment by NotSoShady116** [comment]
I think that would be nice, only problem is blood banned so I think they could make it like fruit punch, fruit punch covered (RUBBER) knife and all that. (JOKE)

**Comment by is52hertz** [comment]
Don't think of OHOL like that.
We're keeping everything.
Including...
18+ Game. hehe

**Comment by is52hertz** [comment]
> 我认为那会很好，唯一的问题是禁血，所以我认为他们可以把它做得像水果宾治、水果宾治覆盖（橡胶）刀等等。（笑话）

What you may have misunderstood about China
If you are Chinese, then I understand your words
你可能对中国有什么误解，
如果你是中国人，那么我理解你的话。

**Comment by is52hertz** [comment]
> I know, I mentioned that those suggestions are too lame and too hard to realize. I think this way, OHOL should focus more on China: There are a lot of players in China who love OHOL as a game, but OHOL has always been inactive in China and ignored the Chinese players, resulting in a player flow. I know it's hard to access China's internet in a proper way, or not familiar with China's internet way characteristics, causing OHOL to be underwater. So I want to do something for OHOL in this area. I want to act as a "proxy" for OHOL in China. I will do so:
> 
> * Chineseize OHOL (steam).
> * Chineseize OHOL tutorials and such.
> * Actively collect opinions from Chinese players and submit them to you.
> * Or whatever you want me to do in China.
>   Extra:
> * Allow me to do something useful for updating OHOL by assigning hard labor to me.
>   Because I am Chinese and I really love OHOL.
>   Eagerly waiting for your reply, can you give me your contact info?
>   Please.

I'd like to come to China to help OHOL register official accounts on various platforms to drop official Chinese videos. (I'll do the Chineseization!)
LIKE #949

**Comment by jasonrohrer** [comment]
I'm pointing to the mod for now.

I'm also really focusing on other things.  I only have so much energy left in my life that I can devote to OHOL, so I need to prioritize.

While it would be great if the game became an international hit, that's just not my focus.
