### ISSUE TITLE
Donkey Town too long (request #34) (public request 2)

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#945]
Balbala whatever playstyle, I'm getting tired of writing about this. Donkey town is too long, why wait five years to come back for griefing. It's like, hey think about what you did for five years of your life buddy, come back when you're in collage, or when you have a wife and kids. You had better think about what you did.

**Comment by NotSoShady116** [comment]
A rule as ancient as the game changes as soon as I join it. I feel like I'm being given too much power, I was just meant to be a normal player. Smh

**Comment by TwistedHBG** [comment]
Most people don't wanna play with you. And when I say most, I'm saying that most people who play this game took time to actually type out an ingame command just so they don't have to have you around them anymore.

So many people did that that there's literally not a single spot for you to spawn on ingame so the game has to create a special new area for you far away from everyone just so you can play.

Reducing the curse timer would be unfair to the many many many people who don't want to play the game with you around them.

**Comment by Rukhmar** [comment]
Oh wow, consequences for your actions? Jason at least added that you can interact with biomes in Donkey Town now, you couldn't before.

But really, if you didn't grief or keep saying _that_ word, then you wouldn't be in this situation. People don't like it if you attack towns.

**Comment by NotSoShady116** [comment]
> Oh wow, consequences for your actions? Jason at least added that you can interact with biomes in Donkey Town now, you couldn't before.
> 
> But really, if you didn't grief or keep saying _that_ word, then you wouldn't be in this situation. People don't like it if you attack towns.

Why don't you take a five year visit and see for yourself.

**Comment by NotSoShady116** [comment]
> Most people don't wanna play with you. And when I say most, I'm saying that most people who play this game took time to actually type out an ingame command just so they don't have to have you around them anymore.
> 
> So many people did that that there's literally not a single spot for you to spawn on ingame so the game has to create a special new area for you far away from everyone just so you can play.
> 
> Reducing the curse timer would be unfair to the many many many people who don't want to play the game with you around them.

Me who hasn't played for 8 months? Your point is so hallow, you don't even know me, most people don't even know me.

**Comment by NotSoShady116** [comment]
> > Oh wow, consequences for your actions? Jason at least added that you can interact with biomes in Donkey Town now, you couldn't before.
> > But really, if you didn't grief or keep saying _that_ word, then you wouldn't be in this situation. People don't like it if you attack towns.
> 
> Why don't you take a five year visit and see for yourself.

Also what if I didn't grief, what if I simply decided not to grief after getting out. Redemption is non existent with this five year system. You dehumanize me like I'll just get out and do the same thing, unlike an unmature 12 year old I'm not about to put all this effort into whatever just to get back in the same situation

**Comment by NotSoShady116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/311232ab-2d0b-41c8-ba21-99e4f8dd48e4)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/e3261ab9-7e41-4440-a4b7-25ac756161ce)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/00c3604a-0e97-4a63-81e9-484e1e38c2f2)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/2ab2cc69-2562-4b90-b2c2-eda81b011a00)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/92d8d599-3f8c-4dec-adde-dbd9a86251f8)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/6ef89e2f-60ef-46c4-8524-c7feb472e3e8)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/2341f605-bcc4-4708-a1d0-72a52a903a27)

**Comment by NotSoShady116** [comment]
I really don't feel like giving up, it's my philosophy.
