### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#946]
I wish there could be a server list and if you wanted your server to be on there you'd have to pay for it (one time) as a way to make income

**Comment by is52hertz** [comment]
Did you actually go online and look it up?
OHOL there's been a server list for a long time

**Comment by NotSoShady116** [comment]
In game one though

**Comment by NotSoShady116** [comment]
so rather than connecting to a webserver I think it would be cool to see the active servers ingame

**Comment by is52hertz** [comment]
You can have Jason add a command.
/SERVER
