### ISSUE TITLE
Donkey Town Is Boring 𝒯𝐻𝐸 𝒮𝐸𝒬𝒰𝒜𝐿

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#947]
Fun Adventures Across Low Population
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/7fa185cb-d1e0-4775-9bc2-66254bbae9ce)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/c63f4bf3-b278-4f2c-a179-b4e67f6b5cd4)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/a22627aa-cb4c-4a0c-9127-6bb42c5665de)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/d6e58e72-4221-4059-98f7-345f633b4005)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/b67f706f-0a9a-417f-a57f-0d58f6568a91)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/d9d220f7-e008-4603-a366-7defc8bef1fa)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/85eecbf2-c7d4-4216-8a53-5437939a2e7f)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/c9b7b745-66db-4990-bf94-c7c820427ad3)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/6a7ce078-4570-41d4-8d4f-a9da163515bf)
And so this ends this presentation, way better than literal wilderness

**Comment by NotSoShady116** [comment]
Like I don't understand what you're meant to do in donker sloot land where you just get to live for afew seconds and die. The main selling point in the game is social interaction and teambuilding, the main reason most of these people bought the game.

**Comment by NotSoShady116** [comment]
Jason, think of it this way. Out of the hundreds of sales a month in this game... what difference would it make if I just bought the game for 20$ and if you just let me out of donkey town. Both would have the same outcome, I'm out of donkey town, that changes literally nothing about the outcome of the situation no matter the tree I go down.
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/6216514d-7727-4bd0-8a38-20840814aa52)

**Comment by NotSoShady116** [comment]
Now I know some people may be in opposition but if you're not speaking from a first hand view you should shhushh till you know what you're talking about, rather than acting like a **SHEEP** following the orders of your godly Shepards that are the random 10 people who are all up on me all the time. 
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/40469f3e-3b0b-4a90-ac9d-03890fc787fb)

**Comment by SoloAceMouse** [comment]
Hi Shady,

You probably don't know me but I've learned a lot about you from your posts in the OHOL community and your anti-social behavior in game. I see that you've been having a really tough time in Donkey Town lately and are just not quite understanding the purpose of that game mechanic.

Well have no fear, because I'll give you a story that might clear it up for you...

-----

Let's say I really like this movie, _Leon: The Professional_
It's a great film, one of those action movies that doesn't quite break through the mainstream but absolutely deserves a fair shake
Well, maybe I'll have an acquaintance [you] over and I'll show him the awesome acting chops of Gary Oldman as the nefarious crooked cop Norman Stansfield

The first day I call you up and you drop by, so I greet you at the door
We head to the living room and I tell you I'll be right back and to get settled in while I get some snacks
When I return, you are gone, but in your place is fresh pile of human shit
Yup, you shit on the floor of my home and fled

The next day comes and, despite my hesitation, I call him again because Jean Reno is a phenomenally underrated actor
You arrive and I let you inside, eager to share the film you missed the day prior
While maintaining direct eye contact with me, you drop your pants and shit into my decorative flower vase before leaving
Ohh well, guess I'll try again tomorrow...

The third day arrives and against my better judgement I let you over for another try
This time, you don't even wait for me to speak, you immediately barge in the door and push past me before taking dump in my coffee maker
On your way out you piss on my doormat, it appears I have another mess to clean up again

On the fourth day, I make you promise not shit or piss in my home anywhere but the toilet
_Leon_ is already playing in the corner of the room, as I'm hoping you'll be captivated by Luc Besson's masterpiece
To my surprise, you sit down and we watch the whole film together
Ohh how we enjoy our fun time and I am so happy that you finally got to see this fantastic movie
After you leave, I discover you've murdered my goldfish and in his place is a slowly disintegrating poopie floating in the fish tank

The fifth day comes around and you call me to ask what movie we're watching
This is when I tell you things aren't working out and I you can't come over anymore

-----

This is what it is like to deal with you, Shady

I hope you can appreciate a small glimmer of the burden that is putting up with you

**Comment by DopiePanda** [comment]
People who play this game for positive social interaction and teambuilding don't end up in Donkey Town. Donkey Town is reserved for the very few people who repeatedly grief and ruin the game experience for everyone else. If you have a problem with Donkey Town, get a new copy of the game and stop ruining the fun for everyone around you.

**Comment by NotSoShady116** [comment]
So what you're saying is you don't know me from a first hand perspective and you're disregarding anything I said at all. And it's been 8 months not doing anything and you're claiming I've been griefing. Get a little knowledge first. I bet you won't do shit to quirky, the person who started the griefer group. You of two people have nothing really to prove, get out when you have some useful information.

**Comment by NotSoShady116** [comment]
> People who play this game for positive social interaction and teambuilding don't end up in Donkey Town. Donkey Town is reserved for the very few people who repeatedly grief and ruin the game experience for everyone else. If you have a problem with Donkey Town, get a new copy of the game and stop ruining the fun for everyone around you.

That will literally do nothing, whos to say I won't grief after buying the game. You just have to find out

**Comment by SoloAceMouse** [comment]
> So what you're saying is you don't know me from a first hand perspective and you're disregarding anything I said at all. And it's been 8 months not doing anything and you're claiming I've been griefing. Get a little knowledge first. I bet you won't do shit to quirky, the person who started the griefer group. You of two people have nothing really to prove, get out when you have some useful information.

What I'm saying is you're a nuisance and you deserve to never leave Donkey Town again

I'll also curse Quirky [and I have cursed him before] when he griefs

Go play a different game, you're done here, Shady

**Comment by DopiePanda** [comment]
> That will literally do nothing, whos to say I won't grief after buying the game. You just have to find out

Well, then there is no point about crying about the consequences of your actions.

**Comment by NotSoShady116** [comment]
> [DopiePanda](/DopiePanda)

All you're doing is speaking blindly from emotion and not from any real foundation. What is the risk of me being released from donkey town. A single man, a single person. If I were to buy the game the outcome would still be the same. You're not thinking from a strategic standpoint. With these new griefer control updates the risk would be near nothing. But you're standing on an emotional foundation. Please do come again when you've assessed the real risked of being released, because blablabla curses isn't a point anymore for a community of fresh new players who don't know anything about me.

**Comment by SoloAceMouse** [comment]
[By the way, I know you're lying about the 8 months thing. I know you don't understand the public data logs, but I assure you we can see when you play]

Dear Shady,

You lost

You can try to keep lying and pretending folks are "out to get you" but the truth is that we see right through all your lies. I don't know how much longer before you quit the game for good, but hopefully it is soon. Please keep the following in mind as you reflect on this experience:

**Your choices** got you here [kicked off the Discord, subreddit, and forum]
**Your decisions** are why you are in Donkey Town
**Your actions** are why **YOU LOST OHOL**

Sincerely,
The OHOL Community

**Comment by NotSoShady116** [comment]
How many months has it been, and my point still stands.

**Comment by NotSoShady116** [comment]
If you knock out part of the plant it doesn't die it just grows back. utterly you have no idea what you're talking about, you tag  along

**Comment by SoloAceMouse** [comment]
> How many months has it been, and my point still stands.

Your point does not stand

In fact, you were playing on x Hound Tomb x in July, which was only 3 months ago...

Why do you feel the need to lie when your lies are so easy to disprove?

**Comment by NotSoShady116** [comment]
> [By the way, I know you're lying about the 8 months thing. I know you don't understand the public data logs, but I assure you we can see when you play]
> 
> Dear Shady,
> 
> You lost
> 
> You can try to keep lying and pretending folks are "out to get you" but the truth is that we see right through all your lies. I don't know how much longer before you quit the game for good, but hopefully it is soon. Please keep the following in mind as you reflect on this experience:
> 
> **Your choices** got you here [kicked off the Discord, subreddit, and forum] **Your decisions** are why you are in Donkey Town **Your actions** are why **YOU LOST OHOL**
> 
> Sincerely, The OHOL Community

You don't speak for no one but your own division of assholes who charge without reason. Just know I'm not giving up till I'm unbanned, this shit will go on for five years. I don't care how many expendable v-machines or web browsers it takes to disprove you. Just know you have disproven nothing. Jason should really read through these

**Comment by NotSoShady116** [comment]
> [By the way, I know you're lying about the 8 months thing. I know you don't understand the public data logs, but I assure you we can see when you play]
> 
> Dear Shady,
> 
> You lost
> 
> You can try to keep lying and pretending folks are "out to get you" but the truth is that we see right through all your lies. I don't know how much longer before you quit the game for good, but hopefully it is soon. Please keep the following in mind as you reflect on this experience:
> 
> **Your choices** got you here [kicked off the Discord, subreddit, and forum] **Your decisions** are why you are in Donkey Town **Your actions** are why **YOU LOST OHOL**
> 
> Sincerely, The OHOL Community

Jason please review these comments, these people will tell you anything without evidence, because yes undoubtably I got cursed into donkey town. But these people are not looking at anything from any source of reason besides. GLAWKKMSKWMDS SHADY YOU DEsEREeeeVEE IIIwT. In general the whole donkey town system is just fucked and I'd argue things were better before the rift and five year update.

**Comment by SoloAceMouse** [comment]
"Just know I'm not giving up till I'm unbanned, this shit will go on for five years."
-Shady [prior to him editing his comment]

Of all the things to devote your life to, and you choose to dedicate your energy to trying to annoy as many people as possible in a niche indie game

I dunno what to tell you kid, the OHOL community collectively decided to ban you
That's literally what Donkey Town is, it's the community deciding to ban someone

**Comment by NotSoShady116** [comment]
> "Just know I'm not giving up till I'm unbanned, this shit will go on for five years." -Shady [prior to him editing his comment]
> 
> Of all the things to devote your life to, and you choose to dedicate your energy to trying to annoy as many people as possible in a niche indie game
> 
> I dunno what to tell you kid, the OHOL community collectively decided to ban you That's literally what Donkey Town is, it's the community deciding to ban someone

I got no idea how to respond to this but my point still stands while your point is built on mountains of desert sand.

**Comment by SoloAceMouse** [comment]
> > "Just know I'm not giving up till I'm unbanned, this shit will go on for five years." -Shady [prior to him editing his comment]
> > Of all the things to devote your life to, and you choose to dedicate your energy to trying to annoy as many people as possible in a niche indie game
> > I dunno what to tell you kid, the OHOL community collectively decided to ban you That's literally what Donkey Town is, it's the community deciding to ban someone
> 
> I got no idea how to respond to this but my point still stands while your point is built on mountains of desert sand.

Ok, I'll humor you, Shady [seeing as it's only a matter of time before you're banned here as well and I lose the chance]

What do you think Donkey Town is for?
If it's not for putting naughty little kids like you in timeout, then why else would it exist?

**Comment by NotSoShady116** [comment]
> > > [By the way, I know you're lying about the 8 months thing. I know you don't understand the public data logs, but I assure you we can see when you play]
> > > Dear Shady,
> > > You lost
> > > You can try to keep lying and pretending folks are "out to get you" but the truth is that we see right through all your lies. I don't know how much longer before you quit the game for good, but hopefully it is soon. Please keep the following in mind as you reflect on this experience:
> > > **Your choices** got you here [kicked off the Discord, subreddit, and forum] **Your decisions** are why you are in Donkey Town **Your actions** are why **YOU LOST OHOL**
> > > Sincerely, The OHOL Community
> > 
> > 
> > Jason please review these comments, these people will tell you anything without evidence, because yes undoubtably I got cursed into donkey town. But these people are not looking at anything from any source of reason besides. GLAWKKMSKWMDS SHADY YOU DEsEREeeeVEE IIIwT. In general the whole donkey town system is just fucked and I'd argue things were better before the rift and five year update.
> 
> Jason already told you that he won't unban you
> 
> You can spend the next 10 years making thousands of posts and that won't change
> 
> You messed up, now deal with the consequences This is part of growing up, Shady

Give uwp shady, (No) The fight doesn't stop till I'm out, (I DO NOT CARE) about what you have to say anymore because you have tossed out all respect. All I want Jason to do is look past the mountains of bullshit given by a single person.

**Comment by SoloAceMouse** [comment]
> Give uwp shady, (No) The fight doesn't stop till I'm out, (I DO NOT CARE) about what you have to say anymore because you have tossed out all respect. All I want Jason to do is look past the mountains of bullshit given by a single person.

This is no "single person", Shady

There are literally over 100 people in this game who all came to the conclusion you're the bad guy

"The fight doesn't stop till I'm out"
Buddy, you've been out for awhile at this point
The fight is over, and you're just punching at the air after getting knocked out in round 1

**Comment by SoloAceMouse** [comment]
> Acting like he's king, like he owns the community. When did the 1 of the 1000 people who play this game start becoming district representatives. You have just as much player value as me, we both bought the game. Infact what do you gain out of this besides thinking you're a good person.

I've played hundreds, even thousands of lives

I've taught new players the skills they need to start their OHOL journeys so many times I can't remember a fraction of them

I've made visual guides which teach players about complicated in-game concepts and mechanics [such as drilling oil]

In my time in the OHOL community, I've done my best to make the game a better place for the people I share it with. I do this because I love OHOL and I love [most] of the wonderful people who play it. I want them to have as much good times as possible because that's just the kind of guy I am

Unlike you, who seeks only to make everyone else have a worse time playing the game

**Comment by NotSoShady116** [comment]
> Fun Adventures Across Low Population ![image](https://user-images.githubusercontent.com/126307271/274131182-7fa185cb-d1e0-4775-9bc2-66254bbae9ce.png) ![image](https://user-images.githubusercontent.com/126307271/274131234-c63f4bf3-b278-4f2c-a179-b4e67f6b5cd4.png) ![image](https://user-images.githubusercontent.com/126307271/274131384-a22627aa-cb4c-4a0c-9127-6bb42c5665de.png) ![image](https://user-images.githubusercontent.com/126307271/274131489-d6e58e72-4221-4059-98f7-345f633b4005.png) ![image](https://user-images.githubusercontent.com/126307271/274131529-b67f706f-0a9a-417f-a57f-0d58f6568a91.png) ![image](https://user-images.githubusercontent.com/126307271/274131553-d9d220f7-e008-4603-a366-7defc8bef1fa.png) ![image](https://user-images.githubusercontent.com/126307271/274131615-85eecbf2-c7d4-4216-8a53-5437939a2e7f.png) ![image](https://user-images.githubusercontent.com/126307271/274131661-c9b7b745-66db-4990-bf94-c7c820427ad3.png) ![image](https://user-images.githubusercontent.com/126307271/274131694-6a7ce078-4570-41d4-8d4f-a9da163515bf.png) And so this ends this presentation, way better than literal wilderness

This was true fun, I bet everybody wants this, but for you it's not rare so you speak from privilege.

**Comment by NotSoShady116** [comment]
Just see what happens please Jason, what is life without risks. And you're the maker of the game...

**Comment by ShamWish** [comment]
All I see from the pictures is Shady taking a horse from his fam to abandon it in some far off swamp where he kills himself with a boar, lowering his immediate family's gene score. Was this supposed to prove he's not a griefer?

**Comment by Tarr-OHOL** [comment]
I am surprised Jason hasn’t banned this shitposting from the GitHub yet.

**Comment by NotSoShady116** [comment]
> I am surprised Jason hasn’t banned this shitposting from the GitHub yet.

Than you for bringing this very informational comment to the table, you sure are proving me wrong.





















(You're not)

**Comment by NotSoShady116** [comment]
> All I see from the pictures is Shady taking a horse from his fam to abandon it in some far off swamp where he kills himself with a boar, lowering his immediate family's gene score. Was this supposed to prove he's not a griefer?

I found this horse in the wild, dying at 34 doesn't lower your gene score. Please stop being like a twitter mom, you're too. sensitive. Learn to chill out, because something I didn't do was slaughter my entire family by feeding my children to bears and luring them. That will have been griefing enough. Just please stop proving my point, look I'm giving you the  chance to just disengage, you don't even have to talk. Infact if in I ever get back I won't even communicate with you ever. You don't even have to hear a word out of me talking to you ( A person I don't know ) If you don't trust me you can easily just banish me back to donkey town. There is literally no problem with dealing with a single shady, it's not like you're releasing a bunch of griefers. Just chill out and think about it.

**Comment by NotSoShady116** [comment]
Jason I know this is alot to read and that is simply because people like to tag along mindlessly like vultures

**Comment by NotSoShady116** [comment]
> becoming

I'm usually welcoming to new players, I teach them about curses and stuff so they don't end up stuck for 
t̶h̶r̶e̶e̶ ̶m̶o̶n̶t̶h̶s̶  Lord forgive me.. FIVE GOD DAM YEARS

**Comment by NotSoShady116** [comment]
> > becoming
> 
> I'm usually welcoming to new players, I teach them about curses and stuff so they don't end up stuck for t̶h̶r̶e̶e̶ ̶m̶o̶n̶t̶h̶s̶ Lord forgive me.. FIVE GOD DAM YEARS

also narcissus chill with the self love, it's gone to far. I feel like I've done more than you.. Got bears banned, the apocalypse, me a single player who joined last year during a Christmas sale has some how left a footprint upon this game. Yet you don't see me constantly flaunting my achievements in your face. Get humble please and don't be a hypocrite.

![image](https://github.com/jasonrohrer/OneLife/assets/126307271/49488bda-1dce-4e30-bace-a878994a0748)
