### ISSUE TITLE
New players in donkey town (Five Year Curses) Issue 36

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#948]
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/a0c050ee-81de-4890-bff0-d820a0d3ec5b)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/0f4ccd5a-cfed-4d0c-81e7-e1c06f31e24b)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/566f8530-d68b-4902-81f4-228cf74cf7e2)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/20c1cb0b-7565-475b-9391-06b0d084f925)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/3dbcfb2e-9e9a-421a-ad75-8379a82dcc70)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/ac50d025-ea1b-4f9d-a036-50cf2d234198)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/500a71d4-86e3-4370-ba3a-7599e073e517)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/3797e3a4-a124-4041-b212-abf0a9f50941)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/97d5f981-83e3-4af6-8588-a41260a3fb52)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/7ff1df80-0327-475e-b8e4-f343e5ab8b10)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/23f4bb36-b3e7-404a-ad5c-ab367d9305fe)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/5d837573-d734-4e91-a493-bcffbc8a4bdf)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/62aa7e77-016e-4795-b7c0-39fff44da725)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/1500ce9e-4670-4a6c-8147-83b4b3b57095)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/9c0756ae-385c-4101-9def-e68fe6a50bd8)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/bde324f1-c15b-4b1d-8e76-3cbbfb29650d)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/fc6ed18c-09bb-49cc-96c2-f86e7a051466)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/05936d80-1f2e-4d0f-a971-a4dfbf8beae5)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/5837d8c2-dcd5-41b6-b983-5ddffdd03c40)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/7b529fb6-a491-4236-bce3-94c15511ca10)
The town once had abunch of people

Edit: If worst comes to worst (likely) I'll just have to do what I must do.

**Comment by NotSoShady116** [comment]
when will this be addressed, I need a response

**Comment by NotSoShady116** [comment]
I'll be ignoring any random annoying comments

**Comment by NotSoShady116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/0ed306fc-d00c-47d1-aa52-b6337519f373)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/6425abd7-8a86-4094-a9ed-834be98c6a33)
Jason will you please fix this, no new player should be in dt that quickly and for that long. Please Jason 🥺

**Comment by NotSoShady116** [comment]
This is wacky and loony
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/179d0177-8716-4f55-ac44-6305731da4ed)

**Comment by NotSoShady116** [comment]
Will we need a friday update or downdate?

**Comment by SoloAceMouse** [comment]
Jason, can you not ban him from the project?

This kid clearly is just gonna keep spamming this nonsense until he's banned here

**Comment by NotSoShady116** [comment]
> Jason, are you able to ban him from the project?
> 
> This kid clearly is just gonna keep spamming this nonsense until he's banned here

I got like infinite accounts broo.  if you don't get it first month you try again the next month. Btw NNN is coming up.

**Comment by NotSoShady116** [comment]
> Jason, are you able to ban him from the project?
> 
> This kid clearly is just gonna keep spamming this nonsense until he's banned here

Also I don't think the phrase  players fall off your curse list after 
(several) days is nonsense

**Comment by cordy-123** [comment]
Whether the curse length is 5 years or 3 months...

... it MOSTLY does NOT matter when it comes to NEW PLAYERS (excluding new accounts that are alts).

Based on my years of playing and looking at people's accounts, most NEW players who repeatedly spawn to donkey town for a few days to a week will give up on the game. 
(Even the ones that don't know or are not told what donkey town is.)
New players will NOT wait 3 months to pick up the game again.

**So even if Mr. Rohrer reverted the curse length to 3 months, almost all of those new players that get cursed will not benefit from it.**

----

Curse length mostly matters to LONG TERM regular players.

**Comment by cordy-123** [comment]
> ![image](https://user-images.githubusercontent.com/126307271/274456795-179d0177-8716-4f55-ac44-6305731da4ed.png) 

Yeah, Mr. Rohrer has not updated the tutorial in quite a long time.
