### ISSUE TITLE
Add Unicode Language Mod Link to Game Menu and Make Videos about It

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLife#949]
This is the sequel of https://github.com/jasonrohrer/OneLife/issues/931

First, thanks for adding the link to official website! I feel honored.
But I think not everyone will read the website carefully.
So maybe add the link to in-game menu as well? Just like [\[TECH\]](https://onetech.info/) button.
Maybe make it a [\[TRANSLATE\]](https://github.com/skps2010/OneLife) button

Also I suggest making a video about it, because Chinese players may not notice a single update in OHOL, and a video by official owner is a great way to spread information.

If you want to make a video, I suggest also posting it into [bilibili](https://www.bilibili.com/), because Youtube is blocked in China, and bilibili is the largest video platform in China. If you don't want to make an account there, we can help you posting it.

We can also help you making the video if you want. There are one Taiwanese(me) and several Chinese in our group.

**Comment by NotSoShady116** [comment]
👏WOOOO👏

**Comment by SoloAceMouse** [comment]
Fully in support of translation efforts and accessibility for non-English speakers.

However, I do think for the purposes of videos/promotion, that might be better handled within the community. No offense to Jason, but I'm sure a native speaker would have an easier time making videos which appeal to the Chinese market. Perhaps a small group of Mandarin-speakers [I know of several within the OHOL community] could coordinate this.

But yeah, completely agree with adding features to increase accessibility of OHOL.

**Comment by is52hertz** [comment]
I am ......

**Comment by jasonrohrer** [comment]
I gave it some thought, and I don't think it's a good idea to specifically link to the mod from inside the game itself.

Also, I'm not in a great position to make a video for Chinese players.  Hopefully the community can do that, if needed.
