### ISSUE TITLE
Gestures automatically switching

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#953]
The issue described in jasonrohrer/OneLifeData7#1103 is not a mod issue and can be reproduced in vanilla too. Reproducing it is not easy, however, and multiple tries were needed to produce this recording. I am not sure what the cause is.

https://github.com/jasonrohrer/OneLife/assets/23004012/0d2cf059-9b07-444c-b190-2446602f52e6

**Comment by NotSoShady116** [comment]
Jason, you should have also added the middle finger gesture. And tossing money gesture.
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/d062e96d-a320-49ce-91b6-61b3290d0046)

**Comment by TwistedHBG** [comment]
Yes, I can confirm, this happens to me every time and I do not use a modded client

**Comment by TwistedHBG** [comment]
Video example - https://youtu.be/xf0yVCnrT3w

Also it would be nice if the emotes kept going when you flip left/right due to mouse movement

**Comment by NotSoShady116** [comment]
Jason can you update the earth?

**Comment by jasonrohrer** [comment]
Whoa!  Yeah, I'm suddenly able to reproduce this myself on the live server.

Very strange, since it wasn't happening for me before.

I'll get right on fixing this.

**Comment by jasonrohrer** [comment]
Very strangely, I can't reproduce this on my private server.  Still looking into it.

**Comment by jasonrohrer** [comment]
Oh my goodness...

Basically other player's gestures are completely overwriting each other.

That's why it's hard to reproduce... depends on other players gesturing too in parallel.  Ugg!
