### ISSUE TITLE
I hava some questions.

### ISSUE THREAD

**Issue by is52hertz** [jasonrohrer/OneLife#955]
The unique style of OHOL sets it apart from other games. I have a few queries that I would greatly appreciate if you could answer.
___
Question:

- About OHOL's graphics: OHOL's graphics are hand-painted, which leads me to the following questions.
  > 1. What type of paper has been used for the paintings in OHOL, and which brand does it belong to? (I'm guessing it might be white cardstock)
  > 2. What pens are used for coloring and outlining the art in OHOL? (Based on a video from 5 years ago, you may have mentioned Tombo brushes, but they're not available in my region. Could you please specify the type of brushes you use?)

- Regarding OHOL's item editor:
  > 1. How are files exported from OHOL 'Scence' enabled on the local test server?
  > 2. What tool does OHOL use for importing 'lines' and 'Sprites'? Alternatively, could you share with me the tool you use to scan physical images into digital ones?

 - Pertaining to OHOL's server settings:
   > 1. How can I set specific mailboxes in OHOLserver to spawn at given coordinates? (I noticed this in the settings but I'm not sure about the format)
   > 2. How can I set the OHOLserver such that players who reach a specific age are required to spawn next to a death or home marker, regardless of whether they are Eve or multiples?
   > 3. I need assistance with using OHOLwebserver! I'm having trouble running it without encountering errors.

 - Concerning OHOL's compiling processes:
   > 1. How can I compile the Windows/MacOS version of OHOLserver?
   > 2. How can I compile the Windows/MacOS version of OHOLeditor?
___

**Comment by NotSoShady116** [comment]
I think he drew them online using paint studio or somin but it could be hand drawn
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/b65a0b73-eb1d-4e7f-956f-c534d082b2a5)

**Comment by is52hertz** [comment]
> 我想他用绘画工作室或索明在网上画了它们，但它可能是手绘的 ![image](https://user-images.githubusercontent.com/126307271/275344010-b65a0b73-eb1d-4e7f-956f-c534d082b2a5.png)

No, it isn't.
With the video below, jason demonstrates.
https://youtu.be/WbQsZ5rQ2gg?si=7rLxfisXy4MeooYs

**Comment by is52hertz** [comment]
> OHOL 的独特风格使其与其他游戏区分开来。我有几个问题，如果您能回答，我将不胜感激。
> 
> 问题：
> 
> ......
>   > 2. 如何编译 Windows/MacOS 版本的 OHOLeditor？

I think all of these issues are important to me.
But none is more important than painting.
Can you show us your current paintings?

**Comment by NotSoShady116** [comment]
> > OHOL 的独特风格使其与其他游戏区分开来。我有几个问题，如果您能回答，我将不胜感激。
> > 问题：
> > ......
> > > 2. 如何编译 Windows/MacOS 版本的 OHOLeditor？
> 
> I think all of these issues are important to me. But none is more important than painting. Can you show us your current paintings?

GOOD LORD Every Single Frame and Part Hand Painted...

**Comment by jasonrohrer** [comment]
Yes, they are drawn with Uni-bal Vision pens (regular Vision, not Elite).  They are the "micro" tip size, 0.5mm tips.  Black ink.

https://uniballco.com/products/vision-rollerball-pens?variant=39362320171214

The paper is from Dick Blick.  I'm pretty sure it is the Sulphite drawing paper.  It came in 18x24 inch sheets, and we had them cut into 4 pieces, so each piece was 9x12.

https://www.dickblick.com/items/blick-sulphite-drawing-papers-18-x-24-white-500-sheets-80-lb

The markers are Tombow Dual Brush pens.  The brush end is always used.

https://www.tombowusa.com/dual-brush-pen.html

The line are is drawn, and then using a lighted tracing table, an outline is traced, and that outline is colored.  So the color doesn't "smear" the lines in the drawing.  The two parts are scanned separately and combined in the editor (as shown in the video).

Several examples are also shown here:

http://onehouronelife.com/artLogPage.php

I scan them with an "Epson v550 Photo" scanner.  They get saved in here automatically by the scanner:

/home/jasonrohrer/default.png  

I scan whole sheets at a time, with lots of sprites on each sheet.

When you click "Sprite Import" or "Line Import" in the editor, it loads the PNG file from default.png.

That file location can be changed in "settings/editorImportPath.ini"


Sprite Import brings in a "solid" thing, observing outer black lines to define the boundary of the solid area.

Line Import brings in a transparent line overlay with no solid areas.  You can combine the Solid part with the transparent Line part to make the finished sprite.

This allows the sprites to have "sketchy lines" on the outside edges.
