### ISSUE TITLE
Issue And Compromise

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#956]
The issue is that others may end up in the same situation as I was in in donkey town where they have so many curses they can't leave. (Softlocked)

The _**𝐜𝐨𝐦𝐩𝐫𝐨𝐦𝐢𝐬𝐞 𝐢𝐝𝐞𝐚**_ is a sort of system where **every hour spent in donkey town is one less curse**, but **this system is only employed when the person is above 30 curses.** This way the person still learns their lesson without not being able to play the game again. It would just take a lot of hours of playing in donkey town to get out. 

**Not only will the person learn to stop griefing, the total population of donkey town would increase full of people desperate to get out.** 

A good name for it seems like the funneling system. But again my specialty is not complex mathematics in the c++ language so I got no idea how this would be employed.

**Comment by is52hertz** [comment]
Maybe we need a whole new curse system. Think about it...

**Comment by NotSoShady116** [comment]
Or just a system where curses last forever and you must work off the griefing you have done or stay in donkey town. You pay for the damage you have caused just like irl.

**Comment by NotSoShady116** [comment]
> Maybe we need a whole new curse system. Think about it...

Like think about it. In a penial colony they force you to work to get out.  
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/3ae0cea7-6c7d-455c-acd8-aa4eebe8cb59)

**Comment by NotSoShady116** [comment]
Mr. Rohrer, this also solves the issue of griefers cycling alts, in order to get all those alts out of dt you'd need to live out lives for hours on every alt which would be too lengthy for most people.

**Comment by TwistedHBG** [comment]
That's not how curses work, all curses do is block you from spawning near the person who cursed you. If you are blocked from literally every player on the server you spawn in Donkey Town.

It's not fair to people who don't want you near them to just randomly remove their curses against you.

**Comment by NotSoShady116** [comment]
> That's not how curses work, all curses do is block you from spawning near the person who cursed you. If you are blocked from literally every player on the server you spawn in Donkey Town.
> 
> It's not fair to people who don't want you near them to just randomly remove their curses against you.

Yes I totally understand that, you know but the only issue is that people end up getting soft locked as a result of that. And I understand people hate griefers for ruining societal progress in the game but you must understand that these are people who bought this game.

**Comment by NotSoShady116** [comment]
> That's not how curses work, all curses do is block you from spawning near the person who cursed you. If you are blocked from literally every player on the server you spawn in Donkey Town.
> 
> It's not fair to people who don't want you near them to just randomly remove their curses against you.

And responding to the bottom comment, I'd like Jason to keep all the curses so the people who've been charged will pay for the things they've done during the high griefing age. It's only fair, each time you curse a person for griefing or anything else you'd be giving them one hour in donkey town and preventing them from being born near you. It's communitive punishment

**Comment by SoloAceMouse** [comment]
Jason has put enough thought and energy into Donkey Town. DT players should be grateful they can play at all.

In a normal game, anyone who acts like the DT players in OHOL would get banned permanently.

**Comment by NotSoShady116** [comment]
> Jason has put enough thought and energy into Donkey Town. DT players should be grateful they can play at all.
> 
> In a normal game, anyone who acts like the DT players in OHOL would get banned permanently.

Very selfish mindset

**Comment by NotSoShady116** [comment]
Guess it's just like the others.

**Comment by NotSoShady116** [comment]
Issue Rejected (Try Again Next Month)
