### ISSUE TITLE
Swamp Trees Can't Be Planted

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#957]
Trees such as Willows and Bald Cypresses are unable to be planted
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/5ee777f9-bbf4-4de6-8c63-e96a61f341dc)

**Comment by NotSoShady116** [comment]
I think a good willow tree would really contribute to gardening, perhaps you could harvest it's strongest lengths into rope. And with the cypress tree, I'm not really sure. Those trees usually just chill out in the swamp and house alligators. I swamps of Louisiana are really annoying with the amount of mosquito bites you get, even in the urbanized areas like the city you get horrible bites during any season.

**Comment by NotSoShady116** [comment]
Really the swamp has been kinda useless besides adobe and reeds.

**Comment by TwistedHBG** [comment]
https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account


> In repositories you own, blocked users also cannot:

    Open issues

**Comment by NotSoShady116** [comment]
Who is this?

**Comment by NotSoShady116** [comment]
> https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account
> 
> > In repositories you own, blocked users also cannot:
> 
> ```
> Open issues
> ```

Ohh shit it's twisted, noo wayyyyy.

**Comment by NotSoShady116** [comment]
> https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account
> 
> > In repositories you own, blocked users also cannot:
> 
> ```
> Open issues
> ```

The VPN changes the network ID to Ex. 182.221.129.0 (Class C) and along with the ip of any devices subnets to fit it's id Ex 182.221.129.43, now the IP of the device is _**void**_ed to any ban from a specific part of a webserver. This is a common issue for many servers do to the lack of an ability to prevent users from longing in by using a virtual network ID that tells the router it's from a different location than the banned router. 
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/c56a58f7-7d99-4296-a2c0-2d0d04ad92c5)

**Comment by NotSoShady116** [comment]
> https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account
> 
> > In repositories you own, blocked users also cannot:
> 
> ```
> Open issues
> ```

Jeez, I'll make sure to never report bugs or issues again.

**Comment by Tarr-OHOL** [comment]
Can you stop posting false issues? Jason really needs to block you from opening random fake issues.

**Comment by NotSoShady116** [comment]
This is one of those weird issues where you can be sure if it's an issue or not. But call it what you want

**Comment by Tarr-OHOL** [comment]
This is because they’re biome locked like mango trees. Not understanding game mechanics then complaining is a waste of time. This is just like the popcorn issue which I had to go double check which you were wrong about.

Next you’re gonna complain that you can’t plant dead trees.

**Comment by NotSoShady116** [comment]
Lol than why come out with guns instead of facts.
