### ISSUE TITLE
the #live-dev-changes discord channel is not updating

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#961]
see title

**Comment by Shadie116** [comment]
Also you should totally add radio towers to extend the range of radios

**Comment by jasonrohrer** [comment]
Ah!  MonitorRSS bot started disabling Legacy Feeds....  would be nice if the bot itself had posted warnings in these channels.

**Comment by jasonrohrer** [comment]
I just posted a test message in the forums, and it should get cross-posted on Discord in 10 minutes (update delay is 600 seconds)

**Comment by jasonrohrer** [comment]
Okay, updated to Personal Feeds from Legacy Feeds, and it's tested and working.
