### ISSUE TITLE
Infinite Newcomen Wells

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#962]
https://edge.onetech.info/4913

Latest change makes newcomen wells (check onetech link above).

Honestly, the issue (https://github.com/jasonrohrer/OneLifeData7/issues/1098) I posted that started this is very much not common.

Just roll it back? (Simplest solution.)

**Comment by cordy-123** [comment]
Oh Tarr also posted the same issue here: https://github.com/jasonrohrer/OneLifeData7/issues/1113

Still leaving this post here on OneLife part of github since you tend to look at OneLife first vs OneLifeData7.
 
To head off the release of the newcomen problem before the upcoming update.

**Comment by jasonrohrer** [comment]
Closing to consolidate with the other issue.

Thanks for catching this!
