### ISSUE TITLE
SUGGESTION: Change Riding Horses to "Follow" Move Behavior

### ISSUE THREAD

**Issue by SoloAceMouse** [jasonrohrer/OneLife#965]
![Horses issue](https://github.com/jasonrohrer/OneLife/assets/147592460/8f99578a-c6dc-4265-b3ea-0f1cd343ac27)

Currently, all domestic animals in the game use the "follow" behavior.

In the real world, domestic animals live in a close bond with their humans. They often have a home which they'll return to for sleeping/feeding/shelter and become distressed if they cannot return. Domesticated animals in OHOL already model this in-game this via the "follow" move behavior.

The only animal which doesn't is the riding horse [including the riding horse and horsecart versions], which I believe is an oversight.

My suggestion for correcting this would be to simply alter the move behavior of riding horses and horsecarts from "flee" into "follow".

**Comment by SoloAceMouse** [comment]
Herd animals, such as horses, form strong social relationships with humans when they are tame.

Please change the behavior of horses in game to reflect this. [Also, to save my sanity after the 1000th time chasing a fleeing horse in OHOL]

**Comment by Shadie116** [comment]
Or just make a system where the horse is less likely to run off if it's been riden alot by multiple people

**Comment by ghost** [comment]
I remember hearing a story from an ex-amish man about how their horses always found their way home on their own if they got loose. [Here](https://youtube.com/shorts/137FhBDNjRg?si=PeGI1qn8mO-25hPe) is a similar story from another ex-amish about the same phenomenon. 
I know coding this wouldn't be possible but they at least shouldn't flee. I really like this suggestion.

**Comment by jasonrohrer** [comment]
This is the way that it is, on purpose, for two reasons:

1.  It's funny.  These are wild horses, not domesticated ones.  You've tamed it, but it wants to get away the first chance it gets.  It's a royal pain in the ass to actually get anything done with this horse.

2.  It helps to balance the horses against other forms of more advanced fast transport, like cars and such.  Those don't run away!  Horses don't require fuel, and you don't have to spend expensive resources to "make" them (no metal, etc.), but they are a pain to use.
