### ISSUE TITLE
Discord Issues (Take Action Right The Hell Now)

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#969]
Somebody is posting zoophile p*rn and g*y p*rn in the discord and people are thinking it's me. I'm only a 14 year old and this is pretty fucked up and terrifying. The worst part is that they really sent that fucking shit in general. It's fucked up, I really need the community to take action against whatever sick fuck sent that shit.

**Comment by Shadie116** [comment]
I'm really trying to go public with this bullshit, what sick fucker accuses a 14 year old of posting zoophile gay porn.

**Comment by Shadie116** [comment]
![Screenshot 2023-10-22 195141](https://github.com/jasonrohrer/OneLife/assets/126846097/cab812f3-30ea-494e-af61-f3a6360bd017)
![Screenshot 2023-10-22 210057](https://github.com/jasonrohrer/OneLife/assets/126846097/8da56937-9ece-4797-b898-66d5af97dbdc)
![Screenshot 2023-10-22 213201](https://github.com/jasonrohrer/OneLife/assets/126846097/7b93862a-bd4c-4d74-81ac-46dc504b8702)
![Screenshot 2023-10-22 213252](https://github.com/jasonrohrer/OneLife/assets/126846097/991730a4-9765-4542-b5e0-866cf0725fd1)

**Comment by Shadie116** [comment]
If you look at the time of the sending it was the same time when Kaden (bluehawk) started threating me.

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/bd8ec7a0-40ed-4722-b9f2-0f402484a540)
Just look into this bullshit for once, I'm serious

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/6e9b17c5-3f7b-4a32-aed6-a320bb2cb503)

**Comment by Tarr-OHOL** [comment]
You are the one raiding the server my guy. You ask why you are banned instantly then come here to complain.

![image](https://github.com/jasonrohrer/OneLife/assets/53706597/e7cbd3d1-4cb0-4360-94aa-1fe55a9ee49d)


Get some help my guy, because you need it.

**Comment by Shadie116** [comment]
> You are the one raiding the server my guy. You ask why you are banned instantly then come here to complain.
> 
> ![image](https://user-images.githubusercontent.com/53706597/277472671-e7cbd3d1-4cb0-4360-94aa-1fe55a9ee49d.png)
> 
> Get some help my guy, because you need it.

That wasn't me

**Comment by Shadie116** [comment]
That's clearly kaden

**Comment by Tarr-OHOL** [comment]
![Kaden](https://github.com/jasonrohrer/OneLife/assets/53706597/a98e8763-f241-4cd9-a005-3fa67107f6c5)

I hate to break this to you but I don't think anyone is gonna believe that story. You've done this sort of stuff yourself and lied about it in the past. You can't just blame someone else for your actions, I get your a kid but once you cry wolf repeatedly people tend not to believe you anymore.  

I would recommend getting hobbies other than bothering people on the internet.

**Comment by Shadie116** [comment]
> ![room](https://user-images.githubusercontent.com/53706597/277489071-73f7b912-b2dd-41eb-848c-ebda7775df7f.png)
> 
> I hate to break this to you but I don't think anyone is gonna believe that story. You've done this sort of stuff yourself and lied about it in the past. You can't just blame someone else for your actions, I get your a kid but once you cry wolf repeatedly people tend not to believe you anymore.
> 
> I would recommend getting hobbies other than bothering people on the internet.

Boy who cries wolf. You got no idea what the fuck you are talking about right now do you? I'm not doing any of this bullshit with any of you, I don't give a flying fuck about griefing and all this other shit. This is serious, this fucker literally is spamming the god dam N WORD, POSTING MY LITTLE PONY ZOOPHILE PORN, SENDING ROBLOX PORN.. DO YOU FUCKING UNDERSTAND THIS SHIT. ROBLOX PORN IS WHAT HE IS SENDING, LESBIAN PORN MOTHERFUCKER, LESBIAN PORN WHERE CHILDREN COULD BE. DO YOU UNDERSTAND THE GRAVITY OF THIS SITUATION AND THE BULLSHIT HE IS ATTEMPTING TO FRAME ME OF???

**Comment by Shadie116** [comment]
Infact just to prove this shit isn't me I'm staying off of discord for a week on every account

**Comment by Shadie116** [comment]
> You are the one raiding the server my guy. You ask why you are banned instantly then come here to complain.
> 
> ![image](https://user-images.githubusercontent.com/53706597/277472671-e7cbd3d1-4cb0-4360-94aa-1fe55a9ee49d.png)
> 
> Get some help my guy, because you need it.

Infact Tarr, If your ass thinks I'm lying than here is some fucking proof for you. 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/71a13f5d-e1c7-479f-9b62-ba9353db93e3)
Exactly the time of the attacks

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/0ddd4eb2-e510-4743-ac37-ef50de4ef565)
I think you see the fucking problem, people really think that's me

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/9e91d9af-16b1-469b-8ef4-b120bde054e9)
Say @Tarr-OHOL So right there were two people? Would have been real nice to disclose this to me.

**Comment by Tarr-OHOL** [comment]
I really like that part where you take this out of context to complain. That's about the raid from 6/26 where Superspymain got banned for creating an invite for you and someone else to spam porn and gore. 

Anyways that's enough attention for you for now. See you when you start spamming again.

**Comment by Shadie116** [comment]
> I really like that part where you take this out of context to complain. That's about the raid from 6/26 where Superspymain got banned for creating an invite for you and someone else to spam porn and gore.
> 
> Anyways that's enough attention for you for now. See you when you start spamming again.

I got no idea who the fuck superspymain is and I don't like gore. It's fucking sickining

**Comment by Shadie116** [comment]
Infact I shouldn't be having to have a moderator stand up for me and take action. That's your fucking job.. I'll just go ahead and do it myself

**Comment by Shadie116** [comment]
Now looking at this from a more forward perspective. Why the fuck would I send dicks in the one hour one life general chat. That has to be the gayest shit ever.

**Comment by Shadie116** [comment]
Infact why would I send videos of men having sex in the ohol general? I'm deleting all this as to not taint the games reputation too much once this gets resolved.

**Comment by Shadie116** [comment]
Wait wait wait noo.. why the fuck would I send dicks, gore, men having sex, lesbians. and my little pony porn?

**Comment by Shadie116** [comment]
The real fucking queston is why the fuck would tarr accuse me of doing all of the above when all I've ever done is sneak back into the server.
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/5698ca09-d5bd-4986-b22e-abd83b30f79c)

**Comment by Shadie116** [comment]
Infact I got a brother a sister a mother a father. What type of son would I be to my own father if I were sending this sexually deviant shit. What type of brother to my little sister would I be??

**Comment by Kaden56** [comment]
Shady I really hope you find the help you're looking for. You really need to get your life back in shape. You're still really young and you can do alot of things in life.

**Comment by Shadie116** [comment]
> Shady I really hope you find the help you're looking for. You really need to get your life back in shape. You're still really young and you can do alot of things in life.

Aww thanks, I'll sure follow through when I find out which bitch is framing me of sending dicks to people over the internet via discord server

**Comment by Shadie116** [comment]
kaden I see you left a thumbs down. Do I just sit there and let it continue or handle this shit like a man and find out who's doing it?

**Comment by Shadie116** [comment]
> Shady I really hope you find the help you're looking for. You really need to get your life back in shape. You're still really young and you can do alot of things in life.

And Kaden I still suspect you but slightly less now that I know that it's a group doing it

**Comment by Tarr-OHOL** [comment]
![IMG_2705](https://github.com/jasonrohrer/OneLife/assets/53706597/433cfab5-11b8-4467-9ee7-7c8b507a5dd1)

**Comment by Shadie116** [comment]
Selfish Bunch, proofless bunch. Just know off of this evidence it ain't me raiding your sever.
