### ISSUE TITLE
Unable to pick up items

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#97]
Multiple reports of being unable to interact with items in the middle of a life resulting in death by starvation.

**Comment by Kailied** [comment]
Are you sure the incidents didn't occur because of a cabbage/berry seed or corn kernel in the hand? That's happened a lot to me.

**Comment by ghost** [comment]
Nah there has been multiple cases of people just losing the ability to do stuff. I've personally never been able to replicate it so I haven't a clue what the trigger is.

**Comment by jasonrohrer** [comment]
I think this was fixed.  It had something to do with people reconnecting.
