### ISSUE TITLE
Spend afew hours in dt Jason, see what you come across

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#971]
![pixil-frame-0 (3)](https://github.com/jasonrohrer/OneLife/assets/126307271/29850f12-1b49-40ba-9164-ba8bf0a7bcf8)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/05e86a49-3304-4f8f-86c1-0f64eb5e58b3)

**Comment by NotSoShady116** [comment]
Again I'm really confused on why you're listening to the people who are in the main world. You don't ask rich people about impoverished areas

**Comment by NotSoShady116** [comment]
So jason really, make yourself an account and get it cursed. See what dt is really like from a first hand perspective.

**Comment by Shadie116** [comment]
@jasonrohrer   This is going to keep causing problems, this should have been a temporary solution till you could develop better systems against griefers. You will have another version of me in the future telling you to change this. A person who will find themselves in my situation
