### ISSUE TITLE
Ghosts arent working as they should.

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLife#972]
People are experiencing that when they turn into a ghost other people can see them still and they're inverted on their sceen when they should be normal colors.

**Comment by selb** [comment]
The color inversion is intended. Players with outdated mod clients can still see ghosts as normal players, since those outdated clients don't know anything about ghosts.

**Comment by Kaden56** [comment]
even in vanilla players are seeing "ghosts" and its not supposed to be like that

**Comment by jasonrohrer** [comment]
Yes, there could be a bug here.  Hopefully, we can get some more information about it.

**Comment by NotSoShady116** [comment]
Burgered down French fries as an alternative to radios, but that would be going too far

**Comment by jasonrohrer** [comment]
I just saw a ghost on BS2, and it looked correct to me.  I could see the clothes.

**Comment by Shadie116** [comment]
Can you make the ghosts point the middle finger when you see them. Just would make me feel better about commiting exorcism

**Comment by TwistedHBG** [comment]
I can confirm, they're not working as they should. Ghosts that existed before I was born looked just like normal people, people that died while I was alive looked like ghosts

**Comment by Shadie116** [comment]
that's for phex clients if you use mods

> I can confirm, they're not working as they should. Ghosts that existed before I was born looked just like normal people, people that died while I was alive looked like ghosts

**Comment by TwistedHBG** [comment]
no mods, I would have specified if I used mods

> that's for phex clients if you use mods
> 
> > I can confirm, they're not working as they should. Ghosts that existed before I was born looked just like normal people, people that died while I was alive looked like ghosts

**Comment by Shadie116** [comment]
> no mods, I would have specified if I used mods
> 
> > that's for phex clients if you use mods
> > > I can confirm, they're not working as they should. Ghosts that existed before I was born looked just like normal people, people that died while I was alive looked like ghosts

@jasonrohrer 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/30db2f52-e67f-4f39-af29-749dc55ace45)

**Comment by jasonrohrer** [comment]
Thanks, Twisted, I will check it out.

**Comment by jasonrohrer** [comment]
Hmm... I can't reproduce this issue with existing ghosts (before you were born) in my test setup...  Very strange.

Oh, I just logged into the live BS2 server, and I see this:

```
Got length 35 message
GH
6752974
6752979
6752984
6752985

Got length 31 message
PE
6752974 39 -2
6753017 23 -2
```

This is weird, because there are 4 ghosts, but only 2 of them have permanent ghost emots (the thing that makes them invisible).

There must be a bug server-side that is causing these permanent emots to either not be assigned or be cleared by accident.

**Comment by Shadie116** [comment]
So some random mathematic equations I got no idea relate to the issue. Got it

**Comment by jasonrohrer** [comment]
Ah, I figured it out...

Someone becomes a ghost during computeAge (when we detect that they are past 60 years).  And then we add a new emote to the new emotes list .

But the new emote message is composed and sent out to all players before a bunch of other player stuff is computed... and there are more calls to computeAge after that.  At the very end of this, the new emotes list is cleared, ready for next time.

And it's DURING the composition of the new emotes message that we detect permanent emotes and add them to each player's permanent emote list.

So what's happening is that computeAge is being called later, which in rare cases turns someone into a ghost, and this happens after the new emotes message is sent, so their permanent emote is lost.

**Comment by Shadie116** [comment]
EEEEEEEEEEEEEEEEP
