### ISSUE TITLE
Change to /die 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#983]
Basically people don’t like to be spammed with players trying to get to a specific town so suggestion(s) to make things less annoying for new players. 

Easy solution to reduce /die

Just make it always cycle and not be completely random. This would reduce one person landing on the same mom repeatedly unless they were blocked.

So this does 1). Makes family selection easier as if there’s four families three /die commands puts you in each family once.

2). Gives you an idea if you are blocked or fertiles not in an area (you will skip a family if blocked or fertile is too young/not in town. 

3). Reduces unintentional/die spam because after the first cycle it is random what family you go to.

4). Allows better family selection while still keeping random lives intact.

also can Sid bones be lowered to either 60 seconds or 30? In the current system people going to a specific town will potentially hit the same mom multiple times which will leave multiple piles of bone for one player which is annoying for the player giving birth.

**Comment by SoloAceMouse** [comment]
Agreed, having a dozen babies spontaneously die after birth resulting in a room full of bones is anti-immersive.

I understand that the goal is to have every life be self-contained, but people are gonna want to get back to a specific family or town. If a family selector isn't available, then they're gonna use /die until they get where they want to be. 

Reducing the number of /die attempts required [or doing away with /die in favor of a family selector] would be greatly welcome.

**Comment by RainstormPw** [comment]
Really annoying, I tried to make a town and this same baby just kept dying and they left a pile of bones and crashed my gene score. I didn't have anymore curses because of the pervious round of babies

**Comment by jasonrohrer** [comment]
If /die babies affect the mother's gene score, that's a bug that I will fix.  I'm pretty sure it doesn't work this way, but I will check.

Also, I'm pretty sure that doing /die will lineage ban you from a family.... so you shouldn't just cycle back through the same mom over and over?

Looking at this now

**Comment by jasonrohrer** [comment]
Yeah, scores of suicide babies don't affect the scores of their ancestors:

https://github.com/jasonrohrer/OneLife/blob/330c1bbd7ce81214cf72f4ed10ae44aff465ecc1/server/server.cpp#L15679


For the other thing, when you /DIE, you are banned from being born to the mother that just birthed you, but only one mother is remembered.  After you SIDS again, you clear that ban, and then can keep cycling through.  I might change this, not sure.

There's also a lineage ban in place, where if you live more than 30 minutes in an area, you are banned from that area for 1.5 hours.  HOWEVER, this is overruled if you live to old age (unless you say Goodbye Forever).

But if you SIDS, you are not put on lineage ban.

But the lineage ban is a soft ban.... if we actually run out of other mothers, we violate it.

So I think these two things kinda fight each other.  Maybe only one mother A is not lineage banned for you, you are born to her, so you SIDs.  Then we keep looking, but no mothers left that aren't lineage banned.  So then we lift the lineage ban, and send you to mother B.  You SIDS again.  This clears the first SIDS ban for mother A.

Now we look again for a non-lineage-banned mother, and A is the only option.  So back to A you go.  You SIDS again.

Repeat forever.

If you are lineage banned everywhere except for one mother, you will visit her much more often than the other mothers as you SIDS around.

I will fix this to remember all emails of babies that have /DIED for you, and prevent any of them from returning to you during your lifetime.

And if they run out of mothers entirely... d-town?  Not sure, but maybe.  Definitely not Eve...

**Comment by jasonrohrer** [comment]
Got this working so that every mother remembers a full list of their SIDS babies as long as the mother is alive.  And you can never re-visit a mother that you've SIDS-died to.

If you run out of mothers because you SIDS with all of them, you go to D-town temporarily until more mothers become available.

**Comment by SoloAceMouse** [comment]
This solution will have significant downsides which are a much bigger problem than the initial issue.

/die has problems, but I hope this fix gets reverted or reworked into another form because DT-ing for too many respawn attempts is gonna backfire hard.
