### ISSUE TITLE
Pavers get entangled in bearcaves

### ISSUE THREAD

**Issue by RainstormPw** [jasonrohrer/OneLife#984]
So currently in road building there is this issue where if your paver hits an unmovable bear cave it just gets completely stuck. The engine is lost, the paver is lost. It's stuck running forever on the bearcave

**Comment by jasonrohrer** [comment]
You can use a hammer on the paver to stop it, and after that you can move it.  See:

https://github.com/jasonrohrer/OneLifeData7/issues/1084
