### ISSUE TITLE
I hava some questions 3 .

### ISSUE THREAD

**Issue by is52hertz** [jasonrohrer/OneLife#988]
Said before:
Thank you very much for your patient answers to my first two lssues (#975 #955).
This helps me a lot.
But I still have some questions that I need to ask.
Next let me describe my problem:
`OneLife` depends on `Server`
But under the directory, there is:
```
| curseServer
| fitnessServer
| lifeTokenServer
| lineageServer
| photoServer
```
There is also `ticketServer` in `minorGems`
and `statsServer` `CurseServer` `ArcServer` etc. mentioned in `settings`.
There is also the important `documentation/html`
But how do these work?
All I know is that they are based on `PHP`
I have a private server and want to use these servers to access my own domain name.
But I don't know how to use them, can you tell me in detail?
Thank you very much.

**Comment by jasonrohrer** [comment]
Yeah, getting those up and running is somewhat complicated...

They all use PHP/MySQL.

In general, most of those servers work the same way, where there's a "settings.php" file, where you edit the settings for where the MySQL database is located, etc.  Most of the settings you need to change are near the top of the settings.php file.

After that, if you access:

http://myserver.com/ticketServer/server.php

(For example.)

It will walk you through an automatic setup process.

After that, you can go to:

http://myserver.com/ticketServer/

You will see a login page for the Admin web-based interface for the server (most servers have this... some, like the reflector, do not).

**Comment by is52hertz** [comment]
But the recommended version of PHP/mySQL is?
