### ISSUE TITLE
You can farm on top of floors and roads.

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLife#99]
You can make rows of "Shallow Tilled Row" and "Deep Tilled Row" on top of "Wooden Floor", "Stone Floor", "Ancient Stone Floor" and "Stone Road" which does not make any sense since crops need space for their roots to grow.

**Comment by Kailied** [comment]
This isn't really fixable since all flooring are just tiles we can put items down on. Dirt lumps are the same as any other item that we can put down.

**Comment by jasonrohrer** [comment]
Yeah, this is a really hard one to fix.  Would require some flag that says, "This thing cannot be created on a floor."
