### ISSUE TITLE
Error where tga frames overflow the Screenshot folder causing all of user's disk space to be used up when they press =.

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#997]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/4bda24ec-a400-4870-bc96-293d5205d52b)
Yeah so basically the screenshot system for the editor just eats all your bytes

**Comment by Shadie116** [comment]
This was also an issue in the outdated editor so I'm guessing it just got looked over. The first time I saw it like accouple months ago I was searching through my entire hard drive to see what could be taking up that many bytes. It turns out it was just the editor screenshotting every frame of movement and causing like 100,000 files to fill up my 80gbs of storage left

**Comment by is52hertz** [comment]
After testing, there was no such vicious bug in the early versions of OOHOLEditor, and `=` at that time would only capture a picture.

**Comment by Shadie116** [comment]
Well that's weird, prlly just a goofy thingy. Complex things tend to get a bit funny.

**Comment by Shadie116** [comment]
I can't believe it's been a year since I bought this game. If I had never accepted that party invitation from my Cousain this whole timeline will have never happened.

**Comment by is52hertz** [comment]
> I can't believe it's been a year since I bought this game. If I had never accepted that party invitation from my Cousain this whole timeline will have never happened.

What happened? After you reminded me, I realized I've been playing games like OHOL for 3 years now.

**Comment by Shadie116** [comment]
I came at the worst possible time to buy the game.

**Comment by jasonrohrer** [comment]
If you're seeing "frame" files in there, instead of "screen" files, that's a sign that video recording is enabled.  This is meant for making movies from a series of frames.

Perhaps settings/outputAllFrames.ini is enabled?

**Comment by Shadie116** [comment]
kk,
