### ISSUE TITLE
Property Gate Inheritance

### ISSUE THREAD

**Issue by Rukhmar** [jasonrohrer/OneLife#999]
I love the new change you made a while back to checking for a nearby family member first to inherit leadership within a town. I propose we make a similar system for inheritance of property gates. Inheritance of gates should first check for the most eligible member within 200 tiles or so of the place the gate is built.

There are plenty of reasons someone could be out of town. Highway builders and traders will be outside of towns for a large portion of their lives, maybe far enough it wouldn't be possible for them to return before the end of their lives to pass on the gate to someone in town. With the new colonization update, part of your family could be split between different towns even. It doesn't make sense that vital resources your town requires are now locked out from you or randomly given to a person you have never met in another town because now the language experts can live with any other family.

**Comment by Butterbraugh** [comment]
The current way the gate works leads to very frustrating gameplay. I have built a truck before and stowed it "safely" in the family property. A while later I come back for another life hoping to actually use my new creation and see "owner 5k away" when I check to see who in my family owns the gate. 

You should not be inheriting property from more than 200 tiles away at the most.

The gate is used to keep rare and important resources safe. People need to be able to open it when those resources are needed. Having owners inherit from thousands of tiles away makes no sense.

**Comment by Shadie116** [comment]
I'm proud of you all, so rebellious 🥹

**Comment by DougLefelhocz** [comment]
I know I've inherited property gates when I've gone to other towns (for one reason or another), and planned on not coming back to that town.

**Comment by jasonrohrer** [comment]
This was fixed back in July:

https://github.com/jasonrohrer/OneLife/commit/432bfd33f2ce1e8f461bc59f76002bdd4251034b

The question, of course, is what should happen if there's no one close by to inherit it.

Currently, it searches far away for an heir, if they exist, but only if there are no nearby heirs around.

The other option is for the gate to collapse if there are no heirs nearby.  But I don't think we really want that.

A precious resource is at least kept safe from meddling in this rare case.
